[package]
name = "tairix-drv-display-vesa"
description = "TAIRiX VESA (VBE) linear-framebuffer display driver (x86_64 BIOS)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
tairix-abi = { path = "../../../lib/abi", version = "=0.0.0" }

[lints]
workspace = true
