[package]
name = "tairix-drv-storage-emmc2"
description = "TAIRiX Raspberry Pi 4 (BCM2711) EMMC2 SD-host block driver."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
tairix-abi = { path = "../../../lib/abi", version = "=0.0.0" }
tairix-dma-barrier = { path = "../../../lib/dma-barrier", version = "=0.0.0" }

[lints]
workspace = true
