//! Build script for the Stage 4.D Item 4 virtio-net-mmio (riscv64) QEMU
//! test.
//!
//! Two jobs, both done on the host where the toolchain and
//! `ed25519-dalek` are available:
//!
//! 1. Hand the riscv64 `virt` linker script to `rustc` on the
//!    freestanding `riscv64gc-unknown-none-elf` target (the single
//!    per-arch linker script the architecture port owns).
//! 2. Sign a synthetic virtio-net `.rxe` manifest requesting
//!    [`CapabilityId::MEM_DMA`] with a deterministic test seed, and emit
//!    a Rust source file the bin pulls in via `include!`.
//!
//! Re-running `build.rs` produces byte-identical output for the same
//! seed; the test is therefore deterministic.

use ed25519_dalek::{Signer, SigningKey};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;
use tairix_abi::{CapabilityId, DriverKind, DriverManifest, DRIVER_MANIFEST_MAGIC};

/// Deterministic signing seed so the trust anchor is stable across
/// builds. Distinct from the other QEMU fixtures' seeds so the images
/// cannot be confused.
const TEST_SEED: [u8; 32] = [
    0x72, 0x69, 0x73, 0x63, 0x76, 0x6e, 0x65, 0x74, 0x33, 0xa7, 0x5e, 0x12, 0x8b, 0xc0, 0x6f, 0x21,
    0xd4, 0x3a, 0x90, 0x77, 0x18, 0xee, 0x52, 0x84, 0x66, 0x1b, 0xa9, 0x05, 0xcd, 0x39, 0x7c, 0x40,
];

/// SHA-256 fingerprint of the host's syscall table. The concrete value
/// is irrelevant; both sides feed the same value into the `HostConfig`.
const SYS_HASH: [u8; 32] = [0x22; 32];

fn main() {
    tairix_itest_harness::emit_target_cfg();
    println!("cargo:rerun-if-changed=build.rs");

    let target = std::env::var("TARGET").unwrap_or_default();
    if target == "riscv64gc-unknown-none-elf" {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
        let linker_script = format!(
            "{}/../../../kernel/arch/riscv64/link/riscv64-virt.ld",
            manifest_dir.trim_end_matches('/')
        );
        println!("cargo:rerun-if-changed={linker_script}");
        println!("cargo:rustc-link-arg=-T{linker_script}");
    }

    let signing_key = SigningKey::from_bytes(&TEST_SEED);
    let signer_pubkey: [u8; 32] = signing_key.verifying_key().to_bytes();

    // The virtio-net driver's `register` entry checks `CAP_DRV_LOAD`, and
    // the kernel virtio factory only mints a DMA host for a driver granted
    // `CAP_MEM_DMA`. The driver's effective set is the intersection of the
    // loading user's grants and this manifest request, so name both.
    let caps: &[u16] = &[
        CapabilityId::DRV_LOAD.as_u16(),
        CapabilityId::MEM_DMA.as_u16(),
    ];
    let mut manifest = DriverManifest {
        magic: DRIVER_MANIFEST_MAGIC,
        abi_version: tairix_abi::ABI_VERSION_CURRENT,
        kind: DriverKind::UserSpace,
        bind_key_count: 0,
        capability_count: u16::try_from(caps.len()).expect("caps fit in u16"),
        syscall_table_hash: SYS_HASH,
        signer_pubkey,
        signature: [0u8; 64],
    };
    let encoded = manifest.to_le_bytes();
    let mut signed_message = Vec::with_capacity(DriverManifest::WIRE_LEN - 64 + caps.len() * 2);
    signed_message.extend_from_slice(&encoded[..DriverManifest::WIRE_LEN - 64]);
    for c in caps {
        signed_message.extend_from_slice(&c.to_le_bytes());
    }
    let sig = signing_key.sign(&signed_message);
    manifest.signature = sig.to_bytes();

    let mut image: Vec<u8> = Vec::new();
    image.extend_from_slice(&manifest.to_le_bytes());
    for c in caps {
        image.extend_from_slice(&c.to_le_bytes());
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// Signed virtio-net `.rxe` image bytes.\n");
    out.push_str("pub const RXE_IMAGE: &[u8] = &[");
    for (i, b) in image.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// Trust-anchor public key the host's `HostConfig` accepts.\n");
    out.push_str("pub const TRUSTED_SIGNER_PUBKEY: [u8; 32] = [");
    for (i, b) in signer_pubkey.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// SHA-256 fingerprint of the host's syscall table.\n");
    out.push_str("pub const SYSCALL_TABLE_HASH: [u8; 32] = [");
    for (i, b) in SYS_HASH.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");
    let path = PathBuf::from(out_dir).join("rxe_fixture.rs");
    fs::write(&path, out).expect("write rxe_fixture.rs");
}
