//! The freestanding aarch64 test kernel: build a child and a parent EL0
//! program, install a `KernelProcessSignal` producer over the shared
//! `KernelProcessWait` bookkeeping and the live scheduler, and prove the parent
//! terminates its own child with a signal and reaps the signalled status
//! (`plans/SPAWN.md` `SP7b`).

use core::panic::PanicInfo;
use core::sync::atomic::{AtomicBool, AtomicU64, AtomicUsize, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery, Errno, Signal, SyscallNumber, SYSCALL_MAX_ARGS};
use rustos_arch_aarch64::context_hal::ContextSwitchHal;
use rustos_arch_aarch64::kernel_arch::timer_frequency_hz;
use rustos_arch_aarch64::paging::{
    self, activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool,
};
use rustos_arch_aarch64::userentry::UserMode;
use rustos_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, Aarch64Arch,
    Aarch64ArchStorage, SERIAL_SINK,
};
use rustos_arch_api::{CpuId, EnterUser};
use rustos_fdt::Fdt;
use rustos_kalloc::FreeListAllocator;
use rustos_kernel_core::{
    reschedule_current, spawn_image, spawn_user_kthread, KernelProcessSignal, KernelProcessWait,
    ProcessSignal, ProcessWait, RescheduleAction, SpawnRequest, Yielder,
};
use rustos_kernel_mem::{
    copy_out, AddressSpace, DirectPhysMap, Frame, PhysAddr, PhysMap, UserAddressSpace, UserStack,
    VirtAddr,
};
use rustos_kernel_sched_eevdf::{Priority, Scheduler, SchedulerConfig};
use rustos_kernel_sec::TaskId;
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;
use rustos_log::{log, Event, EventId, Level};
use rustos_sync::SpinLock;

// `CHILD_RXE`, `PARENT_RXE`, and `USER_BIAS`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// The single-core slice runs logical CPU 0 on the boot core.
const BOOT_CPU: CpuId = 0;

/// Gigabytes of identity map each EL0 address space provides.
const IDENTITY_GIB: usize = 2;

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (256 KiB) — generous headroom for `rustos-rt`'s heap arena.
const USER_STACK_PAGES: u64 = 64;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to each program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the test hands each spawn build.
const FRAME_COUNT: usize = 256;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4300);
const TEST_SPAWNED: EventId = EventId(4301);
const TEST_PASS: EventId = EventId(4302);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: u16 = 1;
const FAIL_GIC: u16 = 2;
const FAIL_POOL: u16 = 3;
const FAIL_PARSE: u16 = 4;
const FAIL_BUILD: u16 = 5;
const FAIL_SCHED_NEW: u16 = 6;
const FAIL_SPAWN: u16 = 7;
const FAIL_DEADLOCK: u16 = 8;
const FAIL_NO_CURRENT: u16 = 9;
const FAIL_UNEXPECTED_SYSCALL: u16 = 10;
const FAIL_COPY_STATUS: u16 = 11;
const FAIL_PARENT_BAD_EXIT: u16 = 12;
const FAIL_NO_PRODUCER: u16 = 13;

/// Set once the parent reaped a child carrying the expected signalled status.
static REAP_OK: AtomicBool = AtomicBool::new(false);
/// Scheduler task id of the parent (the program that sends the signal + waits).
static PARENT_TID: AtomicU64 = AtomicU64::new(u64::MAX);

/// Size of the test's bump heap. Lives in `.bss` (zeroed by the trampoline).
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Per-space page-table pools (one per EL0 address space).
static PAGE_TABLES_CHILD: PageTablePool = PageTablePool::new();
static PAGE_TABLES_PARENT: PageTablePool = PageTablePool::new();

/// Physical-frame backing store the spawn builders allocate user pages from.
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame, shared by both builds.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next identity-mapped physical frame, or `None` when exhausted.
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn signal_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires. It does not widen either program's own authority.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The single installed process-wait producer (owns the parent/child +
/// exit-status bookkeeping), set once before the dispatch callback can fire.
static WAIT_PRODUCER: SpinLock<Option<&'static KernelProcessWait<Aarch64Arch>>> =
    SpinLock::new(None);
/// The single installed process-signal producer (authorises + delivers a
/// signal over the wait bookkeeping and the live scheduler).
#[allow(clippy::type_complexity)]
static SIGNAL_PRODUCER: SpinLock<
    Option<&'static KernelProcessSignal<Aarch64Arch, Scheduler<Aarch64Arch>>>,
> = SpinLock::new(None);
/// The live scheduler, leaked `'static` so the dispatch callback can resolve
/// the current task id.
static SCHED: SpinLock<Option<&'static Scheduler<Aarch64Arch>>> = SpinLock::new(None);
/// The parent's frozen address space + direct map, used to copy the reaped
/// child's exit status out to the parent's `status` pointer.
#[allow(clippy::type_complexity)]
static PARENT_SPACE: SpinLock<
    Option<(
        Box<dyn UserAddressSpace + Send + Sync>,
        Box<dyn PhysMap + Send + Sync>,
    )>,
> = SpinLock::new(None);

/// Resolve the scheduler's current task id on [`BOOT_CPU`], failing the test if
/// none is set (it always is inside a dispatched task's `svc`).
fn current_task_id() -> u64 {
    let sched = match *SCHED.lock() {
        Some(s) => s,
        None => qemu_exit::exit_failure(FAIL_NO_CURRENT),
    };
    match sched.current_task(BOOT_CPU) {
        Some(id) => id,
        None => qemu_exit::exit_failure(FAIL_NO_CURRENT),
    }
}

/// Encode a `Result<u64, Errno>` into the syscall return register following the
/// `abi-v1` signed convention (non-negative on success, `-errno` on error).
fn encode(result: Result<u64, Errno>) -> u64 {
    match result {
        Ok(value) => value,
        Err(err) => (-i64::from(err.as_i32())) as u64,
    }
}

/// The syscall-dispatch callback both EL0 programs' `svc` traps reach.
///
/// `signal` is routed through the installed [`SIGNAL_PRODUCER`] exactly as the
/// production handler does: the producer authorises the target against the
/// parent's own children and terminates it on the scheduler, recording the
/// signal's `128 + n` status. `wait` is routed through the [`WAIT_PRODUCER`],
/// which reaps the now-terminated child; the callback copies the recorded
/// status out to the parent's `status` pointer. `yield` reschedules the caller
/// (the child's steady state). `exit` records the caller's code and reaps it; a
/// parent that exits 0 after a verified reap is the PASS. Any other syscall is
/// unexpected and fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: `args_ptr` points at the live `[u64; SYSCALL_MAX_ARGS]` the
    // exception handler built from the saved register frame.
    let args = unsafe { &*args_ptr };
    #[allow(clippy::cast_possible_truncation)]
    let raw = number as u16;
    let cur = current_task_id();

    if raw == SyscallNumber::SIGNAL.as_u16() {
        let signaller = match *SIGNAL_PRODUCER.lock() {
            Some(s) => s,
            None => qemu_exit::exit_failure(FAIL_NO_PRODUCER),
        };
        #[allow(clippy::cast_possible_truncation)]
        let pid = args[0] as i32;
        #[allow(clippy::cast_possible_truncation)]
        let signal = match Signal::from_u32(args[1] as u32) {
            Ok(signal) => signal,
            Err(err) => return encode(Err(err)),
        };
        encode(signaller.signal(TaskId(cur), pid, signal).map(|()| 0))
    } else if raw == SyscallNumber::WAIT.as_u16() {
        let producer = match *WAIT_PRODUCER.lock() {
            Some(p) => p,
            None => qemu_exit::exit_failure(FAIL_NO_PRODUCER),
        };
        #[allow(clippy::cast_possible_truncation)]
        let pid = args[0] as i32;
        match producer.wait(TaskId(cur), pid) {
            Ok(reaped) => {
                // Copy the reaped status out to the parent's `status` pointer
                // through the validated boundary, exactly as the production
                // `wait` handler does.
                if !copy_status_to_parent(args[1], reaped.code) {
                    qemu_exit::exit_failure(FAIL_COPY_STATUS);
                }
                // The parent expects Terminate's 128 + 2 = 130 status.
                if Signal::Terminate.termination_status() == Some(reaped.code) {
                    REAP_OK.store(true, Ordering::SeqCst);
                }
                encode(Ok(u64::from(reaped.pid)))
            }
            Err(err) => encode(Err(err)),
        }
    } else if raw == SyscallNumber::YIELD.as_u16() {
        // The child gives up the CPU each iteration; reschedule it and resume
        // on the next dispatch (until the parent terminates it).
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Yield);
        0
    } else if raw == SyscallNumber::EXIT.as_u16() {
        #[allow(clippy::cast_possible_truncation)]
        let code = args[0] as i32;
        if cur == PARENT_TID.load(Ordering::SeqCst) {
            // The parent verified the reaped signalled status and returned 0.
            if code == 0 && REAP_OK.load(Ordering::SeqCst) {
                note(
                    TEST_PASS,
                    "signal test: parent terminated the child, read its signalled status, and exited 0",
                );
                qemu_exit::exit_success();
            }
            qemu_exit::exit_failure(FAIL_PARENT_BAD_EXIT);
        }
        // Any other task exiting on its own is unexpected (the child is
        // terminated by the signal, not by a self-exit): reap it and continue.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
        0
    } else {
        note(
            TEST_START,
            "signal test: fixture issued an unexpected syscall",
        );
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// Copy `code` (as the parent's `i32` status) out to the parent's `status`
/// pointer through the retained frozen parent space. Returns `false` on a
/// faulting or unmapped pointer (fail closed).
fn copy_status_to_parent(status_va: u64, code: i32) -> bool {
    let guard = PARENT_SPACE.lock();
    let Some((space, physmap)) = guard.as_ref() else {
        return false;
    };
    let bytes = code.to_ne_bytes();
    copy_out(
        space.as_ref(),
        physmap.as_ref(),
        VirtAddr::new(status_va),
        &bytes,
    )
    .is_ok()
}

/// Build one isolated EL0 address space from `rxe` over the per-space `pool`
/// with the given startup `args`, returning its stage-1 root and the entry
/// register state. Activates the space and builds the image through the audited
/// `spawn_image` caller.
fn build_el0_space(
    pool: &'static PageTablePool,
    rxe: &[u8],
    args: &[&[u8]],
) -> (u64, rustos_arch_api::UserEntry) {
    let Ok(image) = LoadImage::parse(rxe, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };
    let Some(arch) = ArchAddressSpace::new_identity_gigapages(pool, IDENTITY_GIB) else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    let root_phys = arch.root_phys();
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, heap,
    // frame pool, and device MMIO (all within `[0, 2 GiB)` on `virt`), so
    // switching it does not move the ground under the running code. Boot CPU.
    unsafe { arch.switch() };

    let mut space = AddressSpace::new(arch);
    let physmap = DirectPhysMap::identity((IDENTITY_GIB as u64) << 30);
    let request = SpawnRequest {
        image: &image,
        image_bytes: rxe,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args,
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once its space is reactivated (via `pre_resume`) and
    // the EL1 trap path is installed. Frames are drawn from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => qemu_exit::exit_failure(FAIL_BUILD),
    };

    // Retain the *parent's* frozen space so the `wait` handler can copy the
    // reaped child's status out to the parent's `status` pointer. Only the
    // parent calls `wait`, so only its space is kept.
    if core::ptr::eq(pool, &PAGE_TABLES_PARENT) {
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());
        let pm: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);
        *PARENT_SPACE.lock() = Some((frozen, pm));
    }

    (root_phys, entry)
}

/// Admit `entry` as a resumable user kthread whose `pre_resume` hook reactivates
/// `root_phys` before every switch-in (isolation). Returns its task id.
fn admit(sched: &Scheduler<Aarch64Arch>, root_phys: u64, entry: rustos_arch_api::UserEntry) -> u64 {
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |_stack_top: u64| {
        // SAFETY: the MMU is enabled and `root_phys` is the L1 root of a space
        // that identity-maps the low kernel window — `activate_user_root`'s
        // contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: the entered space is active (the `pre_resume` hook just
        // reactivated it) and the EL1 trap vector + dispatch callback are
        // installed, so the program's `svc`s are handled.
        unsafe { user_mode.enter_user(entry) }
    };
    match spawn_user_kthread(sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work) {
        Ok(id) => id,
        Err(_) => qemu_exit::exit_failure(FAIL_SPAWN),
    }
}

/// Format `value` as decimal into `buf`, returning the written slice. Used to
/// pass the child's scheduler-assigned PID to the parent as a startup argument.
fn u64_to_decimal(mut value: u64, buf: &mut [u8; 20]) -> &[u8] {
    if value == 0 {
        buf[0] = b'0';
        return &buf[..1];
    }
    let mut i = buf.len();
    while value > 0 {
        i -= 1;
        #[allow(clippy::cast_possible_truncation)]
        {
            buf[i] = b'0' + (value % 10) as u8;
        }
        value /= 10;
    }
    &buf[i..]
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 signal test: starting");

    // Enable FP/SIMD at EL1 before any code that may use it.
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    // P3/P4: discover the board from the embedded `virt` device tree.
    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Bring up the EL1 vectors + GICv2 and install the dispatch callback.
    // SAFETY: called once on the boot CPU with a stack established and the MMU
    // enabled (the address-space builds switch it on below).
    // Build the child space first so we know its task id before laying out the
    // parent's startup arguments.
    let (child_root, child_entry) = build_el0_space(&PAGE_TABLES_CHILD, CHILD_RXE, &[b"signal"]);

    unsafe {
        exceptions::init_vectors();
        gic::init();
    }
    syscall_entry::set_dispatch_callback(dispatch);

    // Build the live scheduler and both producers, leaking each `'static` so
    // the dispatch callback can reach them.
    static SCHED_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();
    let arch = Arc::new(Aarch64Arch::new(&SCHED_STORAGE, BOOT_CPU, counter_hz));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };
    let sched: &'static Scheduler<Aarch64Arch> = Box::leak(Box::new(sched));
    *SCHED.lock() = Some(sched);

    static PRODUCER_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();
    let producer_arch: &'static Aarch64Arch = Box::leak(Box::new(Aarch64Arch::new(
        &PRODUCER_STORAGE,
        BOOT_CPU,
        counter_hz,
    )));
    let wait_producer: &'static KernelProcessWait<Aarch64Arch> =
        Box::leak(Box::new(KernelProcessWait::new(producer_arch)));
    *WAIT_PRODUCER.lock() = Some(wait_producer);
    // The signal producer composes over the same wait bookkeeping and the live
    // scheduler — one source of truth for the parent/child relationship.
    let signal_producer: &'static KernelProcessSignal<Aarch64Arch, Scheduler<Aarch64Arch>> =
        Box::leak(Box::new(KernelProcessSignal::new(wait_producer, sched)));
    *SIGNAL_PRODUCER.lock() = Some(signal_producer);

    // Admit the child, then lay out the parent's startup arguments with the
    // child's scheduler-assigned PID as arg 1 (arg 0 is the program name), and
    // admit the parent. Record the parent/child link so the parent may signal
    // and reap it.
    let child_tid = admit(sched, child_root, child_entry);
    let mut pid_buf = [0u8; 20];
    let pid_arg = u64_to_decimal(child_tid, &mut pid_buf);
    let (parent_root, parent_entry) =
        build_el0_space(&PAGE_TABLES_PARENT, PARENT_RXE, &[b"signal", pid_arg]);
    let parent_tid = admit(sched, parent_root, parent_entry);
    PARENT_TID.store(parent_tid, Ordering::SeqCst);
    wait_producer.register_child(TaskId(parent_tid), TaskId(child_tid));
    note(TEST_SPAWNED, "aarch64 signal test: parent + child spawned");

    // Cooperative dispatch loop. The parent's verified `exit(0)` is the PASS
    // (raised from the dispatch callback). A never-draining loop times out.
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }

    // Reaching here means the workload drained without the parent's verified
    // exit raising PASS — a missed reap or a stall.
    if steps >= MAX_STEPS {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    qemu_exit::exit_failure(FAIL_PARENT_BAD_EXIT);
}
