[package]
name = "rustos-drv-bus-mmio"
description = "RustOS memory-mapped-IO bus driver (DTB-driven enumeration for aarch64/riscv64 `virt`-style platforms)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
rustos-abi = { path = "../../../lib/abi", version = "=0.0.0" }
rustos-util = { path = "../../../lib/util", version = "=0.0.0" }

[lints]
workspace = true
