//! FAT32 boot-partition authoring.
//!
//! The boot partition is laid down by the real in-tree FAT32 driver
//! (`rustos-drv-fs-fat32`) — the same code that mounts it on the running
//! system — so the author and the consumer share one on-disk definition
//! (`AGENTS.md` §2.2). It carries exactly what the Pi GPU bootloader
//! reads: the verified firmware blobs, the generated `config.txt`, and the
//! flat `kernel8.img`.

use rustos_abi::driver::filesystem::{FilesystemRead, FilesystemWrite, NodeKind};
use rustos_drv_fs_fat32::Fat32;

use crate::device::MemBlock;
use crate::firmware::FirmwareFile;
use crate::MkimageError;

/// Name of the kernel image the firmware loads (`config.txt` `kernel=`).
pub const KERNEL_IMG_NAME: &str = "kernel8.img";

/// Name of the generated firmware configuration file.
pub const CONFIG_TXT_NAME: &str = "config.txt";

/// Render the `config.txt` the Pi firmware boots RustOS with.
///
/// The knobs are the P0 facts of record (`docs/src/platform/aarch64.md`,
/// "Boot protocol"): AArch64 cores, the RustOS kernel image, and a held
/// UART clock for a stable early console. `armstub=armstub8.bin` is
/// emitted only when the (optional) stub is among the build inputs.
#[must_use]
pub fn config_txt(with_armstub: bool) -> String {
    let mut text = String::from(
        "# Generated by rustos-mkimage; do not hand-edit on the card.\n\
         # Knobs of record: docs/src/platform/aarch64.md, \"Boot protocol\".\n\
         arm_64bit=1\n\
         kernel=kernel8.img\n\
         enable_uart=1\n",
    );
    if with_armstub {
        text.push_str("armstub=armstub8.bin\n");
    }
    text
}

/// Author the FAT32 boot partition: format `sectors` sectors and plant the
/// firmware blobs, `config.txt`, and `kernel8.img`.
///
/// # Errors
///
/// [`MkimageError::BootPartition`] if formatting or any plant write fails.
pub fn build_boot_partition(
    sectors: u64,
    firmware: &[FirmwareFile],
    kernel8: &[u8],
) -> Result<Vec<u8>, MkimageError> {
    let dev = MemBlock::new(sectors).map_err(MkimageError::BootPartition)?;
    let mut fs = Fat32::format(dev).map_err(MkimageError::BootPartition)?;
    let root = fs.root();

    let with_armstub = firmware.iter().any(|f| f.name == "armstub8.bin");
    let config = config_txt(with_armstub);

    let mut plant = |name: &str, bytes: &[u8]| -> Result<(), MkimageError> {
        fs.create(root, name.as_bytes(), NodeKind::RegularFile)
            .map_err(MkimageError::BootPartition)?;
        let written = fs
            .write_at(root, name.as_bytes(), 0, bytes)
            .map_err(MkimageError::BootPartition)?;
        if written != bytes.len() {
            return Err(MkimageError::BootPartition(
                rustos_abi::DriverError::DeviceFault,
            ));
        }
        Ok(())
    };

    for file in firmware {
        plant(&file.name, &file.bytes)?;
    }
    plant(CONFIG_TXT_NAME, config.as_bytes())?;
    plant(KERNEL_IMG_NAME, kernel8)?;

    fs.flush().map_err(MkimageError::BootPartition)?;
    Ok(fs.into_block().into_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::device::SECTOR_BYTES;

    const TEST_SECTORS: u64 = 131_072; // 64 MiB, the production boot size.

    fn test_firmware() -> Vec<FirmwareFile> {
        vec![
            FirmwareFile {
                name: "start4.elf".into(),
                bytes: vec![0x11; 4096],
            },
            FirmwareFile {
                name: "fixup4.dat".into(),
                bytes: vec![0x22; 64],
            },
            FirmwareFile {
                name: "bcm2711-rpi-4-b.dtb".into(),
                bytes: vec![0x33; 1024],
            },
        ]
    }

    fn read_back(fs: &mut Fat32<MemBlock>, name: &str) -> Vec<u8> {
        let root = fs.root();
        let node = fs.lookup(root, name.as_bytes()).expect("file present");
        let mut out = vec![0u8; 1 << 20];
        let n = fs.read_at(node, 0, &mut out).expect("file reads");
        out.truncate(n);
        out
    }

    #[test]
    fn plants_firmware_config_and_kernel() {
        let kernel8 = vec![0x44u8; 8192];
        let bytes = build_boot_partition(TEST_SECTORS, &test_firmware(), &kernel8)
            .expect("boot partition builds");
        assert_eq!(
            bytes.len(),
            usize::try_from(TEST_SECTORS).expect("fits") * SECTOR_BYTES
        );

        let dev = MemBlock::from_bytes(bytes).expect("whole sectors");
        let mut fs = Fat32::open(dev).expect("the driver mounts its own product");
        assert_eq!(read_back(&mut fs, "start4.elf"), vec![0x11; 4096]);
        assert_eq!(read_back(&mut fs, "fixup4.dat"), vec![0x22; 64]);
        assert_eq!(read_back(&mut fs, "bcm2711-rpi-4-b.dtb"), vec![0x33; 1024]);
        assert_eq!(read_back(&mut fs, KERNEL_IMG_NAME), kernel8);

        let config = read_back(&mut fs, CONFIG_TXT_NAME);
        let config = core::str::from_utf8(&config).expect("config.txt is UTF-8");
        assert!(config.contains("arm_64bit=1"));
        assert!(config.contains("kernel=kernel8.img"));
        assert!(config.contains("enable_uart=1"));
        assert!(!config.contains("armstub="));
    }

    #[test]
    fn emits_the_armstub_knob_only_when_the_stub_is_an_input() {
        let mut firmware = test_firmware();
        firmware.push(FirmwareFile {
            name: "armstub8.bin".into(),
            bytes: vec![0x55; 256],
        });
        let bytes = build_boot_partition(TEST_SECTORS, &firmware, &[0x44u8; 16])
            .expect("boot partition builds");

        let dev = MemBlock::from_bytes(bytes).expect("whole sectors");
        let mut fs = Fat32::open(dev).expect("mounts");
        let config = read_back(&mut fs, CONFIG_TXT_NAME);
        let config = core::str::from_utf8(&config).expect("config.txt is UTF-8");
        assert!(config.contains("armstub=armstub8.bin"));
        assert_eq!(read_back(&mut fs, "armstub8.bin"), vec![0x55; 256]);
    }

    #[test]
    fn fails_closed_when_the_partition_cannot_hold_the_content() {
        // A device too small to even format must error, never panic.
        assert!(build_boot_partition(8, &test_firmware(), &[0x44u8; 16]).is_err());
    }
}
