//! In-kernel driver registry: the single source of truth for the drivers
//! the kernel itself hosts (PLAN Stage 4.HW item 5; `plans/PI.md` P10 5c).
//!
//! keeps drivers in user space *wherever feasible*;
//! sanctions drivers that must run in-kernel (`kind = InKernel`, gated by
//! `CAP_DRV_KERNEL`). This module is the registry of exactly those
//! in-kernel drivers: each [`InKernelDriver`] entry pairs a driver's
//! logical `/System/Drivers/` image path, the driver crate's own canonical
//! `BIND_KEYS`, the build-signed `.rxe` manifest image
//! the load gate verifies, and the statically-linked `register()` entry.
//! All four views of one driver live in a single entry, so the match data,
//! the signed bind table, and the linked code can never drift apart — and the registry is generic over hardware:
//! adding or retiring an in-kernel driver is one entry here, nothing else.
//!
//! Matching is the shared [`rustos_devmatch`] policy: a discovered
//! hardware-tree node's `match_keys` are resolved against the registry to
//! decide which driver binds it — exactly as the user-space `devmgr`
//! autoloader resolves the same policy. The
//! kernel does not *hunt* for a device; it binds a driver because that
//! driver's bind table matched a discovered node, and leaves an unmatched
//! node unbound and logged.
//!
//! This compiled-in list is the **bootstrap floor** candidate source: the only drivers compiled into the kernel are those
//! that must exist before the signed driver store under `/System/Drivers/`
//! is reachable — the general driver set is discovered at runtime from that
//! store, never frozen here. The floor binds by discovery-match through the
//! same shared policy and shrinks toward the store, never grows.
//!
//! The legitimate floor here is **exactly the storage path** — the block
//! drivers that read the volume holding the signed driver store — and it is
//! **per architecture**, holding only the storage the target can actually
//! boot from, never a driver for foreign silicon. [`VIRTIO_BLK_PATH`] is the
//! floor on every target with a virtio-blk root (the QEMU `virt` / x86_64 /
//! riscv64 boards); the BCM2711 SD-host EMMC2 driver is floor **only on
//! aarch64** (the Raspberry Pi 4 SD card), so it is compiled into the aarch64
//! image alone and never baked into an x86_64 or riscv64 build that has no
//! such controller. Nothing else is compiled in: the BCM2711 PCIe root
//! complex, the VL805 USB host, and the USB boot keyboard are all installed as
//! signed `/System/Drivers/` bundles and **autoloaded into user space** by
//! `devmgr` against their discovered hardware-tree nodes
//! (`drivers/bus/pcie_brcm`, `drivers/bus/usb/vl805`, `drivers/input/usb_kbd`;
//! `plans/PI.md` P10 D5d) — they sit *above* the store, not below it, so they
//! belong in the discovered tier, never the floor.

use rustos_abi::{DriverBindKey, HwMatchKey};
use rustos_devmatch::{resolve, DriverCandidate, MatchResolution};
use rustos_drvhost::DriverEntry;

// `KERNEL_DRIVER_SIGNER_PUBKEY` (the build's driver-signing trust anchor) and the per-driver `*_IMAGE` signed-manifest bytes.
// Auto-generated by `build.rs`; never hand-edited.
include!(concat!(env!("OUT_DIR"), "/driver_images.rs"));

/// Logical image path of the virtio-blk block driver
/// (`drivers/storage/virtio_blk`).
///
/// A vendor-neutral block device, so no vendor segment appears in the
/// path: the class (`storage`) names what the device *is*, never who made
/// it.
pub const VIRTIO_BLK_PATH: &str = "/System/Drivers/storage/virtio_blk";

/// Logical image path of the BCM2711 EMMC2 SD-host block driver
/// (`drivers/storage/emmc2`).
///
/// The vendor / chip name (`brcm` / `bcm2711_emmc2`) appears only at the
/// leaf — the directory that holds this one device's driver — while the
/// class namespace above it (`storage`) stays vendor-neutral.
///
/// EMMC2 is the Raspberry Pi 4 SD host, so it is a floor driver **only on
/// aarch64**; an x86_64 or riscv64 image has no such controller and never
/// compiles it in (the charter forbids baking one platform's driver into
/// another's image).
#[cfg(kernel_isa = "aarch64")]
pub const EMMC2_PATH: &str = "/System/Drivers/storage/brcm/bcm2711_emmc2";

/// One in-kernel driver: every view of it the kernel needs, in a single
/// entry so they cannot drift.
pub struct InKernelDriver {
    /// Logical `/System/Drivers/` image path — the driver's stable id.
    pub path: &'static str,
    /// The driver crate's published bind table, borrowed
    /// `'static` from the crate so the matcher never re-types it.
    pub bind_keys: &'static [DriverBindKey],
    /// The build-signed `.rxe` manifest image the load gate verifies
    /// (`build.rs`;).
    pub image: &'static [u8],
    /// The statically-linked `register()` entry the load gate invokes
    /// once the manifest is admitted.
    pub register: DriverEntry,
    /// `true` for the bootstrap-floor **block** drivers — the storage path
    /// that must be up before the signed driver store under
    /// `/System/Drivers/` is reachable. The root-storage
    /// bind gate ([`crate::root_storage`]) treats exactly these as candidates
    /// for the root volume. Every compiled-in floor entry is a block driver
    /// today, but the flag is declared per entry so the role stays explicit
    /// and cannot drift from a parallel list.
    pub provides_root_block: bool,
}

/// The number of drivers the kernel hosts in-kernel — the size of the
/// per-architecture bootstrap floor.
///
/// aarch64 carries two floor block drivers (virtio-blk for the QEMU `virt`
/// board, EMMC2 for the Raspberry Pi 4 SD card); x86_64 and riscv64 boot
/// from a virtio-blk root and carry that one alone — the Pi SD-host driver
/// is never compiled into an image for silicon that lacks the controller.
#[cfg(kernel_isa = "aarch64")]
pub const IN_KERNEL_DRIVER_COUNT: usize = 2;

/// The number of drivers the kernel hosts in-kernel — the size of the
/// per-architecture bootstrap floor (virtio-blk only on the non-aarch64
/// targets; see the aarch64 definition for the rationale).
#[cfg(not(kernel_isa = "aarch64"))]
pub const IN_KERNEL_DRIVER_COUNT: usize = 1;

/// The in-kernel driver registry — the single source of truth. Adding hardware support the kernel must host in-kernel is one
/// entry here; the build signs the driver's manifest (`build.rs`) and the
/// loader admits it through the same signed gate (`driver_loader`).
pub static IN_KERNEL_DRIVERS: [InKernelDriver; IN_KERNEL_DRIVER_COUNT] = [
    // The bootstrap-floor storage path: a block driver
    // must be up before the signed driver store under `/System/Drivers/`
    // is reachable, so the root volume can be read. virtio-blk backs the
    // QEMU `virt` / x86_64 / riscv64 root on every target; it sits
    // genuinely *below* the store and so is a floor, not discovered-tier,
    // driver.
    InKernelDriver {
        path: VIRTIO_BLK_PATH,
        bind_keys: rustos_drv_storage_virtio_blk::BIND_KEYS,
        image: VIRTIO_BLK_IMAGE,
        register: rustos_drv_storage_virtio_blk::register,
        provides_root_block: true,
    },
    // EMMC2 backs the Raspberry Pi 4 SD card, so it is floor **only on
    // aarch64**. An x86_64 / riscv64 image has no such controller and never
    // compiles it in — baking one platform's driver into another's image is
    // the board coupling the charter forbids.
    #[cfg(kernel_isa = "aarch64")]
    InKernelDriver {
        path: EMMC2_PATH,
        bind_keys: rustos_drv_storage_emmc2::BIND_KEYS,
        image: EMMC2_IMAGE,
        register: rustos_drv_storage_emmc2::register,
        provides_root_block: true,
    },
];

/// The registry entry whose `path` is `path`, or [`None`] if no in-kernel
/// driver owns it (the caller leaves an unknown node
/// unbound rather than guessing).
#[must_use]
pub fn driver_for(path: &str) -> Option<&'static InKernelDriver> {
    IN_KERNEL_DRIVERS.iter().find(|driver| driver.path == path)
}

/// `true` when `path` names a bootstrap-floor **block** driver — the
/// storage path the root volume is read through.
///
/// The single source of truth is each registry entry's
/// [`InKernelDriver::provides_root_block`] flag, so this can never drift
/// from a parallel path list. An unknown path is not a
/// block driver (fail closed).
#[must_use]
pub fn is_root_block_driver(path: &str) -> bool {
    driver_for(path).is_some_and(|driver| driver.provides_root_block)
}

/// The registry as match candidates (`path` + `bind_keys`), index-aligned
/// with [`IN_KERNEL_DRIVERS`] so a [`MatchResolution::Winner`] index names
/// the same driver in both. Derived from the one registry, never re-typed.
#[must_use]
pub fn driver_candidates() -> [DriverCandidate<'static>; IN_KERNEL_DRIVER_COUNT] {
    core::array::from_fn(|i| DriverCandidate {
        path: IN_KERNEL_DRIVERS[i].path,
        bind_keys: IN_KERNEL_DRIVERS[i].bind_keys,
    })
}

/// Resolve a discovered node's `match_keys` against the registry.
///
/// Returns the deterministic [`MatchResolution`]: the
/// strictly highest-priority matching driver wins, an unbroken tie across
/// distinct drivers is a packaging defect, and a node matching nothing is
/// [`MatchResolution::Unmatched`] — left unbound by the caller.
#[must_use]
pub fn resolve_driver(node_keys: &[HwMatchKey]) -> MatchResolution {
    resolve(node_keys, &driver_candidates())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn winner_path(resolution: MatchResolution) -> Option<&'static str> {
        match resolution {
            MatchResolution::Winner { candidate, .. } => Some(driver_candidates()[candidate].path),
            _ => None,
        }
    }

    #[test]
    fn discovered_storage_nodes_bind_the_block_drivers() {
        // The bootstrap-floor storage path: a discovered
        // virtio node whose probed device id is `virtio-blk` (2) binds the
        // virtio-blk driver on every target — by the driver's own bind
        // key, not a kernel guess.
        let virtio_blk = [HwMatchKey::virtio(2)];
        assert_eq!(
            winner_path(resolve_driver(&virtio_blk)),
            Some(VIRTIO_BLK_PATH)
        );
        // The device-tree `brcm,bcm2711-emmc2` node binds the EMMC2 driver
        // — but only on aarch64, the sole target whose floor carries the Pi
        // SD host; on x86_64 / riscv64 that node matches nothing in the
        // (virtio-blk-only) floor and is left unmatched.
        let emmc2 = [HwMatchKey::compatible(b"brcm,bcm2711-emmc2").expect("fits")];
        #[cfg(kernel_isa = "aarch64")]
        assert_eq!(winner_path(resolve_driver(&emmc2)), Some(EMMC2_PATH));
        #[cfg(not(kernel_isa = "aarch64"))]
        assert_eq!(resolve_driver(&emmc2), MatchResolution::Unmatched);
    }

    #[test]
    fn an_unrelated_device_is_left_unmatched() {
        // An AHCI storage controller matches no in-kernel driver: the caller
        // leaves it unbound and logged, never a guess.
        let ahci = [HwMatchKey::pci(0x8086, 0x2922, 0x01_06_01)];
        assert_eq!(resolve_driver(&ahci), MatchResolution::Unmatched);
        // A different-protocol HID device (a non-boot interface) also fails
        // the boot-class wildcard and is unmatched.
        let non_boot_hid = [HwMatchKey::usb(0x3434, 0x0E21, 0x03_00_00)];
        assert_eq!(resolve_driver(&non_boot_hid), MatchResolution::Unmatched);
    }

    #[test]
    fn the_registry_is_authored_from_the_driver_crates_bind_keys() {
        // The registry must borrow each driver's own published table, so the
        // match data can never drift from the signed-manifest source. The compiled-in floor is storage-only
        // : everything else autoloads from the store.
        assert_eq!(
            IN_KERNEL_DRIVERS[0].bind_keys,
            rustos_drv_storage_virtio_blk::BIND_KEYS
        );
        // The aarch64 floor's second entry is the EMMC2 SD-host driver,
        // authored from its own crate's bind table; no other target's
        // floor carries it.
        #[cfg(kernel_isa = "aarch64")]
        assert_eq!(
            IN_KERNEL_DRIVERS[1].bind_keys,
            rustos_drv_storage_emmc2::BIND_KEYS
        );
    }

    #[test]
    fn only_the_storage_floor_entries_provide_the_root_block() {
        // virtio-blk is the floor block driver on every target.
        assert!(is_root_block_driver(VIRTIO_BLK_PATH));
        // EMMC2 is a floor block driver only on aarch64 (the Pi SD host).
        #[cfg(kernel_isa = "aarch64")]
        assert!(is_root_block_driver(EMMC2_PATH));
        // An unknown path is not a block driver (fail closed). A
        // user-space-autoloaded bus/input driver is never in the floor.
        assert!(!is_root_block_driver(
            "/System/Drivers/bus_pcie/bcm2711/Run"
        ));
        assert!(!is_root_block_driver("/System/Drivers/not_in_kernel"));
        // The flag and the helper agree for every registry entry.
        for driver in &IN_KERNEL_DRIVERS {
            assert_eq!(
                is_root_block_driver(driver.path),
                driver.provides_root_block
            );
        }
    }

    #[test]
    fn driver_for_resolves_exactly_the_registry_paths() {
        for driver in &IN_KERNEL_DRIVERS {
            let found = driver_for(driver.path).expect("a registered path resolves");
            assert_eq!(found.path, driver.path);
        }
        assert!(driver_for("/System/Drivers/not_in_kernel").is_none());
    }
}
