//! In-kernel driver registry: the single source of truth for the drivers
//! the kernel itself hosts (PLAN Stage 4.HW item 5; `plans/PI.md` P10 5c).
//!
//! `AGENTS.md` §4 keeps drivers in user space *wherever feasible*; §8
//! sanctions drivers that must run in-kernel (`kind = InKernel`, gated by
//! `CAP_DRV_KERNEL`). This module is the registry of exactly those
//! in-kernel drivers: each [`InKernelDriver`] entry pairs a driver's
//! logical `/System/Drivers/` image path, the driver crate's own canonical
//! `BIND_KEYS` (`AGENTS.md` §18.3), the build-signed `.rxe` manifest image
//! the load gate verifies, and the statically-linked §8 `register()` entry.
//! All four views of one driver live in a single entry, so the match data,
//! the signed bind table, and the linked code can never drift apart
//! (`AGENTS.md` §2.2 / §18.5) — and the registry is generic over hardware:
//! adding or retiring an in-kernel driver is one entry here, nothing else.
//!
//! Matching is the shared [`rustos_devmatch`] policy: a discovered
//! hardware-tree node's `match_keys` are resolved against the registry to
//! decide which driver binds it — exactly as the user-space `devmgr`
//! autoloader resolves the same policy (`AGENTS.md` §2.2 / §18.3). The
//! kernel does not *hunt* for a device; it binds a driver because that
//! driver's bind table matched a discovered node, and leaves an unmatched
//! node unbound and logged (`AGENTS.md` §18.4).

use rustos_abi::{DriverBindKey, HwMatchKey};
use rustos_devmatch::{resolve, DriverCandidate, MatchResolution};
use rustos_drvhost::DriverEntry;

// `KERNEL_DRIVER_SIGNER_PUBKEY` (the build's driver-signing trust anchor,
// `AGENTS.md` §8 / §9) and the per-driver `*_IMAGE` signed-manifest bytes.
// Auto-generated by `build.rs`; never hand-edited (`AGENTS.md` §2.2).
include!(concat!(env!("OUT_DIR"), "/driver_images.rs"));

/// Logical image path of the BCM2711 PCIe root-complex driver
/// (`drivers/bus/pcie_brcm`).
///
/// The `/System/Drivers/` tree is organised `<class>/<vendor>/<driver>` so
/// the bus class (`pcie`) is never tied to a vendor: a vendor-specific
/// root-complex driver lives under its vendor (`brcm`), keeping the tree
/// sane as more vendors land (`AGENTS.md` §2.20).
pub const PCIE_BRCM_PATH: &str = "/System/Drivers/pcie/brcm/bcm2711";

/// Logical image path of the xHCI USB host-controller bus driver
/// (`drivers/bus/usb`).
pub const BUS_USB_PATH: &str = "/System/Drivers/bus_usb";

/// Logical image path of the HID boot-protocol input driver
/// (`drivers/input/usb_hid`).
pub const USB_HID_PATH: &str = "/System/Drivers/usb_hid";

/// One in-kernel driver: every view of it the kernel needs, in a single
/// entry so they cannot drift (`AGENTS.md` §2.2).
pub struct InKernelDriver {
    /// Logical `/System/Drivers/` image path — the driver's stable id.
    pub path: &'static str,
    /// The driver crate's published bind table (`AGENTS.md` §18.3), borrowed
    /// `'static` from the crate so the matcher never re-types it.
    pub bind_keys: &'static [DriverBindKey],
    /// The build-signed `.rxe` manifest image the load gate verifies
    /// (`build.rs`; `AGENTS.md` §8 / §9).
    pub image: &'static [u8],
    /// The statically-linked §8 `register()` entry the load gate invokes
    /// once the manifest is admitted.
    pub register: DriverEntry,
}

/// The number of drivers the kernel hosts in-kernel.
pub const IN_KERNEL_DRIVER_COUNT: usize = 3;

/// The in-kernel driver registry — the single source of truth (`AGENTS.md`
/// §2.2). Adding hardware support the kernel must host in-kernel is one
/// entry here; the build signs the driver's manifest (`build.rs`) and the
/// loader admits it through the same signed gate (`driver_loader`).
pub static IN_KERNEL_DRIVERS: [InKernelDriver; IN_KERNEL_DRIVER_COUNT] = [
    InKernelDriver {
        path: PCIE_BRCM_PATH,
        bind_keys: rustos_drv_bus_pcie_brcm::BIND_KEYS,
        image: PCIE_BRCM_IMAGE,
        register: rustos_drv_bus_pcie_brcm::register,
    },
    InKernelDriver {
        path: BUS_USB_PATH,
        bind_keys: rustos_drv_bus_usb::BIND_KEYS,
        image: BUS_USB_IMAGE,
        register: rustos_drv_bus_usb::register,
    },
    InKernelDriver {
        path: USB_HID_PATH,
        bind_keys: rustos_drv_input_usb_hid::BIND_KEYS,
        image: USB_HID_IMAGE,
        register: rustos_drv_input_usb_hid::register,
    },
];

/// The registry entry whose `path` is `path`, or [`None`] if no in-kernel
/// driver owns it (`AGENTS.md` §2.9 — the caller leaves an unknown node
/// unbound rather than guessing).
#[must_use]
pub fn driver_for(path: &str) -> Option<&'static InKernelDriver> {
    IN_KERNEL_DRIVERS.iter().find(|driver| driver.path == path)
}

/// The registry as match candidates (`path` + `bind_keys`), index-aligned
/// with [`IN_KERNEL_DRIVERS`] so a [`MatchResolution::Winner`] index names
/// the same driver in both. Derived from the one registry, never re-typed
/// (`AGENTS.md` §2.2).
#[must_use]
pub fn driver_candidates() -> [DriverCandidate<'static>; IN_KERNEL_DRIVER_COUNT] {
    core::array::from_fn(|i| DriverCandidate {
        path: IN_KERNEL_DRIVERS[i].path,
        bind_keys: IN_KERNEL_DRIVERS[i].bind_keys,
    })
}

/// Resolve a discovered node's `match_keys` against the registry.
///
/// Returns the deterministic [`MatchResolution`] (`AGENTS.md` §18.3): the
/// strictly highest-priority matching driver wins, an unbroken tie across
/// distinct drivers is a packaging defect, and a node matching nothing is
/// [`MatchResolution::Unmatched`] — left unbound by the caller (§18.4).
#[must_use]
pub fn resolve_driver(node_keys: &[HwMatchKey]) -> MatchResolution {
    resolve(node_keys, &driver_candidates())
}

/// Build the discovered PCIe root-complex node's `compatible` match key
/// from the discovery-contract identity string
/// (`kernel/arch/aarch64::platform::PCIE_COMPATIBLE`).
///
/// This reconstructs the *discovered* node's identity — the `compatible`
/// string the device tree advertised and the platform discovery verified
/// before yielding the bring-up windows — not the driver's bind key, so the
/// match against [`driver_candidates`] is a genuine node↔driver resolution
/// (`AGENTS.md` §18.5). Returns [`None`] fail-closed if the string does not
/// fit a [`HwMatchKey`] (`AGENTS.md` §2.9); the caller then leaves the node
/// unbound rather than guessing.
#[must_use]
pub fn bridge_compatible_key(compatible: &[u8]) -> Option<HwMatchKey> {
    HwMatchKey::compatible(compatible).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The BCM2711 PCIe root complex advertises this `compatible` string
    /// (mirrors `kernel/arch/aarch64::platform::PCIE_COMPATIBLE`).
    const PCIE_COMPATIBLE: &[u8] = b"brcm,bcm2711-pcie";

    /// The 24-bit xHCI PCI class (`base 0x0C`, sub `0x03`, prog-if `0x30`).
    const XHCI_CLASS: u32 = 0x0C_03_30;

    /// The HID boot-keyboard / boot-mouse 24-bit USB interface classes.
    const HID_KEYBOARD_CLASS: u32 = 0x03_01_01;
    const HID_MOUSE_CLASS: u32 = 0x03_01_02;

    fn winner_path(resolution: MatchResolution) -> Option<&'static str> {
        match resolution {
            MatchResolution::Winner { candidate, .. } => Some(driver_candidates()[candidate].path),
            _ => None,
        }
    }

    #[test]
    fn discovered_pcie_bridge_binds_the_root_complex_driver() {
        let key = bridge_compatible_key(PCIE_COMPATIBLE).expect("the contract string fits");
        assert_eq!(
            winner_path(resolve_driver(&[key])),
            Some(PCIE_BRCM_PATH),
            "the discovered brcm,bcm2711-pcie node must bind pcie_brcm"
        );
    }

    #[test]
    fn enumerated_vl805_function_binds_the_usb_bus_driver() {
        // The VL805 xHCI function node the PCI bus emits
        // (`PciBus::describe_function`): a concrete vendor/device with the
        // full 24-bit xHCI class. The bus driver's class-wildcard bind key
        // claims it without hard-coding the device id (`AGENTS.md` §18.5).
        let vl805 = [HwMatchKey::pci(0x1106, 0x3483, XHCI_CLASS)];
        assert_eq!(winner_path(resolve_driver(&vl805)), Some(BUS_USB_PATH));
    }

    #[test]
    fn enumerated_hid_interface_binds_the_input_driver() {
        // The HID child node the USB host emits (`UsbDevice::describe_device`)
        // keyed by its interface class. Both boot classes bind usb_hid.
        let keyboard = [HwMatchKey::usb(0x3434, 0x0E21, HID_KEYBOARD_CLASS)];
        let mouse = [HwMatchKey::usb(0x046D, 0xC52B, HID_MOUSE_CLASS)];
        assert_eq!(winner_path(resolve_driver(&keyboard)), Some(USB_HID_PATH));
        assert_eq!(winner_path(resolve_driver(&mouse)), Some(USB_HID_PATH));
    }

    #[test]
    fn an_unrelated_device_is_left_unmatched() {
        // An AHCI storage controller matches no in-kernel driver: the caller
        // leaves it unbound and logged (`AGENTS.md` §18.4), never a guess.
        let ahci = [HwMatchKey::pci(0x8086, 0x2922, 0x01_06_01)];
        assert_eq!(resolve_driver(&ahci), MatchResolution::Unmatched);
        // A different-protocol HID device (a non-boot interface) also fails
        // the boot-class wildcard and is unmatched.
        let non_boot_hid = [HwMatchKey::usb(0x3434, 0x0E21, 0x03_00_00)];
        assert_eq!(resolve_driver(&non_boot_hid), MatchResolution::Unmatched);
    }

    #[test]
    fn the_registry_is_authored_from_the_driver_crates_bind_keys() {
        // The registry must borrow each driver's own published table, so the
        // match data can never drift from the signed-manifest source
        // (`AGENTS.md` §2.2 / §18.3).
        assert_eq!(
            IN_KERNEL_DRIVERS[0].bind_keys,
            rustos_drv_bus_pcie_brcm::BIND_KEYS
        );
        assert_eq!(
            IN_KERNEL_DRIVERS[1].bind_keys,
            rustos_drv_bus_usb::BIND_KEYS
        );
        assert_eq!(
            IN_KERNEL_DRIVERS[2].bind_keys,
            rustos_drv_input_usb_hid::BIND_KEYS
        );
    }

    #[test]
    fn driver_for_resolves_exactly_the_registry_paths() {
        for driver in &IN_KERNEL_DRIVERS {
            let found = driver_for(driver.path).expect("a registered path resolves");
            assert_eq!(found.path, driver.path);
        }
        assert!(driver_for("/System/Drivers/not_in_kernel").is_none());
    }

    #[test]
    fn a_too_long_compatible_string_fails_closed() {
        // 256 bytes overruns HW_COMPATIBLE_MAX: no key, the caller leaves
        // the node unbound rather than fabricating one (`AGENTS.md` §2.9).
        let oversized = [b'a'; 256];
        assert!(bridge_compatible_key(&oversized).is_none());
    }
}
