//! aarch64 (Raspberry Pi 4) PID 1 (`init`) spawn seam — `plans/PI.md`
//! P6c-3.
//!
//! [`Aarch64InitSpawn`] implements the architecture-neutral
//! [`rustos_kernel_core::InitSpawn`] hook the boot pipeline installs into
//! the [`rustos_kernel_core::BootInfo`] hand-off
//! (`boot_aarch64::enter_kernel_core` → `BootInfo::with_init`). Once every
//! init phase has succeeded and `kernel_core::kernel_main` has emitted
//! [`rustos_kernel_core::AuditEvent::BootCompleted`], the core invokes
//! [`InitSpawn::spawn_init`]; this implementation builds the embedded
//! `init` (`Run`) program's EL0 image and drops into it through the
//! production, capability-checked, audited spawn caller
//! ([`rustos_kernel_core::spawn_and_enter`]). On the authorised, well-formed
//! path the call diverges into EL0 and never returns; on any failure it
//! returns so `kernel_main` parks the boot CPU fail-closed (`AGENTS.md`
//! §2.9).
//!
//! The image, its relocation bias ([`INIT_USER_BIAS`]), and the kernel's
//! syscall CFI tag are baked at build time (`build.rs` →
//! `rustos_itest_harness::elf2rxe`), exactly like the proven
//! `spawn_program_qemu_aarch64` fixture, so there is one conversion path
//! (`AGENTS.md` §2.2). Spawning `init` is *not* a privileged bypass: the
//! program receives only the authority its `rxe` manifest requests
//! intersected with its user's grants (`AGENTS.md` §4, §16.5); this seam
//! only authorises the *act* of spawning under `CAP_PROC_SPAWN`.

use core::sync::atomic::{AtomicBool, Ordering};

use alloc::boxed::Box;

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery};
use rustos_arch_aarch64::paging::{AddressSpace as ArchAddressSpace, PageTablePool};
use rustos_arch_aarch64::userentry::UserMode;
use rustos_arch_api::EnterUser;
use rustos_caps::CapabilitySet;
use rustos_kernel_core::{spawn_image, InitSpawn, InitSpawnCtx, SpawnRequest};
use rustos_kernel_mem::{AddressSpace, DirectPhysMap, PhysMap, UserAddressSpace, UserStack};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;

// `INIT_RXE: &[u8]` and `INIT_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/init_rxe.rs"));

/// Gigabytes of identity map the spawn address space provides.
///
/// `[0, 2 GiB)` covers the QEMU `virt` board's device MMIO (GiB 0) and the
/// RAM base at GiB 1 where the kernel image, its boot heap, the leaked
/// `KernelState`, and the live frame allocator all live — so switching to
/// this space does not move the ground under the running kernel (every
/// pointer keeps its identity address). [`INIT_USER_BIAS`] (64 GiB) sits
/// far above it, so the program's pages land on freshly walked stage-1
/// tables instead of colliding with an identity gigapage block — the same
/// 2 GiB window the `spawn_program_qemu_aarch64` fixture uses (`AGENTS.md`
/// §2.2). A board whose usable RAM extends past 2 GiB is a later
/// Raspberry-Pi-hardware stage (`plans/PI.md`); the P6c-3 proving ground is
/// the `virt` board, whose RAM falls inside this window.
const IDENTITY_GIB: usize = 2;

/// User stack base (1 MiB into the high user region) and size. The
/// `rustos-rt` runtime carves scratch space off the stack, so the stack
/// must comfortably exceed it (mirrors the spawn fixture).
const USER_STACK_BASE: u64 = INIT_USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB), generous headroom over the runtime's
/// scratch span plus call frames.
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up,
/// well clear of the program image and the stack).
const USER_BLOCK_BASE: u64 = INIT_USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to `init` (`AGENTS.md` §19.2). Any
/// value; the kernel RNG-seeded canary is a later stage.
const INIT_CANARY: u64 = 0x1117_A5ED_C0DE_0001;

/// Page-table pool backing the spawn address space's stage-1 hierarchy.
///
/// Lives in `.bss` for the lifetime of the kernel image, so `TTBR0_EL1`
/// keeps pointing at a valid table after [`Aarch64InitSpawn::spawn_init`]
/// switches to it (`AGENTS.md` §2.1 — monotonic, never freed). The identity
/// map needs a single root L1 frame; the rest serve the freshly walked user
/// mappings at [`INIT_USER_BIAS`].
static INIT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Set once PID 1 has been spawned so a re-entry cannot re-run the path.
static INIT_SPAWNED: AtomicBool = AtomicBool::new(false);

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege
/// [`spawn_and_enter`] requires to authorise spawning PID 1 (`AGENTS.md`
/// §5.4). It does not widen `init`'s own authority, which is its `rxe`
/// manifest's request intersected with its user's grants (`AGENTS.md`
/// §16.5).
struct SpawnAuthority;

impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The aarch64 PID 1 spawn seam installed into the [`rustos_kernel_core::BootInfo`]
/// hand-off by `boot_aarch64::enter_kernel_core`.
pub struct Aarch64InitSpawn;

/// The single, `'static` [`Aarch64InitSpawn`] the boot path borrows.
pub static AARCH64_INIT_SPAWN: Aarch64InitSpawn = Aarch64InitSpawn;

/// `init`'s effective capability set: exactly `CAP_CONSOLE_WRITE`, so PID 1
/// can write its startup banner through the `console_write` syscall
/// (`plans/PI.md` P6a/P6b). The boot path passes this as both the user
/// grant and the manifest request, so the intersection the kernel derives
/// is the same set — `init` is granted no more (`AGENTS.md` §5.2).
fn init_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::CONSOLE_WRITE);
    caps
}

impl InitSpawn for Aarch64InitSpawn {
    fn spawn_init(&self, ctx: &dyn InitSpawnCtx) {
        // Spawn PID 1 at most once; a spurious re-entry falls through to the
        // caller's fail-closed halt rather than building a second image.
        if INIT_SPAWNED
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }

        // Build a stage-1 address space identity-mapping the kernel + MMIO,
        // then activate it so the user mappings below land in the active
        // hierarchy. The EL1 vector table and the production `svc` dispatch
        // callback were installed earlier by the boot path, so the new
        // program's first `svc` is handled rather than faulting.
        let Some(arch) = ArchAddressSpace::new_identity_gigapages(&INIT_PAGE_TABLES, IDENTITY_GIB)
        else {
            return;
        };
        // SAFETY: the identity map covers the kernel's current `pc`, `sp`,
        // the leaked kernel state, the boot heap, and the device MMIO (all
        // within `[0, 2 GiB)` on the proving-ground board), so enabling it
        // does not move the ground under the running code — exactly
        // `AddressSpace::switch`'s contract. Called once on the boot CPU.
        unsafe { arch.switch() };

        let mut space = AddressSpace::new(arch);
        let physmap = DirectPhysMap::identity((IDENTITY_GIB as u64) << 30);

        // Parse the build-time `init` `rxe` blob against the kernel's own
        // compiled-in syscall CFI tag (§9 / §19.2). A mismatch fails closed.
        let Ok(image) = LoadImage::parse(INIT_RXE, &SYSCALL_TABLE_HASH) else {
            return;
        };

        let request = SpawnRequest {
            image: &image,
            image_bytes: INIT_RXE,
            bias: INIT_USER_BIAS,
            stack: UserStack {
                base: USER_STACK_BASE,
                page_count: USER_STACK_PAGES,
            },
            start_block_base: USER_BLOCK_BASE,
            args: &[b"init"],
            env: &[],
            canary: INIT_CANARY,
        };

        // Authorise + build the EL0 image (emits `ProcessSpawned`) without
        // entering yet — PID 1 must be registered with the scheduler /
        // capability table / address-space registry *first* so its first
        // syscall resolves a caller context (`plans/PI.md` P6c-3).
        // SAFETY: building the image is itself safe; the returned `UserEntry`
        // is only entered below, once `space` is active (just switched to)
        // and the EL1 trap path is installed. The frame source draws
        // identity-mapped RAM frames from the kernel's live allocator. A
        // returning `Err` (denial or build failure) drops back to the
        // caller's fail-closed halt (`AGENTS.md` §2.9).
        let frames = ctx.frames();
        let Ok(entry) = (unsafe {
            spawn_image(
                &SpawnAuthority,
                ctx.audit(),
                &mut space,
                &physmap,
                &request,
                move || frames.alloc().ok(),
            )
        }) else {
            return;
        };

        // The user-mode transition, boxed for the scheduler task body the
        // core wraps PID 1 in. `enter_user` diverges into EL0, so the
        // closure never truly returns (its `!` coerces to `()`).
        let user_mode = UserMode::new();
        let enter: Box<dyn FnMut() + Send> = Box::new(move || {
            // SAFETY: `space` is the active address space and the EL1 trap
            // vector + production dispatch callback are installed, so the
            // entered program's first `svc` is handled. `build_process_image`
            // mapped the entry/stack as user-accessible pages.
            unsafe { user_mode.enter_user(entry) }
        });

        // Freeze the just-built mappings into the registry-storable,
        // `Send + Sync` snapshot the kernel-wide address-space registry
        // holds (the live arch `space` is not `Sync`), and box the direct
        // map that backs it, so PID 1's `console_write` can copy its banner
        // out of user memory (`plans/PI.md` P6c-3 follow-up). Freezing
        // *after* `spawn_image` captures every mapped page — segments,
        // stack, and the startup-vector block.
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());
        let physmap: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);

        // Register PID 1's caps + address space, publish it as the current
        // task, and dispatch it — `admit_init` diverges into EL0 on success.
        // SAFETY: the image was built into and `space` switched to active
        // above, and the trap path is installed, per the
        // `InitSpawnCtx::admit_init` contract; `frozen` faithfully describes
        // the active mappings and `physmap` backs them.
        unsafe {
            ctx.admit_init(init_caps(), frozen, physmap, enter);
        }
    }
}
