//! riscv64 (QEMU `virt` / SiFive) PID 1 (`init`) spawn seam —
//! `plans/PI.md` RV-P3.
//!
//! [`RiscvInitSpawn`] implements the architecture-neutral
//! [`rustos_kernel_core::InitSpawn`] hook the boot pipeline installs into
//! the [`rustos_kernel_core::BootInfo`] hand-off
//! (`boot_riscv64::try_boot` → `BootInfo::with_init`). Once every init
//! phase has succeeded and `kernel_core::kernel_main` has emitted
//! [`rustos_kernel_core::AuditEvent::BootCompleted`], the core invokes
//! [`InitSpawn::spawn_init`]; this implementation builds the embedded
//! `init` (`Run`) program's U-mode image and drops into it through the
//! production, capability-checked, audited spawn caller
//! ([`rustos_kernel_core::spawn_image`] + [`InitSpawnCtx::admit_init`]).
//! On the authorised, well-formed path the task is dispatched into U-mode;
//! on any failure it returns so `kernel_main` parks the boot hart
//! fail-closed (`AGENTS.md` §2.9).
//!
//! The image, its relocation bias ([`INIT_USER_BIAS`]), and the kernel's
//! syscall CFI tag are baked at build time (`build.rs` →
//! `rustos_itest_harness::elf2rxe`), exactly like the aarch64 and x86_64
//! seams, so there is one conversion path (`AGENTS.md` §2.2). Spawning
//! `init` is *not* a privileged bypass: the program receives only the
//! authority its `rxe` manifest requests intersected with its user's
//! grants (`AGENTS.md` §4, §16.5); this seam only authorises the *act* of
//! spawning under `CAP_PROC_SPAWN`.
//!
//! PID 1's kernel stack is drawn from the boot-reserved guard arena
//! (`plans/PI.md` G3b-2): the seam re-expresses the coarse identity block
//! covering the stack's guard page at 4 KiB granularity in PID 1's *own*
//! Sv39 root and unmaps that single page, so an overrun takes a synchronous
//! store page fault under PID 1's `satp` (`AGENTS.md` §4 / §2.17) — the
//! cross-port mirror of the aarch64/x86_64 seams. Where no arena region is
//! available, or the split/unmap fails, it falls back to a heap-backed
//! software-canary [`BoxStack`] (fail closed, `AGENTS.md` §2.9), so PID 1
//! never runs on an unguarded raw stack.

use core::sync::atomic::{AtomicBool, Ordering};

use alloc::boxed::Box;

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery};
use rustos_arch_api::mmu::AddressSpace as MmuAddressSpace;
use rustos_arch_api::EnterUser;
use rustos_arch_riscv64::paging::{
    activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool,
};
use rustos_arch_riscv64::userentry::UserMode;
use rustos_caps::CapabilitySet;
use rustos_kernel_core::{
    spawn_image, BoxStack, InitSpawn, InitSpawnCtx, KernelStack, SpawnRequest,
};
use rustos_kernel_mem::{AddressSpace, DirectPhysMap, PhysMap, UserAddressSpace, UserStack};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;

use crate::stack_arena::{FrameArenaGrow, KTHREAD_STACK_ARENA};

// `INIT_RXE: &[u8]` and `INIT_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/init_rxe.rs"));

/// Gigabytes of identity map the spawn address space provides.
///
/// `[0, 4 GiB)` covers the QEMU `virt` board's low device MMIO and the
/// RAM base at `0x8000_0000` (GiB 2), where the kernel image, its boot
/// heap, the leaked `KernelState`, and the live frame allocator all live
/// — so switching to this space does not move the ground under the
/// running kernel (every pointer keeps its identity address).
/// [`INIT_USER_BIAS`] (64 GiB) sits far above it, so the program's pages
/// land on freshly walked Sv39 tables instead of colliding with an
/// identity gigapage leaf — the same 4 GiB window the
/// `spawn_session_qemu_riscv64` vertical uses (`AGENTS.md` §2.2).
const IDENTITY_GIB: usize = 4;

/// User stack base (1 MiB into the high user region) and size. The
/// `rustos-rt` runtime carves scratch space off the stack, so the stack
/// must comfortably exceed it (mirrors the spawn fixture and the
/// aarch64/x86_64 seams).
const USER_STACK_BASE: u64 = INIT_USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB), generous headroom over the runtime's
/// scratch span plus call frames.
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up,
/// well clear of the program image and the stack).
const USER_BLOCK_BASE: u64 = INIT_USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to `init` (`AGENTS.md` §19.2). Any
/// value; the kernel RNG-seeded canary is a later stage.
const INIT_CANARY: u64 = 0x1117_A5ED_C0DE_0001;

/// Page-table pool backing the spawn address space's Sv39 hierarchy.
///
/// Lives in `.bss` for the lifetime of the kernel image, so `satp` keeps
/// pointing at a valid table after [`RiscvInitSpawn::spawn_init`] switches
/// to it (`AGENTS.md` §2.1 — monotonic, never freed). The identity map
/// needs a single root frame; the rest serve the freshly walked user
/// mappings at [`INIT_USER_BIAS`].
static INIT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Set once PID 1 has been spawned so a re-entry cannot re-run the path.
static INIT_SPAWNED: AtomicBool = AtomicBool::new(false);

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege
/// [`spawn_image`] requires to authorise spawning PID 1 (`AGENTS.md`
/// §5.4). It does not widen `init`'s own authority, which is its `rxe`
/// manifest's request intersected with its user's grants (`AGENTS.md`
/// §16.5).
struct SpawnAuthority;

impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The riscv64 PID 1 spawn seam installed into the
/// [`rustos_kernel_core::BootInfo`] hand-off by `boot_riscv64::try_boot`.
pub struct RiscvInitSpawn;

/// The single, `'static` [`RiscvInitSpawn`] the boot path borrows.
pub static RISCV_INIT_SPAWN: RiscvInitSpawn = RiscvInitSpawn;

/// `init`'s effective capability set: `CAP_CONSOLE_WRITE`, so PID 1 can
/// write its startup banner through the `stream_write` syscall, plus
/// `CAP_PROC_SPAWN`, so it can launch the user's session program through
/// the `spawn` syscall (`plans/SPAWN.md` `SP3b`). The boot path passes
/// this as both the user grant and the manifest request, so the
/// intersection the kernel derives is the same set — `init` is granted no
/// more (`AGENTS.md` §5.2). Spawning is not ambient authority: the child
/// PID 1 launches receives only *its own* manifest∩user-grant set, never
/// `init`'s (`AGENTS.md` §4, §16.5).
fn init_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::CONSOLE_WRITE);
    caps.insert(CapabilityId::PROC_SPAWN);
    caps
}

impl InitSpawn for RiscvInitSpawn {
    fn spawn_init(&self, ctx: &dyn InitSpawnCtx) {
        // Spawn PID 1 at most once; a spurious re-entry falls through to the
        // caller's fail-closed halt rather than building a second image.
        if INIT_SPAWNED
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }

        // Build an Sv39 address space identity-mapping the kernel + MMIO,
        // then activate it so the user mappings below land in the active
        // hierarchy. The S-mode trap vector and the production `ecall`
        // dispatch callback were installed earlier by the boot path, so the
        // new program's first `ecall` is handled rather than faulting.
        let Some(mut arch) =
            ArchAddressSpace::new_identity_gigapages(&INIT_PAGE_TABLES, IDENTITY_GIB)
        else {
            return;
        };
        // Capture PID 1's `satp` root before the arch space is moved into the
        // `kernel/mem` wrapper, so the `pre_resume` hook can reactivate `satp`
        // with it before every switch into PID 1 (`plans/SPAWN.md` SP2). It is
        // a plain `u64`, so the boxed hook stays `Send`.
        let init_root_phys = arch.root_phys();

        // Build PID 1's kernel stack (`plans/PI.md` G3b-2). The boot path
        // published the reserved guard arena to the kthread-stack
        // allocator; if a region is available, re-express the coarse
        // identity block covering its guard page at 4 KiB granularity in
        // PID 1's *own* root and unmap that single page, so an overrun of
        // `init`'s kernel stack takes a synchronous store page fault under
        // PID 1's `satp` rather than corrupting the lower-addressed
        // neighbour (the real guard-page fault-form, `AGENTS.md` §4 /
        // §2.17). Doing it on `arch` *before* it is switched to means no
        // live access is disturbed (`split_block` only adds table levels
        // reproducing the existing translation) and no TLB maintenance is
        // needed. If no arena region is available, or the split/unmap could
        // not be applied, fall back to a heap-backed software-canary
        // `BoxStack` rather than ever running on an unguarded stack (fail
        // closed, `AGENTS.md` §2.9 / §2.17).
        // The arena grows on demand by chaining fresh 2 MiB blocks out of
        // the kernel's live frame allocator when its boot-carved block is
        // exhausted (`AGENTS.md` §24.1); a chained block is bounded to the
        // identity window so the stack stays mapped in PID 1's own root.
        let grow = FrameArenaGrow::new(ctx.frames(), (IDENTITY_GIB as u64) << 30);
        let kernel_stack: Box<dyn KernelStack + Send> =
            match KTHREAD_STACK_ARENA.alloc(&grow, &crate::stack_arena::IdentityBlockStore) {
                Some(stack) => {
                    let guard = stack.guard_page();
                    match arch
                        .split_block(guard)
                        .and_then(|()| arch.unmap(guard).map(|_| ()))
                    {
                        Ok(()) => Box::new(stack),
                        Err(_) => Box::new(BoxStack::new()),
                    }
                }
                None => Box::new(BoxStack::new()),
            };

        // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
        // leaked kernel state, the boot heap, and the device MMIO (all within
        // `[0, 4 GiB)` on the `virt` board), so enabling it does not move the
        // ground under the running code — exactly `AddressSpace::switch`'s
        // contract. Called once on the boot hart.
        unsafe { arch.switch() };

        let mut space = AddressSpace::new(arch);
        let physmap = DirectPhysMap::identity((IDENTITY_GIB as u64) << 30);

        // Parse the build-time `init` `rxe` blob against the kernel's own
        // compiled-in syscall CFI tag (§9 / §19.2). A mismatch fails closed.
        let Ok(image) = LoadImage::parse(INIT_RXE, &SYSCALL_TABLE_HASH) else {
            return;
        };

        let request = SpawnRequest {
            image: &image,
            image_bytes: INIT_RXE,
            bias: INIT_USER_BIAS,
            stack: UserStack {
                base: USER_STACK_BASE,
                page_count: USER_STACK_PAGES,
            },
            start_block_base: USER_BLOCK_BASE,
            args: &[b"init"],
            env: &[],
            canary: INIT_CANARY,
        };

        // Authorise + build the U-mode image (emits `ProcessSpawned`) without
        // entering yet — PID 1 must be registered with the scheduler /
        // capability table / address-space registry *first* so its first
        // syscall resolves a caller context (`plans/PI.md` RV-P3).
        // SAFETY: building the image is itself safe; the returned `UserEntry`
        // is only entered below, once `space` is active (just switched to) and
        // the S-mode trap path is installed. The frame source draws
        // identity-mapped RAM frames from the kernel's live allocator. A
        // returning `Err` (denial or build failure) drops back to the caller's
        // fail-closed halt (`AGENTS.md` §2.9).
        let frames = ctx.frames();
        let Ok(entry) = (unsafe {
            spawn_image(
                &SpawnAuthority,
                ctx.audit(),
                &mut space,
                &physmap,
                &request,
                move || frames.alloc().ok(),
            )
        }) else {
            return;
        };

        // The user-mode transition, boxed for the scheduler task body the core
        // wraps PID 1 in. `enter_user` diverges into U-mode, so the closure
        // never truly returns (its `!` coerces to `()`).
        let user_mode = UserMode::new();
        let enter: Box<dyn FnMut() + Send> = Box::new(move || {
            // SAFETY: `space` is the active address space and the S-mode trap
            // vector + production dispatch callback are installed, so the
            // entered program's first `ecall` is handled. `build_process_image`
            // mapped the entry/stack as user-accessible pages.
            unsafe { user_mode.enter_user(entry) }
        });

        // PID 1's user-address-space reactivation hook (`plans/SPAWN.md` SP2):
        // the core runs it on the dispatcher's context immediately before every
        // switch into PID 1, so the task `sret`s back into U-mode under its own
        // `satp` root and stays isolated from any sibling process
        // (`AGENTS.md` §4). It captures only the `u64` root, so it is `Send`.
        // The kernel-stack top the hook is handed is unused on riscv64:
        // `sscratch` is per-task hardware state armed by `userentry::enter_user`
        // and re-armed by the trap vector from each task's own kernel-stack
        // frame on every U-return, so a trap always lands on *its* kernel stack
        // with no dispatcher-side repointing.
        let pre_resume: Box<dyn FnMut(u64) + Send> = Box::new(move |_stack_top: u64| {
            // SAFETY: paging is enabled and `init_root_phys` is the Sv39 root
            // of PID 1's space, which identity-maps the low kernel window the
            // running kernel executes from — exactly `activate_user_root`'s
            // contract.
            unsafe { activate_user_root(init_root_phys) };
        });

        // Freeze the just-built mappings into the registry-storable,
        // `Send + Sync` snapshot the kernel-wide address-space registry holds
        // (the live arch `space` is not `Sync`), and box the direct map that
        // backs it, so PID 1's `stream_write` can copy its banner out of user
        // memory. Freezing *after* `spawn_image` captures every mapped page —
        // segments, stack, and the startup-vector block.
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());
        let physmap: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);

        // Register PID 1's caps + address space, publish it as the current
        // task, and dispatch it — `admit_init` diverges into U-mode on success.
        // SAFETY: the image was built into and `space` switched to active
        // above, and the trap path is installed, per the
        // `InitSpawnCtx::admit_init` contract; `frozen` faithfully describes
        // the active mappings and `physmap` backs them.
        unsafe {
            ctx.admit_init(
                init_caps(),
                frozen,
                physmap,
                kernel_stack,
                pre_resume,
                enter,
            );
        }
    }
}
