//! riscv64 (QEMU `virt` / SiFive) runtime `spawn` producer —
//! `plans/PI.md` RV-P3 / `plans/SPAWN.md` `SP3b`.
//!
//! [`RiscvProcessSpawn`] implements the architecture-neutral
//! [`rustos_kernel_core::ProcessSpawn`] seam the boot pipeline installs into
//! the [`rustos_kernel_core::BootInfo`] hand-off
//! (`boot_riscv64::try_boot` → `BootInfo::with_spawn`). When a task that
//! holds `CAP_PROC_SPAWN` issues the `spawn` syscall, the kernel resolves
//! the requested path against [`RISCV_PROGRAM_REGISTRY`] and hands the
//! matching `rxe` bytes to [`ProcessSpawn::spawn`], which builds the child a
//! *fresh, hardware-isolated* Sv39 address space, populates it through the
//! production capability-checked, audited spawn caller ([`spawn_image`],
//! gated on `CAP_PROC_SPAWN`), and admits it **Ready** through
//! [`SpawnCtx::admit_process`]. Unlike the PID-1 [`rustos_kernel_core::InitSpawn`]
//! seam (`init_spawn_riscv64.rs`) it does **not** switch the active
//! translation regime (`satp`) or enter user mode: the spawning caller keeps
//! running under its own root, and the child runs when the scheduler next
//! steps it (a true concurrent spawn, not an `exec`-style hand-off,
//! `AGENTS.md` §4) — the riscv64 sibling of the `Aarch64ProcessSpawn` /
//! x86_64 producers.
//!
//! The child's `rxe`, its relocation bias ([`SHELL_USER_BIAS`]), and the
//! kernel's syscall CFI tag are baked at build time (`build.rs` →
//! `rustos_itest_harness::elf2rxe`), exactly like PID 1, so there is one
//! conversion path (`AGENTS.md` §2.2). Spawning is *not* a privileged
//! bypass: the child receives only the authority [`child_caps`] requests
//! intersected with its user's grants (`AGENTS.md` §4, §16.5); this seam
//! only authorises the *act* of spawning under `CAP_PROC_SPAWN`.
//!
//! # Difference from the aarch64 producer
//!
//! Each spawned child gets a heap-backed software-canary [`BoxStack`]
//! kernel stack rather than a hardware-guarded arena stack (the riscv64
//! guarded kthread-stack arena is a later increment, `plans/PI.md` G3b-2),
//! the same fail-closed fallback the aarch64 producer takes when no arena
//! region is available (`AGENTS.md` §2.9).

use alloc::boxed::Box;

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery, Errno};
use rustos_arch_api::EnterUser;
use rustos_arch_riscv64::paging::{activate_user_root, AddressSpace as ArchAddressSpace};
use rustos_arch_riscv64::userentry::UserMode;
use rustos_caps::CapabilitySet;
use rustos_kernel_core::{
    spawn_image, AdmitError, BoxStack, EmbeddedProgram, KernelStack, ProcessSpawn, ProgramRegistry,
    SpawnCallerError, SpawnCtx, SpawnRequest,
};
use rustos_kernel_mem::{
    AddressSpace, DirectPhysMap, FrameAllocator, FrameTableSource, PhysMap, UserAddressSpace,
    UserStack,
};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;
use rustos_sync::Once;

// `SHELL_RXE: &[u8]` and `SHELL_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/shell_rxe.rs"));

/// Absolute path the `Shell` session program is registered under
/// (`AGENTS.md` §16.5 bundle layout). It must match exactly the `session`
/// path PID 1 `init` reads from its startup config and hands to the `spawn`
/// syscall (`userland/system/init/src/startup.rs`); the registry match is
/// byte-for-byte with no alias resolution (`AGENTS.md` §2.1).
const SHELL_PATH: &[u8] = b"/Apps/Shell.app/Run";

/// Gigabytes of identity map each spawned child address space provides.
///
/// `[0, 4 GiB)` covers the QEMU `virt` board's low device MMIO and the RAM
/// base at `0x8000_0000` (GiB 2), where the kernel image, its boot heap,
/// the leaked `KernelState`, and the live frame allocator all live. The
/// producer never switches to this space (the spawning caller keeps its own
/// `satp` active), so the identity map exists only so the child itself
/// executes under a translation regime that maps the low kernel window when
/// the scheduler later resumes it through `activate_user_root`.
/// [`SHELL_USER_BIAS`] (64 GiB) sits far above it, so the program's pages
/// land on freshly walked Sv39 tables rather than colliding with an identity
/// gigapage leaf — the same window PID 1 uses (`AGENTS.md` §2.2).
const IDENTITY_GIB: usize = 4;

/// User stack base (1 MiB into the high user region) and size, mirroring the
/// PID-1 layout (`init_spawn_riscv64.rs`): the `rustos-rt` runtime carves
/// scratch space off the stack, so it must comfortably exceed it.
const USER_STACK_BASE: u64 = SHELL_USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB), generous headroom over the runtime's
/// scratch span plus call frames.
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up,
/// well clear of the program image and the stack).
const USER_BLOCK_BASE: u64 = SHELL_USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to a spawned child (`AGENTS.md`
/// §19.2). Any value; the kernel RNG-seeded canary is a later stage.
const CHILD_CANARY: u64 = 0x1117_A5ED_C0DE_5E55;

/// Identity direct map the page-table frame source translates a freshly
/// allocated frame's physical address through to a CPU-dereferenceable
/// pointer (`AGENTS.md` §24.1 / `plans/WIRING.md` W5b-3).
///
/// It is the **identity** map (`offset == 0`) covering the same
/// `[0, IDENTITY_GIB GiB)` window each child space identity-maps, because
/// the Sv39 page-table walk recovers an existing child table by
/// dereferencing its physical address directly (`paging`: identity), so the
/// frame view the source hands the port must satisfy `virtual == physical`.
/// A frame the allocator draws from outside this window fails the translate
/// and the spawn fails closed (`AGENTS.md` §2.9) rather than building tables
/// the walk cannot reach — the same window the child's image data frames
/// already use (§2.2).
static SPAWN_TABLE_PHYSMAP: DirectPhysMap = DirectPhysMap::identity((IDENTITY_GIB as u64) << 30);

/// The single, `'static` allocator-backed page-table frame source every
/// spawned child's Sv39 hierarchy is built from (`AGENTS.md` §24.1).
///
/// Page-table frames come from the kernel's live [`FrameAllocator`] through
/// [`FrameTableSource`], so the spawn capacity **scales with discovered RAM
/// and grows on demand**: each child draws only the handful of Sv39 tables
/// it needs, and the system spawns processes until physical RAM is genuinely
/// exhausted, when [`FrameTableSource::alloc_table`] returns `None` and the
/// build fails closed with [`Errno::NoSpace`] (`AGENTS.md` §2.9, §4 —
/// deterministic OOM, never a panic). The frames are never freed while a
/// child lives (the monotonic discipline, `AGENTS.md` §2.1); reclaiming a
/// dead process's page-table frames is a later stage.
///
/// Initialised on the first `spawn` from the boot-threaded `'static`
/// allocator and reused thereafter — the source is stateless (its state
/// lives in the allocator), so one shared instance serves every CPU.
static SPAWN_FRAME_SOURCE: Once<FrameTableSource> = Once::new();

/// Borrow the `'static` allocator-backed page-table frame source,
/// initialising it from `frames` on the first call (`AGENTS.md` §24.1).
///
/// Fails closed with [`Errno::NotImplemented`] if the one-shot initialiser
/// was poisoned by a panicking earlier attempt — [`FrameTableSource::new`]
/// cannot panic, so this is unreachable in practice, but it is never
/// papered over (`AGENTS.md` §2.9).
fn page_table_source(frames: &'static FrameAllocator) -> Result<&'static FrameTableSource, Errno> {
    SPAWN_FRAME_SOURCE
        .call_once_infallible(|| FrameTableSource::new(frames, &SPAWN_TABLE_PHYSMAP))
        .map_err(|_| Errno::NotImplemented)
}

/// The embedded programs the `spawn` syscall can resolve: the `Shell`
/// session program PID 1 launches (`plans/SPAWN.md` `SP3b`). Its `rxe` is
/// baked at build time (`build.rs`); the real interpreter REPL is
/// `plans/PI.md` P6e.
static SPAWN_PROGRAMS: [EmbeddedProgram; 1] = [EmbeddedProgram {
    path: SHELL_PATH,
    rxe: SHELL_RXE,
}];

/// The `'static` embedded-program registry the boot path installs through
/// `BootInfo::with_spawn`.
pub static RISCV_PROGRAM_REGISTRY: ProgramRegistry = ProgramRegistry::new(&SPAWN_PROGRAMS);

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege
/// [`spawn_image`] requires to authorise building a child image (`AGENTS.md`
/// §5.4). It does not widen the child's authority, which is [`child_caps`]
/// intersected with its user's grants (`AGENTS.md` §16.5).
struct SpawnAuthority;

impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// A spawned child's effective capability set: exactly `CAP_CONSOLE_WRITE`,
/// so the session program can write its banner through the `stream_write`
/// syscall. Passed as both the user grant and the manifest request, so the
/// intersection the kernel derives is the same set — the child is granted no
/// more (`AGENTS.md` §5.2), and never inherits the spawning caller's
/// authority (`AGENTS.md` §4 — no ambient authority).
fn child_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::CONSOLE_WRITE);
    caps
}

/// The riscv64 runtime `spawn` producer installed into the
/// [`rustos_kernel_core::BootInfo`] hand-off by `boot_riscv64::try_boot`.
pub struct RiscvProcessSpawn;

/// The single, `'static` [`RiscvProcessSpawn`] the boot path borrows.
pub static RISCV_PROCESS_SPAWN: RiscvProcessSpawn = RiscvProcessSpawn;

impl ProcessSpawn for RiscvProcessSpawn {
    fn spawn(&self, rxe: &[u8], ctx: &dyn SpawnCtx) -> Result<u64, Errno> {
        // The child's Sv39 hierarchy is drawn from the kernel's live frame
        // allocator (`AGENTS.md` §24.1): there is no fixed page-table reserve
        // and so no hard cap on how many processes can be spawned — the
        // capacity scales with discovered RAM and grows on demand. A build
        // with no `'static` allocator wired fails closed (`AGENTS.md` §2.9),
        // as does genuine RAM exhaustion below.
        let pt_frames = ctx.page_table_allocator().ok_or(Errno::NoSpace)?;
        let table_frames = page_table_source(pt_frames)?;

        // Build an Sv39 address space identity-mapping the kernel + MMIO, and
        // capture its root *without* switching to it: the spawning caller
        // stays active under its own `satp`, so the running parent is never
        // moved out from under itself. The child's mappings below are written
        // through the identity `physmap` (physical frame addresses the
        // caller's active identity space already maps), so the build does not
        // require the child space to be active. The child's own root is
        // reactivated by its `pre_resume` hook before the scheduler first
        // resumes it (`plans/SPAWN.md` SP2). An allocator exhausted of even
        // the root table fails closed with `NoSpace`.
        let arch = ArchAddressSpace::new_identity_gigapages(table_frames, IDENTITY_GIB)
            .ok_or(Errno::NoSpace)?;
        let child_root_phys = arch.root_phys();

        // The child's kernel stack. This slice uses a heap-backed
        // software-canary `BoxStack` rather than a hardware-guarded arena
        // stack (the riscv64 guarded kthread-stack arena is a later
        // increment, `plans/PI.md` G3b-2) — the same fail-closed fallback the
        // aarch64/x86_64 producers take when no arena region is available, so
        // the child never runs on an unguarded raw stack (`AGENTS.md` §2.9).
        let kernel_stack: Box<dyn KernelStack + Send> = Box::new(BoxStack::new());

        let mut space = AddressSpace::new(arch);
        let physmap = DirectPhysMap::identity((IDENTITY_GIB as u64) << 30);

        // Parse the build-time `rxe` blob against the kernel's own compiled-in
        // syscall CFI tag (§9 / §19.2). A mismatch fails closed; the registry
        // holds bytes that already parsed once at build time, so reaching this
        // is a kernel build defect, surfaced as a stable errno.
        let image = LoadImage::parse(rxe, &SYSCALL_TABLE_HASH).map_err(|_| Errno::BadMagic)?;

        let request = SpawnRequest {
            image: &image,
            image_bytes: rxe,
            bias: SHELL_USER_BIAS,
            stack: UserStack {
                base: USER_STACK_BASE,
                page_count: USER_STACK_PAGES,
            },
            start_block_base: USER_BLOCK_BASE,
            args: &[b"shell"],
            env: &[],
            canary: CHILD_CANARY,
        };

        // Authorise + build the child's U-mode image (emits `ProcessSpawned`).
        // SAFETY: building the image is itself safe; the returned `UserEntry`
        // is only entered later, once the child is dispatched and its
        // `pre_resume` hook has made `space` active (the `spawn_image`
        // contract). The frame source draws identity-mapped RAM frames from
        // the kernel's live allocator. When the child space is not active the
        // build reaches the child's tables + frames through the caller's
        // identity window (the pool and frames are in `[0, 4 GiB)`), so the
        // child's space need not be active to be built (the cross-port
        // producer discipline, §2.2). A returning `Err` reclaims nothing
        // user-visible (the page-table + image frames are handed out
        // monotonically and not reclaimed this stage) and maps to a stable
        // errno; the cause is already audited by `spawn_image` (`AGENTS.md`
        // §2.9).
        let frames = ctx.frames();
        let entry = unsafe {
            spawn_image(
                &SpawnAuthority,
                ctx.audit(),
                &mut space,
                &physmap,
                &request,
                move || frames.alloc().ok(),
            )
        }
        .map_err(spawn_caller_errno)?;

        // The child's user-address-space reactivation hook (`plans/SPAWN.md`
        // SP2): the core runs it on the dispatcher's context immediately
        // before every switch into the child, so it `sret`s into U-mode under
        // its own `satp` root and stays hardware-isolated from the spawning
        // parent and every sibling (`AGENTS.md` §4). It captures only the
        // `u64` root, so it is `Send`. The kernel-stack top it is handed is
        // unused on riscv64: `sscratch` is per-task hardware state armed by
        // `userentry::enter_user` and re-armed by the trap vector from each
        // task's own kernel-stack frame on every U-return.
        let pre_resume: Box<dyn FnMut(u64) + Send> = Box::new(move |_stack_top: u64| {
            // SAFETY: paging is enabled and `child_root_phys` is the Sv39 root
            // of the child's space, which identity-maps the low kernel window
            // the running kernel executes from — exactly `activate_user_root`'s
            // contract.
            unsafe { activate_user_root(child_root_phys) };
        });

        // The user-mode transition, boxed for the scheduler task body the core
        // wraps the child in. `enter_user` diverges into U-mode, so the
        // closure never truly returns (its `!` coerces to `()`).
        let user_mode = UserMode::new();
        let enter: Box<dyn FnMut() + Send> = Box::new(move || {
            // SAFETY: by the time this body runs the child has been dispatched,
            // so its `pre_resume` hook has activated `space` and the S-mode
            // trap vector + production dispatch callback are installed; the
            // child's first `ecall` is handled. `build_process_image` mapped
            // the entry/stack as user pages.
            unsafe { user_mode.enter_user(entry) }
        });

        // Freeze the just-built mappings into the registry-storable,
        // `Send + Sync` snapshot the kernel-wide address-space registry holds
        // (the live arch `space` is not `Sync`), and box the direct map that
        // backs it, so the child's `stream_write` can copy its banner out of
        // its own user memory. Freezing *after* `spawn_image` captures every
        // mapped page — segments, stack, and the startup-vector block.
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());
        let physmap: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);

        // Register the child's caps + frozen address space and admit it Ready,
        // returning its PID. The spawning caller keeps running.
        // SAFETY: `frozen` faithfully describes the mappings just built into
        // `space`, `physmap` backs them, `pre_resume` activates the child's
        // root before it is first entered, and `kernel_stack` is a region
        // exclusive to this child that stays mapped for the task's lifetime —
        // the `admit_process` contract.
        unsafe {
            ctx.admit_process(
                child_caps(),
                frozen,
                physmap,
                kernel_stack,
                pre_resume,
                enter,
            )
        }
        .map_err(admit_errno)
    }
}

/// Map a [`SpawnCallerError`] onto a stable [`Errno`] for the `spawn`
/// syscall's caller (`AGENTS.md` §2.9). The precise cause is already on the
/// audit log via the `ProcessSpawn*` events `spawn_image` emits.
fn spawn_caller_errno(err: SpawnCallerError) -> Errno {
    match err {
        // A missing `CAP_PROC_SPAWN` (cannot occur — the dispatcher already
        // gated the syscall — but mapped for completeness).
        SpawnCallerError::Denied => Errno::PermissionDenied,
        // Image construction failed (a frame/pool exhaustion, a malformed
        // segment, an over-size startup block). One stable resource errno.
        SpawnCallerError::Build(_) => Errno::NoSpace,
        // `SpawnCallerError` is `#[non_exhaustive]`: any future variant fails
        // closed to the same stable resource errno (`AGENTS.md` §2.9).
        _ => Errno::NoSpace,
    }
}

/// Map an [`AdmitError`] onto a stable [`Errno`] (`AGENTS.md` §2.9).
fn admit_errno(err: AdmitError) -> Errno {
    match err {
        AdmitError::SchedulerFull => Errno::NoSpace,
        AdmitError::AspaceConflict => Errno::AlreadyExists,
        // `AdmitError` is `#[non_exhaustive]`: any future variant fails
        // closed to a stable resource errno (`AGENTS.md` §2.9).
        _ => Errno::NoSpace,
    }
}
