//! x86_64 runtime `spawn` producer — `plans/PI.md` `X3b`.
//!
//! [`X86_64ProcessSpawn`] implements the architecture-neutral
//! [`rustos_kernel_core::ProcessSpawn`] seam the boot pipeline installs into
//! the [`rustos_kernel_core::BootInfo`] hand-off (`boot::try_boot` →
//! `BootInfo::with_spawn`). It is the cross-port sibling of the aarch64
//! `spawn_producer` (`plans/SPAWN.md` `SP3b`): when a task that holds
//! `CAP_PROC_SPAWN` issues the `spawn` syscall, the kernel resolves the
//! requested path against [`X86_64_PROGRAM_REGISTRY`] and hands the matching
//! `rxe` bytes to [`ProcessSpawn::spawn`], which builds the child a *fresh,
//! hardware-isolated* PML4 hierarchy, populates it through the production
//! capability-checked, audited spawn caller ([`spawn_image`], gated on
//! `CAP_PROC_SPAWN`), and admits it **Ready** through
//! [`SpawnCtx::admit_process`]. Unlike the PID-1 [`InitSpawn`] seam
//! (`init_spawn_x86_64.rs`) it does **not** switch CR3 or enter ring 3: the
//! spawning caller keeps running under its own root, and the child runs when
//! the scheduler next steps it (a true concurrent spawn, not an `exec`-style
//! hand-off, `AGENTS.md` §4).
//!
//! # Building the child without switching CR3
//!
//! The runtime `spawn` syscall is issued by PID 1 `init`, so the producer runs
//! under PID 1's own root, which [`init_spawn_x86_64`](crate::init_spawn_x86_64)
//! built with [`ArchAddressSpace::new_identity_first_gib`]: it identity-maps the
//! low [`IDENTITY_GIB`] GiB **and** mirrors the higher-half kernel window. The
//! x86_64 page-table walk recovers each existing intermediate table from its
//! **low physical address** (`paging::ensure_child`) and writes each new table
//! through its higher-half static pointer, and the image content is written
//! through a higher-half [`DirectPhysMap`] — all three are mapped under PID 1's
//! active root (the child pool is a `.bss` static and the live allocator's
//! frames are in the low identity window). So the producer builds the child's
//! tables *through the caller's active CR3*, never switching it, exactly as the
//! aarch64 producer builds through its identity window. The child's own CR3 is
//! reloaded by its `pre_resume` hook before the scheduler first resumes it
//! (`plans/SPAWN.md` SP2, `plans/PI.md` X1).
//!
//! Spawning is *not* a privileged bypass: the child receives only the authority
//! [`child_caps`] requests intersected with its user's grants (`AGENTS.md` §4,
//! §16.5); this seam only authorises the *act* of spawning under
//! `CAP_PROC_SPAWN`.

use core::sync::atomic::{AtomicUsize, Ordering};

use alloc::boxed::Box;

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery, Errno};
use rustos_arch_api::EnterUser;
use rustos_arch_x86_64::paging::{
    activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool, KERNEL_VMA_BASE,
};
use rustos_arch_x86_64::syscall_entry;
use rustos_arch_x86_64::userentry::UserMode;
use rustos_caps::CapabilitySet;
use rustos_kernel_core::{
    spawn_image, AdmitError, BoxStack, EmbeddedProgram, KernelStack, ProcessSpawn, ProgramRegistry,
    SpawnCallerError, SpawnCtx, SpawnRequest,
};
use rustos_kernel_mem::{AddressSpace, DirectPhysMap, PhysMap, UserAddressSpace, UserStack};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;

// `SHELL_RXE: &[u8]` and `SHELL_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/shell_rxe.rs"));

/// Logical CPU the boot processor runs as — the single core the (c7-bin)
/// bring-up initialises and the one [`syscall_entry::set_kernel_rsp0`]
/// repoints (mirrors `init_spawn_x86_64::BOOT_CPU`).
const BOOT_CPU: usize = 0;

/// Span of the direct physical map the spawn build writes frame contents
/// through: the `[0, 1 GiB)` physical window the boot trampoline mirrors at
/// [`KERNEL_VMA_BASE`] (`boot.s` SAFETY-INVARIANT 9), the same window PID 1
/// uses (`init_spawn_x86_64`).
const PHYSMAP_SPAN: u64 = 1 << 30;

/// Gigabytes of identity map each spawned child address space provides.
///
/// 4 GiB mirrors the boot trampoline's identity map and PID 1's space: it
/// covers all of the platform's RAM (so the page-table walk's low-physical
/// table dereferences and the live allocator's image frames resolve) and the
/// architectural LAPIC MMIO page at ~3.98 GiB (so the scheduler's LAPIC
/// accesses stay valid under the child's CR3 once it is resumed).
/// [`SHELL_USER_BIAS`] (64 GiB) sits far above it, so the program's pages land
/// on freshly walked tables rather than colliding with an identity huge page
/// — the same window PID 1 uses (`AGENTS.md` §2.2).
const IDENTITY_GIB: usize = 4;

/// Absolute path the `Shell` session program is registered under
/// (`AGENTS.md` §16.5 bundle layout). It must match exactly the `session`
/// path PID 1 `init` reads from its startup config and hands to the `spawn`
/// syscall (`userland/system/init/src/startup.rs`); the registry match is
/// byte-for-byte with no alias resolution (`AGENTS.md` §2.1). Identical to the
/// aarch64 producer's `SHELL_PATH` (`AGENTS.md` §2.2 — one path contract).
const SHELL_PATH: &[u8] = b"/Apps/Shell.app/Run";

/// User stack base (1 MiB into the high user region) and size, mirroring the
/// PID-1 layout (`init_spawn_x86_64.rs`): the `rustos-rt` runtime carves
/// scratch space off the stack, so it must comfortably exceed it.
const USER_STACK_BASE: u64 = SHELL_USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB), generous headroom over the runtime's scratch
/// span plus call frames.
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up, well
/// clear of the program image and the stack).
const USER_BLOCK_BASE: u64 = SHELL_USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to a spawned child (`AGENTS.md`
/// §19.2). Any value; the kernel RNG-seeded canary is a later stage.
const CHILD_CANARY: u64 = 0x1117_A5ED_C0DE_5E55;

/// Maximum number of processes the runtime `spawn` syscall can build before
/// the static page-table-pool reserve is exhausted (`plans/PI.md` `X3b`).
///
/// Each child's PML4 hierarchy is carved from its own [`PageTablePool`] (a
/// `.bss` reserve, monotonic and never freed, `AGENTS.md` §2.1), so the
/// reserve bounds how many distinct processes can be spawned this stage. A
/// real per-process page-table allocator over `kernel/mem` lifts this bound
/// later (`plans/WIRING.md`); for the `X3b` proving ground a small fixed reserve
/// is enough, and exhausting it fails closed with [`Errno::NoSpace`] rather
/// than panicking (`AGENTS.md` §2.9, §4). Mirrors the aarch64 producer.
const MAX_SPAWNS: usize = 8;

/// The static page-table-pool reserve backing spawned children's PML4
/// hierarchies. Lives in `.bss` for the lifetime of the kernel image, so a
/// child's CR3 keeps pointing at valid tables after it is admitted
/// (`AGENTS.md` §2.1 — monotonic, never freed).
static SPAWN_PAGE_TABLES: [PageTablePool; MAX_SPAWNS] =
    [const { PageTablePool::new() }; MAX_SPAWNS];

/// Monotonic cursor handing out the next free [`SPAWN_PAGE_TABLES`] pool.
/// `fetch_add` is the same lock-free, hand-out-once discipline
/// [`PageTablePool`] itself uses (`AGENTS.md` §2.1).
static SPAWN_POOL_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Claim the next free page-table pool, or [`None`] when the reserve is
/// exhausted (fail closed, `AGENTS.md` §2.9).
fn claim_pool() -> Option<&'static PageTablePool> {
    let idx = SPAWN_POOL_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= MAX_SPAWNS {
        // Saturate so a torrent of failed spawns cannot wrap the cursor.
        SPAWN_POOL_CURSOR.store(MAX_SPAWNS, Ordering::SeqCst);
        return None;
    }
    Some(&SPAWN_PAGE_TABLES[idx])
}

/// The embedded programs the `spawn` syscall can resolve: the `Shell` session
/// program PID 1 launches (`plans/PI.md` `X3b`). Its `rxe` is baked at build
/// time (`build.rs`), exactly like the aarch64 producer's registry
/// (`AGENTS.md` §2.2).
static SPAWN_PROGRAMS: [EmbeddedProgram; 1] = [EmbeddedProgram {
    path: SHELL_PATH,
    rxe: SHELL_RXE,
}];

/// The `'static` embedded-program registry the boot path installs through
/// `BootInfo::with_spawn`.
pub static X86_64_PROGRAM_REGISTRY: ProgramRegistry = ProgramRegistry::new(&SPAWN_PROGRAMS);

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege
/// [`spawn_image`] requires to authorise building a child image (`AGENTS.md`
/// §5.4). It does not widen the child's authority, which is [`child_caps`]
/// intersected with its user's grants (`AGENTS.md` §16.5).
struct SpawnAuthority;

impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// A spawned child's effective capability set: exactly `CAP_CONSOLE_WRITE`, so
/// the session program can write its banner through the `stream_write`
/// syscall. Passed as both the user grant and the manifest request, so the
/// intersection the kernel derives is the same set — the child is granted no
/// more (`AGENTS.md` §5.2), and never inherits the spawning caller's authority
/// (`AGENTS.md` §4 — no ambient authority). Identical to the aarch64 producer
/// (`AGENTS.md` §2.2).
fn child_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::CONSOLE_WRITE);
    caps
}

/// The x86_64 runtime `spawn` producer installed into the
/// [`rustos_kernel_core::BootInfo`] hand-off by `boot::try_boot`.
pub struct X86_64ProcessSpawn;

/// The single, `'static` [`X86_64ProcessSpawn`] the boot path borrows.
pub static X86_64_PROCESS_SPAWN: X86_64ProcessSpawn = X86_64ProcessSpawn;

impl ProcessSpawn for X86_64ProcessSpawn {
    fn spawn(&self, rxe: &[u8], ctx: &dyn SpawnCtx) -> Result<u64, Errno> {
        // Claim a fresh page-table pool for the child's PML4 hierarchy. An
        // exhausted reserve fails closed rather than building a process whose
        // tables alias another's (`AGENTS.md` §2.9, §4).
        let pool = claim_pool().ok_or(Errno::NoSpace)?;

        // Build a PML4 identity-mapping the low `IDENTITY_GIB` GiB (RAM + the
        // LAPIC MMIO page) and the higher-half kernel window, and capture its
        // root *without* switching CR3: the spawning caller (PID 1) stays
        // active under its own root, so the running parent is never moved out
        // from under itself. The child's tables and image are written through
        // the caller's active root — which identity-maps the child pool and
        // the live allocator's frames in the low window and mirrors the
        // higher-half kernel window the page-table walk and `DirectPhysMap`
        // use — so the build does not require the child space to be active.
        // The child's own CR3 is reloaded by its `pre_resume` hook before the
        // scheduler first resumes it (`plans/SPAWN.md` SP2, `plans/PI.md` X1).
        let arch =
            ArchAddressSpace::new_identity_first_gib(pool, IDENTITY_GIB).ok_or(Errno::NoSpace)?;
        let child_root_phys = arch.pml4_phys();

        // The child's kernel stack: the heap-backed software-canary
        // [`BoxStack`]. The hardware guard-page fault-form is aarch64-only so
        // far (`plans/PI.md` G-series; riscv64/x86_64 are honest `Pending`),
        // so x86_64 uses the software canary rather than ever running on an
        // unguarded stack (`AGENTS.md` §2.17). The heap is in the low identity
        // window, so the stack is reachable under the child's CR3.
        let kernel_stack: Box<dyn KernelStack + Send> = Box::new(BoxStack::new());

        let mut space = AddressSpace::new(arch);
        let physmap = DirectPhysMap::new(KERNEL_VMA_BASE, PHYSMAP_SPAN);

        // Parse the build-time `rxe` blob against the kernel's own compiled-in
        // syscall CFI tag (§9 / §19.2). A mismatch fails closed; the registry
        // holds bytes that already parsed once at build time, so reaching this
        // is a kernel build defect, surfaced as a stable errno.
        let image = LoadImage::parse(rxe, &SYSCALL_TABLE_HASH).map_err(|_| Errno::BadMagic)?;

        let request = SpawnRequest {
            image: &image,
            image_bytes: rxe,
            bias: SHELL_USER_BIAS,
            stack: UserStack {
                base: USER_STACK_BASE,
                page_count: USER_STACK_PAGES,
            },
            start_block_base: USER_BLOCK_BASE,
            args: &[b"shell"],
            env: &[],
            canary: CHILD_CANARY,
        };

        // Authorise + build the child's ring-3 image (emits `ProcessSpawned`).
        // SAFETY: building the image is itself safe; the returned `UserEntry`
        // is only entered later, once the child is dispatched and its
        // `pre_resume` hook has made `space` active (the `spawn_image`
        // contract). The frame source draws first-GiB RAM frames from the
        // kernel's live allocator, written through the higher-half `physmap`
        // mapped under the caller's active root. A returning `Err` reclaims
        // nothing user-visible (the pool/frames are monotonic kernel reserves)
        // and maps to a stable errno; the cause is already audited by
        // `spawn_image` (`AGENTS.md` §2.9).
        let frames = ctx.frames();
        let entry = unsafe {
            spawn_image(
                &SpawnAuthority,
                ctx.audit(),
                &mut space,
                &physmap,
                &request,
                move || frames.alloc().ok(),
            )
        }
        .map_err(spawn_caller_errno)?;

        // The child's user-address-space reactivation hook (`plans/SPAWN.md`
        // SP2, `plans/PI.md` X1): the core runs it on the dispatcher's context
        // immediately before every switch into the child. It reloads CR3 to
        // the child's own root (isolation §4) and repoints the per-CPU
        // `syscall` entry stack at the child's own kernel stack (the value the
        // runtime hands it). It captures only the `u64` root, so it is `Send`.
        let pre_resume: Box<dyn FnMut(u64) + Send> = Box::new(move |stack_top: u64| {
            // Repoint the per-CPU syscall entry stack before the switch-in. A
            // rejected value (it is validated canonical/aligned/kernel-half)
            // leaves the slot unchanged and the next syscall faults loudly —
            // fail closed, never a silent wrong stack (`AGENTS.md` §5.4 /
            // §2.9).
            let _ = syscall_entry::set_kernel_rsp0(BOOT_CPU, stack_top);
            // SAFETY: paging is enabled and `child_root_phys` is the PML4 of
            // the child's space, which identity-maps the low kernel window the
            // running dispatcher executes from and mirrors the higher-half
            // kernel window — exactly `activate_user_root`'s contract.
            unsafe { activate_user_root(child_root_phys) };
        });

        // The user-mode transition, boxed for the scheduler task body the core
        // wraps the child in. `enter_user` diverges into ring 3, so the
        // closure never truly returns (its `!` coerces to `()`).
        let user_mode = UserMode::new();
        let enter: Box<dyn FnMut() + Send> = Box::new(move || {
            // SAFETY: by the time this body runs the child has been
            // dispatched, so its `pre_resume` hook has activated `space` and
            // the `syscall` entry + production dispatch callback are installed;
            // the child's first `syscall` is handled. `build_process_image`
            // mapped the entry/stack as user pages.
            unsafe { user_mode.enter_user(entry) }
        });

        // Freeze the just-built mappings into the registry-storable,
        // `Send + Sync` snapshot the kernel-wide address-space registry holds
        // (the live arch `space` is not `Sync`), and box the direct map that
        // backs it, so the child's `stream_write` can copy its banner out of
        // its own user memory. Freezing *after* `spawn_image` captures every
        // mapped page — segments, stack, and the startup-vector block.
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());
        let physmap: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);

        // Register the child's caps + frozen address space and admit it Ready,
        // returning its PID. The spawning caller keeps running.
        // SAFETY: `frozen` faithfully describes the mappings just built into
        // `space`, `physmap` backs them, `pre_resume` activates the child's
        // root before it is first entered, and `kernel_stack` is a region
        // exclusive to this child that stays mapped (in the low identity
        // window) for the task's lifetime — the `admit_process` contract.
        unsafe {
            ctx.admit_process(
                child_caps(),
                frozen,
                physmap,
                kernel_stack,
                pre_resume,
                enter,
            )
        }
        .map_err(admit_errno)
    }
}

/// Map a [`SpawnCallerError`] onto a stable [`Errno`] for the `spawn` syscall's
/// caller (`AGENTS.md` §2.9). The precise cause is already on the audit log via
/// the `ProcessSpawn*` events `spawn_image` emits. Identical to the aarch64
/// producer (`AGENTS.md` §2.2).
fn spawn_caller_errno(err: SpawnCallerError) -> Errno {
    match err {
        // A missing `CAP_PROC_SPAWN` (cannot occur — the dispatcher already
        // gated the syscall — but mapped for completeness).
        SpawnCallerError::Denied => Errno::PermissionDenied,
        // Image construction failed (a frame/pool exhaustion, a malformed
        // segment, an over-size startup block). One stable resource errno.
        SpawnCallerError::Build(_) => Errno::NoSpace,
        // `SpawnCallerError` is `#[non_exhaustive]`: any future variant fails
        // closed to the same stable resource errno (`AGENTS.md` §2.9).
        _ => Errno::NoSpace,
    }
}

/// Map an [`AdmitError`] onto a stable [`Errno`] (`AGENTS.md` §2.9).
fn admit_errno(err: AdmitError) -> Errno {
    match err {
        AdmitError::SchedulerFull => Errno::NoSpace,
        AdmitError::AspaceConflict => Errno::AlreadyExists,
        // `AdmitError` is `#[non_exhaustive]`: any future variant fails closed
        // to a stable resource errno (`AGENTS.md` §2.9).
        _ => Errno::NoSpace,
    }
}
