//! Shared user-space layout constants for the PID 1 (`init`) spawn seam
//! and the runtime `spawn` producer.
//!
//! Every architecture port lays its first user program — and every child
//! the `spawn` syscall builds — out at the *same* offsets above the
//! build-time image bias, with the *same* stack/MMIO-window sizing and the
//! *same* canary seeds. Those values are equal across the ports by
//! definition (they describe one user-space layout, not a per-architecture
//! register layout), so they live here once rather than being copy-pasted
//! into each `init_spawn` / `spawn_producer` sibling.
//!
//! The image bias itself (`INIT_USER_BIAS` / `SHELL_USER_BIAS`) is *not*
//! here: it is baked per embedded program by `build.rs`, so it genuinely
//! belongs beside each consumer. The absolute bases are derived as
//! `bias + <offset>` at each call site.
//!
//! This module is also the single home for the data that is equal across
//! every port *by definition*: the registry of embedded
//! programs the runtime `spawn` syscall resolves (their absolute paths,
//! manifest∩user capability sets, and startup-argument vectors), the
//! `CAP_PROC_SPAWN` [`SpawnAuthority`] every spawn seam authorises under,
//! and PID 1 `init`'s own grant and argument vector. The per-port
//! `ProcessSpawn` / `InitSpawn` implementations (the architecture paging
//! glue) are the deliberate trait carve-out and stay beside each port;
//! the values they *consume* live here once.

use rustos_abi::{CapabilityId, CapabilityQuery};
use rustos_caps::CapabilitySet;
use rustos_kernel_core::{EmbeddedProgram, ProgramRegistry};

use crate::program_manifests::{
    DEVMGR_MANIFEST, INIT_MANIFEST, LOGIN_MANIFEST, LS_MANIFEST, MAN_MANIFEST, PS_MANIFEST,
    SESSION_BASELINE, SYSINFOD_MANIFEST, SYSINFO_MANIFEST, TOP_MANIFEST, USERS_TOOL_MANIFEST,
};

// `SHELL_RXE: &[u8]` and `SHELL_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/shell_rxe.rs"));
// `LOGIN_RXE: &[u8]` and `LOGIN_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/login_rxe.rs"));
// `DEVMGR_RXE: &[u8]` and `DEVMGR_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/devmgr_rxe.rs"));
// `SYSINFOD_RXE: &[u8]` and `SYSINFOD_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/sysinfod_rxe.rs"));
// `PS_RXE: &[u8]` and `PS_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/ps_rxe.rs"));
// `SYSINFO_RXE: &[u8]` and `SYSINFO_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/sysinfo_rxe.rs"));
// `TOP_RXE: &[u8]` and `TOP_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/top_rxe.rs"));
// `LS_RXE: &[u8]` and `LS_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/ls_rxe.rs"));
// `MAN_RXE: &[u8]` and `MAN_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/man_rxe.rs"));
// `USERS_CLI_RXE: &[u8]` and `USERS_CLI_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/users_cli_rxe.rs"));

// Every embedded program is relocated for the one shared user bias
// (`build.rs` `USER_BIAS`); every port maps each child at
// [`SHELL_USER_BIAS`], so a fixture baked for a different bias is a build
// defect caught at compile time rather than a child whose pointers do not
// match where it is mapped.
const _: () = assert!(LOGIN_USER_BIAS == SHELL_USER_BIAS);
const _: () = assert!(DEVMGR_USER_BIAS == SHELL_USER_BIAS);
const _: () = assert!(SYSINFOD_USER_BIAS == SHELL_USER_BIAS);
const _: () = assert!(PS_USER_BIAS == SHELL_USER_BIAS);
const _: () = assert!(SYSINFO_USER_BIAS == SHELL_USER_BIAS);
const _: () = assert!(TOP_USER_BIAS == SHELL_USER_BIAS);
const _: () = assert!(LS_USER_BIAS == SHELL_USER_BIAS);
const _: () = assert!(MAN_USER_BIAS == SHELL_USER_BIAS);
const _: () = assert!(USERS_CLI_USER_BIAS == SHELL_USER_BIAS);

// The registered program paths live in `spawn_paths` (pure data, so its
// store-spelling drift test runs on the CI host); this module binds each
// path to its baked rxe, manifest, and argument vector.
pub use crate::spawn_paths::{
    DEVMGR_PATH, LOGIN_PATH, LS_PATH, MAN_PATH, PS_PATH, SHELL_PATH, SYSINFOD_PATH, SYSINFO_PATH,
    TOP_PATH, USERS_CLI_PATH,
};

/// The embedded programs the runtime `spawn` syscall can resolve, each
/// carrying the capability set its manifest requests and its
/// startup-argument vector: the login service PID
/// 1 launches as the per-console session supervisor (`plans/PI.md` P11), and
/// the `Shell` session program login spawns as an authenticated user's shell
/// of choice (`plans/SPAWN.md` `SP3b`). The `rxe`s are baked at build time
/// (`build.rs`).
///
/// Each row's request is the shared, pinned manifest list from
/// [`crate::program_manifests`] (`plans/CAPABILITY_USE.md` CU2): the shell
/// requests the session baseline; login is the one privileged
/// spawn-as-user holder; each service and tool requests exactly what it
/// exercises. The rationale for every list lives on the manifest constant
/// it names.
///
/// This registry is identical across every port by definition, so it is
/// defined once here and shared rather than copy-pasted into each port's
/// `spawn_producer` sibling.
pub static SPAWN_PROGRAMS: [EmbeddedProgram; 10] = [
    EmbeddedProgram {
        path: SHELL_PATH,
        rxe: SHELL_RXE,
        caps: SESSION_BASELINE,
        args: &[b"shell"],
    },
    EmbeddedProgram {
        path: LOGIN_PATH,
        rxe: LOGIN_RXE,
        caps: LOGIN_MANIFEST,
        args: &[b"login"],
    },
    EmbeddedProgram {
        path: DEVMGR_PATH,
        rxe: DEVMGR_RXE,
        caps: DEVMGR_MANIFEST,
        args: &[b"devmgr"],
    },
    EmbeddedProgram {
        path: SYSINFOD_PATH,
        rxe: SYSINFOD_RXE,
        caps: SYSINFOD_MANIFEST,
        args: &[b"sysinfod"],
    },
    EmbeddedProgram {
        path: PS_PATH,
        rxe: PS_RXE,
        caps: PS_MANIFEST,
        args: &[b"ps"],
    },
    EmbeddedProgram {
        path: SYSINFO_PATH,
        rxe: SYSINFO_RXE,
        caps: SYSINFO_MANIFEST,
        args: &[b"sysinfo"],
    },
    EmbeddedProgram {
        path: TOP_PATH,
        rxe: TOP_RXE,
        caps: TOP_MANIFEST,
        args: &[b"top"],
    },
    EmbeddedProgram {
        path: LS_PATH,
        rxe: LS_RXE,
        caps: LS_MANIFEST,
        args: &[b"ls"],
    },
    EmbeddedProgram {
        path: MAN_PATH,
        rxe: MAN_RXE,
        caps: MAN_MANIFEST,
        args: &[b"man"],
    },
    EmbeddedProgram {
        path: USERS_CLI_PATH,
        rxe: USERS_CLI_RXE,
        caps: USERS_TOOL_MANIFEST,
        args: &[b"users"],
    },
];

/// The `'static` embedded-program registry every port's boot path installs
/// through `BootInfo::with_spawn`. One shared registry over the shared
/// [`SPAWN_PROGRAMS`].
pub static PROGRAM_REGISTRY: ProgramRegistry = ProgramRegistry::new(&SPAWN_PROGRAMS);

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege
/// the spawn callers (`spawn_image` for a runtime child, `spawn_and_enter`
/// for PID 1) require to authorise building a child image. It does not widen the child's authority, which is its registered
/// program's declared set intersected with its user's grants. Shared by every port's `spawn_producer` and `init_spawn` seam
/// rather than redefined in each.
pub struct SpawnAuthority;

impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// PID 1 `init`'s startup-argument vector. Shared across the ports.
pub const INIT_ARGS: &[&[u8]] = &[b"init"];

/// PID 1 `init`'s effective capability set, built from the shared, pinned
/// [`crate::program_manifests::INIT_MANIFEST`] (`plans/PI.md` P6a/P6b,
/// `plans/SPAWN.md` `SP3b`). The boot path passes this as both the user
/// grant and the manifest request, so the intersection the kernel derives
/// is the same set — `init` is granted no more. Spawning is not ambient
/// authority: the child PID 1 launches receives only *its own*
/// manifest∩user-grant set, never `init`'s. The set
/// is identical across the ports, so it is built here once.
pub fn init_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    for cap in INIT_MANIFEST {
        caps.insert(*cap);
    }
    caps
}

/// Offset of the user stack base above the image bias (1 MiB into the high
/// user region). The `rustos-rt` runtime carves scratch space off the
/// stack, so the stack must comfortably exceed it.
pub const USER_STACK_OFFSET: u64 = 0x10_0000;

/// User stack pages (1.125 MiB): generous headroom over the runtime's
/// scratch span plus call frames.
pub const USER_STACK_PAGES: u64 = 288;

/// Offset of the startup-vector block above the image bias (3 MiB up, well
/// clear of the program image and the stack).
pub const USER_BLOCK_OFFSET: u64 = 0x30_0000;

/// Offset of the device-window virtual region above the image bias
/// (`plans/PI.md` 5d-0-ii (b′)): placed 1 GiB above the image bias — far
/// clear of the program image, stack, and startup block, and the lowest of
/// the four guarded windows.
///
/// Every port retains a live address space and grants its tasks an
/// `mmio_map` device window out of this region, so the offset — shared by
/// each port's `init_spawn` and `spawn_producer` — is
/// one value, not a per-port copy.
pub const MMIO_WINDOW_OFFSET: u64 = 0x4000_0000;

/// Pages backing the device-window region (1 MiB): generous headroom over
/// the few device windows a driver task maps.
pub const MMIO_WINDOW_PAGES: usize = 256;

/// Offset of the guarded DMA-buffer virtual window above the image bias
/// (`plans/PI.md` 5d-0-ii (c) DMA half): placed 2 GiB above the bias — above
/// the device window (1 GiB up) and far clear of the program image, stack,
/// and startup block. The `dma_alloc` carve hands each request a
/// guard-bracketed buffer out of `[bias + DMA_WINDOW_OFFSET, … +
/// DMA_WINDOW_PAGES·4 KiB)`. One value shared by every port for the same
/// reason as [`MMIO_WINDOW_OFFSET`].
pub const DMA_WINDOW_OFFSET: u64 = 0x8000_0000;

/// Pages backing the DMA-buffer window (1 MiB): generous headroom over the
/// few small coherent buffers a driver task carves (a DMA
/// buffer is bounded to the [`rustos_kernel_mem::MAX_ORDER`] 8 MiB block).
pub const DMA_WINDOW_PAGES: usize = 256;

/// Offset of the cross-process shared-memory virtual window above the image
/// bias: placed 3 GiB above the bias — above the DMA window (which spans
/// `[2 GiB, 2 GiB + 1 MiB)`) and far clear of the program image, stack,
/// startup block, and the device and DMA windows below it. The
/// `shm_create` / `shm_map` syscalls map a granted shared region out of
/// `[bias + SHARED_WINDOW_OFFSET, ... + SHARED_WINDOW_PAGES * 4 KiB)`. One
/// value shared by every port for the same reason as [`MMIO_WINDOW_OFFSET`].
pub const SHARED_WINDOW_OFFSET: u64 = 0xC000_0000;

/// Pages backing the shared-memory window (1 MiB): generous headroom over
/// the few small shared regions a driver task maps (an URB data buffer is
/// a handful of pages).
pub const SHARED_WINDOW_PAGES: usize = 256;

/// Offset of the non-`FIXED` anonymous-heap virtual window above the image
/// bias (`plans/PI.md` 5d-0-ii (c)): placed 4 GiB above the bias — the
/// **topmost** of the four guarded windows, above the device (1 GiB), DMA
/// (2 GiB), and shared-memory (3 GiB) windows and far clear of the program
/// image, stack, and startup block. It is highest so it can extend upward
/// toward the per-architecture user-VA ceiling without colliding with a
/// fixed-size sibling — the room that lets the heap window scale with
/// discovered RAM (see [`crate::anon_layout::anon_window_pages`]). The
/// `mem_map` placement allocator hands each non-`FIXED` request a base out
/// of `[bias + ANON_WINDOW_OFFSET, … + anon_window_pages·4 KiB)`. One value
/// shared by every port for the same reason as [`MMIO_WINDOW_OFFSET`].
pub const ANON_WINDOW_OFFSET: u64 = 0x1_0000_0000;

/// Per-process stack-canary seed handed to PID 1 `init`. Any value; the kernel RNG-seeded canary is a later stage.
pub const INIT_CANARY: u64 = 0x1117_A5ED_C0DE_0001;

/// Per-process stack-canary seed handed to a spawned child. Any value; the kernel RNG-seeded canary is a later stage.
pub const CHILD_CANARY: u64 = 0x1117_A5ED_C0DE_5E55;
