//! The freestanding aarch64 test kernel: spawn one runaway EL0 spinner and
//! prove the production generic-timer IRQ involuntarily preempts it
//! (`plans/PI.md` D2b-2b-A P-1).

use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU64, AtomicUsize, Ordering};

use alloc::sync::Arc;

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery, SyscallNumber, SYSCALL_MAX_ARGS};
use rustos_arch_aarch64::context_hal::ContextSwitchHal;
use rustos_arch_aarch64::kernel_arch::timer_frequency_hz;
use rustos_arch_aarch64::paging::{
    self, activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool,
};
use rustos_arch_aarch64::preempt::{self, PreemptStorage};
use rustos_arch_aarch64::userentry::UserMode;
use rustos_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, SERIAL_SINK,
};
use rustos_arch_api::{CpuId, EnterUser};
use rustos_bumpalloc::BumpAllocator;
use rustos_fdt::Fdt;
use rustos_kernel_core::{
    reschedule_current, spawn_image, spawn_user_kthread, RescheduleAction, SpawnRequest, Yielder,
};
use rustos_kernel_mem::{AddressSpace, DirectPhysMap, Frame, PhysAddr, UserStack};
use rustos_kernel_sched_eevdf::{Priority, Scheduler, SchedulerConfig};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;
use rustos_log::{log, Event, EventId, Level};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// The single-core slice runs logical CPU 0 on the boot core.
const BOOT_CPU: CpuId = 0;

/// Preemption tick rate (hertz). A fast tick so the runaway spinner is
/// preempted promptly under QEMU TCG; the spinner's loop spans many ticks.
const PREEMPT_TICK_HZ: u64 = 100;

/// Gigabytes of identity map the EL0 address space provides: `[0, 2 GiB)`
/// covers the `virt` board device MMIO (GiB 0) and the RAM base at GiB 1 where
/// this kernel runs, so switching into the space never moves the ground under
/// the running kernel.
const IDENTITY_GIB: usize = 2;

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (256 KiB).
const USER_STACK_PAGES: u64 = 64;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program (`AGENTS.md` §19.2).
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the spawn build draws from: the program's segments, its
/// user stack, and the startup block, with headroom.
const FRAME_COUNT: usize = 256;

/// `step`-loop watchdog: maximum iterations before declaring the workload
/// stuck. Each iteration is one preemption quantum; sized generously for TCG.
const MAX_STEPS: u64 = 50_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4280);
const TEST_SPAWNED: EventId = EventId(4281);
const TEST_PASS: EventId = EventId(4282);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: u16 = 1;
const FAIL_GIC_NOT_DISCOVERED: u16 = 2;
const FAIL_POOL: u16 = 3;
const FAIL_PARSE: u16 = 4;
const FAIL_BUILD: u16 = 5;
const FAIL_SCHED_NEW: u16 = 6;
const FAIL_SPAWN: u16 = 7;
const FAIL_DEADLOCK: u16 = 8;
const FAIL_NO_PREEMPT: u16 = 9;
const FAIL_PREEMPT_STORAGE: u16 = 10;
const FAIL_UNEXPECTED_SYSCALL: u16 = 11;

/// Count of involuntary timer-driven preemptions of the running EL0 task.
static PREEMPTIONS: AtomicU64 = AtomicU64::new(0);
/// `exit` syscalls observed (the spinner exits exactly once on completion).
static EXITS: AtomicU64 = AtomicU64::new(0);

/// Bump-heap size: the spawn caller allocates the startup-vector block buffer
/// and the user kthread's kernel stack + control block from it.
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: BumpAllocator =
    unsafe { BumpAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the EL0 address space's stage-1 hierarchy.
static PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Per-CPU preemption backing for the single boot CPU (`AGENTS.md` §24.1 —
/// `PreemptStorage<1>` covers a single-core slice).
static PREEMPT_STORAGE: PreemptStorage<1> = PreemptStorage::new();

/// Physical-frame backing store the spawn builder allocates user pages from.
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next identity-mapped physical frame from [`FRAME_POOL`], or
/// `None` when the pool is exhausted (the spawn builder then fails closed).
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    // The pool is identity-mapped, so its kernel virtual address is also its
    // physical address.
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn preempt_el0_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires (`AGENTS.md` §5.4).
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The EL0-preemption callback the timer IRQ path invokes for a tick taken
/// from EL0 — the production dispatch shape verbatim (`AGENTS.md` §2.2): it
/// suspends the running user task back to the scheduler via
/// `reschedule_current(_, Yield)`, the involuntary analogue of a `yield`
/// syscall. It records each preemption so the test can prove at least one
/// fired against the never-yielding spinner.
extern "C" fn preempt_dispatch(cpu: CpuId) {
    PREEMPTIONS.fetch_add(1, Ordering::SeqCst);
    let _ = reschedule_current(cpu, RescheduleAction::Yield);
}

/// The syscall-dispatch callback the spinner's final `exit` `svc` reaches.
///
/// The spinner issues no `yield`; its only syscall is the `exit` that
/// `rustos-rt` routes `main`'s return through. Any other syscall is unexpected
/// and fails the test loudly (`AGENTS.md` §7).
extern "C" fn dispatch(number: u64, _args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    #[allow(clippy::cast_possible_truncation)]
    let raw = number as u16;
    if raw == SyscallNumber::EXIT.as_u16() {
        EXITS.fetch_add(1, Ordering::SeqCst);
        // Reap the caller: this switches back to the dispatcher and never
        // resumes the task, so the `0` below is unreachable.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
        0
    } else {
        note(TEST_START, "fixture program issued an unexpected syscall");
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// Build the isolated EL0 address space from the fixture `image` over
/// [`PAGE_TABLES`], returning its stage-1 root and the entry register state.
fn build_el0_space(image: &LoadImage) -> (u64, rustos_arch_api::UserEntry) {
    let Some(arch) = ArchAddressSpace::new_identity_gigapages(&PAGE_TABLES, IDENTITY_GIB) else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // Capture the root before the arch space is moved into the `kernel/mem`
    // wrapper, so the `pre_resume` hook can reactivate `TTBR0_EL1` with it.
    let root_phys = arch.root_phys();
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
    // heap, the frame pool, and the device MMIO (all within `[0, 2 GiB)` on the
    // `virt` board), so enabling it does not move the ground under the running
    // code — exactly `AddressSpace::switch`'s contract. Called on the boot CPU.
    unsafe { arch.switch() };

    let mut space = AddressSpace::new(arch);
    let physmap = DirectPhysMap::identity((IDENTITY_GIB as u64) << 30);
    let request = SpawnRequest {
        image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"el0"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once its space is reactivated (via the `pre_resume`
    // hook) and the EL1 trap path is installed. The frame source draws
    // identity-mapped frames from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => qemu_exit::exit_failure(FAIL_BUILD),
    };
    (root_phys, entry)
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `rustos_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 EL0 preemption test: starting");

    // Enable FP/SIMD at EL1 before any code that may use it (the `rxe` decoder
    // and `build_process_image`'s fills compile to NEON `memcpy`/`memcmp`).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    // P3/P4: discover the board from the embedded `virt` device tree.
    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC_NOT_DISCOVERED);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC_NOT_DISCOVERED);
    }

    // Parse the build-time `rxe` blob once against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    // Build the isolated EL0 address space (it leaves its own space active).
    let (root_phys, entry) = build_el0_space(&image);

    // Bring up the EL1 vectors + GICv2 and install the dispatch callback so the
    // spinner's `exit` `svc` is handled.
    // SAFETY: called once on the boot CPU with a stack established and the MMU
    // enabled (the address-space build switched it on).
    unsafe {
        exceptions::init_vectors();
        gic::init();
    }
    syscall_entry::set_dispatch_callback(dispatch);

    // Arm the production preemption path verbatim (`AGENTS.md` §2.2): register
    // the per-CPU storage, install the EL0-preemption callback, and start the
    // periodic generic timer. EL0 runs preemptible (`SPSR_EL0T_PREEMPTIBLE`),
    // so a tick taken while the spinner is in EL0 drives `preempt_dispatch`.
    if PREEMPT_STORAGE.register().is_err() {
        qemu_exit::exit_failure(FAIL_PREEMPT_STORAGE);
    }
    preempt::set_preempt_callback(preempt_dispatch);
    let interval = preempt::interval_for_hz(counter_hz, PREEMPT_TICK_HZ);
    // SAFETY: the boot CPU (id 0); the preempt callback is installed (above),
    // the per-CPU storage is registered (above), the EL1 vector table is
    // installed (`init_vectors`), and the GIC is up (`gic::init`). This enables
    // the timer PPI and starts the down-counter. PE IRQs stay masked at EL1, so
    // no tick is taken until the spinner runs in preemptible EL0.
    unsafe {
        preempt::init_local_preempt(BOOT_CPU, interval);
    }

    // Build the live scheduler over the arch port. Per-CPU bookkeeping backing
    // for this single-CPU vertical (`AGENTS.md` §24.1).
    static ARCH_STORAGE: rustos_arch_aarch64::Aarch64ArchStorage<1> =
        rustos_arch_aarch64::Aarch64ArchStorage::new();
    let arch = Arc::new(rustos_arch_aarch64::Aarch64Arch::new(
        &ARCH_STORAGE,
        BOOT_CPU,
        counter_hz,
    ));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    // Admit the spinner as a resumable user kthread: its `pre_resume` hook
    // reactivates its page-table root (isolation, §4), and its work body
    // `enter_user`s into EL0.
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |_stack_top: u64| {
        // SAFETY: the MMU is enabled and `root_phys` is the L1 root of a space
        // that identity-maps the low kernel window the running kernel executes
        // from — exactly `activate_user_root`'s contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: the entered space is active (the `pre_resume` hook just
        // reactivated it) and the EL1 trap vector + dispatch callback are
        // installed, so the program's `exit` `svc` is handled.
        unsafe { user_mode.enter_user(entry) }
    };
    if spawn_user_kthread(&sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work).is_err() {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(TEST_SPAWNED, "aarch64 EL0 preemption test: spinner spawned");

    // Dispatch loop: drive `step` until the spinner exits. The spinner never
    // yields, so each `step` enters it into EL0 where it busy-loops until a
    // timer tick preempts it (the preempt callback `reschedule_current`s back
    // here) — or, on the final quantum, until it finishes the loop and `exit`s.
    // A preemption that never fires would leave `step` spinning forever inside
    // EL0 and the harness would time out (fail-loud, `AGENTS.md` §7).
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }
    if sched.live_task_count() != 0 {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    // The runaway loop never yielded, so the only thing that returned control
    // to the dispatcher before `exit` is an involuntary preemption: at least
    // one must have fired, proving the timer IRQ preempts a non-cooperative
    // EL0 task.
    if PREEMPTIONS.load(Ordering::SeqCst) == 0 {
        qemu_exit::exit_failure(FAIL_NO_PREEMPT);
    }
    if EXITS.load(Ordering::SeqCst) != 1 {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }

    note(
        TEST_PASS,
        "aarch64 EL0 preemption test: runaway EL0 task involuntarily preempted and resumed to exit",
    );
    qemu_exit::exit_success();
}
