//! Build script for the wasm32 framebuffer-display browser vertical
//! (`plans/WIRING.md` — the wasm32 `display`-row parity gap).
//!
//! It does the one host-side job the vertical needs: sign a synthetic
//! framebuffer-driver `.rxe` manifest requesting exactly
//! [`CapabilityId::DRV_LOAD`] with a deterministic test seed, and emit a
//! Rust source file the `cdylib` pulls in via `include!`. Unlike the
//! bare-metal `framebuffer_display_qemu_*` verticals there is no linker
//! script: a `wasm32-unknown-unknown` `cdylib` is laid out by the
//! WebAssembly object format, not a per-arch script.
//!
//! The manifest requests only `CAP_DRV_LOAD`: the vertical's in-process
//! spawner gates on it (the load-time check a spawned `Run` process
//! clears through the driver-host gate), and the host
//! installs the manifest's requested set intersected with the caller's
//! grants. The `CAP_MMIO_MAP` the surface mapping
//! additionally requires is granted on the separate `DriverHost` the
//! `cdylib` builds for `Framebuffer::open`, never through the manifest,
//! mirroring how the bus-driver verticals separate the load gate from
//! the map gate.
//!
//! Re-running `build.rs` produces byte-identical output for the same
//! seed; the test is therefore deterministic.

use ed25519_dalek::{Signer, SigningKey};
use rustos_abi::{CapabilityId, DriverKind, DriverManifest, DRIVER_MANIFEST_MAGIC};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

/// Deterministic signing seed so the trust anchor is stable across
/// builds. Distinct from the other fixtures' seeds so the images cannot
/// be confused. The bytes spell `"fbwasmdisplay…"`.
const TEST_SEED: [u8; 32] = [
    0x66, 0x62, 0x77, 0x61, 0x73, 0x6d, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x71, 0x2e, 0x84,
    0x19, 0x6a, 0x3d, 0xc7, 0x52, 0xab, 0x90, 0x1f, 0x68, 0xd4, 0x0b, 0x37, 0xe2, 0x5c, 0x41, 0x9d,
];

/// SHA-256 fingerprint of the host's syscall table. The concrete value
/// is irrelevant; both sides feed the same value into the `HostConfig`.
const SYS_HASH: [u8; 32] = [0x33; 32];

fn main() {
    rustos_itest_harness::emit_target_cfg();
    println!("cargo:rerun-if-changed=build.rs");

    let signing_key = SigningKey::from_bytes(&TEST_SEED);
    let signer_pubkey: [u8; 32] = signing_key.verifying_key().to_bytes();

    // The framebuffer driver's `register` entry checks `CAP_DRV_LOAD`.
    // The effective set is the intersection of the loading user's grants
    // and this manifest request, so name it here as well as on the caller.
    let caps: &[u16] = &[CapabilityId::DRV_LOAD.as_u16()];
    let mut manifest = DriverManifest {
        magic: DRIVER_MANIFEST_MAGIC,
        abi_version: rustos_abi::ABI_VERSION_CURRENT,
        kind: DriverKind::UserSpace,
        bind_key_count: 0,
        capability_count: u16::try_from(caps.len()).expect("caps fit in u16"),
        syscall_table_hash: SYS_HASH,
        signer_pubkey,
        signature: [0u8; 64],
    };
    let encoded = manifest.to_le_bytes();
    let mut signed_message = Vec::with_capacity(DriverManifest::WIRE_LEN - 64 + caps.len() * 2);
    signed_message.extend_from_slice(&encoded[..DriverManifest::WIRE_LEN - 64]);
    for c in caps {
        signed_message.extend_from_slice(&c.to_le_bytes());
    }
    let sig = signing_key.sign(&signed_message);
    manifest.signature = sig.to_bytes();

    let mut image: Vec<u8> = Vec::new();
    image.extend_from_slice(&manifest.to_le_bytes());
    for c in caps {
        image.extend_from_slice(&c.to_le_bytes());
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// Signed framebuffer-driver `.rxe` image bytes.\n");
    out.push_str("pub const FB_IMAGE: &[u8] = &[");
    for (i, b) in image.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// Trust-anchor public key the host's `HostConfig` accepts.\n");
    out.push_str("pub const TRUSTED_SIGNER_PUBKEY: [u8; 32] = [");
    for (i, b) in signer_pubkey.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// SHA-256 fingerprint of the host's syscall table.\n");
    out.push_str("pub const SYSCALL_TABLE_HASH: [u8; 32] = [");
    for (i, b) in SYS_HASH.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");
    let path = PathBuf::from(out_dir).join("fb_fixture.rs");
    fs::write(&path, out).expect("write fb_fixture.rs");
}
