//! The freestanding riscv64 test kernel: spawn one runaway U-mode spinner and
//! prove the production supervisor-timer interrupt involuntarily preempts it
//! (`plans/PI.md` D2b-2b-A P-1b, the riscv64 sibling of
//! `preempt_el0_qemu_aarch64`).

use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU32, AtomicU64, AtomicUsize, Ordering};

use alloc::sync::Arc;

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery, SyscallNumber, SYSCALL_MAX_ARGS};
use rustos_arch_api::{CpuId, EnterUser, UserEntry};
use rustos_arch_riscv64::context_hal::ContextSwitchHal;
use rustos_arch_riscv64::fdt::Fdt;
use rustos_arch_riscv64::paging::{self, activate_user_root, AddressSpace as ArchAddressSpace};
use rustos_arch_riscv64::preempt::{self, PreemptStorage};
use rustos_arch_riscv64::userentry::UserMode;
use rustos_arch_riscv64::{
    handle_panic_via_serial, qemu_exit, syscall_entry, trap, RiscvArch, RiscvArchStorage,
    SERIAL_SINK,
};
use rustos_bumpalloc::{BumpAllocator, Heap, HEAP_BYTES};
use rustos_kernel_core::{
    reschedule_current, spawn_image, spawn_user_kthread, RescheduleAction, SpawnRequest, Yielder,
};
use rustos_kernel_mem::{AddressSpace, DirectPhysMap, Frame, PhysAddr, UserStack};
use rustos_kernel_sched_eevdf::{Priority, Scheduler, SchedulerConfig};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;
use rustos_log::{log, Event, EventId, Level};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// The single-hart slice runs logical CPU 0 on the boot hart.
const BOOT_CPU: CpuId = 0;

/// Preemption tick rate (hertz). Matches the production rate
/// (`rustos_kernel::riscv64::boot::PREEMPT_TICK_HZ`): a fast tick so the
/// runaway spinner is preempted promptly under QEMU TCG; the spinner's loop
/// spans many ticks.
const PREEMPT_TICK_HZ: u64 = 100;

/// Gigabytes of identity map the U-mode address space provides: `[0, 4 GiB)`
/// covers the `virt` board's low MMIO and the RAM base where this kernel runs,
/// so switching into the space never moves the ground under the running kernel.
/// [`USER_BIAS`] (64 GiB) sits far above, on freshly walked Sv39 tables.
const IDENTITY_GIGABYTES: usize = 4;

/// User stack base (1 MiB into the high user region) and size. `rustos-rt`
/// carves scratch space off the stack, so it must comfortably exceed it.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB > the runtime's scratch span plus call frames).
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program (`AGENTS.md` §19.2).
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the spawn build draws from: the program's segments, its
/// user stack, and the startup block, with headroom. The page-table frames
/// come from the per-space [`paging::PageTablePool`], not from here.
const FRAME_COUNT: usize = 384;

/// `step`-loop watchdog: maximum iterations before declaring the workload
/// stuck. Each iteration is one preemption quantum; sized generously for TCG.
const MAX_STEPS: u64 = 50_000_000;

/// Stable audit-event ids for the QEMU transcript (clear of the `4000..5000`
/// `kernel/core` boot range).
const TEST_START: EventId = EventId(4328);
const TEST_SPAWNED: EventId = EventId(4329);
const TEST_PASS: EventId = EventId(4330);
const TEST_FAIL: EventId = EventId(4331);

/// `SiFive` Test failure codes, distinct per failure site.
const FAIL_NO_TIMEBASE: u16 = 1;
const FAIL_UNEXPECTED_HART: u16 = 2;
const FAIL_POOL: u16 = 3;
const FAIL_PARSE: u16 = 4;
const FAIL_BUILD: u16 = 5;
const FAIL_SCHED_NEW: u16 = 6;
const FAIL_SPAWN: u16 = 7;
const FAIL_UNEXPECTED_SYSCALL: u16 = 8;
const FAIL_DEADLOCK: u16 = 9;
const FAIL_NO_PREEMPT: u16 = 10;
const FAIL_PREEMPT_STORAGE: u16 = 11;
const FAIL_EXIT_COUNT: u16 = 12;

/// Count of involuntary timer-driven preemptions of the running U-mode task.
static PREEMPTIONS: AtomicU64 = AtomicU64::new(0);
/// `exit` syscalls observed (the spinner exits exactly once on completion).
static EXITS: AtomicU64 = AtomicU64::new(0);

/// Set once the round-trip has been driven so a re-entry cannot re-run it.
static TEST_DRIVEN: AtomicU32 = AtomicU32::new(0);

/// Static boot heap, in the linker's NOLOAD `.heap` section so the boot
/// trampoline neither zeroes nor counts it in the usable memory map. The user
/// kthread's kernel stack + control block and the spawn caller's
/// startup-vector block allocate from it.
#[link_section = ".heap"]
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: BumpAllocator =
    unsafe { BumpAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// Page-table pool backing the U-mode address space's Sv39 hierarchy.
static PAGE_TABLES: paging::PageTablePool = paging::PageTablePool::new();

/// Per-hart preemption backing for the single boot hart (`AGENTS.md` §24.1 —
/// `PreemptStorage<1>` covers a single-hart slice).
static PREEMPT_STORAGE: PreemptStorage<1> = PreemptStorage::new();

/// Physical-frame backing store the spawn builder allocates user pages from.
/// `align(4096)` so each `PAGE_SIZE` slice is a valid page frame; identity-
/// mapped (its physical address equals its kernel virtual address), so the
/// builder reaches it through [`DirectPhysMap::identity`].
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next identity-mapped physical frame from [`FRAME_POOL`], or
/// `None` when the pool is exhausted (the spawn builder then fails closed).
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    // The pool is identity-mapped, so its kernel virtual address is also its
    // physical address.
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared riscv64 panic bridge (parks the hart; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn preempt_el0_qemu_riscv64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires (`AGENTS.md` §5.4).
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The U-mode-preemption callback the timer trap path invokes for a tick taken
/// from U-mode — the production dispatch shape verbatim (`AGENTS.md` §2.2): it
/// suspends the running user task back to the scheduler via
/// `reschedule_current(_, Yield)`, the involuntary analogue of a `yield`
/// syscall. It records each preemption so the test can prove at least one fired
/// against the never-yielding spinner.
extern "C" fn preempt_dispatch(cpu: CpuId) {
    PREEMPTIONS.fetch_add(1, Ordering::SeqCst);
    let _ = reschedule_current(cpu, RescheduleAction::Yield);
}

/// The syscall-dispatch callback the spinner's final `exit` `ecall` reaches.
///
/// The spinner issues no `yield`; its only syscall is the `exit` that
/// `rustos-rt` routes `main`'s return through. Any other syscall is unexpected
/// and fails the test loudly (`AGENTS.md` §7).
extern "C" fn dispatch(number: u64, _args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    #[allow(clippy::cast_possible_truncation)]
    let raw = number as u16;
    if raw == SyscallNumber::EXIT.as_u16() {
        EXITS.fetch_add(1, Ordering::SeqCst);
        // Reap the caller: this switches back to the dispatcher and never
        // resumes the task, so the `0` below is unreachable.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
        0
    } else {
        note(TEST_FAIL, "fixture program issued an unexpected syscall");
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// Build the isolated U-mode address space from the fixture `image` over
/// [`PAGE_TABLES`], returning its Sv39 root and the entry register state.
fn build_user_space(image: &LoadImage) -> (u64, UserEntry) {
    let Some(arch) = ArchAddressSpace::new_identity_gigapages(&PAGE_TABLES, IDENTITY_GIGABYTES)
    else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // Capture the `satp` root before the arch space is moved into the
    // `kernel/mem` wrapper, so the `pre_resume` hook can reactivate it.
    let root_phys = arch.root_phys();
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, heap,
    // frame pool, and device MMIO (all within `[0, 4 GiB)` on `virt`), so the
    // `satp` switch does not move the ground under the running code. Boot hart.
    unsafe { arch.switch() };

    let mut space = AddressSpace::new(arch);
    let physmap = DirectPhysMap::identity((IDENTITY_GIGABYTES as u64) << 30);
    let request = SpawnRequest {
        image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"el0"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once its space is reactivated (via the `pre_resume`
    // hook) and the trap path is installed. The frame source draws identity-
    // mapped frames from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => qemu_exit::exit_failure(FAIL_BUILD),
    };
    (root_phys, entry)
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(hartid: u64, dtb: u64) -> ! {
    if TEST_DRIVEN
        .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_POOL);
    }

    note(TEST_START, "riscv64 U-mode preemption test: starting");

    // Read the timer frequency from the firmware tree. Fail closed (finisher)
    // if it is omitted rather than guessing a divisor (`AGENTS.md` §5.4).
    // SAFETY: `dtb` is the verbatim `a1` pointer OpenSBI handed the boot hart;
    // `boot.s` forwards it unchanged.
    let Some(timebase) = (unsafe { Fdt::from_ptr(dtb as *const u8) })
        .ok()
        .and_then(|f| f.timebase_frequency())
    else {
        qemu_exit::exit_failure(FAIL_NO_TIMEBASE);
    };

    // The single-hart slice only brings up logical CPU 0 on hart 0.
    if hartid != u64::from(BOOT_CPU) {
        qemu_exit::exit_failure(FAIL_UNEXPECTED_HART);
    }

    // Parse the build-time `rxe` blob once against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    // Build the isolated U-mode address space (it leaves its own space active).
    let (root_phys, entry) = build_user_space(&image);

    // Install the trap vector + the syscall-dispatch callback before any user
    // task runs. Crucially this uses `install_trap_vector`, NOT `init_traps`:
    // `sstatus.SIE` stays clear, so the kernel (the S-mode `step` loop below)
    // is never preempted — only the U-mode spinner is (a supervisor-timer
    // interrupt is taken in U-mode by the privilege rule U < S, regardless of
    // `SIE`). This mirrors the production riscv64 boot, which arms preemption
    // without enabling `sstatus.SIE`.
    // SAFETY: called once on the boot hart with a stack established and the MMU
    // enabled (the address-space build switched it on).
    unsafe { trap::install_trap_vector() };
    syscall_entry::set_dispatch_callback(dispatch);

    // Arm the production preemption path verbatim (`AGENTS.md` §2.2): register
    // the per-hart storage, install the U-mode-preemption callback, and start
    // the periodic SBI timer. `init_local_preempt` sets `sie.STIE` and arms the
    // first timer but does not touch `sstatus.SIE`, so no tick is taken until
    // the spinner runs in U-mode.
    if PREEMPT_STORAGE.register().is_err() {
        qemu_exit::exit_failure(FAIL_PREEMPT_STORAGE);
    }
    preempt::set_preempt_callback(preempt_dispatch);
    let interval = preempt::interval_for_hz(timebase, PREEMPT_TICK_HZ);
    // SAFETY: the boot hart (id 0); the preempt callback is installed (above),
    // the per-hart storage is registered (above), and the trap vector is
    // installed (`install_trap_vector`). It records the interval, arms the
    // first SBI timer, and enables `sie.STIE`. `sstatus.SIE` stays clear, so no
    // tick is taken until the spinner runs in U-mode.
    unsafe {
        preempt::init_local_preempt(BOOT_CPU, interval);
    }

    // Build the live scheduler over the production arch handle. Single-hart
    // slice: one per-CPU slot, owned by an allocator-free `static` backing
    // (`AGENTS.md` §24.1).
    static STORAGE: RiscvArchStorage<1> = RiscvArchStorage::new();
    let arch = Arc::new(RiscvArch::new(&STORAGE, BOOT_CPU, timebase));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    // Admit the spinner as a resumable user kthread: its `pre_resume` hook
    // reactivates its page-table root (isolation, §4), and its work body
    // `enter_user`s into U-mode.
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |_top: u64| {
        // SAFETY: paging is enabled and `root_phys` is the Sv39 root of a space
        // that maps the low identity window the running dispatcher executes
        // from — exactly `activate_user_root`'s contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: by the time this body runs the task has been dispatched, so
        // its `pre_resume` hook reactivated `satp`, and the trap vector +
        // dispatch callback are installed; the program's `exit` `ecall` is
        // handled. `build_process_image` mapped the entry/stack as user pages.
        unsafe { user_mode.enter_user(entry) }
    };
    if spawn_user_kthread(&sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work).is_err() {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(
        TEST_SPAWNED,
        "riscv64 U-mode preemption test: spinner spawned",
    );

    // Dispatch loop: drive `step` until the spinner exits. The spinner never
    // yields, so each `step` enters it into U-mode where it busy-loops until a
    // timer tick preempts it (the preempt callback `reschedule_current`s back
    // here) — or, on the final quantum, until it finishes the loop and `exit`s.
    // A preemption that never fires would leave `step` spinning forever inside
    // U-mode and the harness would time out (fail-loud, `AGENTS.md` §7).
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }
    if sched.live_task_count() != 0 {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    // The runaway loop never yielded, so the only thing that returned control
    // to the dispatcher before `exit` is an involuntary preemption: at least
    // one must have fired, proving the timer interrupt preempts a
    // non-cooperative U-mode task.
    if PREEMPTIONS.load(Ordering::SeqCst) == 0 {
        qemu_exit::exit_failure(FAIL_NO_PREEMPT);
    }
    if EXITS.load(Ordering::SeqCst) != 1 {
        qemu_exit::exit_failure(FAIL_EXIT_COUNT);
    }

    note(
        TEST_PASS,
        "riscv64 U-mode preemption test: runaway U-mode task involuntarily preempted and resumed to exit",
    );
    qemu_exit::exit_success();
}
