//! Minimal x86_64 IDT for the Stage-2 QEMU integration tests.
//!
//! Only the exception vectors the tests actually exercise are wired up:
//! `#GP` (vector 13), `#PF` (vector 14) and `#DF` (vector 8). Every other
//! vector points to a default trampoline that reports failure to QEMU —
//! the charter forbids silent resets, and the charter requires us to fail
//! closed on any unexpected exception.
//!
//! The IDT is stored in a per-binary `static mut`. That is the *only*
//! mutable static in this crate; it is justified because
//!
//!   1. There is exactly one IDT per CPU and the Stage-2 tests are
//!      single-CPU (see crate docs and `PLAN.md` Stage 3a checklist);
//!   2. It is written exactly once — during [`init`] — before any other
//!      CPU could observe it;
//!   3. Writing after `lidt` is forbidden by [`init`] returning a
//!      `&'static Idt` so re-installation is a compile-time error.
//!
//! When SMP lands in Stage 3a this moves behind a per-CPU `Box`.

use core::mem::size_of;

/// Number of entries (256 = the architecturally fixed maximum).
const IDT_LEN: usize = 256;

/// Callback type registered by the test for the page-fault vector.
///
/// `error_code` is the architecturally defined `#PF` error code. `rip` is
/// the faulting instruction pointer pulled from the interrupt frame. The
/// callback **must not return**: the kernel cannot resume the faulting
/// instruction without architecture-level fix-up logic the Stage-2 tests
/// deliberately do not exercise. Test bodies typically write a marker to
/// serial and call [`crate::qemu_exit::exit_success`] /
/// [`crate::qemu_exit::exit_failure`].
pub type PageFaultHandler = fn(error_code: u64, rip: u64) -> !;

#[repr(C, packed)]
#[derive(Clone, Copy)]
struct IdtEntry {
    offset_lo: u16,
    selector: u16,
    ist: u8,
    type_attr: u8,
    offset_mid: u16,
    offset_hi: u32,
    zero: u32,
}

impl IdtEntry {
    const fn empty() -> Self {
        Self {
            offset_lo: 0,
            selector: 0,
            ist: 0,
            type_attr: 0,
            offset_mid: 0,
            offset_hi: 0,
            zero: 0,
        }
    }
}

#[repr(C, packed)]
struct IdtPointer {
    limit: u16,
    base: u64,
}

/// The IDT itself, plus a slot for the Stage-2 page-fault callback. The
/// callback is loaded by [`init`] before `lidt` runs and is never written
/// again.
pub struct Idt {
    entries: [IdtEntry; IDT_LEN],
    pf_handler: Option<PageFaultHandler>,
}

static mut IDT: Idt = Idt {
    entries: [IdtEntry::empty(); IDT_LEN],
    pf_handler: None,
};

/// Install the IDT with the supplied page-fault handler.
///
/// # Safety
///
/// Must be called exactly once on the boot CPU before any instruction that
/// could raise an exception. The function asserts that contract in debug
/// builds with the `INSTALLED` flag.
///
/// Returns a `'static` reference to the IDT for symmetry — callers cannot
/// use it to mutate the table because the table's interior is private.
pub unsafe fn init(pf: PageFaultHandler) -> &'static Idt {
    // `IDT_LEN` is a small compile-time constant; the byte size of
    // the table fits in the 16-bit `lidt` limit field. The const is
    // declared at the top of the function (rather than just before
    // its single use) to satisfy `clippy::items_after_statements`.
    const IDT_LIMIT: u16 = {
        let bytes = size_of::<[IdtEntry; IDT_LEN]>();
        assert!(bytes >= 1 && bytes - 1 <= u16::MAX as usize);
        // SAFETY-INVARIANT: the `assert!` proves the truncation cast
        // is lossless; justified `#[allow]`.
        #[allow(clippy::cast_possible_truncation)]
        let limit = (bytes - 1) as u16;
        limit
    };
    // SAFETY: we are documented as the single, one-shot writer of `IDT`
    // (see module-level comment, points 1–3). Subsequent reads via `lidt`
    // observe a fully-initialised table.
    unsafe {
        IDT.pf_handler = Some(pf);

        // Wire architecturally fixed vectors. The `_thunk` symbols are
        // generated by `global_asm!` below.
        set_handler(13, gp_thunk as *const () as u64);
        set_handler(14, pf_thunk as *const () as u64);
        set_handler(8, df_thunk as *const () as u64);

        // Every other vector traps to a default-fail thunk so the kernel
        // fails closed on an unexpected exception.
        for v in 0..IDT_LEN {
            if v != 8 && v != 13 && v != 14 {
                set_handler(v, default_thunk as *const () as u64);
            }
        }

        let ptr = IdtPointer {
            limit: IDT_LIMIT,
            base: core::ptr::addr_of!(IDT.entries) as u64,
        };
        core::arch::asm!(
            "lidt [{ptr}]",
            ptr = in(reg) &raw const ptr,
            options(nostack, preserves_flags),
        );

        &*core::ptr::addr_of!(IDT)
    }
}

unsafe fn set_handler(vector: usize, addr: u64) {
    // SAFETY: vector range checked statically (`vector < IDT_LEN`); the
    // single in-flight writer is `init`, see module comment.
    unsafe {
        let e = &mut (*core::ptr::addr_of_mut!(IDT)).entries[vector];
        e.offset_lo = (addr & 0xFFFF) as u16;
        e.selector = 0x08; // kernel 64-bit code segment from `boot.s`
        e.ist = 0;
        e.type_attr = 0x8E; // P=1, DPL=0, type=interrupt gate
        e.offset_mid = ((addr >> 16) & 0xFFFF) as u16;
        e.offset_hi = ((addr >> 32) & 0xFFFF_FFFF) as u32;
        e.zero = 0;
    }
}

/// Entry point the `#PF` ISR thunk calls into.
///
/// Pulled out of the inline assembly so the actual fault handling logic
/// can be audited as plain Rust. Receives the error code and the faulting
/// `rip` straight from the trap frame; never returns.
#[no_mangle]
extern "C" fn tairix_arch_x86_64_page_fault(error_code: u64, rip: u64) -> ! {
    // SAFETY: `IDT.pf_handler` is set exactly once by `init` and never
    // changed again; reading it here is therefore a data-race-free read
    // of an initialised `Option<fn>` through an aliased shared reference.
    let handler = unsafe { (*core::ptr::addr_of!(IDT)).pf_handler };
    match handler {
        Some(h) => h(error_code, rip),
        None => crate::qemu_exit::exit_failure(),
    }
}

#[no_mangle]
extern "C" fn tairix_arch_x86_64_general_protection(error_code: u64, rip: u64) -> ! {
    // GP doesn't fire in either Stage-2 test on a healthy kernel; treat
    // it as a closed-fail. `error_code` and `rip` are
    // accepted into the ABI now so adding diagnostics in Stage 3a does
    // not require a signature change (no interface
    // creep, extend through dispatched callbacks).
    let _ = (error_code, rip);
    crate::qemu_exit::exit_failure();
}

#[no_mangle]
extern "C" fn tairix_arch_x86_64_double_fault(_error_code: u64) -> ! {
    crate::qemu_exit::exit_failure();
}

#[no_mangle]
extern "C" fn tairix_arch_x86_64_unexpected_interrupt() -> ! {
    crate::qemu_exit::exit_failure();
}

// Naked-ish ISR thunks. We can't use `#[naked]` on stable nightly without
// extra unstable features, so we hand-write the entry prologue with
// `global_asm!` and have it call into the `extern "C"` functions above.
//
// The thunks observe SysV AMD64: error code (already pushed by the CPU
// for #GP/#PF/#DF) is moved to %rdi, faulting %rip from the trap frame is
// moved to %rsi. We do not enter `iretq` — the Rust callbacks all return
// `!`, so the thunk falls through to a defensive `hlt` loop.
core::arch::global_asm!(
    r#"
    .global pf_thunk
    pf_thunk:
        // [rsp+0] = error code
        // [rsp+8] = rip
        mov rdi, [rsp]
        mov rsi, [rsp+8]
        call tairix_arch_x86_64_page_fault
    1:  cli
        hlt
        jmp 1b

    .global gp_thunk
    gp_thunk:
        mov rdi, [rsp]
        mov rsi, [rsp+8]
        call tairix_arch_x86_64_general_protection
    1:  cli
        hlt
        jmp 1b

    .global df_thunk
    df_thunk:
        mov rdi, [rsp]
        call tairix_arch_x86_64_double_fault
    1:  cli
        hlt
        jmp 1b

    .global default_thunk
    default_thunk:
        call tairix_arch_x86_64_unexpected_interrupt
    1:  cli
        hlt
        jmp 1b
    "#
);

extern "C" {
    fn pf_thunk();
    fn gp_thunk();
    fn df_thunk();
    fn default_thunk();
}
