//! The x86_64 C-program test kernel: boot the production pipeline, then on
//! `BootCompleted` build a ring-3 image for the C program and drop into it
//! through the production spawn caller, servicing the syscalls it issues.

use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU32, Ordering};

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery, SyscallNumber, SYSCALL_MAX_ARGS};
use rustos_arch_x86_64::paging::{self, KERNEL_VMA_BASE};
use rustos_arch_x86_64::userentry::UserMode;
use rustos_arch_x86_64::{qemu_exit, syscall_entry};
use rustos_kernel::kalloc::{Heap, HEAP_BYTES};
use rustos_kernel::{
    boot, handle_panic_via_kernel_core, FreeListAllocator, SerialSink, SERIAL_SINK,
};
use rustos_kernel_core::{spawn_and_enter, SpawnRequest};
use rustos_kernel_mem::{AddressSpace, DirectPhysMap, Frame, PhysAddr, UserStack};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;
use rustos_log::{log, Event, EventId, Level, Sink};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// Static heap for the bump allocator (per the production bin); the boot
/// pipeline and the spawn caller's startup-vector block allocate from it.
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// `EventId` emitted when every boot init phase completed.
const BOOT_COMPLETED_EVENT_ID: EventId = EventId(4004);

/// Stable audit-event ids for the QEMU transcript (kept clear of the
/// `4000..5000` `kernel/core` boot range used above).
const TEST_START: EventId = EventId(4270);
const TEST_FAIL: EventId = EventId(4272);

/// Exit code the C program returns when every abi-v1 check and both syscall
/// round-trips pass (`csrc/main.c` `EXIT_OK`).
const EXPECTED_EXIT: u64 = 99;
/// Capability id the program queries (`csrc/main.c` `PROBE_CAP`, which names
/// `ROS_CAP_DRV_KERNEL`); the callback asserts the marshalled argument equals
/// it. Derived from the same `lib/abi` source of truth, never a bare literal.
const PROBE_CAP: u64 = CapabilityId::DRV_KERNEL.as_u16() as u64;
/// Sentinel `clock_get` returns to the program (`csrc/main.c`
/// `CLOCK_SENTINEL`), exercising full 64-bit result marshalling.
const CLOCK_SENTINEL: u64 = 0x0123_4567_89ab_cdef;

/// User stack base (1 MiB into the high user region) and size. crt0 carves a
/// 1 MiB scratch span off the stack, so the stack must comfortably exceed it.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB > crt0's 1 MiB scratch + call frames).
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up, well
/// clear of the program image and the stack).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program (any value).
const CANARY: u64 = 0xC0FF_EE00_D15E_A5ED;

/// Number of physical frames the test hands the spawn builder: the program's
/// segments, the user stack, and the startup block. Sized with headroom.
const FRAME_COUNT: usize = 320;

/// `IA32_EFER` MSR number and its No-Execute-Enable bit (bit 11).
const IA32_EFER: u32 = 0xC000_0080;
const EFER_NXE: u64 = 1 << 11;

/// Page-table pool backing the new address space (lives in `.bss`).
static PAGE_TABLE_POOL: paging::PageTablePool = paging::PageTablePool::new();

/// Physical-frame backing store the spawn builder allocates user pages from.
/// `align(4096)` so each `PAGE_SIZE` slice is a valid page frame. It is a
/// higher-half kernel static, so its physical address is its virtual address
/// minus [`KERNEL_VMA_BASE`]; the builder reaches it through a
/// [`DirectPhysMap`] with that same offset.
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Set once the round-trip has been driven so a duplicate `BootCompleted`
/// cannot re-enter the test logic.
static TEST_DRIVEN: AtomicU32 = AtomicU32::new(0);

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared bridge in `rustos_kernel`.
#[panic_handler]
fn c_program_qemu_x86_64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_kernel_core(info)
}

/// A `CapabilityQuery` granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The syscall dispatch callback the C program's traps reach.
///
/// Services the two round-trip syscalls (`cap_query` → "held", `clock_get` →
/// the 64-bit sentinel) and, on `exit`, asserts the program computed
/// [`EXPECTED_EXIT`] before flipping the QEMU success finisher. Any unexpected
/// syscall, a wrong `cap_query` argument, or a wrong exit code flips the
/// failure finisher. The `cap_query` / `clock_get` arms return the answer to
/// ring 3; the `exit` and failure arms never return.
extern "C" fn dispatch_and_finish(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the `IA32_LSTAR` entry stub built the `[u64; SYSCALL_MAX_ARGS]`
    // array on the kernel stack and passes a pointer valid for this call
    // (`syscall_entry` contract).
    let args = unsafe { *args_ptr };

    if number == u64::from(SyscallNumber::CAP_QUERY.as_u16()) {
        if args[0] != PROBE_CAP {
            note(TEST_FAIL, "cap_query marshalled the wrong capability id");
            qemu_exit::exit_failure();
        }
        // Report the capability as held (the C program checks for `1`).
        return 1;
    }

    if number == u64::from(SyscallNumber::CLOCK_GET.as_u16()) {
        return CLOCK_SENTINEL;
    }

    if number == u64::from(SyscallNumber::EXIT.as_u16()) {
        if args[0] != EXPECTED_EXIT {
            note(TEST_FAIL, "C program exited with the wrong code");
            qemu_exit::exit_failure();
        }
        qemu_exit::exit_success();
    }

    note(TEST_FAIL, "C program issued an unexpected syscall");
    qemu_exit::exit_failure();
}

/// Hand out the next physical frame from [`FRAME_POOL`]. The pool is a
/// higher-half kernel static, so its physical address is its virtual address
/// minus [`KERNEL_VMA_BASE`].
fn frame_source() -> impl FnMut() -> Option<Frame> {
    let mut next = 0usize;
    move || {
        if next >= FRAME_COUNT {
            return None;
        }
        let offset = next * paging::PAGE_SIZE;
        next += 1;
        let virt = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
        Some(Frame::containing(PhysAddr::new(virt - KERNEL_VMA_BASE)))
    }
}

/// Outer audit sink: replays every event to serial (so the QEMU transcript
/// captures the boot timeline) and, on the single [`BOOT_COMPLETED_EVENT_ID`],
/// drives [`run_round_trip`].
struct BootCompletedSink;

impl Sink for BootCompletedSink {
    fn write_event(&self, event: &Event<'_>) {
        SerialSink::new().write_event(event);

        if event.id == BOOT_COMPLETED_EVENT_ID
            && TEST_DRIVEN
                .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
                .is_ok()
        {
            run_round_trip();
        }
    }
}

static AUDIT_SINK: BootCompletedSink = BootCompletedSink;

/// Build the ring-3 image, install the dispatch callback, and drop into it.
/// Never returns.
fn run_round_trip() -> ! {
    note(
        TEST_START,
        "x86_64 C-program round-trip: building the ring-3 image",
    );

    // Enable `IA32_EFER.NXE` so the W^X No-Execute leaf bit the adapter sets
    // on data/rodata pages is honoured rather than reserved.
    // SAFETY: reading and writing `IA32_EFER` is the documented enable
    // sequence; it runs once on the BSP and only sets bit 11, preserving
    // `SCE`/`LME`/`LMA` the boot pipeline established.
    unsafe {
        let lo: u32;
        let hi: u32;
        core::arch::asm!(
            "rdmsr",
            in("ecx") IA32_EFER,
            out("eax") lo,
            out("edx") hi,
            options(nostack, preserves_flags),
        );
        let efer = (((hi as u64) << 32) | lo as u64) | EFER_NXE;
        core::arch::asm!(
            "wrmsr",
            in("ecx") IA32_EFER,
            in("eax") efer as u32,
            in("edx") (efer >> 32) as u32,
            options(nostack, preserves_flags),
        );
    }

    // 1. Fresh address space (low 32 MiB identity + higher-half kernel window)
    //    and activate it before any user mapping is added.
    let Some(mut arch) = paging::AddressSpace::new_identity_first_32mib(&PAGE_TABLE_POOL) else {
        note(TEST_FAIL, "page-table pool exhausted (identity map)");
        qemu_exit::exit_failure();
    };
    // Identity-map the architectural LAPIC MMIO page (supervisor-only). The
    // production boot now arms ring-3 preemption (P-1c): a periodic LAPIC-timer
    // IRQ is taken while the program runs in ring 3 (under this CR3), and its
    // ISR reads the LAPIC ID register and writes EOI at `LAPIC_BASE_PHYS`.
    // Without this mapping that kernel-mode MMIO access would page-fault under
    // the minimal user CR3 — the same page the production /
    // timeshare spaces map. The preempt callback then no-ops here (no user
    // kthread is published), so preemption stays transparent to this round-trip.
    if arch
        .map_4k(
            &PAGE_TABLE_POOL,
            rustos_arch_x86_64::preempt::LAPIC_BASE_PHYS,
            rustos_arch_x86_64::preempt::LAPIC_BASE_PHYS,
            true,
        )
        .is_none()
    {
        note(TEST_FAIL, "could not map LAPIC MMIO page");
        qemu_exit::exit_failure();
    }
    // SAFETY: the new space maps the low 32 MiB, the higher-half kernel window,
    // and the LAPIC MMIO page, so the executing RIP, the current stack, the
    // per-CPU `swapgs` TLS, the page-table pool, `dispatch_and_finish`, and the
    // timer ISR's LAPIC access all stay mapped across the CR3 switch.
    unsafe { arch.switch() };
    syscall_entry::set_dispatch_callback(dispatch_and_finish);

    // 2. Parse the build-time `rxe` blob against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        note(TEST_FAIL, "C program rxe image failed to parse");
        qemu_exit::exit_failure();
    };

    // 3. Build the ring-3 image into the (active) address space and enter it
    //    through the production capability-checked, audited spawn caller. The
    //    physmap offsets a frame's physical address back to its higher-half
    //    kernel virtual address (the static's own address), so the builder's
    //    kernel-side fill writes land in the right place.
    // The arch `paging::AddressSpace` implements the Arch HAL page-table
    // surface (`mmu::AddressSpace` + `tlb::TlbShootdown`) directly, so the
    // `kernel/mem` façade drives it with no per-test adapter (the Stage W5b-2 wiring removed the old `PageTableOps` shim).
    let mut space = AddressSpace::new(arch);
    let physmap = DirectPhysMap::new(KERNEL_VMA_BASE, 1 << 30);
    let request = SpawnRequest {
        image: &image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"prog"],
        env: &[],
        canary: CANARY,
    };

    note(TEST_START, "dropping into the spawned C program");

    // SAFETY: `space` is the active address space (we `switch`ed to it above)
    // and the production boot pipeline installed the GDT user selectors, the
    // TSS, and the `syscall`/`IA32_LSTAR` entry path, so the new program's
    // `syscall` is handled. `spawn_and_enter` checks `CAP_PROC_SPAWN`, builds
    // the image into `space`, and `iretq`s into it; on the authorised path it
    // diverges.
    let outcome = unsafe {
        spawn_and_enter(
            &SpawnAuthority,
            &SERIAL_SINK,
            &UserMode::new(),
            &mut space,
            &physmap,
            &request,
            frame_source(),
        )
    };

    // `spawn_and_enter` only returns on a denial or a build failure; the
    // authorised, well-formed path diverges into ring 3. Reaching here is a
    // closed failure.
    match outcome {
        Err(_) => {
            note(TEST_FAIL, "spawn_and_enter returned instead of entering");
            qemu_exit::exit_failure();
        }
        Ok(never) => match never {},
    }
}

/// The symbol the arch crate's boot trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(multiboot_info: u64) -> ! {
    boot(
        multiboot_info,
        &SERIAL_SINK,
        &AUDIT_SINK,
        rustos_log::Level::Info,
    )
}
