[package]
name = "rustos-drv-bus-pci"
description = "RustOS PCI/PCIe bus driver (x86_64 mechanism #1 configuration access)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
rustos-abi = { path = "../../../lib/abi", version = "=0.0.0" }

[lints]
workspace = true
