//! Build script for the aarch64 live service-control QEMU vertical
//! (`plans/NEW-SERVICEMANAGER.md` SVC-8).
//!
//! Two jobs on the freestanding `aarch64-unknown-none` target:
//!
//! 1. Hand the aarch64 `virt` linker script to `rustc` — the single per-board
//!    linker script the architecture port owns.
//! 2. Dump the canonical QEMU `virt` flattened device tree and embed it,
//!    because QEMU's `-kernel <ELF>` aarch64 path passes no DTB pointer
//!    (`x0 = 0`); the boot pipeline is handed a pointer to this embedded blob
//!    so it discovers the console, GIC, `/memory` window, timer rate, PSCI
//!    conduit, and the `virtio,mmio` transport slots the encrypted root is
//!    reached over, exactly as on real firmware. The dump helper lives in the
//!    shared harness so no aarch64 build script re-rolls it.
//!
//! Re-running `build.rs` produces byte-identical output, so the test is
//! deterministic.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    tairix_itest_harness::emit_target_cfg();
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");

    let target = std::env::var("TARGET").unwrap_or_default();
    let dtb_bytes = if target == "aarch64-unknown-none" {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
        let linker_script = format!(
            "{}/../../../kernel/arch/aarch64/link/aarch64-virt.ld",
            manifest_dir.trim_end_matches('/')
        );
        println!("cargo:rerun-if-changed={linker_script}");
        println!("cargo:rustc-link-arg=-T{linker_script}");
        // One CPU: PID 1, the login session, the shell, and the spawned
        // `servicectl` process all run in the same drain loop on the boot CPU.
        tairix_itest_harness::dump_aarch64_virt_dtb(&out_dir, 1)
    } else {
        // Host builds compile the bin to a no-op `main`; no DTB needed.
        Vec::new()
    };

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// Canonical QEMU `virt` flattened device tree, dumped at build\n");
    out.push_str("/// time for the aarch64-none target (empty on host builds).\n");
    out.push_str("pub const DTB_BLOB: &[u8] = &[");
    for (i, b) in dtb_bytes.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n");

    let path = PathBuf::from(&out_dir).join("dtb_fixture.rs");
    fs::write(&path, out).expect("write dtb_fixture.rs");
}
