//! x86_64 PID 1 (`init`) spawn seam — `plans/PI.md` X3a.
//!
//! [`X86_64InitSpawn`] implements the architecture-neutral
//! [`tairix_kernel_core::InitSpawn`] hook the boot pipeline installs into the
//! [`tairix_kernel_core::BootInfo`] hand-off (`boot::try_boot` →
//! `BootInfo::with_init`). It is the cross-port sibling of the aarch64
//! `init_spawn` seam: once every init phase has succeeded and
//! `kernel_core::kernel_main` has emitted
//! [`tairix_kernel_core::AuditEvent::BootCompleted`], the core invokes
//! [`InitSpawn::spawn_init`]; this implementation builds the embedded `init`
//! (`Run`) program's ring-3 image through the production, capability-checked,
//! audited spawn caller ([`tairix_kernel_core::spawn_image`]) and admits it as
//! a **resumable user kthread** ([`InitSpawnCtx::admit_init`]). PID 1 then runs
//! under the live scheduler `kernel_main` drains; its `yield`/`exit` syscalls
//! suspend it back through the Arch-HAL context switch.
//!
//! The image, its relocation bias ([`INIT_USER_BIAS`]), and the kernel's
//! syscall CFI tag are baked at build time (`build.rs` →
//! `tairix_itest_harness::elf2rxe`), exactly like the aarch64 seam and the
//! proven `spawn_el0_resume_qemu_x86_64` fixture, so there is one conversion
//! path. Spawning `init` is *not* a privileged bypass: the
//! program receives only the authority its manifest requests intersected with
//! its user's grants; this seam only authorises the
//! *act* of spawning under `CAP_PROC_SPAWN`.
//!
//! # x86_64 specifics versus the aarch64 sibling
//!
//! * The address space is built from
//!   [`ArchAddressSpace::new_identity_first_gib`] over the window the boot
//!   path sized from the discovered memory map
//!   ([`paging::configured_identity_gigapages`]), plus the higher-half kernel
//!   window the trampoline established. The
//!   x86_64 page-table walk recovers each intermediate table from its **low
//!   physical address**, and the live allocator hands the image's frames out
//!   of physical RAM past the low 32 MiB, so the fresh space the seam switches
//!   to while building the image must identity-map all of RAM (and the
//!   architectural LAPIC MMIO page at ~3.98 GiB, which the scheduler touches
//!   under PID 1's CR3 between user entries). The narrower 32 MiB window the
//!   other x86_64 verticals use
//!   is only enough when every table and frame lives in low memory.
//! * The `pre_resume` hook does two things (the aarch64 hook only the first):
//!   reload CR3 to PID 1's own PML4 ([`activate_user_root`], isolation) and
//!   repoint the per-CPU `syscall` entry stack at PID 1's own kernel stack
//!   ([`syscall_entry::set_kernel_rsp0`]) — the gap aarch64 fills implicitly
//!   through `SP_EL1` (`plans/PI.md` §X). A rejected stack top leaves the slot
//!   unchanged and the next syscall faults loudly (fail closed).
//! * PID 1's kernel stack comes from the shared
//!   [`crate::stack_arena::guarded_kernel_stack`] builder, so the guard page
//!   is re-expressed at 4 KiB granularity and unmapped in PID 1's *own* PML4
//!   and a kernel-stack overrun faults under its CR3 (`plans/PI.md` G3b-2).
//! * Physical frames are reached through the port's one direct physical map
//!   ([`ConfiguredIdentityPhysMap`]), which covers the same discovered-RAM
//!   window the space identity-maps.

use core::sync::atomic::{AtomicBool, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_arch_x86_64::paging::{self, activate_user_root, AddressSpace as ArchAddressSpace};
use tairix_arch_x86_64::syscall_entry;
use tairix_arch_x86_64::userentry::{set_user_thread_pointer, USER_MODE};
use tairix_kernel_core::{
    spawn_image, InitSpawn, InitSpawnCtx, ProcessResume, ProcessSpace, SpawnMode, UserThreadEntry,
};
use tairix_kernel_mem::{AddressSpace, LiveSpace, PhysMap, UserAddressSpace, VirtAddr};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;

use crate::spawn_layout;
use crate::stack_arena::guarded_kernel_stack;
use crate::x86_64::spawn_producer::{page_table_source, ConfiguredIdentityPhysMap};

// `INIT_RXE: &[u8]` and `INIT_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/init_rxe.rs"));

/// Logical CPU the boot processor runs as — the single core the (c7-bin)
/// bring-up initialises and the one `set_kernel_rsp0` repoints.
const BOOT_CPU: usize = 0;

/// PID 1's four fixed guarded-window bases (`plans/PI.md` 5d-0-ii (b′)/(c)),
/// derived from the one shared offset set the retained [`LiveSpace`]'s
/// window allocators are configured with.
const WINDOWS: spawn_layout::WindowBases = spawn_layout::window_bases(INIT_USER_BIAS);

/// Set once PID 1 has been spawned so a re-entry cannot re-run the path.
static INIT_SPAWNED: AtomicBool = AtomicBool::new(false);

/// The x86_64 PID 1 spawn seam installed into the
/// [`tairix_kernel_core::BootInfo`] hand-off by `boot::try_boot`.
pub struct X86_64InitSpawn;

/// The single, `'static` [`X86_64InitSpawn`] the boot path borrows.
pub static X86_64_INIT_SPAWN: X86_64InitSpawn = X86_64InitSpawn;

impl InitSpawn for X86_64InitSpawn {
    fn spawn_init(&self, ctx: &'static (dyn InitSpawnCtx + Sync)) {
        // Spawn PID 1 at most once; a spurious re-entry falls through to the
        // caller's fail-closed halt rather than building a second image.
        if INIT_SPAWNED
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }

        // PID 1's hierarchy is drawn from the kernel's live frame allocator
        // through the same source every runtime spawn uses. A part without
        // 1 GiB pages costs one page directory per gigabyte of the identity
        // window, so a fixed `.bss` reserve here would be a ceiling that a
        // machine with enough RAM outgrows — the aarch64 sibling can keep its
        // reserve because its stage-1 format always has 1 GiB blocks and its
        // cost is flat. A context with no `'static` allocator cannot build
        // PID 1 at all and falls through to the caller's fail-closed halt.
        let Some(static_frames) = ctx.static_frames() else {
            return;
        };
        let Ok(table_frames) = page_table_source(static_frames) else {
            return;
        };

        // Build a PML4 identity-mapping the discovered-RAM window (RAM +
        // the LAPIC MMIO page) and the higher-half kernel window, so the
        // page-table walk's low-physical table dereferences, the live
        // allocator's image frames, and the scheduler's LAPIC accesses all
        // resolve under PID 1's CR3 (the production `kernel_main` drain runs
        // on PID 1's root once `pre_resume` has reloaded it). Fail closed on
        // frame exhaustion.
        let Some(mut arch) = ArchAddressSpace::new_identity_first_gib(
            table_frames,
            paging::configured_identity_gigapages(),
        ) else {
            return;
        };
        // Capture PID 1's PML4 root before the arch space is moved into the
        // `kernel/mem` wrapper, so the `pre_resume` hook can reload CR3 with
        // it before every switch into PID 1 (`plans/SPAWN.md` SP2). It is a
        // plain `u64`, so the boxed hook stays `Send`.
        let init_root_phys = arch.pml4_phys();

        // Build PID 1's kernel stack (`plans/PI.md` G3b-2). Guarding `arch`
        // *before* it is switched to disturbs no live access and needs no TLB
        // maintenance; a chained block is bounded to the identity window so
        // the stack stays mapped in PID 1's own root.
        let kernel_stack =
            guarded_kernel_stack(&mut arch, ctx.frames(), paging::configured_identity_bytes());

        // SAFETY: the new space maps the low 32 MiB identity, the higher-half
        // kernel window, and the LAPIC MMIO page, so the executing RIP, the
        // current kernel stack, the per-CPU `swapgs` TLS, the page-table
        // pool, the live frame allocator's frames (the QEMU box's RAM is in
        // the first GiB), the heap, the dispatch path, and every LAPIC access
        // stay mapped across the CR3 switch — exactly `AddressSpace::switch`'s
        // contract. Called once on the boot CPU. The `admit_init` contract
        // requires the image be built into the active space, so the switch
        // precedes `spawn_image` below.
        unsafe { arch.switch() };

        let mut space = AddressSpace::new(arch);
        let physmap = ConfiguredIdentityPhysMap;

        // Parse the build-time `init` `rxe` blob against the kernel's own
        // compiled-in syscall CFI tag. A mismatch fails closed.
        let Ok(image) = LoadImage::parse(INIT_RXE, &SYSCALL_TABLE_HASH) else {
            return;
        };

        // Place the stack and startup block above the image's mapped top,
        // and derive the span record the stack-growth fault path backs
        // pages inside, through the one shared per-spawn derivation. An
        // image too large for the user region fails the boot closed.
        let Some((request, stack_span)) =
            spawn_layout::init_request(&image, INIT_RXE, INIT_USER_BIAS)
        else {
            return;
        };

        // Authorise + build the ring-3 image (emits `ProcessSpawned`) without
        // entering yet — PID 1 must be registered with the scheduler /
        // capability table / address-space registry *first* so its first
        // syscall resolves a caller context (`plans/PI.md` P6c-3).
        // SAFETY: building the image is itself safe; the returned `UserEntry`
        // is only entered below, once `space` is active (just switched to)
        // and the ring-3 trap path is installed. The frame source draws
        // first-GiB RAM frames from the kernel's live allocator. A returning
        // `Err` drops back to the caller's fail-closed halt.
        let frames = ctx.frames();
        let Ok(entry) = (unsafe {
            spawn_image(
                &spawn_layout::SpawnAuthority,
                SpawnMode::General,
                ctx.audit(),
                &mut space,
                &physmap,
                &request,
                move || frames.alloc().ok(),
            )
        }) else {
            return;
        };

        // PID 1's switch-in hook (`plans/SPAWN.md` SP2): the core runs it on
        // the dispatcher's context immediately before every switch into any
        // thread of PID 1. It reloads CR3 to PID 1's own root (isolation),
        // repoints the per-CPU `syscall` entry stack at the switching-in
        // thread's own kernel stack, and reinstalls that thread's thread
        // pointer. It captures only the `u64` root, so it is `Send`.
        let pre_resume: ProcessResume = Arc::new(move |stack_top: u64, tls_base: u64| {
            // `set_kernel_rsp0` repoints **both** PID 1's `syscall` entry
            // stack (`gs:0`) and its trap entry stack (`TSS.RSP0`) at PID 1's
            // own kernel stack — the latter is what makes an involuntary
            // LAPIC-timer preemption (P-1c), delivered through the IDT
            // interrupt gate which reads `TSS.RSP0`, land on PID 1's own stack
            // (one per-task kernel stack for both entry
            // kinds). A rejected value leaves the slots unchanged and the next
            // entry faults loudly (fail closed).
            let _ = syscall_entry::set_kernel_rsp0(BOOT_CPU, stack_top);
            // The `FS` base is privileged on this port, so the kernel — not
            // the thread — maintains it: every switch-in reinstalls the
            // switching-in thread's own value (`plans/THREADS.md` decision 7).
            // SAFETY: this runs at CPL 0 on the dispatcher's context, on the
            // CPU about to enter that thread, which is exactly
            // `set_user_thread_pointer`'s contract.
            unsafe { set_user_thread_pointer(tls_base) };
            // SAFETY: paging is enabled and `init_root_phys` is the PML4 of
            // PID 1's space, which maps the low identity + higher-half kernel
            // window the running dispatcher executes from — exactly
            // `activate_user_root`'s contract.
            unsafe { activate_user_root(init_root_phys) };
        });

        // Freeze the just-built mappings into the registry-storable,
        // `Send + Sync` snapshot the kernel-wide address-space registry holds
        // (the live arch `space` is not `Sync`), and box the direct map that
        // backs it, so PID 1's `stream_write` can copy its banner out of user
        // memory. Freezing *after* `spawn_image` captures every mapped page —
        // segments, stack, and the startup-vector block.
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());

        // PID 1's process address space (`plans/PI.md` 5d-0-ii (b′)): the
        // *same* arch space the snapshot above was frozen from, zeroing
        // anonymous frames through the same identity direct map the image
        // build used (PID 1's CR3 carries it). A window the allocator rejects
        // retains none and PID 1's `mem_map` / `mmio_map` fail closed.
        let live: Option<Arc<ProcessSpace>> = {
            let windows = crate::user_windows::user_windows(
                static_frames.total_frames() as u64,
                WINDOWS.anon,
                super::USER_VA_TOP,
            );
            LiveSpace::new(
                space,
                ConfiguredIdentityPhysMap,
                static_frames,
                VirtAddr::new(WINDOWS.mmio),
                spawn_layout::MMIO_WINDOW_PAGES,
                VirtAddr::new(WINDOWS.anon),
                windows.anon_pages,
                VirtAddr::new(WINDOWS.dma),
                spawn_layout::DMA_WINDOW_PAGES,
                VirtAddr::new(WINDOWS.shared),
                spawn_layout::SHARED_WINDOW_PAGES,
                VirtAddr::new(windows.file_base),
                windows.file_pages,
            )
            .ok()
            .map(|live| {
                Arc::new(ProcessSpace::new(
                    Box::new(live),
                    Arc::clone(&pre_resume),
                    &USER_MODE,
                ))
            })
        };

        let physmap: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);

        // Start the in-kernel root-unlock service alongside PID 1
        // (`plans/ARCHSUPPORT.md` A2). Admitted onto the boot CPU's run queue
        // *before* `admit_init` diverges into the dispatch loop, the kthread
        // brings up the bound virtio-blk-PCI root device over the production
        // MSI-X interrupt path, then serves the driver store and (fail-closed
        // on the input-less COM1 console this slice) resolves login. With no
        // bound disk (a PC shape without a planted root) it starts nothing,
        // opens the console-0 gate, and PID 1 runs unchanged.
        let _unlock_started = crate::x86_64::root_unlock::spawn_if_present(ctx);

        // Register PID 1's caps + address space, publish it as the current
        // task, and dispatch it — `admit_init` drains the run queue until PID
        // 1 has exited, then returns so `kernel_main` halts fail-closed.
        // SAFETY: the image was built into and `space` switched to active
        // above, and the trap path is installed, per the
        // `InitSpawnCtx::admit_init` contract; `frozen` faithfully describes
        // the active mappings, `physmap` backs them, `kernel_stack` is a
        // region exclusive to PID 1 that stays mapped for the task's lifetime,
        // and `live` retains the same arch space `frozen` was taken from.
        unsafe {
            ctx.admit_init(
                spawn_layout::init_caps(),
                frozen,
                physmap,
                stack_span,
                kernel_stack,
                pre_resume,
                live,
                UserThreadEntry {
                    port: &USER_MODE,
                    regs: entry,
                },
            );
        }
    }
}
