//! Build script for the Stage W11-B framebuffer-display (aarch64) QEMU
//! vertical.
//!
//! Three jobs, all done on the host where the toolchain, `ed25519-dalek`,
//! and `qemu-system-aarch64` are available:
//!
//! 1. Hand the aarch64 `virt` linker script to `rustc` on the
//!    freestanding `aarch64-unknown-none` target (the single per-arch
//!    linker script the architecture port owns — `AGENTS.md` §2.2).
//! 2. Sign a synthetic framebuffer-driver `.rxe` manifest requesting
//!    exactly [`CapabilityId::DRV_LOAD`] with a deterministic test seed,
//!    and emit a Rust source file the bin pulls in via `include!`.
//! 3. Dump the canonical QEMU `virt` flattened device tree and embed it:
//!    QEMU's `-kernel <ELF>` aarch64 path passes no DTB pointer, so the
//!    test reads the `fw_cfg` MMIO base from this build-time blob.
//!
//! The manifest requests only `CAP_DRV_LOAD`:
//! `rustos_drv_display_framebuffer::register` gates on it, and the host
//! installs the manifest's requested set intersected with the caller's
//! grants (`AGENTS.md` §5.2). The `CAP_MMIO_MAP` the surface mapping
//! additionally requires is granted on the separate `DriverHost` the bin
//! builds for `Framebuffer::open`, never through the manifest, mirroring
//! how the bus-driver verticals separate the load gate from the map gate.
//!
//! Re-running `build.rs` produces byte-identical output for the same
//! seed; the test is therefore deterministic (`AGENTS.md` §7).

use ed25519_dalek::{Signer, SigningKey};
use rustos_abi::{CapabilityId, DriverKind, DriverManifest, DRIVER_MANIFEST_MAGIC};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

/// Deterministic signing seed so the trust anchor is stable across
/// builds. Distinct from the other QEMU fixtures' seeds so the images
/// cannot be confused. The leading bytes spell `"fbarm64disp"`.
const TEST_SEED: [u8; 32] = [
    0x66, 0x62, 0x61, 0x72, 0x6d, 0x36, 0x34, 0x64, 0x69, 0x73, 0x70, 0x27, 0xb1, 0x4e, 0x9a, 0x33,
    0xc5, 0x08, 0x72, 0x1d, 0xe6, 0x4b, 0x90, 0x82, 0x3f, 0xa7, 0x16, 0x5c, 0xd0, 0x29, 0x84, 0x6b,
];

/// SHA-256 fingerprint of the host's syscall table. The concrete value
/// is irrelevant; both sides feed the same value into the `HostConfig`.
const SYS_HASH: [u8; 32] = [0x22; 32];

fn main() {
    rustos_itest_harness::emit_target_cfg();
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");

    let target = std::env::var("TARGET").unwrap_or_default();
    let dtb_bytes = if target == "aarch64-unknown-none" {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
        let linker_script = format!(
            "{}/../../../kernel/arch/aarch64/link/aarch64-virt.ld",
            manifest_dir.trim_end_matches('/')
        );
        println!("cargo:rerun-if-changed={linker_script}");
        println!("cargo:rustc-link-arg=-T{linker_script}");
        dump_virt_dtb(&out_dir)
    } else {
        // Host builds compile the bin to a no-op `main`; no DTB needed.
        Vec::new()
    };

    let signing_key = SigningKey::from_bytes(&TEST_SEED);
    let signer_pubkey: [u8; 32] = signing_key.verifying_key().to_bytes();

    // The framebuffer driver's `register` entry checks `CAP_DRV_LOAD`.
    // The effective set is the intersection of the loading user's grants
    // and this manifest request, so name it here as well as on the caller.
    let caps: &[u16] = &[CapabilityId::DRV_LOAD.as_u16()];
    let mut manifest = DriverManifest {
        magic: DRIVER_MANIFEST_MAGIC,
        abi_version: rustos_abi::ABI_VERSION_CURRENT,
        kind: DriverKind::UserSpace,
        reserved0: 0,
        capability_count: u16::try_from(caps.len()).expect("caps fit in u16"),
        syscall_table_hash: SYS_HASH,
        signer_pubkey,
        signature: [0u8; 64],
    };
    let encoded = manifest.to_le_bytes();
    let mut signed_message = Vec::with_capacity(DriverManifest::WIRE_LEN - 64 + caps.len() * 2);
    signed_message.extend_from_slice(&encoded[..DriverManifest::WIRE_LEN - 64]);
    for c in caps {
        signed_message.extend_from_slice(&c.to_le_bytes());
    }
    let sig = signing_key.sign(&signed_message);
    manifest.signature = sig.to_bytes();

    let mut image: Vec<u8> = Vec::new();
    image.extend_from_slice(&manifest.to_le_bytes());
    for c in caps {
        image.extend_from_slice(&c.to_le_bytes());
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// Signed framebuffer-driver `.rxe` image bytes.\n");
    out.push_str("pub const FB_IMAGE: &[u8] = &[");
    for (i, b) in image.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// Trust-anchor public key the host's `HostConfig` accepts.\n");
    out.push_str("pub const TRUSTED_SIGNER_PUBKEY: [u8; 32] = [");
    for (i, b) in signer_pubkey.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// SHA-256 fingerprint of the host's syscall table.\n");
    out.push_str("pub const SYSCALL_TABLE_HASH: [u8; 32] = [");
    for (i, b) in SYS_HASH.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n");

    out.push_str("\n/// Canonical QEMU `virt` flattened device tree, dumped at build\n");
    out.push_str("/// time for the aarch64-none target (empty on host builds).\n");
    out.push_str("pub const DTB_BLOB: &[u8] = &[");
    for (i, b) in dtb_bytes.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n");

    let path = PathBuf::from(&out_dir).join("fb_fixture.rs");
    fs::write(&path, out).expect("write fb_fixture.rs");
}

/// Dump the canonical QEMU `virt`-board flattened device tree to a file
/// in `OUT_DIR` and return its bytes, so the freestanding bin can embed
/// it. QEMU's `-kernel <ELF>` aarch64 path passes no DTB pointer to the
/// kernel, so the test embeds the board's DTB instead. The machine args
/// match the runner's (`tools/qemu` aarch64 `virt`, `cortex-a72`, 256
/// MiB, 1 CPU); the `fw_cfg` MMIO base the test reads from it is the
/// stable `virt`-board layout.
fn dump_virt_dtb(out_dir: &std::ffi::OsStr) -> Vec<u8> {
    let dtb_path = PathBuf::from(out_dir).join("virt.dtb");
    let machine = format!("virt,dumpdtb={}", dtb_path.display());
    let status = Command::new("qemu-system-aarch64")
        .args([
            "-M",
            &machine,
            "-cpu",
            "cortex-a72",
            "-m",
            "256M",
            "-smp",
            "1",
            "-display",
            "none",
            "-no-reboot",
        ])
        .status()
        .expect("run qemu-system-aarch64 to dump the virt DTB");
    assert!(status.success(), "qemu dumpdtb failed: {status}");
    fs::read(&dtb_path).expect("read dumped virt.dtb")
}
