//! x86_64 PID 1 (`init`) spawn seam — `plans/PI.md` X3a.
//!
//! [`X86_64InitSpawn`] implements the architecture-neutral
//! [`rustos_kernel_core::InitSpawn`] hook the boot pipeline installs into the
//! [`rustos_kernel_core::BootInfo`] hand-off (`boot::try_boot` →
//! `BootInfo::with_init`). It is the cross-port sibling of the aarch64
//! `init_spawn` seam: once every init phase has succeeded and
//! `kernel_core::kernel_main` has emitted
//! [`rustos_kernel_core::AuditEvent::BootCompleted`], the core invokes
//! [`InitSpawn::spawn_init`]; this implementation builds the embedded `init`
//! (`Run`) program's ring-3 image through the production, capability-checked,
//! audited spawn caller ([`rustos_kernel_core::spawn_image`]) and admits it as
//! a **resumable user kthread** ([`InitSpawnCtx::admit_init`]). PID 1 then runs
//! under the live scheduler `kernel_main` drains; its `yield`/`exit` syscalls
//! suspend it back through the Arch-HAL context switch.
//!
//! The image, its relocation bias ([`INIT_USER_BIAS`]), and the kernel's
//! syscall CFI tag are baked at build time (`build.rs` →
//! `rustos_itest_harness::elf2rxe`), exactly like the aarch64 seam and the
//! proven `spawn_el0_resume_qemu_x86_64` fixture, so there is one conversion
//! path (`AGENTS.md` §2.2). Spawning `init` is *not* a privileged bypass: the
//! program receives only the authority its manifest requests intersected with
//! its user's grants (`AGENTS.md` §4, §16.5); this seam only authorises the
//! *act* of spawning under `CAP_PROC_SPAWN`.
//!
//! # x86_64 specifics versus the aarch64 sibling
//!
//! * The address space is built from
//!   [`ArchAddressSpace::new_identity_first_gib`] ([`IDENTITY_GIB`] GiB of low
//!   identity + the higher-half kernel window the trampoline established). The
//!   x86_64 page-table walk recovers each intermediate table from its **low
//!   physical address**, and the live allocator hands the image's frames out
//!   of physical RAM past the low 32 MiB, so the fresh space the seam switches
//!   to while building the image must identity-map all of RAM (and the
//!   architectural LAPIC MMIO page at ~3.98 GiB, which the scheduler touches
//!   under PID 1's CR3 between user entries) — exactly the boot trampoline's
//!   identity map. The narrower 32 MiB window the other x86_64 verticals use
//!   is only enough when every table and frame lives in low memory.
//! * The `pre_resume` hook does two things (the aarch64 hook only the first):
//!   reload CR3 to PID 1's own PML4 ([`activate_user_root`], isolation §4) and
//!   repoint the per-CPU `syscall` entry stack at PID 1's own kernel stack
//!   ([`syscall_entry::set_kernel_rsp0`]) — the gap aarch64 fills implicitly
//!   through `SP_EL1` (`plans/PI.md` §X). A rejected stack top leaves the slot
//!   unchanged and the next syscall faults loudly (fail closed, §5.4 / §2.9).
//! * PID 1's kernel stack is drawn from the boot-carved kthread guard arena
//!   (`ArenaStack` via `KTHREAD_STACK_ARENA`): the seam re-expresses the
//!   2 MiB identity block covering the stack's guard page at 4 KiB
//!   granularity in PID 1's *own* PML4 and unmaps that page, so a kernel-
//!   stack overrun takes a synchronous page fault under PID 1's CR3 — the
//!   real hardware guard-page fault-form, the cross-port sibling of the
//!   aarch64 seam (`plans/PI.md` G3b-2, `AGENTS.md` §4 / §2.17). When the
//!   boot path carved no arena (a machine too small, or the split/unmap
//!   fails) the seam falls back to the heap-backed software-canary
//!   [`BoxStack`] rather than ever running unguarded (fail closed, §2.9).
//! * Physical frames are reached through a [`DirectPhysMap`] over the
//!   higher-half kernel window (`[0, 1 GiB)` physical), the same window
//!   `boot.s` maps; the QEMU proving-ground box's RAM falls inside it. Wider
//!   physical RAM is a later direct-map stage shared with the rest of the
//!   x86_64 port.

use core::sync::atomic::{AtomicBool, Ordering};

use alloc::boxed::Box;

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery};
use rustos_arch_api::mmu::AddressSpace as MmuAddressSpace;
use rustos_arch_api::EnterUser;
use rustos_arch_x86_64::paging::{
    activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool, KERNEL_VMA_BASE,
};
use rustos_arch_x86_64::syscall_entry;
use rustos_arch_x86_64::userentry::UserMode;
use rustos_caps::CapabilitySet;
use rustos_kernel_core::{
    spawn_image, BoxStack, InitSpawn, InitSpawnCtx, KernelStack, SpawnRequest,
};
use rustos_kernel_mem::{AddressSpace, DirectPhysMap, PhysMap, UserAddressSpace, UserStack};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;

use crate::spawn_layout;
use crate::stack_arena::{FrameArenaGrow, KTHREAD_STACK_ARENA};

// `INIT_RXE: &[u8]` and `INIT_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/init_rxe.rs"));

/// Logical CPU the boot processor runs as — the single core the (c7-bin)
/// bring-up initialises and the one `set_kernel_rsp0` repoints.
const BOOT_CPU: usize = 0;

/// Span of the direct physical map the spawn build writes frame contents
/// through: the `[0, 1 GiB)` physical window the boot trampoline mirrors at
/// [`KERNEL_VMA_BASE`] (`boot.s` SAFETY-INVARIANT 9).
const PHYSMAP_SPAN: u64 = 1 << 30;

/// Gigabytes of low identity map PID 1's address space provides.
///
/// 4 GiB mirrors the boot trampoline's identity map: it covers all of the
/// platform's RAM (so the page-table walk's low-physical table dereferences
/// and the live allocator's image frames resolve) and the architectural LAPIC
/// MMIO page at ~3.98 GiB (so the scheduler's LAPIC accesses stay valid under
/// PID 1's CR3). [`INIT_USER_BIAS`] (64 GiB) sits far above it, so the
/// program's pages land on freshly walked tables rather than colliding with an
/// identity huge page.
const IDENTITY_GIB: usize = 4;

/// User stack base: the shared [`spawn_layout::USER_STACK_OFFSET`] above
/// this image's bias (the layout offsets and sizes are shared across the
/// ports in [`crate::spawn_layout`], `AGENTS.md` §2.2).
const USER_STACK_BASE: u64 = INIT_USER_BIAS + spawn_layout::USER_STACK_OFFSET;
/// User virtual address the startup-vector block is written at.
const USER_BLOCK_BASE: u64 = INIT_USER_BIAS + spawn_layout::USER_BLOCK_OFFSET;

/// Page-table pool backing PID 1's PML4 hierarchy.
///
/// Lives in `.bss` for the lifetime of the kernel image, so CR3 keeps
/// pointing at a valid hierarchy after [`X86_64InitSpawn::spawn_init`]
/// switches to it (`AGENTS.md` §2.1 — monotonic, never freed).
static INIT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Set once PID 1 has been spawned so a re-entry cannot re-run the path.
static INIT_SPAWNED: AtomicBool = AtomicBool::new(false);

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege
/// [`spawn_image`] requires to authorise building PID 1's image (`AGENTS.md`
/// §5.4). It does not widen `init`'s own authority, which is its `rxe`
/// manifest's request intersected with its user's grants (`AGENTS.md` §16.5).
struct SpawnAuthority;

impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The x86_64 PID 1 spawn seam installed into the
/// [`rustos_kernel_core::BootInfo`] hand-off by `boot::try_boot`.
pub struct X86_64InitSpawn;

/// The single, `'static` [`X86_64InitSpawn`] the boot path borrows.
pub static X86_64_INIT_SPAWN: X86_64InitSpawn = X86_64InitSpawn;

/// `init`'s effective capability set: `CAP_CONSOLE_WRITE`, so PID 1 can write
/// its startup banner through the `stream_write` syscall, plus
/// `CAP_PROC_SPAWN`, so it can launch the user's session program through the
/// `spawn` syscall (served by the x86_64 `ProcessSpawn` producer
/// `spawn_producer`, `plans/PI.md` X3b). The boot path passes this as both the
/// user grant and the manifest request, so the intersection the kernel derives
/// is the same set — `init` is granted no more (`AGENTS.md` §5.2), and the
/// child it later launches receives only *its own* set, never `init`'s
/// (`AGENTS.md` §4, §16.5).
fn init_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::CONSOLE_WRITE);
    caps.insert(CapabilityId::PROC_SPAWN);
    caps
}

impl InitSpawn for X86_64InitSpawn {
    fn spawn_init(&self, ctx: &dyn InitSpawnCtx) {
        // Spawn PID 1 at most once; a spurious re-entry falls through to the
        // caller's fail-closed halt rather than building a second image.
        if INIT_SPAWNED
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }

        // Build a PML4 identity-mapping the low [`IDENTITY_GIB`] GiB (RAM +
        // the LAPIC MMIO page) and the higher-half kernel window, so the
        // page-table walk's low-physical table dereferences, the live
        // allocator's image frames, and the scheduler's LAPIC accesses all
        // resolve under PID 1's CR3 (the production `kernel_main` drain runs
        // on PID 1's root once `pre_resume` has reloaded it). Fail closed on
        // page-table-pool exhaustion (`AGENTS.md` §2.9).
        let Some(mut arch) =
            ArchAddressSpace::new_identity_first_gib(&INIT_PAGE_TABLES, IDENTITY_GIB)
        else {
            return;
        };
        // Capture PID 1's PML4 root before the arch space is moved into the
        // `kernel/mem` wrapper, so the `pre_resume` hook can reload CR3 with
        // it before every switch into PID 1 (`plans/SPAWN.md` SP2). It is a
        // plain `u64`, so the boxed hook stays `Send`.
        let init_root_phys = arch.pml4_phys();

        // Build PID 1's kernel stack (`plans/PI.md` G3b-2). The boot path
        // carved a guard arena out of firmware-usable RAM and published it to
        // the kthread-stack allocator; if a region is available, re-express
        // the coarse identity block covering its guard page at 4 KiB
        // granularity in PID 1's *own* PML4 and unmap that single page, so an
        // overrun of `init`'s kernel stack takes a synchronous page fault
        // under PID 1's CR3 rather than corrupting the lower-addressed
        // neighbour (the real guard-page fault-form, `AGENTS.md` §4 / §2.17).
        // Doing it on `arch` *before* it is switched to means no live access
        // is disturbed (`split_block` only adds table levels reproducing the
        // existing translation) and no TLB maintenance is needed. The arena
        // grows on demand by chaining fresh 2 MiB blocks out of the kernel's
        // live frame allocator when its boot-carved block is exhausted
        // (`AGENTS.md` §24.1); a chained block is bounded to the identity
        // window so the stack stays mapped in PID 1's own root. If no arena
        // region is available, or the split/unmap could not be applied, fall
        // back to a heap-backed software-canary `BoxStack` rather than ever
        // running on an unguarded stack (fail closed, `AGENTS.md` §2.9 /
        // §2.17).
        let grow = FrameArenaGrow::new(ctx.frames(), (IDENTITY_GIB as u64) << 30);
        let kernel_stack: Box<dyn KernelStack + Send> =
            match KTHREAD_STACK_ARENA.alloc(&grow, &crate::stack_arena::IdentityBlockStore) {
                Some(stack) => {
                    let guard = stack.guard_page();
                    match arch
                        .split_block(guard)
                        .and_then(|()| arch.unmap(guard).map(|_| ()))
                    {
                        Ok(()) => Box::new(stack),
                        Err(_) => Box::new(BoxStack::new()),
                    }
                }
                None => Box::new(BoxStack::new()),
            };

        // SAFETY: the new space maps the low 32 MiB identity, the higher-half
        // kernel window, and the LAPIC MMIO page, so the executing RIP, the
        // current kernel stack, the per-CPU `swapgs` TLS, the page-table
        // pool, the live frame allocator's frames (the QEMU box's RAM is in
        // the first GiB), the heap, the dispatch path, and every LAPIC access
        // stay mapped across the CR3 switch — exactly `AddressSpace::switch`'s
        // contract. Called once on the boot CPU. The `admit_init` contract
        // requires the image be built into the active space, so the switch
        // precedes `spawn_image` below.
        unsafe { arch.switch() };

        let mut space = AddressSpace::new(arch);
        let physmap = DirectPhysMap::new(KERNEL_VMA_BASE, PHYSMAP_SPAN);

        // Parse the build-time `init` `rxe` blob against the kernel's own
        // compiled-in syscall CFI tag (§9 / §19.2). A mismatch fails closed.
        let Ok(image) = LoadImage::parse(INIT_RXE, &SYSCALL_TABLE_HASH) else {
            return;
        };

        let request = SpawnRequest {
            image: &image,
            image_bytes: INIT_RXE,
            bias: INIT_USER_BIAS,
            stack: UserStack {
                base: USER_STACK_BASE,
                page_count: spawn_layout::USER_STACK_PAGES,
            },
            start_block_base: USER_BLOCK_BASE,
            args: &[b"init"],
            env: &[],
            canary: spawn_layout::INIT_CANARY,
        };

        // Authorise + build the ring-3 image (emits `ProcessSpawned`) without
        // entering yet — PID 1 must be registered with the scheduler /
        // capability table / address-space registry *first* so its first
        // syscall resolves a caller context (`plans/PI.md` P6c-3).
        // SAFETY: building the image is itself safe; the returned `UserEntry`
        // is only entered below, once `space` is active (just switched to)
        // and the ring-3 trap path is installed. The frame source draws
        // first-GiB RAM frames from the kernel's live allocator. A returning
        // `Err` drops back to the caller's fail-closed halt (`AGENTS.md`
        // §2.9).
        let frames = ctx.frames();
        let Ok(entry) = (unsafe {
            spawn_image(
                &SpawnAuthority,
                ctx.audit(),
                &mut space,
                &physmap,
                &request,
                move || frames.alloc().ok(),
            )
        }) else {
            return;
        };

        // The user-mode transition, boxed for the scheduler task body the
        // core wraps PID 1 in. `enter_user` diverges into ring 3, so the
        // closure never truly returns (its `!` coerces to `()`).
        let user_mode = UserMode::new();
        let enter: Box<dyn FnMut() + Send> = Box::new(move || {
            // SAFETY: `space` is the active address space and the `syscall`
            // entry + production dispatch callback are installed, so the
            // entered program's first `syscall` is handled.
            // `build_process_image` mapped the entry/stack as user pages.
            unsafe { user_mode.enter_user(entry) }
        });

        // PID 1's user-address-space reactivation hook (`plans/SPAWN.md` SP2):
        // the core runs it on the dispatcher's context immediately before
        // every switch into PID 1. It reloads CR3 to PID 1's own root
        // (isolation §4) and repoints the per-CPU `syscall` entry stack at
        // PID 1's own kernel stack (the value the runtime hands it). It
        // captures only the `u64` root, so it is `Send`.
        let pre_resume: Box<dyn FnMut(u64) + Send> = Box::new(move |stack_top: u64| {
            // Repoint the per-CPU syscall entry stack before the switch-in. A
            // rejected value (it is validated canonical/aligned/kernel-half)
            // leaves the slot unchanged and the next syscall faults loudly —
            // fail closed, never a silent wrong stack (`AGENTS.md` §5.4 /
            // §2.9).
            let _ = syscall_entry::set_kernel_rsp0(BOOT_CPU, stack_top);
            // SAFETY: paging is enabled and `init_root_phys` is the PML4 of
            // PID 1's space, which maps the low identity + higher-half kernel
            // window the running dispatcher executes from — exactly
            // `activate_user_root`'s contract.
            unsafe { activate_user_root(init_root_phys) };
        });

        // Freeze the just-built mappings into the registry-storable,
        // `Send + Sync` snapshot the kernel-wide address-space registry holds
        // (the live arch `space` is not `Sync`), and box the direct map that
        // backs it, so PID 1's `stream_write` can copy its banner out of user
        // memory. Freezing *after* `spawn_image` captures every mapped page —
        // segments, stack, and the startup-vector block.
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());
        let physmap: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);

        // Register PID 1's caps + address space, publish it as the current
        // task, and dispatch it — `admit_init` drains the run queue until PID
        // 1 has exited, then returns so `kernel_main` halts fail-closed.
        // SAFETY: the image was built into and `space` switched to active
        // above, and the trap path is installed, per the
        // `InitSpawnCtx::admit_init` contract; `frozen` faithfully describes
        // the active mappings, `physmap` backs them, and `kernel_stack` is a
        // region exclusive to PID 1 that stays mapped for the task's lifetime.
        // The x86_64 port does not yet retain a live, mutable address space
        // for `mem_map` / `mmio_map` (that is the aarch64-first chunk
        // `plans/PI.md` 5d-0-ii (b′)-2); pass `None` so PID 1's `mem_map` /
        // `mmio_map` fail closed here (`AGENTS.md` §2.9).
        unsafe {
            ctx.admit_init(
                init_caps(),
                frozen,
                physmap,
                kernel_stack,
                pre_resume,
                None,
                enter,
            );
        }
    }
}
