//! x86_64 PID 1 (`init`) spawn seam — `plans/PI.md` X3a.
//!
//! [`X86_64InitSpawn`] implements the architecture-neutral
//! [`rustos_kernel_core::InitSpawn`] hook the boot pipeline installs into the
//! [`rustos_kernel_core::BootInfo`] hand-off (`boot::try_boot` →
//! `BootInfo::with_init`). It is the cross-port sibling of the aarch64
//! `init_spawn` seam: once every init phase has succeeded and
//! `kernel_core::kernel_main` has emitted
//! [`rustos_kernel_core::AuditEvent::BootCompleted`], the core invokes
//! [`InitSpawn::spawn_init`]; this implementation builds the embedded `init`
//! (`Run`) program's ring-3 image through the production, capability-checked,
//! audited spawn caller ([`rustos_kernel_core::spawn_image`]) and admits it as
//! a **resumable user kthread** ([`InitSpawnCtx::admit_init`]). PID 1 then runs
//! under the live scheduler `kernel_main` drains; its `yield`/`exit` syscalls
//! suspend it back through the Arch-HAL context switch.
//!
//! The image, its relocation bias ([`INIT_USER_BIAS`]), and the kernel's
//! syscall CFI tag are baked at build time (`build.rs` →
//! `rustos_itest_harness::elf2rxe`), exactly like the aarch64 seam and the
//! proven `spawn_el0_resume_qemu_x86_64` fixture, so there is one conversion
//! path. Spawning `init` is *not* a privileged bypass: the
//! program receives only the authority its manifest requests intersected with
//! its user's grants; this seam only authorises the
//! *act* of spawning under `CAP_PROC_SPAWN`.
//!
//! # x86_64 specifics versus the aarch64 sibling
//!
//! * The address space is built from
//!   [`ArchAddressSpace::new_identity_first_gib`] ([`IDENTITY_GIB`] GiB of low
//!   identity + the higher-half kernel window the trampoline established). The
//!   x86_64 page-table walk recovers each intermediate table from its **low
//!   physical address**, and the live allocator hands the image's frames out
//!   of physical RAM past the low 32 MiB, so the fresh space the seam switches
//!   to while building the image must identity-map all of RAM (and the
//!   architectural LAPIC MMIO page at ~3.98 GiB, which the scheduler touches
//!   under PID 1's CR3 between user entries) — exactly the boot trampoline's
//!   identity map. The narrower 32 MiB window the other x86_64 verticals use
//!   is only enough when every table and frame lives in low memory.
//! * The `pre_resume` hook does two things (the aarch64 hook only the first):
//!   reload CR3 to PID 1's own PML4 ([`activate_user_root`], isolation) and
//!   repoint the per-CPU `syscall` entry stack at PID 1's own kernel stack
//!   ([`syscall_entry::set_kernel_rsp0`]) — the gap aarch64 fills implicitly
//!   through `SP_EL1` (`plans/PI.md` §X). A rejected stack top leaves the slot
//!   unchanged and the next syscall faults loudly (fail closed).
//! * PID 1's kernel stack is drawn from the boot-carved kthread guard arena
//!   (`ArenaStack` via `KTHREAD_STACK_ARENA`): the seam re-expresses the
//!   2 MiB identity block covering the stack's guard page at 4 KiB
//!   granularity in PID 1's *own* PML4 and unmaps that page, so a kernel-
//!   stack overrun takes a synchronous page fault under PID 1's CR3 — the
//!   real hardware guard-page fault-form, the cross-port sibling of the
//!   aarch64 seam (`plans/PI.md` G3b-2). When the
//!   boot path carved no arena (a machine too small, or the split/unmap
//!   fails) the seam falls back to the heap-backed software-canary
//!   [`BoxStack`] rather than ever running unguarded (fail closed).
//! * Physical frames are reached through a [`DirectPhysMap`] over the
//!   higher-half kernel window (`[0, 1 GiB)` physical), the same window
//!   `boot.s` maps; the QEMU proving-ground box's RAM falls inside it. Wider
//!   physical RAM is a later direct-map stage shared with the rest of the
//!   x86_64 port.

use core::sync::atomic::{AtomicBool, Ordering};

use alloc::boxed::Box;

use rustos_abi::rxe::LoadImage;
use rustos_arch_api::mmu::AddressSpace as MmuAddressSpace;
use rustos_arch_api::EnterUser;
use rustos_arch_x86_64::paging::{
    activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool, KERNEL_VMA_BASE,
};
use rustos_arch_x86_64::syscall_entry;
use rustos_arch_x86_64::userentry::UserMode;
use rustos_kernel_core::{
    spawn_image, BoxStack, InitSpawn, InitSpawnCtx, KernelStack, SpawnRequest,
};
use rustos_kernel_mem::{
    AddressSpace, DirectPhysMap, LiveSpace, LiveUserSpace, PhysMap, UserAddressSpace, UserStack,
    VirtAddr,
};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;

use crate::spawn_layout;
use crate::stack_arena::{FrameArenaGrow, KTHREAD_STACK_ARENA};

// `INIT_RXE: &[u8]` and `INIT_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/init_rxe.rs"));

/// Logical CPU the boot processor runs as — the single core the (c7-bin)
/// bring-up initialises and the one `set_kernel_rsp0` repoints.
const BOOT_CPU: usize = 0;

/// Span of the direct physical map the spawn build writes frame contents
/// through: the `[0, 1 GiB)` physical window the boot trampoline mirrors at
/// [`KERNEL_VMA_BASE`] (`boot.s` SAFETY-INVARIANT 9).
const PHYSMAP_SPAN: u64 = 1 << 30;

/// Gigabytes of low identity map PID 1's address space provides.
///
/// 4 GiB mirrors the boot trampoline's identity map: it covers all of the
/// platform's RAM (so the page-table walk's low-physical table dereferences
/// and the live allocator's image frames resolve) and the architectural LAPIC
/// MMIO page at ~3.98 GiB (so the scheduler's LAPIC accesses stay valid under
/// PID 1's CR3). [`INIT_USER_BIAS`] (64 GiB) sits far above it, so the
/// program's pages land on freshly walked tables rather than colliding with an
/// identity huge page.
const IDENTITY_GIB: usize = 4;

/// Base of PID 1's device-window virtual region (`plans/PI.md`
/// 5d-0-ii (b′)): the retained [`LiveSpace`]'s
/// [`rustos_kernel_mem::MmioWindowMap`] hands each `mmio_map` a
/// guard-bracketed window out of `[MMIO_WINDOW_BASE, MMIO_WINDOW_BASE +
/// MMIO_WINDOW_PAGES·4 KiB)`.
const MMIO_WINDOW_BASE: u64 = INIT_USER_BIAS + spawn_layout::MMIO_WINDOW_OFFSET;
/// Base of PID 1's non-`FIXED` anonymous-heap virtual region (`plans/PI.md`
/// 5d-0-ii (c)): the retained [`LiveSpace`]'s
/// [`rustos_kernel_mem::AnonWindowMap`] places each non-`FIXED` `mem_map`
/// out of `[ANON_WINDOW_BASE, ANON_WINDOW_BASE + anon_window_pages·4 KiB)`,
/// where the page count scales with discovered RAM (the window is the
/// topmost user region so it has room to grow up to `super::USER_VA_TOP`).
const ANON_WINDOW_BASE: u64 = INIT_USER_BIAS + spawn_layout::ANON_WINDOW_OFFSET;
/// Base of PID 1's guarded DMA-buffer virtual region (`plans/PI.md`
/// 5d-0-ii (c) DMA half): the retained [`LiveSpace`]'s
/// [`rustos_kernel_mem::DmaWindowMap`] carves each `dma_alloc` buffer out of
/// `[DMA_WINDOW_BASE, DMA_WINDOW_BASE + DMA_WINDOW_PAGES·4 KiB)`.
const DMA_WINDOW_BASE: u64 = INIT_USER_BIAS + spawn_layout::DMA_WINDOW_OFFSET;
/// Base of PID 1's cross-process shared-memory virtual region: the retained
/// [`LiveSpace`]'s shared-window allocator maps each granted `shm_map`
/// region out of `[SHARED_WINDOW_BASE, SHARED_WINDOW_BASE +
/// SHARED_WINDOW_PAGES * 4 KiB)`.
const SHARED_WINDOW_BASE: u64 = INIT_USER_BIAS + spawn_layout::SHARED_WINDOW_OFFSET;

/// Page-table pool backing PID 1's PML4 hierarchy.
///
/// Lives in `.bss` for the lifetime of the kernel image, so CR3 keeps
/// pointing at a valid hierarchy after [`X86_64InitSpawn::spawn_init`]
/// switches to it (monotonic, never freed).
static INIT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Set once PID 1 has been spawned so a re-entry cannot re-run the path.
static INIT_SPAWNED: AtomicBool = AtomicBool::new(false);

/// The x86_64 PID 1 spawn seam installed into the
/// [`rustos_kernel_core::BootInfo`] hand-off by `boot::try_boot`.
pub struct X86_64InitSpawn;

/// The single, `'static` [`X86_64InitSpawn`] the boot path borrows.
pub static X86_64_INIT_SPAWN: X86_64InitSpawn = X86_64InitSpawn;

impl InitSpawn for X86_64InitSpawn {
    fn spawn_init(&self, ctx: &'static (dyn InitSpawnCtx + Sync)) {
        // Spawn PID 1 at most once; a spurious re-entry falls through to the
        // caller's fail-closed halt rather than building a second image.
        if INIT_SPAWNED
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }

        // Build a PML4 identity-mapping the low [`IDENTITY_GIB`] GiB (RAM +
        // the LAPIC MMIO page) and the higher-half kernel window, so the
        // page-table walk's low-physical table dereferences, the live
        // allocator's image frames, and the scheduler's LAPIC accesses all
        // resolve under PID 1's CR3 (the production `kernel_main` drain runs
        // on PID 1's root once `pre_resume` has reloaded it). Fail closed on
        // page-table-pool exhaustion.
        let Some(mut arch) =
            ArchAddressSpace::new_identity_first_gib(&INIT_PAGE_TABLES, IDENTITY_GIB)
        else {
            return;
        };
        // Capture PID 1's PML4 root before the arch space is moved into the
        // `kernel/mem` wrapper, so the `pre_resume` hook can reload CR3 with
        // it before every switch into PID 1 (`plans/SPAWN.md` SP2). It is a
        // plain `u64`, so the boxed hook stays `Send`.
        let init_root_phys = arch.pml4_phys();

        // Build PID 1's kernel stack (`plans/PI.md` G3b-2). The boot path
        // carved a guard arena out of firmware-usable RAM and published it to
        // the kthread-stack allocator; if a region is available, re-express
        // the coarse identity block covering its guard page at 4 KiB
        // granularity in PID 1's *own* PML4 and unmap that single page, so an
        // overrun of `init`'s kernel stack takes a synchronous page fault
        // under PID 1's CR3 rather than corrupting the lower-addressed
        // neighbour (the real guard-page fault-form).
        // Doing it on `arch` *before* it is switched to means no live access
        // is disturbed (`split_block` only adds table levels reproducing the
        // existing translation) and no TLB maintenance is needed. The arena
        // grows on demand by chaining fresh 2 MiB blocks out of the kernel's
        // live frame allocator when its boot-carved block is exhausted; a chained block is bounded to the identity
        // window so the stack stays mapped in PID 1's own root. If no arena
        // region is available, or the split/unmap could not be applied, fall
        // back to a heap-backed software-canary `BoxStack` rather than ever
        // running on an unguarded stack (fail closed).
        let grow = FrameArenaGrow::new(ctx.frames(), (IDENTITY_GIB as u64) << 30);
        let kernel_stack: Box<dyn KernelStack + Send> =
            match KTHREAD_STACK_ARENA.alloc(&grow, &crate::stack_arena::IdentityBlockStore) {
                Some(stack) => {
                    let guard = stack.guard_page();
                    match arch
                        .split_block(guard)
                        .and_then(|()| arch.unmap(guard).map(|_| ()))
                    {
                        Ok(()) => Box::new(stack),
                        Err(_) => Box::new(BoxStack::new()),
                    }
                }
                None => Box::new(BoxStack::new()),
            };

        // SAFETY: the new space maps the low 32 MiB identity, the higher-half
        // kernel window, and the LAPIC MMIO page, so the executing RIP, the
        // current kernel stack, the per-CPU `swapgs` TLS, the page-table
        // pool, the live frame allocator's frames (the QEMU box's RAM is in
        // the first GiB), the heap, the dispatch path, and every LAPIC access
        // stay mapped across the CR3 switch — exactly `AddressSpace::switch`'s
        // contract. Called once on the boot CPU. The `admit_init` contract
        // requires the image be built into the active space, so the switch
        // precedes `spawn_image` below.
        unsafe { arch.switch() };

        let mut space = AddressSpace::new(arch);
        let physmap = DirectPhysMap::new(KERNEL_VMA_BASE, PHYSMAP_SPAN);

        // Parse the build-time `init` `rxe` blob against the kernel's own
        // compiled-in syscall CFI tag. A mismatch fails closed.
        let Ok(image) = LoadImage::parse(INIT_RXE, &SYSCALL_TABLE_HASH) else {
            return;
        };

        // Place the stack and startup block above the image's mapped top
        // through the shared per-spawn derivation (one definition across
        // the ports); an image too large for the user region fails closed.
        let Some(layout) = spawn_layout::user_layout(&image, INIT_USER_BIAS) else {
            return;
        };
        // The span record the admission path stores so the stack-growth
        // fault path can back pages inside it (one shared derivation
        // across the ports; a malformed span fails the boot closed).
        let Some(stack_span) = spawn_layout::stack_span(&layout) else {
            return;
        };

        let request = SpawnRequest {
            image: &image,
            image_bytes: INIT_RXE,
            bias: INIT_USER_BIAS,
            stack: UserStack {
                base: layout.stack_base,
                page_count: spawn_layout::USER_STACK_COMMIT_PAGES,
            },
            start_block_base: layout.block_base,
            args: spawn_layout::INIT_ARGS,
            env: &[],
            canary: spawn_layout::INIT_CANARY,
        };

        // Authorise + build the ring-3 image (emits `ProcessSpawned`) without
        // entering yet — PID 1 must be registered with the scheduler /
        // capability table / address-space registry *first* so its first
        // syscall resolves a caller context (`plans/PI.md` P6c-3).
        // SAFETY: building the image is itself safe; the returned `UserEntry`
        // is only entered below, once `space` is active (just switched to)
        // and the ring-3 trap path is installed. The frame source draws
        // first-GiB RAM frames from the kernel's live allocator. A returning
        // `Err` drops back to the caller's fail-closed halt.
        let frames = ctx.frames();
        let Ok(entry) = (unsafe {
            spawn_image(
                &spawn_layout::SpawnAuthority,
                ctx.audit(),
                &mut space,
                &physmap,
                &request,
                move || frames.alloc().ok(),
            )
        }) else {
            return;
        };

        // The user-mode transition, boxed for the scheduler task body the
        // core wraps PID 1 in. `enter_user` diverges into ring 3, so the
        // closure never truly returns (its `!` coerces to `()`).
        let user_mode = UserMode::new();
        let enter: Box<dyn FnMut() + Send> = Box::new(move || {
            // SAFETY: `space` is the active address space and the `syscall`
            // entry + production dispatch callback are installed, so the
            // entered program's first `syscall` is handled.
            // `build_process_image` mapped the entry/stack as user pages.
            unsafe { user_mode.enter_user(entry) }
        });

        // PID 1's user-address-space reactivation hook (`plans/SPAWN.md` SP2):
        // the core runs it on the dispatcher's context immediately before
        // every switch into PID 1. It reloads CR3 to PID 1's own root
        // (isolation) and repoints the per-CPU `syscall` entry stack at
        // PID 1's own kernel stack (the value the runtime hands it). It
        // captures only the `u64` root, so it is `Send`.
        let pre_resume: Box<dyn FnMut(u64) + Send> = Box::new(move |stack_top: u64| {
            // `set_kernel_rsp0` repoints **both** PID 1's `syscall` entry
            // stack (`gs:0`) and its trap entry stack (`TSS.RSP0`) at PID 1's
            // own kernel stack — the latter is what makes an involuntary
            // LAPIC-timer preemption (P-1c), delivered through the IDT
            // interrupt gate which reads `TSS.RSP0`, land on PID 1's own stack
            // (one per-task kernel stack for both entry
            // kinds). A rejected value leaves the slots unchanged and the next
            // entry faults loudly (fail closed).
            let _ = syscall_entry::set_kernel_rsp0(BOOT_CPU, stack_top);
            // SAFETY: paging is enabled and `init_root_phys` is the PML4 of
            // PID 1's space, which maps the low identity + higher-half kernel
            // window the running dispatcher executes from — exactly
            // `activate_user_root`'s contract.
            unsafe { activate_user_root(init_root_phys) };
        });

        // Freeze the just-built mappings into the registry-storable,
        // `Send + Sync` snapshot the kernel-wide address-space registry holds
        // (the live arch `space` is not `Sync`), and box the direct map that
        // backs it, so PID 1's `stream_write` can copy its banner out of user
        // memory. Freezing *after* `spawn_image` captures every mapped page —
        // segments, stack, and the startup-vector block.
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());

        // Retain the live, mutable arch space behind the object-safe
        // `LiveUserSpace` boundary so PID 1's `mem_map` / `mmio_map` /
        // `dma_alloc` syscalls mutate *its own* address space (`plans/PI.md`
        // 5d-0-ii (b′)), the cross-port sibling of the aarch64 seam. The `LiveSpace` composes the audited
        // anonymous-map mechanism (over the kernel's `'static` frame
        // allocator, drawn from `static_frames`) and the guarded device-window
        // allocator (over the `[MMIO_WINDOW_BASE, …)` region); it carries the
        // *same* arch space the snapshot above was frozen from, and zeroes
        // anonymous frames through a fresh higher-half [`DirectPhysMap`]
        // identical to the one the image build used (the low identity + the
        // higher-half kernel window are both mapped under PID 1's CR3). A
        // context with no `'static` allocator, or a window the allocator
        // rejects, retains no live space and PID 1's `mem_map` / `mmio_map`
        // fail closed.
        let live: Option<Box<dyn LiveUserSpace + Send>> = match ctx.static_frames() {
            Some(static_frames) => {
                let windows = crate::user_windows::user_windows(
                    static_frames.total_frames() as u64,
                    ANON_WINDOW_BASE,
                    super::USER_VA_TOP,
                );
                LiveSpace::new(
                    space,
                    DirectPhysMap::new(KERNEL_VMA_BASE, PHYSMAP_SPAN),
                    static_frames,
                    VirtAddr::new(MMIO_WINDOW_BASE),
                    spawn_layout::MMIO_WINDOW_PAGES,
                    VirtAddr::new(ANON_WINDOW_BASE),
                    windows.anon_pages,
                    VirtAddr::new(DMA_WINDOW_BASE),
                    spawn_layout::DMA_WINDOW_PAGES,
                    VirtAddr::new(SHARED_WINDOW_BASE),
                    spawn_layout::SHARED_WINDOW_PAGES,
                    VirtAddr::new(windows.file_base),
                    windows.file_pages,
                )
                .ok()
                .map(|live| Box::new(live) as Box<dyn LiveUserSpace + Send>)
            }
            None => None,
        };

        let physmap: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);

        // Register PID 1's caps + address space, publish it as the current
        // task, and dispatch it — `admit_init` drains the run queue until PID
        // 1 has exited, then returns so `kernel_main` halts fail-closed.
        // SAFETY: the image was built into and `space` switched to active
        // above, and the trap path is installed, per the
        // `InitSpawnCtx::admit_init` contract; `frozen` faithfully describes
        // the active mappings, `physmap` backs them, `kernel_stack` is a
        // region exclusive to PID 1 that stays mapped for the task's lifetime,
        // and `live` retains the same arch space `frozen` was taken from.
        unsafe {
            ctx.admit_init(
                spawn_layout::init_caps(),
                frozen,
                physmap,
                stack_span,
                kernel_stack,
                pre_resume,
                live,
                enter,
            );
        }
    }
}
