//! The M1 demand-paged file-mapping fixture: the **single definition** of
//! the fixture file the `file_map_qemu_*` verticals serve through their
//! kernel-side read-only filesystem double and probe from the EL0 fixture
//! program (`tests/integration/file_map_program`).
//!
//! Both consuming build scripts (`file_map_qemu_aarch64` /
//! `file_map_qemu_riscv64`) read the geometry from here, emit the content
//! bytes for the kernel side, and pin the program's compile-time probe
//! expectations through the `RUSTOS_FM_*` environment variables — so the
//! program, the filesystem double, and the registry paths can never
//! disagree.
//!
//! Fixture shape (all offsets in bytes):
//!
//! * length `FILE_LEN`: three whole pages plus a tail, so the mapped
//!   region's final page straddles end of file (the demand-fault zero-fill
//!   case);
//! * a deterministic non-trivial byte pattern everywhere except…
//! * …a copy of the fixture's own path `FILE_PATH` at the start of page
//!   `PATH_OFFSET`, which the `verify` role hands to `fs_open` straight
//!   out of the **untouched** mapped page (the syscall copy-in
//!   fault-resolution proof).

use std::fmt::Write as _;

/// Page size shared by every Tier-1 MMU target the verticals run on.
pub const PAGE: u64 = 4096;

/// Absolute path the filesystem double serves the fixture under (and the
/// path spliced into the content at [`PATH_OFFSET`]).
pub const FILE_PATH: &str = "/data/fixture.bin";

/// Fixture length: three whole pages plus a 1234-byte tail, so the mapping
/// spans four pages and the last one straddles end of file.
pub const FILE_LEN: u64 = 3 * PAGE + 1234;

/// Byte offset of the spliced [`FILE_PATH`] copy (start of page 2 — a page
/// the `verify` role never probes before handing it to the kernel).
pub const PATH_OFFSET: u64 = 2 * PAGE;

/// Interior-page probe offset (page 1: neither the first page, nor the
/// path page, nor the end-of-file straddle page).
pub const INTERIOR_OFFSET: u64 = PAGE + 17;

// The geometry invariants the fixture roles assume, enforced at compile
// time so a careless edit to the constants above cannot silently break
// the probes' page classification.
const _: () = {
    assert!(PATH_OFFSET % PAGE == 0, "path copy must start a page");
    assert!(
        INTERIOR_OFFSET > PAGE && INTERIOR_OFFSET < 2 * PAGE,
        "interior probe must sit in page 1"
    );
    assert!(
        FILE_LEN / PAGE == 3 && FILE_LEN % PAGE != 0,
        "the last page must straddle EOF"
    );
};

/// The fixture's content bytes: a deterministic, page-varying pattern with
/// the [`FILE_PATH`] copy spliced in at [`PATH_OFFSET`].
///
/// The pattern (`(i * 31 + 7) mod 256`) has no page-size period, so a page
/// served at the wrong file offset can never match its probe.
#[must_use]
pub fn content() -> Vec<u8> {
    #[allow(clippy::cast_possible_truncation)]
    let mut bytes: Vec<u8> = (0..FILE_LEN)
        .map(|i| (i.wrapping_mul(31).wrapping_add(7) % 256) as u8)
        .collect();
    let path = FILE_PATH.as_bytes();
    let at = usize::try_from(PATH_OFFSET).expect("PATH_OFFSET fits usize on the build host");
    bytes[at..at + path.len()].copy_from_slice(path);
    bytes
}

/// The `RUSTOS_FM_*` environment pairs pinning the program's compile-time
/// probe expectations, computed from [`content`] so the program's asserts
/// and the kernel-served bytes share one origin.
#[must_use]
pub fn geometry_env() -> Vec<(&'static str, String)> {
    let bytes = content();
    let at = |offset: u64| bytes[usize::try_from(offset).expect("offset fits usize")];
    vec![
        ("RUSTOS_FM_FILE_LEN", FILE_LEN.to_string()),
        ("RUSTOS_FM_PATH", FILE_PATH.to_string()),
        ("RUSTOS_FM_PATH_OFFSET", PATH_OFFSET.to_string()),
        ("RUSTOS_FM_INTERIOR_OFFSET", INTERIOR_OFFSET.to_string()),
        ("RUSTOS_FM_BYTE_FIRST", at(0).to_string()),
        ("RUSTOS_FM_BYTE_INTERIOR", at(INTERIOR_OFFSET).to_string()),
        ("RUSTOS_FM_BYTE_LAST", at(FILE_LEN - 1).to_string()),
    ]
}

/// Emit the kernel-side fixture constants (`FIXTURE_PATH`,
/// `FIXTURE_CONTENT`) as a Rust source the consuming test `include!`s.
#[must_use]
pub fn kernel_fixture_source() -> String {
    let bytes = content();
    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// Absolute path the filesystem double serves the fixture under.\n");
    let _ = writeln!(out, "pub const FIXTURE_PATH: &str = {FILE_PATH:?};");
    out.push_str("/// The fixture file's content bytes (pattern + spliced path copy).\n");
    out.push_str("pub const FIXTURE_CONTENT: &[u8] = &[");
    for (i, b) in bytes.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        let _ = write!(out, "0x{b:02x}, ");
    }
    out.push_str("\n];\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Widen-or-panic index helper for the test assertions (test-only).
    fn idx(offset: u64) -> usize {
        usize::try_from(offset).expect("offset fits usize on the test host")
    }

    #[test]
    fn content_has_the_pinned_geometry() {
        // The page-classification invariants themselves are compile-time
        // `const` assertions beside the constants; this covers the
        // generated content.
        let bytes = content();
        assert_eq!(bytes.len() as u64, FILE_LEN);
        // The spliced path is intact and page-aligned.
        let at = idx(PATH_OFFSET);
        assert_eq!(&bytes[at..at + FILE_PATH.len()], FILE_PATH.as_bytes());
    }

    #[test]
    fn geometry_env_matches_the_content() {
        let bytes = content();
        let env = geometry_env();
        let get = |name: &str| {
            env.iter()
                .find(|(k, _)| *k == name)
                .map(|(_, v)| v.clone())
                .expect("pinned geometry variable")
        };
        assert_eq!(get("RUSTOS_FM_FILE_LEN"), FILE_LEN.to_string());
        assert_eq!(get("RUSTOS_FM_BYTE_FIRST"), bytes[0].to_string());
        assert_eq!(
            get("RUSTOS_FM_BYTE_INTERIOR"),
            bytes[idx(INTERIOR_OFFSET)].to_string()
        );
        assert_eq!(
            get("RUSTOS_FM_BYTE_LAST"),
            bytes[idx(FILE_LEN - 1)].to_string()
        );
    }

    #[test]
    fn kernel_fixture_source_names_both_constants() {
        let source = kernel_fixture_source();
        assert!(source.contains("pub const FIXTURE_PATH: &str = \"/data/fixture.bin\";"));
        assert!(source.contains("pub const FIXTURE_CONTENT: &[u8]"));
    }
}
