//! The generated-source glue every freestanding fixture program's build
//! script shares: the one linker script they all link with, and the one
//! emitter of the `PROGRAM_RXE` + `USER_BIAS` source they `include!`.
//!
//! Each vertical used to carry its own byte-identical copy of both, so a
//! change to the program layout or to the emitted source had to be made
//! dozens of times to stay consistent. They live here once instead.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use crate::USER_IMAGE_BIAS;

/// The single linker script every freestanding fixture program links with:
/// it roots `tairix-rt`'s `_start` and lays the PIE image out for the bias
/// the kernel spawn path maps a child at.
///
/// Absolute, resolved when this crate is compiled, so a consuming build
/// script names it without walking a relative path of its own. A build
/// script that links a fixture program must also
/// `cargo:rerun-if-changed` this path, or an edit to the script will not
/// relink the program.
pub const PROGRAM_LD: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/program.ld");

/// Buffer length [`format_grouped_hex`] renders into: `0x`, sixteen hex
/// digits, and the three `_` separators between the four digit groups.
pub const GROUPED_HEX_LEN: usize = 2 + 16 + 3;

/// Render `value` as a Rust hexadecimal literal with `_` between each group
/// of four digits (`0x0010_0000_0000`), into `out`.
///
/// The build script emits Rust source the crate `include!`s, and generated
/// source is linted like any other: a bare `{value:#x}` there trips the
/// "long literal lacking separators" lint at the *include site*, where it
/// cannot be fixed. Grouping at the point of emission keeps the generated
/// file idiomatic on its own terms, instead of stamping a blanket lint
/// exemption into it that would also hide a future real finding in the same
/// file. Leading all-zero groups are dropped, but never the last one, so
/// zero renders as `0x0000`. It renders into the caller's buffer rather
/// than allocating, so the kernel image builder can also call it while
/// laying out its own generated constants.
pub fn format_grouped_hex(value: u64, out: &mut [u8; GROUPED_HEX_LEN]) -> &str {
    let mut digits = [b'0'; 16];
    for (i, slot) in digits.iter_mut().enumerate() {
        let nibble = ((value >> ((15 - i) * 4)) & 0xf) as u8;
        *slot = match nibble {
            0..=9 => b'0' + nibble,
            _ => b'a' + (nibble - 10),
        };
    }
    // Whole groups only: every emitted group is four digits wide, which is
    // exactly the shape the lint accepts.
    let mut first = 0;
    while first + 4 < digits.len() && digits[first..first + 4] == [b'0'; 4] {
        first += 4;
    }

    out[0] = b'0';
    out[1] = b'x';
    let mut len = 2;
    for group in digits[first..].as_chunks::<4>().0 {
        if len > 2 {
            out[len] = b'_';
            len += 1;
        }
        out[len..len + 4].copy_from_slice(group);
        len += 4;
    }
    // Every byte written above is ASCII, so the prefix is valid UTF-8; fall
    // back to the empty string rather than panicking if that were broken.
    core::str::from_utf8(&out[..len]).unwrap_or("")
}

/// Open a fixture source: the generated-file banner and the shared
/// [`USER_IMAGE_BIAS`] the images' relocations were baked for, emitted as
/// `USER_BIAS`.
///
/// The bias is rendered through [`format_grouped_hex`] because the emitted
/// file is compiled and linted like any other source; a bare
/// `0x1000000000` there trips the missing-separator lint at the `include!`
/// site, where it cannot be fixed.
///
/// A caller pins its own extra constants onto the returned string, appends
/// each image with [`push_rxe_blob`], and writes the whole thing with
/// [`write_fixture`].
#[must_use]
pub fn fixture_header() -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// Virtual base every program image is mapped at.\n");
    let mut bias = [0u8; GROUPED_HEX_LEN];
    let _ = writeln!(
        out,
        "pub const USER_BIAS: u64 = {};",
        format_grouped_hex(USER_IMAGE_BIAS, &mut bias)
    );
    out
}

/// Append one converted `rxe` image to a fixture source as
/// `pub const <name>: &[u8]`, documented as the image of `description`
/// ("the heap fixture program", "the parent role").
///
/// A host build passes an empty `rxe`, so the vertical's inert stub still
/// compiles against the same names.
pub fn push_rxe_blob(out: &mut String, name: &str, description: &str, rxe: &[u8]) {
    let _ = writeln!(out, "/// The converted `rxe` image of {description}.");
    let _ = write!(out, "pub const {name}: &[u8] = &[");
    for (i, b) in rxe.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        let _ = write!(out, "0x{b:02x}, ");
    }
    out.push_str("\n];\n");
}

/// Write a completed fixture `source` to `path`.
///
/// # Panics
///
/// If the write fails: a build that could not emit its fixture must fail
/// loudly rather than leave a stale one in place for the compiler to pick
/// up.
pub fn write_fixture(path: &Path, source: &str) {
    fs::write(path, source).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A composed fixture source carries the shared bias as a grouped
    /// literal, the caller's own pinned constants, and every image byte.
    #[test]
    fn a_composed_fixture_source_carries_the_bias_and_every_byte() {
        let mut src = fixture_header();
        assert!(
            src.contains("pub const USER_BIAS: u64 = 0x0010_0000_0000;"),
            "{src}"
        );
        src.push_str("pub const ROUNDS: u64 = 3;\n");
        push_rxe_blob(
            &mut src,
            "PROGRAM_RXE",
            "the probe fixture program",
            &[0x7f, 0x45, 0x4c, 0x46],
        );
        assert!(
            src.contains("/// The converted `rxe` image of the probe fixture program."),
            "{src}"
        );
        assert!(src.contains("pub const ROUNDS: u64 = 3;"), "{src}");
        assert!(src.contains("0x7f, 0x45, 0x4c, 0x46,"), "{src}");
        // A host build emits the empty form, which must still be valid source.
        let mut stub = fixture_header();
        push_rxe_blob(&mut stub, "PROGRAM_RXE", "the probe fixture program", &[]);
        assert!(
            stub.contains("pub const PROGRAM_RXE: &[u8] = &[\n];"),
            "{stub}"
        );
    }

    #[test]
    fn grouped_hex_literals_are_separated_every_four_digits() {
        let mut buf = [0u8; GROUPED_HEX_LEN];
        // The user-image bias the generator emits: the regression this
        // helper exists for, a bare `0x1000000000` in generated source.
        assert_eq!(
            format_grouped_hex(0x10_0000_0000, &mut buf),
            "0x0010_0000_0000"
        );
        // Leading all-zero groups are dropped so the literal stays short…
        assert_eq!(format_grouped_hex(0x1234, &mut buf), "0x1234");
        assert_eq!(format_grouped_hex(0x1_2345, &mut buf), "0x0001_2345");
        // …but never the last group, so zero is still a literal.
        assert_eq!(format_grouped_hex(0, &mut buf), "0x0000");
        // Full width round-trips every nibble.
        assert_eq!(
            format_grouped_hex(u64::MAX, &mut buf),
            "0xffff_ffff_ffff_ffff"
        );
        assert_eq!(
            format_grouped_hex(0x0123_4567_89ab_cdef, &mut buf),
            "0x0123_4567_89ab_cdef"
        );
    }

    #[test]
    fn grouped_hex_output_parses_back_to_the_value_it_rendered() {
        // The generated file is compiled, so the rendering must be a Rust
        // literal that means exactly the value asked for — a separator in
        // the wrong place would silently change a mapped base address.
        for value in [
            0,
            1,
            0xffff,
            0x1_0000,
            0x10_0000_0000,
            0xdead_beef_cafe_f00d,
            u64::MAX,
        ] {
            let mut buf = [0u8; GROUPED_HEX_LEN];
            let rendered = format_grouped_hex(value, &mut buf);
            let mut parsed: u64 = 0;
            for digit in rendered.trim_start_matches("0x").bytes() {
                if digit == b'_' {
                    continue;
                }
                let nibble = char::from(digit).to_digit(16).expect("hex digit");
                parsed = (parsed << 4) | u64::from(nibble);
            }
            assert_eq!(parsed, value, "{rendered}");
            // Every group is exactly four digits — the shape the
            // separator lint accepts without complaint.
            for group in rendered.trim_start_matches("0x").split('_') {
                assert_eq!(group.len(), 4, "{rendered}");
            }
        }
    }
}
