//! Build script for the Settings QEMU vertical.
//!
//! Two jobs on the freestanding `aarch64-unknown-none` target, identical to
//! every other aarch64 `virt` vertical:
//!
//! 1. Hand the aarch64 `virt` linker script to `rustc` — the single
//!    per-board linker script the architecture port owns.
//! 2. Dump the canonical QEMU `virt` flattened device tree and embed it,
//!    because QEMU's `-kernel <ELF>` aarch64 path passes no DTB pointer
//!    (`x0 = 0`). The dump helper lives in the shared harness so no aarch64
//!    build script re-rolls it.
//!
//! On every target it also generates the two spellings the contract borrows
//! (`contract.rs`), from their own definitions, so the guest links neither.
//!
//! Re-running `build.rs` produces byte-identical output, so the test is
//! deterministic.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

fn main() {
    tairix_itest_harness::emit_target_cfg();
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");

    let target = std::env::var("TARGET").unwrap_or_default();
    let dtb_bytes = if target == "aarch64-unknown-none" {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
        let linker_script = format!(
            "{}/../../../kernel/arch/aarch64/link/aarch64-virt.ld",
            manifest_dir.trim_end_matches('/')
        );
        println!("cargo:rerun-if-changed={linker_script}");
        println!("cargo:rustc-link-arg=-T{linker_script}");
        // One CPU: PID 1, the unlock kthread, the autoloaded driver
        // processes, and the desktop session all run on the boot CPU.
        tairix_itest_harness::dump_aarch64_virt_dtb(&out_dir, 1)
    } else {
        // Host builds compile the bin to a no-op `main`; no DTB needed.
        Vec::new()
    };

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// Canonical QEMU `virt` flattened device tree, dumped at build\n");
    out.push_str("/// time for the aarch64-none target (empty on host builds).\n");
    out.push_str("pub const DTB_BLOB: &[u8] = &[");
    for (i, b) in dtb_bytes.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n");

    let path = PathBuf::from(&out_dir).join("dtb_fixture.rs");
    fs::write(&path, out).expect("write dtb_fixture.rs");

    let contract = format!(
        "// Auto-generated by build.rs. DO NOT EDIT.\n\
         /// The desktop session's publisher identity: the app-data store its\n\
         /// published settings document is committed into.\n\
         pub const DESKTOP_PUBLISHER: &str = {publisher:?};\n\
         /// The file name the app-data service commits a published document\n\
         /// under.\n\
         pub const PUBLISHED_FILE: &str = {file:?};\n",
        publisher = tairix_wallpaper::PINBOARD_PUBLISHER,
        file = tairix_confd::store::PUBLIC_FILE,
    );
    fs::write(PathBuf::from(&out_dir).join("contract.rs"), contract).expect("write contract.rs");
}
