//! Whole-disk encrypted-root image fixture carrying a kernel-signed
//! virtio-input keyboard driver bundle in `/System/Drivers/`, for the
//! `plans/PI.md` P10 5d-2-ii(b-2-iii) `-M virt` driver-loading-by-discovery
//! autoload vertical.
//!
//! [`build_image`] is [`rustos_test_encrypted_root_image::build_image`] with
//! one addition: the signed `virtio_kbd` driver bundle `build.rs` produced
//! ([`VIRTIO_KBD_BUNDLE`]) is planted into the **read-only `/System`
//! volume**'s `Drivers/` store at [`STORE_PATH`] (design B — the store lives
//! on a volume reachable *before* the encrypted-root passphrase). The booted
//! kernel mounts that `/System` volume read-only, the store scan
//! discovers the bundle **before** unlock, the signed load gate verifies it
//! against the kernel's embedded `KERNEL_DRIVER_SIGNER_PUBKEY` (the bundle is
//! signed with the kernel's own driver-signing seed, so it verifies by
//! construction), `devmatch` binds it to the discovered
//! virtio-input node, and it is spawned into its own user-space process —
//! the full "drivers in user space by discovery" path.
//!
//! `no_std` + `alloc` so the builder links into the host build tool
//! (`tools/xtask`, which plants the image); the bundle itself is built and
//! signed at build time (`build.rs`), never at run time.

#![no_std]
#![forbid(unsafe_code)]
#![deny(missing_docs)]

extern crate alloc;

use alloc::vec::Vec;

use rustos_abi::DriverError;

// `VIRTIO_KBD_BUNDLE` / `VIRTIO_KBD_SIGNER_PUBKEY` — the signed driver bundle
// and its signer public key, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/bundle.rs"));

// The whole-disk geometry and the operator-facing constants are the encrypted-
// root fixture's (this fixture only adds the driver bundle), re-exported so the
// host harness and the guest tail name them in one place.
pub use rustos_test_encrypted_root_image::{
    PASSPHRASE, PASSWORD, SECTOR_BYTES, TOTAL_SECTORS, USERNAME,
};

/// Path of the planted driver bundle's leaf file *under the `/System`
/// volume's root*: `Drivers/input/virtio_kbd/Run`. The `/System` volume's
/// own root *is* `/System` (design B), so the `/System/Drivers/` store
/// is at the volume-relative `Drivers/…` (the store is
/// `<class>/<leaf>/<driver-file>`; the leaf names the device, never the bus
/// namespace).
pub const STORE_PATH: &[&[u8]] = &[b"Drivers", b"input", b"virtio_kbd", b"Run"];

/// Build the whole-disk encrypted-root image with the signed `virtio_kbd`
/// bundle planted in its `/System/Drivers/` store.
///
/// # Errors
///
/// Propagates any [`DriverError`] from the underlying whole-disk assembly
/// (descriptor provisioning, FAT/`RustFS` authoring, the MBR encode, or the
/// bundle plant), surfaced rather than panicked.
pub fn build_image() -> Result<Vec<u8>, DriverError> {
    rustos_test_encrypted_root_image::build_image_with_drivers(&[(STORE_PATH, VIRTIO_KBD_BUNDLE)])
}

#[cfg(test)]
mod tests {
    extern crate std;

    use super::*;

    use alloc::vec::Vec;

    use rustos_abi::{DriverManifest, HwMatchKey, DRIVER_MANIFEST_MAGIC};
    use rustos_devmatch::{resolve, MatchResolution};
    use rustos_drvhost::store::scan_store;
    use rustos_drvhost::{ImageSource, Sink};
    use rustos_log::Event;
    use rustos_virtio_input::VIRTIO_INPUT_DEVICE_ID;

    /// The store path the bundle is planted at, as the `/`-joined string the
    /// store scanner addresses it by on the `/System` volume (volume-relative,
    /// since that volume's root *is* `/System`).
    const STORE_PATH_STR: &str = "/Drivers/input/virtio_kbd/Run";

    /// In-memory [`ImageSource`] returning the embedded bundle for its path.
    struct BundleSource;

    impl ImageSource for BundleSource {
        fn read(&self, path: &str, buf: &mut Vec<u8>) -> Result<(), rustos_abi::Errno> {
            if path == STORE_PATH_STR {
                buf.extend_from_slice(VIRTIO_KBD_BUNDLE);
                Ok(())
            } else {
                Err(rustos_abi::Errno::NotFound)
            }
        }
    }

    /// Discarding audit sink — these tests assert behaviour through the
    /// resolved match, not the audit stream.
    struct DiscardSink;

    impl Sink for DiscardSink {
        fn write_event(&self, _event: &Event<'_>) {}
    }

    #[test]
    fn the_embedded_bundle_is_a_signed_userspace_driver_manifest() {
        // The bundle `build.rs` produced parses as a well-formed
        // `kind = UserSpace` manifest with a non-zero signature, so it is a
        // genuine signed bundle, not an inert stub.
        assert!(
            VIRTIO_KBD_BUNDLE.len() > DriverManifest::WIRE_LEN,
            "the bundle carries a manifest plus a payload"
        );
        let manifest =
            DriverManifest::from_bytes(VIRTIO_KBD_BUNDLE).expect("the bundle's manifest decodes");
        assert_eq!(manifest.magic, DRIVER_MANIFEST_MAGIC);
        assert_eq!(manifest.kind, rustos_abi::DriverKind::UserSpace);
        assert_ne!(manifest.signature, [0u8; 64], "the bundle is signed");
        assert_eq!(
            manifest.signer_pubkey, VIRTIO_KBD_SIGNER_PUBKEY,
            "the manifest names the signer the build recorded"
        );
    }

    #[test]
    fn the_store_scan_discovers_the_bundle_and_it_binds_a_virtio_input_node() {
        // The production store scan decodes the bundle's bind table
        // fail-closed, and the shared match policy resolves a discovered
        // virtio-input node to it as the sole winner — the exact autoload
        // decision the booted kernel makes off the mounted root.
        let store = scan_store(&BundleSource, &[STORE_PATH_STR], &DiscardSink);
        let candidates = store.candidates();
        assert_eq!(candidates.len(), 1, "the signed bundle is a candidate");

        let node_keys = [HwMatchKey::virtio(VIRTIO_INPUT_DEVICE_ID)];
        match resolve(&node_keys, &candidates) {
            MatchResolution::Winner { candidate, .. } => assert_eq!(candidate, 0),
            other => panic!("the virtio-input node must bind the bundle, got {other:?}"),
        }
    }

    #[test]
    fn a_non_virtio_input_node_does_not_bind_the_bundle() {
        // A node advertising a different virtio device id matches nothing —
        // the bundle binds only its declared device.
        let store = scan_store(&BundleSource, &[STORE_PATH_STR], &DiscardSink);
        let candidates = store.candidates();
        let node_keys = [HwMatchKey::virtio(VIRTIO_INPUT_DEVICE_ID + 1)];
        assert_eq!(resolve(&node_keys, &candidates), MatchResolution::Unmatched);
    }

    #[test]
    fn the_image_is_the_advertised_whole_disk_size() {
        let bytes = build_image().expect("the autoload-root image assembles");
        assert_eq!(
            bytes.len(),
            usize::try_from(TOTAL_SECTORS).expect("sector count fits usize") * SECTOR_BYTES,
            "the image is exactly the whole-disk size"
        );
    }
}
