//! Whole-disk encrypted-root image fixture carrying kernel-signed driver
//! bundles in `/System/Drivers/` — the virtio-input keyboard driver
//! (`plans/PI.md` P10 5d-2-ii(b-2-iii)), the framebuffer display
//! service (`plans/DISPLAY.md` D7d), and the virtio-net link-layer driver
//! (`plans/NETWORK.md` N4e-β) — for the `-M virt`
//! driver-loading-by-discovery autoload verticals.
//!
//! [`build_image`] is [`rustos_test_encrypted_root_image::build_image`] with
//! one addition: the signed driver bundles `build.rs` produced
//! ([`VIRTIO_KBD_BUNDLE`], [`FRAMEBUFFER_BUNDLE`], [`VIRTIO_NET_BUNDLE`]) are
//! planted into the
//! **read-only `/System` volume**'s `Drivers/` store at
//! [`STORE_PATH`] / [`FRAMEBUFFER_STORE_PATH`] (design B — the store lives
//! on a volume reachable *before* the encrypted-root passphrase). The booted
//! kernel mounts that `/System` volume read-only, the store scan
//! discovers the bundles **before** unlock, the signed load gate verifies
//! each against the kernel's embedded `KERNEL_DRIVER_SIGNER_PUBKEY` (the
//! bundles are signed with the kernel's own driver-signing seed, so they
//! verify by construction), `devmatch` binds each to its discovered node —
//! the virtio-input transports and the boot display the kernel publishes
//! for its ramfb scan-out surface — and each is spawned into its own
//! user-space process: the full "drivers in user space by discovery" path.
//!
//! `no_std` + `alloc` so the builder links into the host build tool
//! (`tools/xtask`, which plants the image); the bundles themselves are built
//! and signed at build time (`build.rs`), never at run time.

#![no_std]
#![forbid(unsafe_code)]
#![deny(missing_docs)]

extern crate alloc;

use alloc::vec::Vec;

use rustos_abi::DriverError;

// `VIRTIO_KBD_BUNDLE` / `FRAMEBUFFER_BUNDLE` / `DRIVER_SIGNER_PUBKEY` — the
// signed driver bundles and their shared signer public key, generated by
// `build.rs`.
include!(concat!(env!("OUT_DIR"), "/bundle.rs"));

// The whole-disk geometry and the operator-facing constants are the encrypted-
// root fixture's (this fixture only adds the driver bundles), re-exported so
// the host harness and the guest tail name them in one place.
pub use rustos_test_encrypted_root_image::{
    PASSPHRASE, PASSWORD, SECTOR_BYTES, TOTAL_SECTORS, USERNAME,
};

/// Path of the planted virtio-input driver bundle's leaf file *under the
/// `/System` volume's root*: `Drivers/input/virtio_kbd/Run`. The `/System`
/// volume's own root *is* `/System` (design B), so the `/System/Drivers/`
/// store is at the volume-relative `Drivers/…` (the store is
/// `<class>/<leaf>/<driver-file>`; the leaf names the device, never the bus
/// namespace).
pub const STORE_PATH: &[&[u8]] = &[b"Drivers", b"input", b"virtio_kbd", b"Run"];

/// Path of the planted framebuffer display-service bundle's leaf file under
/// the `/System` volume's root: `Drivers/display/framebuffer/Run` — class
/// `display`, the vendor-neutral `framebuffer` leaf.
pub const FRAMEBUFFER_STORE_PATH: &[&[u8]] = &[b"Drivers", b"display", b"framebuffer", b"Run"];

/// Path of the planted virtio-net driver bundle's leaf file under the
/// `/System` volume's root: `Drivers/network/virtio_net/Run` — class
/// `network`, the vendor-neutral `virtio_net` leaf.
pub const NETWORK_STORE_PATH: &[&[u8]] = &[b"Drivers", b"network", b"virtio_net", b"Run"];

/// Build the whole-disk encrypted-root image with the signed `virtio_kbd`
/// and framebuffer display-service bundles planted in its
/// `/System/Drivers/` store and the signed application bundles `apps`
/// planted into the `/System` app/service stores — each
/// `(path_components, bytes)` a volume-relative bundle file, composed and
/// signed by the caller (`plans/APPS.md` deliverable 8). The booted kernel
/// spawns PID 1's services from those on-disk bundles, so an image without
/// them never reaches the `devmgr` autoload this fixture exists to prove.
///
/// # Errors
///
/// Propagates any [`DriverError`] from the underlying whole-disk assembly
/// (descriptor provisioning, FAT/`RustFS` authoring, the MBR encode, or the
/// bundle plant), surfaced rather than panicked.
pub fn build_image(apps: &[(&[&[u8]], &[u8])]) -> Result<Vec<u8>, DriverError> {
    rustos_test_encrypted_root_image::build_image_with_contents(
        &[
            (STORE_PATH, VIRTIO_KBD_BUNDLE),
            (FRAMEBUFFER_STORE_PATH, FRAMEBUFFER_BUNDLE),
            (NETWORK_STORE_PATH, VIRTIO_NET_BUNDLE),
        ],
        apps,
        PASSPHRASE,
    )
}

#[cfg(test)]
mod tests {
    extern crate std;

    use super::*;

    use alloc::vec::Vec;

    use rustos_abi::{DriverManifest, HwMatchKey, DRIVER_MANIFEST_MAGIC};
    use rustos_devmatch::{resolve, MatchResolution};
    use rustos_drv_network_virtio_net::VIRTIO_NET_DEVICE_ID;
    use rustos_drvhost::store::scan_store;
    use rustos_drvhost::{ImageSource, Sink};
    use rustos_log::Event;
    use rustos_virtio_input::VIRTIO_INPUT_DEVICE_ID;

    /// The store path each bundle is planted at, as the `/`-joined string the
    /// store scanner addresses it by on the `/System` volume (volume-relative,
    /// since that volume's root *is* `/System`).
    const STORE_PATH_STR: &str = "/Drivers/input/virtio_kbd/Run";
    /// [`STORE_PATH_STR`]'s display-service sibling.
    const FRAMEBUFFER_STORE_PATH_STR: &str = "/Drivers/display/framebuffer/Run";
    /// [`STORE_PATH_STR`]'s virtio-net driver sibling.
    const NETWORK_STORE_PATH_STR: &str = "/Drivers/network/virtio_net/Run";

    /// In-memory [`ImageSource`] returning each embedded bundle for its path.
    struct BundleSource;

    impl ImageSource for BundleSource {
        fn read(&self, path: &str, buf: &mut Vec<u8>) -> Result<(), rustos_abi::Errno> {
            let bytes = match path {
                STORE_PATH_STR => VIRTIO_KBD_BUNDLE,
                FRAMEBUFFER_STORE_PATH_STR => FRAMEBUFFER_BUNDLE,
                NETWORK_STORE_PATH_STR => VIRTIO_NET_BUNDLE,
                _ => return Err(rustos_abi::Errno::NotFound),
            };
            buf.extend_from_slice(bytes);
            Ok(())
        }
    }

    /// Discarding audit sink — these tests assert behaviour through the
    /// resolved match, not the audit stream.
    struct DiscardSink;

    impl Sink for DiscardSink {
        fn write_event(&self, _event: &Event<'_>) {}
    }

    /// The scanned three-bundle store every match test resolves against, with
    /// the candidate indices pinned by planting order (input 0, display 1,
    /// network 2).
    fn scanned_store() -> rustos_drvhost::DriverStore {
        scan_store(
            &BundleSource,
            &[
                STORE_PATH_STR,
                FRAMEBUFFER_STORE_PATH_STR,
                NETWORK_STORE_PATH_STR,
            ],
            &DiscardSink,
        )
    }

    #[test]
    fn each_embedded_bundle_is_a_signed_userspace_driver_manifest() {
        for bundle in [VIRTIO_KBD_BUNDLE, FRAMEBUFFER_BUNDLE, VIRTIO_NET_BUNDLE] {
            // Each bundle `build.rs` produced parses as a well-formed
            // `kind = UserSpace` manifest with a non-zero signature, so it is
            // a genuine signed bundle, not an inert stub.
            assert!(
                bundle.len() > DriverManifest::WIRE_LEN,
                "the bundle carries a manifest plus a payload"
            );
            let manifest =
                DriverManifest::from_bytes(bundle).expect("the bundle's manifest decodes");
            assert_eq!(manifest.magic, DRIVER_MANIFEST_MAGIC);
            assert_eq!(manifest.kind, rustos_abi::DriverKind::UserSpace);
            assert_ne!(manifest.signature, [0u8; 64], "the bundle is signed");
            assert_eq!(
                manifest.signer_pubkey, DRIVER_SIGNER_PUBKEY,
                "the manifest names the signer the build recorded"
            );
        }
    }

    #[test]
    fn the_store_scan_discovers_the_bundles_and_each_binds_its_node() {
        // The production store scan decodes each bundle's bind table
        // fail-closed, and the shared match policy resolves a discovered
        // virtio-input node to the keyboard driver and a boot display node
        // (the kernel's `simple-framebuffer` publication) to the display
        // service — the exact autoload decisions the booted kernel makes off
        // the mounted root, with no cross-binding.
        let store = scanned_store();
        let candidates = store.candidates();
        assert_eq!(
            candidates.len(),
            3,
            "all three signed bundles are candidates"
        );

        let input_keys = [HwMatchKey::virtio(VIRTIO_INPUT_DEVICE_ID)];
        match resolve(&input_keys, &candidates) {
            MatchResolution::Winner { candidate, .. } => assert_eq!(candidate, 0),
            other => panic!("the virtio-input node must bind the keyboard bundle, got {other:?}"),
        }

        let display_keys =
            [HwMatchKey::compatible(rustos_abi::SIMPLE_FRAMEBUFFER_COMPATIBLE).expect("fits")];
        match resolve(&display_keys, &candidates) {
            MatchResolution::Winner { candidate, .. } => assert_eq!(candidate, 1),
            other => panic!("the boot display node must bind the display bundle, got {other:?}"),
        }

        let network_keys = [HwMatchKey::virtio(VIRTIO_NET_DEVICE_ID)];
        match resolve(&network_keys, &candidates) {
            MatchResolution::Winner { candidate, .. } => assert_eq!(candidate, 2),
            other => panic!("the virtio-net node must bind the network bundle, got {other:?}"),
        }
    }

    #[test]
    fn an_unrelated_node_binds_neither_bundle() {
        // A node advertising a different virtio device id matches nothing —
        // each bundle binds only its declared device.
        let store = scanned_store();
        let candidates = store.candidates();
        let node_keys = [HwMatchKey::virtio(VIRTIO_INPUT_DEVICE_ID + 1)];
        assert_eq!(resolve(&node_keys, &candidates), MatchResolution::Unmatched);
    }

    #[test]
    fn the_image_is_the_advertised_whole_disk_size() {
        let bytes = build_image(&[]).expect("the autoload-root image assembles");
        assert_eq!(
            bytes.len(),
            usize::try_from(TOTAL_SECTORS).expect("sector count fits usize") * SECTOR_BYTES,
            "the image is exactly the whole-disk size"
        );
    }
}
