//! aarch64 (Raspberry Pi 4) PID 1 (`init`) spawn seam — `plans/PI.md`
//! P6c-3.
//!
//! [`Aarch64InitSpawn`] implements the architecture-neutral
//! [`tairix_kernel_core::InitSpawn`] hook the boot pipeline installs into
//! the [`tairix_kernel_core::BootInfo`] hand-off
//! (`boot_aarch64::enter_kernel_core` → `BootInfo::with_init`). Once every
//! init phase has succeeded and `kernel_core::kernel_main` has emitted
//! [`tairix_kernel_core::AuditEvent::BootCompleted`], the core invokes
//! [`InitSpawn::spawn_init`]; this implementation builds the embedded
//! `init` (`Run`) program's EL0 image and drops into it through the
//! production, capability-checked, audited spawn caller
//! ([`tairix_kernel_core::spawn_and_enter`]). On the authorised, well-formed
//! path the call diverges into EL0 and never returns; on any failure it
//! returns so `kernel_main` parks the boot CPU fail-closed.
//!
//! The image, its relocation bias ([`INIT_USER_BIAS`]), and the kernel's
//! syscall CFI tag are baked at build time (`build.rs` →
//! `tairix_itest_harness::elf2rxe`), exactly like the proven
//! `spawn_program_qemu_aarch64` fixture, so there is one conversion path. Spawning `init` is *not* a privileged bypass: the
//! program receives only the authority its `rxe` manifest requests
//! intersected with its user's grants; this seam
//! only authorises the *act* of spawning under `CAP_PROC_SPAWN`.

use core::sync::atomic::{AtomicBool, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_arch_aarch64::paging::{
    activate_user_root, configured_identity_gigapages, AddressSpace as ArchAddressSpace,
    PageTablePool,
};
use tairix_arch_aarch64::userentry::USER_MODE;
use tairix_kernel_core::{
    spawn_image, InitSpawn, InitSpawnCtx, ProcessResume, ProcessSpace, SpawnMode, UserThreadEntry,
};
use tairix_kernel_mem::{AddressSpace, LiveSpace, PhysMap, UserAddressSpace, VirtAddr};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;

use super::spawn_producer::ConfiguredIdentityPhysMap;
use crate::spawn_layout;

// `INIT_RXE: &[u8]` and `INIT_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/init_rxe.rs"));

/// PID 1's four fixed guarded-window bases (`plans/PI.md` 5d-0-ii (b′)/(c)),
/// derived from the one shared offset set the retained [`LiveSpace`]'s
/// window allocators are configured with.
const WINDOWS: spawn_layout::WindowBases = spawn_layout::window_bases(INIT_USER_BIAS);

/// Page-table pool backing the spawn address space's stage-1 hierarchy.
///
/// Lives in `.bss` for the lifetime of the kernel image, so `TTBR0_EL1`
/// keeps pointing at a valid table after [`Aarch64InitSpawn::spawn_init`]
/// switches to it (monotonic, never freed). The identity
/// map needs a single root L1 frame; the rest serve the freshly walked user
/// mappings at [`INIT_USER_BIAS`].
static INIT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Set once PID 1 has been spawned so a re-entry cannot re-run the path.
static INIT_SPAWNED: AtomicBool = AtomicBool::new(false);

/// The aarch64 PID 1 spawn seam installed into the [`tairix_kernel_core::BootInfo`]
/// hand-off by `boot_aarch64::enter_kernel_core`.
pub struct Aarch64InitSpawn;

/// The single, `'static` [`Aarch64InitSpawn`] the boot path borrows.
pub static AARCH64_INIT_SPAWN: Aarch64InitSpawn = Aarch64InitSpawn;

impl InitSpawn for Aarch64InitSpawn {
    fn spawn_init(&self, ctx: &'static (dyn InitSpawnCtx + Sync)) {
        // Spawn PID 1 at most once; a spurious re-entry falls through to the
        // caller's fail-closed halt rather than building a second image.
        if INIT_SPAWNED
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }

        // Build a stage-1 address space identity-mapping the kernel + MMIO,
        // then activate it so the user mappings below land in the active
        // hierarchy. The EL1 vector table and the production `svc` dispatch
        // callback were installed earlier by the boot path, so the new
        // program's first `svc` is handled rather than faulting.
        //
        // The window length is derived from the Device/RAM gigapage masks
        // the boot path discovered and installed (`virt`: 2 GiB; Pi 4:
        // 4 GiB — its UART/GIC live in gigapage 3), never a board
        // constant: a window truncated short of the MMIO gigapage would
        // drop the console and interrupt controller from the active map
        // the instant PID 1's root is switched to — exactly the metal
        // Pi 4 silence after "boot completed" (`plans/PI.md`). An empty
        // window (no masks configured) or one reaching the user region
        // at `INIT_USER_BIAS` fails closed.
        let identity_gib = configured_identity_gigapages();
        let identity_limit = (identity_gib as u64) << 30;
        if identity_gib == 0 || identity_limit > INIT_USER_BIAS {
            return;
        }
        let Some(arch) = ArchAddressSpace::new_identity_gigapages(&INIT_PAGE_TABLES, identity_gib)
        else {
            return;
        };
        // Capture PID 1's stage-1 root before the arch space is moved into
        // the `kernel/mem` wrapper, so the `pre_resume` hook can reactivate
        // `TTBR0_EL1` with it before every switch into PID 1 (`plans/SPAWN.md`
        // SP2). It is a plain `u64`, so the boxed hook stays `Send`.
        let init_root_phys = arch.root_phys();

        // PID 1's kernel stack: a run of the shared kernel remap window whose
        // guard slot is unmapped in every root at once, so the stack stays
        // mapped and guarded across the switch below without touching `arch`.
        let kernel_stack = tairix_kernel_core::kstack::alloc_kernel_stack();
        // SAFETY: the identity map covers the kernel's current `pc`, `sp`,
        // the leaked kernel state, the boot heap, and the device MMIO —
        // the window spans every gigapage the configured Device/RAM masks
        // name, and those masks were derived from the kernel extent and
        // the discovered RAM/MMIO — so enabling it does not move the
        // ground under the running code — exactly `AddressSpace::switch`'s
        // contract. Called once on the boot CPU.
        unsafe { arch.switch() };

        let mut space = AddressSpace::new(arch);
        // Fill PID 1's segment pages through the physmap whose cache
        // maintenance is *real*: on the Cortex-A72 the I-cache is not coherent
        // with the loader's cacheable data-side writes, so an executable
        // segment must be made instruction-fetch-coherent through
        // `ConfiguredIdentityPhysMap::sync_instruction_cache` (clean-to-PoU +
        // I-cache invalidate). A plain `DirectPhysMap`'s is a no-op (correct
        // only for I/O-coherent targets), which would let PID 1 fetch stale
        // code. The identity translation is the same live window; only the
        // maintenance becomes real (also for the stored physmap's
        // `clean_invalidate`, per the runtime spawn producer's rationale).
        let physmap = ConfiguredIdentityPhysMap;

        // Parse the build-time `init` `rxe` blob against the kernel's own
        // compiled-in syscall CFI tag. A mismatch fails closed.
        let Ok(image) = LoadImage::parse(INIT_RXE, &SYSCALL_TABLE_HASH) else {
            return;
        };

        // Place the stack and startup block above the image's mapped top,
        // and derive the span record the stack-growth fault path backs
        // pages inside, through the one shared per-spawn derivation. An
        // image too large for the user region fails the boot closed.
        let Some((request, stack_span)) =
            spawn_layout::init_request(&image, INIT_RXE, INIT_USER_BIAS)
        else {
            return;
        };

        // Authorise + build the EL0 image (emits `ProcessSpawned`) without
        // entering yet — PID 1 must be registered with the scheduler /
        // capability table / address-space registry *first* so its first
        // syscall resolves a caller context (`plans/PI.md` P6c-3).
        // SAFETY: building the image is itself safe; the returned `UserEntry`
        // is only entered below, once `space` is active (just switched to)
        // and the EL1 trap path is installed. The frame source draws
        // identity-mapped RAM frames from the kernel's live allocator. A
        // returning `Err` (denial or build failure) drops back to the
        // caller's fail-closed halt.
        let frames = ctx.frames();
        let Ok(entry) = (unsafe {
            spawn_image(
                &spawn_layout::SpawnAuthority,
                SpawnMode::General,
                ctx.audit(),
                &mut space,
                &physmap,
                &request,
                move || frames.alloc().ok(),
            )
        }) else {
            return;
        };

        // PID 1's user-address-space reactivation hook (`plans/SPAWN.md`
        // SP2): the core runs it on the dispatcher's context immediately
        // before every switch into PID 1, so the task `eret`s back into EL0
        // under its own `TTBR0_EL1` root and stays isolated from any sibling
        // process. It captures only the `u64` root, so it is
        // `Send`.
        // The hook is handed the task's kernel-stack top (the x86_64 port
        // uses it to repoint its per-CPU syscall entry stack); aarch64
        // reuses `SP_EL1` implicitly and so ignores it (`plans/PI.md` §X).
        let pre_resume: ProcessResume = Arc::new(move |_stack_top: u64, _tls_base: u64| {
            // SAFETY: the MMU is already enabled and `init_root_phys` is the
            // L1 root of PID 1's space, which identity-maps the low kernel
            // window the running kernel executes from — exactly
            // `activate_user_root`'s contract.
            unsafe { activate_user_root(init_root_phys) };
        });

        // Freeze the just-built mappings into the registry-storable,
        // `Send + Sync` snapshot the kernel-wide address-space registry
        // holds (the live arch `space` is not `Sync`), and box the direct
        // map that backs it, so PID 1's `stream_write` can copy its banner
        // out of user memory (`plans/PI.md` P6c-3 follow-up). Freezing
        // *after* `spawn_image` captures every mapped page — segments,
        // stack, and the startup-vector block. `freeze` only borrows, so
        // the live arch `space` is still owned below.
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());

        // PID 1's process address space (`plans/PI.md` 5d-0-ii (b′)): the
        // *same* arch space the snapshot above was frozen from, so its
        // `mem_map` / `mmio_map` mutate exactly the mappings the snapshot
        // describes. No `'static` allocator, or a window the allocator
        // rejects, retains none and those syscalls fail closed.
        //
        // The `PhysMap` must be [`ConfiguredIdentityPhysMap`]: a `dma_alloc`
        // carve is mapped Normal-Non-Cacheable for the caller while the
        // kernel zeroes it through the cacheable identity alias, so the
        // post-zero `clean_invalidate` must be the real dcache
        // clean+invalidate — a no-op physmap leaves dirty zero lines the
        // cache later writes back over device-visible rings.
        let live: Option<Arc<ProcessSpace>> = match ctx.static_frames() {
            Some(static_frames) => {
                let windows = crate::user_windows::user_windows(
                    static_frames.total_frames() as u64,
                    WINDOWS.anon,
                    super::USER_VA_TOP,
                );
                LiveSpace::new(
                    space,
                    ConfiguredIdentityPhysMap,
                    static_frames,
                    VirtAddr::new(WINDOWS.mmio),
                    spawn_layout::MMIO_WINDOW_PAGES,
                    VirtAddr::new(WINDOWS.anon),
                    windows.anon_pages,
                    VirtAddr::new(WINDOWS.dma),
                    spawn_layout::DMA_WINDOW_PAGES,
                    VirtAddr::new(WINDOWS.shared),
                    spawn_layout::SHARED_WINDOW_PAGES,
                    VirtAddr::new(windows.file_base),
                    windows.file_pages,
                )
                .ok()
                .map(|live| {
                    Arc::new(ProcessSpace::new(
                        Box::new(live),
                        Arc::clone(&pre_resume),
                        &USER_MODE,
                    ))
                })
            }
            None => None,
        };

        let physmap: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);

        // The VL805 USB keyboard now comes up entirely in user space: the
        // boot path's `FdtDiscovery` already emits the discovered
        // `brcm,bcm2711-pcie` node (with its register window + outbound
        // bus-window + inbound DMA grants) and the VideoCore mailbox node into
        // the hardware tree, and `devmgr` autoloads the signed
        // `/System/Drivers/` bundles against them — the PCIe root-complex
        // driver binds the bridge and emits the VL805 PCI function, the VL805
        // driver reloads the controller firmware over the mailbox and emits
        // the `usb,xhci` node, and the keyboard driver binds that, brings the
        // controller up, and pumps key edges into the input arbiter (`plans/PI.md`
        // P10 D5d — drivers in user space). There is no
        // in-kernel keyboard bring-up to start here.

        // Start the in-kernel root-unlock service alongside PID 1
        // (`plans/PI.md` P11 Chunk B-2 INCREMENT (2)).
        // Admitted onto the boot CPU's run queue *before* `admit_init`
        // diverges into the dispatch loop, the kthread brings up the bound
        // root block device over the production device-IRQ path, prompts
        // for the passphrase on the primary console, mounts the encrypted
        // root, and publishes the users database into `LATE_USERS_DB` so
        // `login` can authenticate. With no bound disk (the QEMU `virt`
        // shape without a planted root, a headless Pi) it starts nothing,
        // opens the console-0 gate, and PID 1 runs unchanged.
        let _unlock_started = crate::aarch64::root_unlock::spawn_if_present(ctx);

        // Register PID 1's caps + address space, publish it as the current
        // task, and dispatch it — `admit_init` diverges into EL0 on success.
        // SAFETY: the image was built into and `space` switched to active
        // above, and the trap path is installed, per the
        // `InitSpawnCtx::admit_init` contract; `frozen` faithfully describes
        // the active mappings and `physmap` backs them.
        unsafe {
            ctx.admit_init(
                spawn_layout::init_caps(),
                frozen,
                physmap,
                stack_span,
                kernel_stack,
                pre_resume,
                live,
                UserThreadEntry {
                    port: &USER_MODE,
                    regs: entry,
                },
            );
        }
    }
}
