//! aarch64 (Raspberry Pi 4) PID 1 (`init`) spawn seam — `plans/PI.md`
//! P6c-3.
//!
//! [`Aarch64InitSpawn`] implements the architecture-neutral
//! [`tairix_kernel_core::InitSpawn`] hook the boot pipeline installs into
//! the [`tairix_kernel_core::BootInfo`] hand-off
//! (`boot_aarch64::enter_kernel_core` → `BootInfo::with_init`). Once every
//! init phase has succeeded and `kernel_core::kernel_main` has emitted
//! [`tairix_kernel_core::AuditEvent::BootCompleted`], the core invokes
//! [`InitSpawn::spawn_init`]; this implementation builds the embedded
//! `init` (`Run`) program's EL0 image and drops into it through the
//! production, capability-checked, audited spawn caller
//! ([`tairix_kernel_core::spawn_and_enter`]). On the authorised, well-formed
//! path the call diverges into EL0 and never returns; on any failure it
//! returns so `kernel_main` parks the boot CPU fail-closed.
//!
//! The image, its relocation bias ([`INIT_USER_BIAS`]), and the kernel's
//! syscall CFI tag are baked at build time (`build.rs` →
//! `tairix_itest_harness::elf2rxe`), exactly like the proven
//! `spawn_program_qemu_aarch64` fixture, so there is one conversion path. Spawning `init` is *not* a privileged bypass: the
//! program receives only the authority its `rxe` manifest requests
//! intersected with its user's grants; this seam
//! only authorises the *act* of spawning under `CAP_PROC_SPAWN`.

use core::sync::atomic::{AtomicBool, Ordering};

use alloc::boxed::Box;

use tairix_abi::rxe::LoadImage;
use tairix_arch_aarch64::paging::{
    activate_user_root, configured_identity_gigapages, AddressSpace as ArchAddressSpace,
    PageTablePool,
};
use tairix_arch_aarch64::userentry::UserMode;
use tairix_arch_api::mmu::AddressSpace as MmuAddressSpace;
use tairix_arch_api::EnterUser;
use tairix_kernel_core::{
    spawn_image, BoxStack, InitSpawn, InitSpawnCtx, KernelStack, SpawnRequest,
};
use tairix_kernel_mem::{
    AddressSpace, LiveSpace, LiveUserSpace, PhysMap, UserAddressSpace, UserStack, VirtAddr,
};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;

use super::spawn_producer::ConfiguredIdentityPhysMap;
use crate::spawn_layout;
use crate::stack_arena::{FrameArenaGrow, KTHREAD_STACK_ARENA};

// `INIT_RXE: &[u8]` and `INIT_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/init_rxe.rs"));

/// Base of PID 1's device-window virtual region (`plans/PI.md` 5d-0-ii (b′)):
/// the [`LiveSpace`]'s [`tairix_kernel_mem::MmioWindowMap`] hands each
/// `mmio_map` a guard-bracketed window out of `[MMIO_WINDOW_BASE,
/// MMIO_WINDOW_BASE + MMIO_WINDOW_PAGES·4 KiB)`.
const MMIO_WINDOW_BASE: u64 = INIT_USER_BIAS + spawn_layout::MMIO_WINDOW_OFFSET;
/// Base of PID 1's non-`FIXED` anonymous-heap virtual region (`plans/PI.md`
/// 5d-0-ii (c)): the [`LiveSpace`]'s [`tairix_kernel_mem::AnonWindowMap`]
/// places each non-`FIXED` `mem_map` out of `[ANON_WINDOW_BASE,
/// ANON_WINDOW_BASE + anon_window_pages·4 KiB)`, where the page count scales
/// with discovered RAM (the window is the topmost user region so it has
/// room to grow up to `super::USER_VA_TOP`).
const ANON_WINDOW_BASE: u64 = INIT_USER_BIAS + spawn_layout::ANON_WINDOW_OFFSET;
/// Base of PID 1's guarded DMA-buffer virtual region (`plans/PI.md`
/// 5d-0-ii (c) DMA half): the [`LiveSpace`]'s
/// [`tairix_kernel_mem::DmaWindowMap`] carves each `dma_alloc` buffer out of
/// `[DMA_WINDOW_BASE, DMA_WINDOW_BASE + DMA_WINDOW_PAGES·4 KiB)`.
const DMA_WINDOW_BASE: u64 = INIT_USER_BIAS + spawn_layout::DMA_WINDOW_OFFSET;
/// Base of PID 1's cross-process shared-memory virtual region: the retained
/// [`LiveSpace`]'s shared-window allocator maps each granted `shm_map`
/// region out of `[SHARED_WINDOW_BASE, SHARED_WINDOW_BASE +
/// SHARED_WINDOW_PAGES * 4 KiB)`.
const SHARED_WINDOW_BASE: u64 = INIT_USER_BIAS + spawn_layout::SHARED_WINDOW_OFFSET;

/// Page-table pool backing the spawn address space's stage-1 hierarchy.
///
/// Lives in `.bss` for the lifetime of the kernel image, so `TTBR0_EL1`
/// keeps pointing at a valid table after [`Aarch64InitSpawn::spawn_init`]
/// switches to it (monotonic, never freed). The identity
/// map needs a single root L1 frame; the rest serve the freshly walked user
/// mappings at [`INIT_USER_BIAS`].
static INIT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Set once PID 1 has been spawned so a re-entry cannot re-run the path.
static INIT_SPAWNED: AtomicBool = AtomicBool::new(false);

/// The aarch64 PID 1 spawn seam installed into the [`tairix_kernel_core::BootInfo`]
/// hand-off by `boot_aarch64::enter_kernel_core`.
pub struct Aarch64InitSpawn;

/// The single, `'static` [`Aarch64InitSpawn`] the boot path borrows.
pub static AARCH64_INIT_SPAWN: Aarch64InitSpawn = Aarch64InitSpawn;

impl InitSpawn for Aarch64InitSpawn {
    fn spawn_init(&self, ctx: &'static (dyn InitSpawnCtx + Sync)) {
        // Spawn PID 1 at most once; a spurious re-entry falls through to the
        // caller's fail-closed halt rather than building a second image.
        if INIT_SPAWNED
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }

        // Build a stage-1 address space identity-mapping the kernel + MMIO,
        // then activate it so the user mappings below land in the active
        // hierarchy. The EL1 vector table and the production `svc` dispatch
        // callback were installed earlier by the boot path, so the new
        // program's first `svc` is handled rather than faulting.
        //
        // The window length is derived from the Device/RAM gigapage masks
        // the boot path discovered and installed (`virt`: 2 GiB; Pi 4:
        // 4 GiB — its UART/GIC live in gigapage 3), never a board
        // constant: a window truncated short of the MMIO gigapage would
        // drop the console and interrupt controller from the active map
        // the instant PID 1's root is switched to — exactly the metal
        // Pi 4 silence after "boot completed" (`plans/PI.md`). An empty
        // window (no masks configured) or one reaching the user region
        // at `INIT_USER_BIAS` fails closed.
        let identity_gib = configured_identity_gigapages();
        if identity_gib == 0 || ((identity_gib as u64) << 30) > INIT_USER_BIAS {
            return;
        }
        let Some(mut arch) =
            ArchAddressSpace::new_identity_gigapages(&INIT_PAGE_TABLES, identity_gib)
        else {
            return;
        };
        // Capture PID 1's stage-1 root before the arch space is moved into
        // the `kernel/mem` wrapper, so the `pre_resume` hook can reactivate
        // `TTBR0_EL1` with it before every switch into PID 1 (`plans/SPAWN.md`
        // SP2). It is a plain `u64`, so the boxed hook stays `Send`.
        let init_root_phys = arch.root_phys();

        // Build PID 1's kernel stack (`plans/PI.md` G3b-2). The boot path
        // published the reserved guard arena to the kthread-stack
        // allocator; if a region is available, re-express the coarse
        // identity block covering its guard page at 4 KiB granularity in
        // PID 1's *own* root and unmap that single page, so an overrun of
        // `init`'s kernel stack takes a synchronous data abort under PID
        // 1's `TTBR0_EL1` rather than corrupting the lower-addressed
        // neighbour (the real guard-page fault-form). Doing it on `arch` *before* it is switched to means no
        // live access is disturbed (`split_block` only adds table levels
        // reproducing the existing translation) and no TLB maintenance is
        // needed. If no arena region is available, or the split/unmap could
        // not be applied, fall back to a heap-backed software-canary
        // `BoxStack` rather than ever running on an unguarded stack (fail
        // closed).
        // The arena grows on demand by chaining fresh 2 MiB blocks out of
        // the kernel's live frame allocator when its boot-carved block is
        // exhausted; a chained block is bounded to the
        // identity window so the stack stays mapped in PID 1's own root.
        let grow = FrameArenaGrow::new(ctx.frames(), (identity_gib as u64) << 30);
        let kernel_stack: Box<dyn KernelStack + Send> =
            match KTHREAD_STACK_ARENA.alloc(&grow, &crate::stack_arena::IdentityBlockStore) {
                Some(stack) => {
                    let guard = stack.guard_page();
                    match arch
                        .split_block(guard)
                        .and_then(|()| arch.unmap(guard).map(|_| ()))
                    {
                        Ok(()) => Box::new(stack),
                        Err(_) => Box::new(BoxStack::new()),
                    }
                }
                None => Box::new(BoxStack::new()),
            };
        // SAFETY: the identity map covers the kernel's current `pc`, `sp`,
        // the leaked kernel state, the boot heap, and the device MMIO —
        // the window spans every gigapage the configured Device/RAM masks
        // name, and those masks were derived from the kernel extent and
        // the discovered RAM/MMIO — so enabling it does not move the
        // ground under the running code — exactly `AddressSpace::switch`'s
        // contract. Called once on the boot CPU.
        unsafe { arch.switch() };

        let mut space = AddressSpace::new(arch);
        // Fill PID 1's segment pages through the physmap whose cache
        // maintenance is *real*: on the Cortex-A72 the I-cache is not coherent
        // with the loader's cacheable data-side writes, so an executable
        // segment must be made instruction-fetch-coherent through
        // `ConfiguredIdentityPhysMap::sync_instruction_cache` (clean-to-PoU +
        // I-cache invalidate). A plain `DirectPhysMap`'s is a no-op (correct
        // only for I/O-coherent targets), which would let PID 1 fetch stale
        // code. The identity translation is the same live window; only the
        // maintenance becomes real (also for the stored physmap's
        // `clean_invalidate`, per the runtime spawn producer's rationale).
        let physmap = ConfiguredIdentityPhysMap;

        // Parse the build-time `init` `rxe` blob against the kernel's own
        // compiled-in syscall CFI tag. A mismatch fails closed.
        let Ok(image) = LoadImage::parse(INIT_RXE, &SYSCALL_TABLE_HASH) else {
            return;
        };

        // Place the stack and startup block above the image's mapped top
        // through the shared per-spawn derivation (one definition across
        // the ports); an image too large for the user region fails closed.
        let Some(layout) = spawn_layout::user_layout(&image, INIT_USER_BIAS) else {
            return;
        };
        // The span record the admission path stores so the stack-growth
        // fault path can back pages inside it (one shared derivation
        // across the ports; a malformed span fails the boot closed).
        let Some(stack_span) = spawn_layout::stack_span(&layout) else {
            return;
        };

        let request = SpawnRequest {
            image: &image,
            image_bytes: INIT_RXE,
            bias: INIT_USER_BIAS,
            stack: UserStack {
                base: layout.stack_base,
                page_count: spawn_layout::USER_STACK_COMMIT_PAGES,
            },
            start_block_base: layout.block_base,
            args: spawn_layout::INIT_ARGS,
            env: &[],
            canary: spawn_layout::INIT_CANARY,
        };

        // Authorise + build the EL0 image (emits `ProcessSpawned`) without
        // entering yet — PID 1 must be registered with the scheduler /
        // capability table / address-space registry *first* so its first
        // syscall resolves a caller context (`plans/PI.md` P6c-3).
        // SAFETY: building the image is itself safe; the returned `UserEntry`
        // is only entered below, once `space` is active (just switched to)
        // and the EL1 trap path is installed. The frame source draws
        // identity-mapped RAM frames from the kernel's live allocator. A
        // returning `Err` (denial or build failure) drops back to the
        // caller's fail-closed halt.
        let frames = ctx.frames();
        let Ok(entry) = (unsafe {
            spawn_image(
                &spawn_layout::SpawnAuthority,
                ctx.audit(),
                &mut space,
                &physmap,
                &request,
                move || frames.alloc().ok(),
            )
        }) else {
            return;
        };

        // The user-mode transition, boxed for the scheduler task body the
        // core wraps PID 1 in. `enter_user` diverges into EL0, so the
        // closure never truly returns (its `!` coerces to `()`).
        let user_mode = UserMode::new();
        let enter: Box<dyn FnMut() + Send> = Box::new(move || {
            // SAFETY: `space` is the active address space and the EL1 trap
            // vector + production dispatch callback are installed, so the
            // entered program's first `svc` is handled. `build_process_image`
            // mapped the entry/stack as user-accessible pages.
            unsafe { user_mode.enter_user(entry) }
        });

        // PID 1's user-address-space reactivation hook (`plans/SPAWN.md`
        // SP2): the core runs it on the dispatcher's context immediately
        // before every switch into PID 1, so the task `eret`s back into EL0
        // under its own `TTBR0_EL1` root and stays isolated from any sibling
        // process. It captures only the `u64` root, so it is
        // `Send`.
        // The hook is handed the task's kernel-stack top (the x86_64 port
        // uses it to repoint its per-CPU syscall entry stack); aarch64
        // reuses `SP_EL1` implicitly and so ignores it (`plans/PI.md` §X).
        let pre_resume: Box<dyn FnMut(u64) + Send> = Box::new(move |_stack_top: u64| {
            // SAFETY: the MMU is already enabled and `init_root_phys` is the
            // L1 root of PID 1's space, which identity-maps the low kernel
            // window the running kernel executes from — exactly
            // `activate_user_root`'s contract.
            unsafe { activate_user_root(init_root_phys) };
        });

        // Freeze the just-built mappings into the registry-storable,
        // `Send + Sync` snapshot the kernel-wide address-space registry
        // holds (the live arch `space` is not `Sync`), and box the direct
        // map that backs it, so PID 1's `stream_write` can copy its banner
        // out of user memory (`plans/PI.md` P6c-3 follow-up). Freezing
        // *after* `spawn_image` captures every mapped page — segments,
        // stack, and the startup-vector block. `freeze` only borrows, so
        // the live arch `space` is still owned below.
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());

        // Retain the live, mutable arch space behind the object-safe
        // `LiveUserSpace` boundary so PID 1's `mem_map` / `mmio_map`
        // syscalls mutate *its own* address space (`plans/PI.md`
        // 5d-0-ii (b′)). The `LiveSpace` composes the audited anonymous-map
        // mechanism (over the kernel's `'static` frame allocator, drawn from
        // `static_frames`) and the guarded device-window allocator (over the
        // `[MMIO_WINDOW_BASE, …)` region); it carries the *same* arch space
        // the snapshot above was frozen from. A context with no `'static`
        // allocator, or a window the allocator rejects, retains no live space
        // and PID 1's `mem_map` / `mmio_map` fail closed.
        //
        // The live space's `PhysMap` must be [`ConfiguredIdentityPhysMap`]:
        // a `dma_alloc` carve is mapped Normal-Non-Cacheable for the caller
        // while the kernel zeroes it through the cacheable identity alias,
        // so the post-zero `clean_invalidate` must be the real dcache
        // clean+invalidate (the runtime spawn producer's rationale applies
        // identically here — a no-op physmap leaves dirty zero lines that
        // the cache later writes back over device-visible rings).
        let live: Option<Box<dyn LiveUserSpace + Send>> = match ctx.static_frames() {
            Some(static_frames) => {
                let windows = crate::user_windows::user_windows(
                    static_frames.total_frames() as u64,
                    ANON_WINDOW_BASE,
                    super::USER_VA_TOP,
                );
                LiveSpace::new(
                    space,
                    ConfiguredIdentityPhysMap,
                    static_frames,
                    VirtAddr::new(MMIO_WINDOW_BASE),
                    spawn_layout::MMIO_WINDOW_PAGES,
                    VirtAddr::new(ANON_WINDOW_BASE),
                    windows.anon_pages,
                    VirtAddr::new(DMA_WINDOW_BASE),
                    spawn_layout::DMA_WINDOW_PAGES,
                    VirtAddr::new(SHARED_WINDOW_BASE),
                    spawn_layout::SHARED_WINDOW_PAGES,
                    VirtAddr::new(windows.file_base),
                    windows.file_pages,
                )
                .ok()
                .map(|live| Box::new(live) as Box<dyn LiveUserSpace + Send>)
            }
            None => None,
        };

        let physmap: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);

        // The VL805 USB keyboard now comes up entirely in user space: the
        // boot path's `FdtDiscovery` already emits the discovered
        // `brcm,bcm2711-pcie` node (with its register window + outbound
        // bus-window + inbound DMA grants) and the VideoCore mailbox node into
        // the hardware tree, and `devmgr` autoloads the signed
        // `/System/Drivers/` bundles against them — the PCIe root-complex
        // driver binds the bridge and emits the VL805 PCI function, the VL805
        // driver reloads the controller firmware over the mailbox and emits
        // the `usb,xhci` node, and the keyboard driver binds that, brings the
        // controller up, and pumps key edges into the input arbiter (`plans/PI.md`
        // P10 D5d — drivers in user space). There is no
        // in-kernel keyboard bring-up to start here.

        // Start the in-kernel root-unlock service alongside PID 1
        // (`plans/PI.md` P11 Chunk B-2 INCREMENT (2)).
        // Admitted onto the boot CPU's run queue *before* `admit_init`
        // diverges into the dispatch loop, the kthread brings up the bound
        // root block device over the production device-IRQ path, prompts
        // for the passphrase on the primary console, mounts the encrypted
        // root, and publishes the users database into `LATE_USERS_DB` so
        // `login` can authenticate. With no bound disk (the QEMU `virt`
        // shape without a planted root, a headless Pi) it starts nothing,
        // opens the console-0 gate, and PID 1 runs unchanged.
        let _unlock_started = crate::aarch64::root_unlock::spawn_if_present(ctx);

        // Register PID 1's caps + address space, publish it as the current
        // task, and dispatch it — `admit_init` diverges into EL0 on success.
        // SAFETY: the image was built into and `space` switched to active
        // above, and the trap path is installed, per the
        // `InitSpawnCtx::admit_init` contract; `frozen` faithfully describes
        // the active mappings and `physmap` backs them.
        unsafe {
            ctx.admit_init(
                spawn_layout::init_caps(),
                frozen,
                physmap,
                stack_span,
                kernel_stack,
                pre_resume,
                live,
                enter,
            );
        }
    }
}
