//! Build the pure-Rust syscall-resume fixture and canonical one-CPU QEMU DTB.

use std::env;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use tairix_itest_harness::pie::PieArch;

/// Freestanding target this vertical cross-compiles for.
const ARCH: PieArch = PieArch::Aarch64;

fn main() {
    tairix_itest_harness::emit_target_cfg();
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let manifest_dir = manifest_dir.trim_end_matches('/');

    let rxe_path = PathBuf::from(&out_dir).join("program_rxe.rs");
    let dtb_path = PathBuf::from(&out_dir).join("dtb_fixture.rs");
    if env::var("TARGET").unwrap_or_default() == ARCH.target_triple() {
        let kernel_linker =
            format!("{manifest_dir}/../../../kernel/arch/aarch64/link/aarch64-virt.ld");
        println!("cargo:rerun-if-changed={kernel_linker}");
        println!("cargo:rustc-link-arg=-T{kernel_linker}");
        let out_dir_os = std::ffi::OsString::from(&out_dir);
        let dtb = tairix_itest_harness::dump_aarch64_virt_dtb(&out_dir_os, 1);
        write_bytes(&dtb_path, "DTB_BLOB", &dtb);
        let rxe = tairix_itest_harness::program_fixture::GuestBuild {
            manifest_dir,
            out_dir: &out_dir,
            arch: ARCH,
            package: "tairix-test-syscall-resume-program",
            variant: None,
            env: &[],
        }
        .program_rxe(&tairix_kernel_syscall::SYSCALL_TABLE_HASH);
        write_program(&rxe_path, &rxe);
    } else {
        write_bytes(&dtb_path, "DTB_BLOB", &[]);
        write_program(&rxe_path, &[]);
    }
}

fn write_program(path: &Path, bytes: &[u8]) {
    let mut out = tairix_itest_harness::program_fixture::fixture_header();
    tairix_itest_harness::program_fixture::push_rxe_blob(
        &mut out,
        "PROGRAM_RXE",
        "the syscall-resume fixture program",
        bytes,
    );
    tairix_itest_harness::program_fixture::write_fixture(path, &out);
}

fn write_bytes(path: &Path, name: &str, bytes: &[u8]) {
    let mut out = String::from("// Auto-generated by build.rs. DO NOT EDIT.\n");
    write_array(&mut out, name, bytes);
    tairix_itest_harness::program_fixture::write_fixture(path, &out);
}

fn write_array(out: &mut String, name: &str, bytes: &[u8]) {
    let _ = write!(out, "pub const {name}: &[u8] = &[");
    for (index, byte) in bytes.iter().enumerate() {
        if index % 16 == 0 {
            out.push_str("\n    ");
        }
        let _ = write!(out, "0x{byte:02x}, ");
    }
    out.push_str("\n];\n");
}
