//! Build script for the aarch64 direct-physical-map QEMU vertical
//! (`plans/OPEN-DEFECTS.md` D56).
//!
//! Two jobs on the freestanding `aarch64-unknown-none` target:
//!
//! 1. Hand the aarch64 `virt` linker script to `rustc` — the single
//!    per-board linker script the architecture port owns.
//! 2. Dump the `virt` flattened device tree and embed it, because QEMU's
//!    `-kernel <ELF>` aarch64 path passes no DTB pointer (`x0 = 0`).
//!
//! The dump asks for [`GUEST_RAM_MIB`] rather than the harness default,
//! because the boot path sizes the direct physical map from the tree's
//! `/memory` window: a tree describing the default would leave the extra
//! RAM invisible, which is the very thing under test. It must match the
//! `ram_mib` this vertical's QEMU enrolment declares.
//!
//! Re-running `build.rs` produces byte-identical output, so the test is
//! deterministic.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

/// Guest RAM this vertical runs with, in mebibytes — enough that RAM spans
/// gigapages above the one holding the kernel image, so a process root that
/// carried a full-RAM identity map would be visible as one.
const GUEST_RAM_MIB: u32 = 3072;

fn main() {
    tairix_itest_harness::emit_target_cfg();
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");

    let target = std::env::var("TARGET").unwrap_or_default();
    let dtb_bytes = if target == "aarch64-unknown-none" {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
        let linker_script = format!(
            "{}/../../../kernel/arch/aarch64/link/aarch64-virt.ld",
            manifest_dir.trim_end_matches('/')
        );
        println!("cargo:rerun-if-changed={linker_script}");
        println!("cargo:rustc-link-arg=-T{linker_script}");
        // One CPU: sizing and installing the map is a boot-CPU-only step.
        tairix_itest_harness::dump_aarch64_virt_dtb_with_ram(&out_dir, 1, GUEST_RAM_MIB)
    } else {
        // Host builds compile the bin to a no-op `main`; no DTB needed.
        Vec::new()
    };

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// QEMU `virt` flattened device tree, dumped at build time\n");
    out.push_str("/// for this vertical's guest RAM (empty on host builds).\n");
    out.push_str("pub const DTB_BLOB: &[u8] = &[");
    for (i, b) in dtb_bytes.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n");
    writeln!(
        out,
        "/// Guest RAM the dumped tree describes, in mebibytes."
    )
    .expect("write to String never fails");
    writeln!(out, "pub const GUEST_RAM_MIB: u64 = {GUEST_RAM_MIB};")
        .expect("write to String never fails");

    let path = PathBuf::from(&out_dir).join("dtb_fixture.rs");
    fs::write(&path, out).expect("write dtb_fixture.rs");
}
