//! Build-time fixture generator for the M1 riscv64 demand-paged
//! file-mapping vertical — the riscv64 twin of
//! `tests/integration/file_map_qemu_aarch64/build.rs`.
//!
//! Three jobs on the freestanding `riscv64gc-unknown-none-elf` target
//! (unlike the aarch64 twin there is no DTB dump: OpenSBI passes the live
//! board tree in `a1`, so the test kernel reads it at boot):
//!
//! 1. Hand the riscv64 `virt` linker script to the test kernel (the single
//!    per-board script the architecture port owns).
//! 2. Emit the fixture file the kernel-side read-only filesystem double
//!    serves, from the shared single definition
//!    (`tairix_itest_harness::filemap_fixture`).
//! 3. Compile the pure-Rust U-mode fixture program
//!    (`tests/integration/file_map_program`) **once** — the four roles are
//!    selected at runtime from the registry argument vector —
//!    position-independent for the freestanding riscv64 target, pinning the
//!    fixture geometry through the `TAIRIX_FM_*` environment variables the
//!    shared definition computes, and convert the linked PIE ELF to an
//!    `rxe` blob with [`tairix_itest_harness::elf2rxe::elf_to_rxe`], baking
//!    relocations for the [`tairix_itest_harness::USER_IMAGE_BIAS`] the production spawn producer maps
//!    every image at and stamping the kernel's compiled-in syscall CFI tag
//!    (`tairix_kernel_syscall::SYSCALL_TABLE_HASH`) so
//!    [`tairix_abi::rxe::LoadImage::parse`] accepts it; emit the blob and
//!    the bias as a Rust source the test `include!`s.
//!
//! On any non-riscv64 target (host `cargo build --workspace`, clippy) it
//! emits inert stubs so the crate still builds; the kernel body that
//! consumes them compiles only for the freestanding riscv64 target.
//!
//! Re-running `build.rs` produces byte-identical output, so the test is
//! deterministic.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

use tairix_itest_harness::filemap_fixture;

/// Rust target triple of the freestanding riscv64 build.
const RISCV64_TARGET: &str = "riscv64gc-unknown-none-elf";

fn main() {
    tairix_itest_harness::emit_target_cfg();
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let manifest_dir = manifest_dir.trim_end_matches('/');

    let program_dir = format!("{manifest_dir}/../file_map_program");
    println!("cargo:rerun-if-changed={program_dir}/src/main.rs");
    println!(
        "cargo:rerun-if-changed={}",
        tairix_itest_harness::program_fixture::PROGRAM_LD
    );
    println!("cargo:rerun-if-changed={program_dir}/Cargo.toml");

    let rxe_path = PathBuf::from(&out_dir).join("program_rxe.rs");
    let fixture_path = PathBuf::from(&out_dir).join("fm_fixture.rs");

    let target = env::var("TARGET").unwrap_or_default();
    if target == RISCV64_TARGET {
        // The test kernel itself links with the riscv64 `virt` script the
        // architecture port owns (the single per-board script).
        let linker = format!("{manifest_dir}/../../../kernel/arch/riscv64/link/riscv64-virt.ld");
        println!("cargo:rerun-if-changed={linker}");
        println!("cargo:rustc-link-arg=-T{linker}");

        fs::write(&fixture_path, filemap_fixture::kernel_fixture_source())
            .expect("write fm_fixture.rs");

        let rxe = build_and_convert_program(manifest_dir, &out_dir);
        write_program_fixture(&rxe_path, &rxe);
    } else {
        // Inert stubs for host / other targets; the kernel body that uses
        // these compiles only for the freestanding riscv64 target.
        fs::write(
            &fixture_path,
            "// Auto-generated by build.rs. DO NOT EDIT.\n",
        )
        .expect("write fm_fixture.rs");
        write_program_fixture(&rxe_path, &[]);
    }
}

/// Compile the U-mode fixture program PIE for the freestanding riscv64
/// target (pinning the shared fixture geometry into its build) and convert
/// the linked ELF into an `rxe` blob.
fn build_and_convert_program(manifest_dir: &str, out_dir: &str) -> Vec<u8> {
    let program_ld = tairix_itest_harness::program_fixture::PROGRAM_LD;
    let target_dir = format!("{out_dir}/file-map-target");

    // Cargo fingerprints the RUSTFLAGS *string* (which names the linker
    // script by path) but not the script's *content*, so a `program.ld` edit
    // would not by itself trigger a relink and the converter could read a
    // stale ELF. A geometry change is keyed by the `rerun-if-env-changed`
    // declarations in the program's own build script. Wiping the private
    // target directory here forces a clean rebuild against the current
    // script + geometry without churning ordinary incremental builds.
    let _ = fs::remove_dir_all(&target_dir);

    // The program links no architecture crate, so `program.ld`'s
    // `ENTRY(_start)` roots `tairix-rt`'s trampoline; it is built
    // position-independent. Scope the PIE link flags to the riscv64 target
    // so the program's own host build script is unaffected, and build
    // `core` / `alloc` / `compiler_builtins` as PIC alongside it
    // (`-Z build-std`). `alloc` is required because `tairix-rt` registers a
    // `#[global_allocator]`, so the program names `alloc`.
    let cargo = env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let mut command = Command::new(cargo);
    command
        .current_dir(manifest_dir)
        // The outer build exports `CARGO_ENCODED_RUSTFLAGS` / `RUSTFLAGS`
        // into this build script's environment; both outrank the
        // target-scoped var below, so a nested cargo would inherit the outer
        // kernel's flags and drop the PIE link recipe. Clear them so the
        // target-scoped flags win and apply only to the riscv64 program
        // crates.
        .env_remove("CARGO_ENCODED_RUSTFLAGS")
        .env_remove("RUSTFLAGS")
        .env(
            "CARGO_TARGET_RISCV64GC_UNKNOWN_NONE_ELF_RUSTFLAGS",
            format!("-C relocation-model=pie -C link-arg=-pie -C link-arg=-T{program_ld}"),
        )
        .args([
            "build",
            "-p",
            "tairix-test-file-map",
            "--target",
            RISCV64_TARGET,
            "-Z",
            "build-std=core,compiler_builtins,alloc",
            "--target-dir",
            &target_dir,
        ]);
    // Pin the fixture geometry (the shared single definition).
    for (name, value) in filemap_fixture::geometry_env() {
        command.env(name, value);
    }
    let status = command
        .status()
        .expect("spawn cargo to build the file-map fixture program");
    assert!(
        status.success(),
        "building the file-map fixture program failed"
    );

    let elf_path = format!("{target_dir}/{RISCV64_TARGET}/debug/tairix-test-file-map");
    let elf = fs::read(&elf_path).unwrap_or_else(|e| panic!("read {elf_path}: {e}"));

    tairix_itest_harness::elf2rxe::elf_to_rxe(
        &elf,
        &tairix_kernel_syscall::SYSCALL_TABLE_HASH,
        tairix_itest_harness::USER_IMAGE_BIAS,
    )
    .unwrap_or_else(|_| panic!("convert the file-map fixture program ELF into an rxe image"))
}

/// Emit `PROGRAM_RXE` and `USER_BIAS` as a Rust source the test includes.
fn write_program_fixture(path: &std::path::Path, rxe: &[u8]) {
    let mut out = tairix_itest_harness::program_fixture::fixture_header();
    tairix_itest_harness::program_fixture::push_rxe_blob(
        &mut out,
        "PROGRAM_RXE",
        "the four-role fixture program",
        rxe,
    );
    tairix_itest_harness::program_fixture::write_fixture(path, &out);
}
