//! The freestanding aarch64 test kernel: build an EL0 image for the C program
//! and drop into it through the production spawn caller, servicing the syscalls
//! it issues.

use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU32, Ordering};

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery, SyscallNumber, SYSCALL_MAX_ARGS};
use rustos_arch_aarch64::paging::{
    self, el0_code_leaf_attrs, el0_data_leaf_attrs, el0_rodata_leaf_attrs,
};
use rustos_arch_aarch64::{
    exceptions, handle_panic_via_serial, qemu_exit, syscall_entry, userentry::UserMode, SERIAL_SINK,
};
use rustos_bumpalloc::BumpAllocator;
use rustos_kernel_core::{spawn_and_enter, SpawnRequest};
use rustos_kernel_mem::{
    AddressSpace, DirectPhysMap, Frame, MapFlags, Page, PageTableError, PageTableOps, PhysAddr,
    UserStack,
};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;
use rustos_log::{log, Event, EventId, Level};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// Size of the test's bump heap, from which the spawn caller allocates the
/// startup-vector block buffer. It lives in `.bss` (zeroed by the boot
/// trampoline); the aarch64 `virt` linker script has no dedicated `.heap`
/// section, so unlike the riscv64 sibling the heap is a plain `.bss` static.
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: BumpAllocator =
    unsafe { BumpAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Exit code the C program returns when every abi-v1 check and both syscall
/// round-trips pass (`csrc/main.c` `EXIT_OK`).
const EXPECTED_EXIT: u64 = 99;
/// Capability id the program queries (`csrc/main.c` `PROBE_CAP`); the callback
/// asserts the marshalled argument equals it.
const PROBE_CAP: u64 = 4;
/// Sentinel `clock_get` returns to the program (`csrc/main.c`
/// `CLOCK_SENTINEL`), exercising full 64-bit result marshalling.
const CLOCK_SENTINEL: u64 = 0x0123_4567_89ab_cdef;

/// Gigabytes of identity map: `[0, 2 GiB)` covers the `virt` board's device
/// MMIO (GiB 0) and the RAM base at GiB 1 where this kernel runs.
const IDENTITY_GIB: usize = 2;

/// User stack base (1 MiB into the high user region) and size. crt0 carves a
/// 1 MiB scratch span off the stack, so the stack must comfortably exceed it.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB > crt0's 1 MiB scratch + call frames).
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up, well
/// clear of the program image and the stack).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program (any value).
const CANARY: u64 = 0xC0FF_EE00_D15E_A5ED;

/// Number of physical frames the test hands the spawn builder: the program's
/// segments, the user stack, and the startup block. Sized with headroom.
const FRAME_COUNT: usize = 320;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4250);
const TEST_FAIL: EventId = EventId(4252);

/// Semihosting failure codes, distinct per failure site.
const FAIL_POOL: u16 = 1;
const FAIL_PARSE: u16 = 2;
const FAIL_SPAWN_RETURNED: u16 = 3;
const FAIL_WRONG_SYSCALL: u16 = 4;
const FAIL_WRONG_CODE: u16 = 5;
const FAIL_WRONG_CAP: u16 = 6;

/// Page-table pool backing the stage-1 hierarchy (lives in `.bss`).
static PAGE_TABLE_POOL: paging::PageTablePool = paging::PageTablePool::new();

/// Physical-frame backing store the spawn builder allocates user pages from.
/// `align(4096)` so each `PAGE_SIZE` slice is a valid page frame; identity-
/// mapped (its physical address equals its kernel virtual address), so the
/// builder reaches it through [`DirectPhysMap::identity`].
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Set once the round-trip has been driven so a re-entry cannot re-run it.
static TEST_DRIVEN: AtomicU32 = AtomicU32::new(0);

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn c_program_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A `CapabilityQuery` granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires (`AGENTS.md` §5.4).
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// A `PageTableOps` adapter over the aarch64 stage-1 [`paging::AddressSpace`].
///
/// `kernel/mem`'s `build_process_image` is generic over a [`PageTableOps`]
/// backend; this is the bare-metal aarch64 backend the round-trip needs. It
/// lives in the test crate rather than `kernel/arch/aarch64` because §17.4
/// forbids an architecture crate from depending on `kernel/mem` (where the
/// trait lives); the test crate may depend on both. The `unsafe` stage-1 walk
/// and `TTBR0`/TLB sequencing stay encapsulated in `paging`; this adapter only
/// translates flags and routes calls (`AGENTS.md` §2.10).
struct AarchUserPageTable {
    arch: paging::AddressSpace,
    pool: &'static paging::PageTablePool,
}

impl AarchUserPageTable {
    fn new(arch: paging::AddressSpace, pool: &'static paging::PageTablePool) -> Self {
        Self { arch, pool }
    }
}

/// Translate the architecture-neutral [`MapFlags`] into the EL0 stage-1 page
/// leaf attributes. `build_process_image` always sets [`MapFlags::USER`], so
/// every mapping this adapter receives is an EL0 mapping; the executable /
/// writable bits pick the matching leaf-attribute helper (W^X: code is
/// read-only-executable, data is read/write-non-executable, read-only data is
/// read-only-non-executable).
fn to_el0_attrs(flags: MapFlags) -> u64 {
    if flags.contains(MapFlags::EXEC) {
        el0_code_leaf_attrs()
    } else if flags.contains(MapFlags::WRITE) {
        el0_data_leaf_attrs()
    } else {
        el0_rodata_leaf_attrs()
    }
}

impl PageTableOps for AarchUserPageTable {
    fn map(&mut self, page: Page, frame: Frame, flags: MapFlags) -> Result<(), PageTableError> {
        let vaddr = page.start().as_u64();
        let paddr = frame.start().as_u64();
        self.arch
            .map_4k_with_attrs(self.pool, vaddr, paddr, to_el0_attrs(flags))
            .ok_or(PageTableError::AllocFailed(
                rustos_kernel_mem::AllocError::OutOfMemory,
            ))
    }

    fn unmap(&mut self, _page: Page) -> Result<Frame, PageTableError> {
        // The spawn builder never unmaps; refusing keeps the adapter minimal.
        Err(PageTableError::NotMapped)
    }

    fn translate(&self, _page: Page) -> Option<(Frame, MapFlags)> {
        // The spawn builder never translates; it only maps and fills.
        None
    }

    fn flush(&mut self, page: Page) {
        // The address space is already active, so a freshly inserted leaf needs
        // a local TLB invalidation by virtual address. `tlbi vaae1` takes the
        // VA shifted right by 12 (the page number); `dsb`/`isb` order the
        // invalidation before the next access.
        let va_page = page.start().as_u64() >> 12;
        // SAFETY: `tlbi vaae1` is the documented stage-1 by-VA TLB-invalidate
        // instruction; it touches no memory and only invalidates the cached
        // translation for the page we have just (re)mapped. No Rust spelling
        // exists.
        unsafe {
            core::arch::asm!(
                "dsb ishst",
                "tlbi vaae1, {va}",
                "dsb ish",
                "isb",
                va = in(reg) va_page,
                options(nostack, preserves_flags),
            );
        }
    }
}

/// The syscall dispatch callback the C program's traps reach.
///
/// Services the two round-trip syscalls (`cap_query` → "held", `clock_get` →
/// the 64-bit sentinel) and, on `exit`, asserts the program computed
/// [`EXPECTED_EXIT`] before writing the PASS finisher. Any unexpected syscall,
/// a wrong `cap_query` argument, or a wrong exit code writes a distinct failure
/// finisher. The `cap_query` / `clock_get` arms return the answer to user
/// mode; the `exit` and failure arms never return.
extern "C" fn dispatch_and_finish(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the EL1 vector built the `[u64; SYSCALL_MAX_ARGS]` array and
    // passes a pointer valid for this call (`syscall_entry` contract).
    let args = unsafe { *args_ptr };

    if number == u64::from(SyscallNumber::CAP_QUERY.as_u16()) {
        if args[0] != PROBE_CAP {
            note(TEST_FAIL, "cap_query marshalled the wrong capability id");
            qemu_exit::exit_failure(FAIL_WRONG_CAP);
        }
        // Report the capability as held (the C program checks for `1`).
        return 1;
    }

    if number == u64::from(SyscallNumber::CLOCK_GET.as_u16()) {
        return CLOCK_SENTINEL;
    }

    if number == u64::from(SyscallNumber::EXIT.as_u16()) {
        if args[0] != EXPECTED_EXIT {
            note(TEST_FAIL, "C program exited with the wrong code");
            qemu_exit::exit_failure(FAIL_WRONG_CODE);
        }
        qemu_exit::exit_success();
    }

    note(TEST_FAIL, "C program issued an unexpected syscall");
    qemu_exit::exit_failure(FAIL_WRONG_SYSCALL);
}

/// Hand out the next identity-mapped physical frame from [`FRAME_POOL`].
fn frame_source() -> impl FnMut() -> Option<Frame> {
    let mut next = 0usize;
    move || {
        if next >= FRAME_COUNT {
            return None;
        }
        let offset = next * paging::PAGE_SIZE;
        next += 1;
        // The pool is identity-mapped, so its kernel virtual address is also
        // its physical address.
        let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
        Some(Frame::containing(PhysAddr::new(base)))
    }
}

/// Boot entry point (called by the arch crate's boot trampoline via
/// `rustos_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    if TEST_DRIVEN
        .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_POOL);
    }

    // Enable FP/SIMD at EL1 before running any code that may use it: the `rxe`
    // decoder and `build_process_image`'s fills compile to vectorised
    // (NEON) `memcpy`/`memcmp`, which trap as an undefined instruction
    // (ESR EC=0x7) unless `CPACR_EL1.FPEN` is set. The boot trampoline leaves
    // FP trapped, so each freestanding kernel that uses FP enables it itself.
    // SAFETY: writing `CPACR_EL1.FPEN = 0b11` (do-not-trap) followed by `isb`
    // is the documented enable sequence; it runs once on the boot CPU before
    // any FP/SIMD instruction executes and grants no cross-privilege
    // authority.
    unsafe {
        core::arch::asm!(
            "mrs {t}, CPACR_EL1",
            "orr {t}, {t}, {fpen}",
            "msr CPACR_EL1, {t}",
            "isb",
            t = out(reg) _,
            fpen = in(reg) 0b11u64 << 20,
            options(nostack, preserves_flags),
        );
    }

    note(
        TEST_START,
        "aarch64 C-program round-trip: building the EL0 image",
    );

    // 1. Stage-1 address space identity-mapping the kernel + MMIO, then
    //    activate it and install the EL1 vector table before any user mapping.
    let Some(arch) = paging::AddressSpace::new_identity_gigapages(&PAGE_TABLE_POOL, IDENTITY_GIB)
    else {
        note(TEST_FAIL, "page-table pool exhausted (identity map)");
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, and the
    // device MMIO, so enabling the MMU is sound.
    unsafe { arch.switch() };
    // SAFETY: called once on the boot CPU before any exception fires.
    unsafe { exceptions::init_vectors() };
    syscall_entry::set_dispatch_callback(dispatch_and_finish);

    // 2. Parse the build-time `rxe` blob against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        note(TEST_FAIL, "C program rxe image failed to parse");
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    // 3. Build the EL0 image into the (active) address space and enter it
    //    through the production capability-checked, audited spawn caller.
    let mut space = AddressSpace::new(AarchUserPageTable::new(arch, &PAGE_TABLE_POOL));
    let physmap = DirectPhysMap::identity((IDENTITY_GIB as u64) << 30);
    let request = SpawnRequest {
        image: &image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"prog"],
        env: &[],
        canary: CANARY,
    };

    note(TEST_START, "dropping into the spawned C program");

    // SAFETY: `space` is the active address space (we `switch`ed to it above)
    // and the EL1 vector table is installed, so the new program's `svc` is
    // handled. `spawn_and_enter` checks `CAP_PROC_SPAWN`, builds the image into
    // `space`, and `enter_user`s into it; on the authorised path it diverges.
    let outcome = unsafe {
        spawn_and_enter(
            &SpawnAuthority,
            &SERIAL_SINK,
            &UserMode::new(),
            &mut space,
            &physmap,
            &request,
            frame_source(),
        )
    };

    // `spawn_and_enter` only returns on a denial or a build failure; the
    // authorised, well-formed path diverges into EL0. Reaching here is a
    // closed failure.
    match outcome {
        Err(_) => {
            note(TEST_FAIL, "spawn_and_enter returned instead of entering");
            qemu_exit::exit_failure(FAIL_SPAWN_RETURNED);
        }
        Ok(never) => match never {},
    }
}
