//! riscv64 (QEMU `virt` / SiFive) PID 1 (`init`) spawn seam —
//! `plans/PI.md` RV-P3.
//!
//! [`RiscvInitSpawn`] implements the architecture-neutral
//! [`tairix_kernel_core::InitSpawn`] hook the boot pipeline installs into
//! the [`tairix_kernel_core::BootInfo`] hand-off
//! (`boot_riscv64::try_boot` → `BootInfo::with_init`). Once every init
//! phase has succeeded and `kernel_core::kernel_main` has emitted
//! [`tairix_kernel_core::AuditEvent::BootCompleted`], the core invokes
//! [`InitSpawn::spawn_init`]; this implementation builds the embedded
//! `init` (`Run`) program's U-mode image and drops into it through the
//! production, capability-checked, audited spawn caller
//! ([`tairix_kernel_core::spawn_image`] + [`InitSpawnCtx::admit_init`]).
//! On the authorised, well-formed path the task is dispatched into U-mode;
//! on any failure it returns so `kernel_main` parks the boot hart
//! fail-closed.
//!
//! The image, its relocation bias ([`INIT_USER_BIAS`]), and the kernel's
//! syscall CFI tag are baked at build time (`build.rs` →
//! `tairix_itest_harness::elf2rxe`), exactly like the aarch64 and x86_64
//! seams, so there is one conversion path. Spawning
//! `init` is *not* a privileged bypass: the program receives only the
//! authority its `rxe` manifest requests intersected with its user's
//! grants; this seam only authorises the *act* of
//! spawning under `CAP_PROC_SPAWN`.
//!
//! PID 1's kernel stack comes from the window-backed tier
//! ([`tairix_kernel_core::kstack::alloc_kernel_stack`]), whose guard slot is
//! unmapped in every root at once, so an overrun takes a synchronous store
//! page fault under PID 1's `satp` without this seam touching its root.

use core::sync::atomic::{AtomicBool, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_arch_riscv64::paging::{
    activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool,
};
use tairix_arch_riscv64::userentry::USER_MODE;
use tairix_kernel_core::{
    spawn_image, InitSpawn, InitSpawnCtx, ProcessResume, ProcessSpace, SpawnMode, UserThreadEntry,
};
use tairix_kernel_mem::{
    AddressSpace, DirectPhysMap, LiveSpace, PhysMap, UserAddressSpace, VirtAddr,
};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;

use crate::spawn_layout;

// `INIT_RXE: &[u8]` and `INIT_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/init_rxe.rs"));

/// Gigabytes of identity map the spawn address space provides.
///
/// `[0, 4 GiB)` covers the QEMU `virt` board's low device MMIO and the
/// RAM base at `0x8000_0000` (GiB 2), where the kernel image, its boot
/// heap, the leaked `KernelState`, and the live frame allocator all live
/// — so switching to this space does not move the ground under the
/// running kernel (every pointer keeps its identity address).
/// [`INIT_USER_BIAS`] (64 GiB) sits far above it, so the program's pages
/// land on freshly walked Sv39 tables instead of colliding with an
/// identity gigapage leaf — the same 4 GiB window the
/// `spawn_session_qemu_riscv64` vertical uses.
const IDENTITY_GIB: usize = 4;

/// Exclusive top of the identity window in bytes: a chained kthread-stack
/// block must lie wholly below it so the stack stays mapped in PID 1's own
/// root.
const IDENTITY_LIMIT: u64 = (IDENTITY_GIB as u64) << 30;

/// PID 1's four fixed guarded-window bases (`plans/PI.md` 5d-0-ii (b′)/(c)),
/// derived from the one shared offset set the retained [`LiveSpace`]'s
/// window allocators are configured with.
const WINDOWS: spawn_layout::WindowBases = spawn_layout::window_bases(INIT_USER_BIAS);

/// Page-table pool backing the spawn address space's Sv39 hierarchy.
///
/// Lives in `.bss` for the lifetime of the kernel image, so `satp` keeps
/// pointing at a valid table after [`RiscvInitSpawn::spawn_init`] switches
/// to it (monotonic, never freed). The identity map
/// needs a single root frame; the rest serve the freshly walked user
/// mappings at [`INIT_USER_BIAS`].
static INIT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Set once PID 1 has been spawned so a re-entry cannot re-run the path.
static INIT_SPAWNED: AtomicBool = AtomicBool::new(false);

/// The riscv64 PID 1 spawn seam installed into the
/// [`tairix_kernel_core::BootInfo`] hand-off by `boot_riscv64::try_boot`.
pub struct RiscvInitSpawn;

/// The single, `'static` [`RiscvInitSpawn`] the boot path borrows.
pub static RISCV_INIT_SPAWN: RiscvInitSpawn = RiscvInitSpawn;

impl InitSpawn for RiscvInitSpawn {
    fn spawn_init(&self, ctx: &'static (dyn InitSpawnCtx + Sync)) {
        // Spawn PID 1 at most once; a spurious re-entry falls through to the
        // caller's fail-closed halt rather than building a second image.
        if INIT_SPAWNED
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }

        // Build an Sv39 address space identity-mapping the kernel + MMIO,
        // then activate it so the user mappings below land in the active
        // hierarchy. The S-mode trap vector and the production `ecall`
        // dispatch callback were installed earlier by the boot path, so the
        // new program's first `ecall` is handled rather than faulting.
        let Some(arch) = ArchAddressSpace::new_identity_gigapages(&INIT_PAGE_TABLES, IDENTITY_GIB)
        else {
            return;
        };
        // Capture PID 1's `satp` root before the arch space is moved into the
        // `kernel/mem` wrapper, so the `pre_resume` hook can reactivate `satp`
        // with it before every switch into PID 1 (`plans/SPAWN.md` SP2). It is
        // a plain `u64`, so the boxed hook stays `Send`.
        let init_root_phys = arch.root_phys();

        // PID 1's kernel stack: a run of the shared kernel remap window whose
        // guard slot is unmapped in every root at once, so the stack stays
        // mapped and guarded across the switch below without touching `arch`.
        let kernel_stack = tairix_kernel_core::kstack::alloc_kernel_stack();

        // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
        // leaked kernel state, the boot heap, and the device MMIO (all within
        // `[0, 4 GiB)` on the `virt` board), so enabling it does not move the
        // ground under the running code — exactly `AddressSpace::switch`'s
        // contract. Called once on the boot hart.
        unsafe { arch.switch() };

        let mut space = AddressSpace::new(arch);
        let physmap = DirectPhysMap::identity(IDENTITY_LIMIT);

        // Parse the build-time `init` `rxe` blob against the kernel's own
        // compiled-in syscall CFI tag. A mismatch fails closed.
        let Ok(image) = LoadImage::parse(INIT_RXE, &SYSCALL_TABLE_HASH) else {
            return;
        };

        // Place the stack and startup block above the image's mapped top,
        // and derive the span record the stack-growth fault path backs
        // pages inside, through the one shared per-spawn derivation. An
        // image too large for the user region fails the boot closed.
        let Some((request, stack_span)) =
            spawn_layout::init_request(&image, INIT_RXE, INIT_USER_BIAS)
        else {
            return;
        };

        // Authorise + build the U-mode image (emits `ProcessSpawned`) without
        // entering yet — PID 1 must be registered with the scheduler /
        // capability table / address-space registry *first* so its first
        // syscall resolves a caller context (`plans/PI.md` RV-P3).
        // SAFETY: building the image is itself safe; the returned `UserEntry`
        // is only entered below, once `space` is active (just switched to) and
        // the S-mode trap path is installed. The frame source draws
        // identity-mapped RAM frames from the kernel's live allocator. A
        // returning `Err` (denial or build failure) drops back to the caller's
        // fail-closed halt.
        let frames = ctx.frames();
        let Ok(entry) = (unsafe {
            spawn_image(
                &spawn_layout::SpawnAuthority,
                SpawnMode::General,
                ctx.audit(),
                &mut space,
                &physmap,
                &request,
                move || frames.alloc().ok(),
            )
        }) else {
            return;
        };

        // PID 1's user-address-space reactivation hook (`plans/SPAWN.md` SP2):
        // the core runs it on the dispatcher's context immediately before every
        // switch into PID 1, so the task `sret`s back into U-mode under its own
        // `satp` root and stays isolated from any sibling process. It captures only the `u64` root, so it is `Send`.
        // The kernel-stack top the hook is handed is unused on riscv64:
        // `sscratch` is per-task hardware state armed by `userentry::enter_user`
        // and re-armed by the trap vector from each task's own kernel-stack
        // frame on every U-return, so a trap always lands on *its* kernel stack
        // with no dispatcher-side repointing.
        let pre_resume: ProcessResume = Arc::new(move |_stack_top: u64, _tls_base: u64| {
            // SAFETY: paging is enabled and `init_root_phys` is the Sv39 root
            // of PID 1's space, which identity-maps the low kernel window the
            // running kernel executes from — exactly `activate_user_root`'s
            // contract.
            unsafe { activate_user_root(init_root_phys) };
        });

        // Freeze the just-built mappings into the registry-storable,
        // `Send + Sync` snapshot the kernel-wide address-space registry holds
        // (the live arch `space` is not `Sync`), and box the direct map that
        // backs it, so PID 1's `stream_write` can copy its banner out of user
        // memory. Freezing *after* `spawn_image` captures every mapped page —
        // segments, stack, and the startup-vector block.
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());

        // PID 1's process address space (`plans/PI.md` 5d-0-ii (b′)): the
        // *same* arch space the snapshot above was frozen from, zeroing
        // anonymous frames through a fresh identity [`DirectPhysMap`] over the
        // identity window PID 1 runs under. No `'static` allocator, or a
        // window the allocator rejects, retains none and PID 1's `mem_map` /
        // `mmio_map` fail closed.
        let live: Option<Arc<ProcessSpace>> = match ctx.static_frames() {
            Some(static_frames) => {
                let windows = crate::user_windows::user_windows(
                    static_frames.total_frames() as u64,
                    WINDOWS.anon,
                    super::USER_VA_TOP,
                );
                LiveSpace::new(
                    space,
                    DirectPhysMap::identity(IDENTITY_LIMIT),
                    static_frames,
                    VirtAddr::new(WINDOWS.mmio),
                    spawn_layout::MMIO_WINDOW_PAGES,
                    VirtAddr::new(WINDOWS.anon),
                    windows.anon_pages,
                    VirtAddr::new(WINDOWS.dma),
                    spawn_layout::DMA_WINDOW_PAGES,
                    VirtAddr::new(WINDOWS.shared),
                    spawn_layout::SHARED_WINDOW_PAGES,
                    VirtAddr::new(windows.file_base),
                    windows.file_pages,
                )
                .ok()
                .map(|live| {
                    Arc::new(ProcessSpace::new(
                        Box::new(live),
                        Arc::clone(&pre_resume),
                        &USER_MODE,
                    ))
                })
            }
            None => None,
        };

        let physmap: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);

        // Start the in-kernel root-unlock service alongside PID 1
        // (`plans/NETWORK.md` N4e-riscv64). Admitted onto the boot hart's run
        // queue *before* `admit_init` diverges into the dispatch loop, the
        // kthread brings up the bound virtio-blk root device over the
        // production PLIC device-IRQ path, then serves the driver store and
        // (fail-closed on the input-less SBI console) resolves login. With no
        // bound disk (a `virt` shape without a planted root) it starts
        // nothing, opens the console-0 gate, and PID 1 runs unchanged.
        let _unlock_started = crate::riscv64::root_unlock::spawn_if_present(ctx);

        // Register PID 1's caps + address space, publish it as the current
        // task, and dispatch it — `admit_init` diverges into U-mode on success.
        // SAFETY: the image was built into and `space` switched to active
        // above, and the trap path is installed, per the
        // `InitSpawnCtx::admit_init` contract; `frozen` faithfully describes
        // the active mappings, `physmap` backs them, and `live` retains the
        // same arch space `frozen` was taken from.
        unsafe {
            ctx.admit_init(
                spawn_layout::init_caps(),
                frozen,
                physmap,
                stack_span,
                kernel_stack,
                pre_resume,
                live,
                UserThreadEntry {
                    port: &USER_MODE,
                    regs: entry,
                },
            );
        }
    }
}
