//! The freestanding aarch64 test kernel: prove the `mem_pin` / `mem_unpin`
//! pair end to end (`plans/STRESSTEST.md` ST2).
//!
//! Unlike the bespoke micro-kernel harnesses, every syscall and every user
//! fault here runs the production `KernelDispatchHook` /
//! `KernelSyscallHandlers` path: the chassis installs the hook through a
//! `DispatchCallbackSlot`, binds the production user-fault resolver to the
//! same slot, wires the production `LiveMemMap` producer (backing
//! `mem_map` and the stack-growth fault path), a real `KernelProcessWait`,
//! and a `ProgramRegistry` carrying the three child roles, their numeric
//! parameters derived from the one shared `spawn_layout` policy. The parent
//! role is spawned through the production
//! `InitSpawnCtx::spawn_driver_process` seam; it spawns and reaps the
//! children through the production `spawn` + `wait` syscalls:
//!
//! * `deny` — holds no `CAP_MEM_PIN`: `mem_pin` is refused
//!   `PermissionDenied` at the dispatcher gate while the ungated
//!   `mem_unpin` still answers success, exits 0;
//! * `pin` — lowers its own `pinned-memory-bytes` bound via `rlimit_set`,
//!   pins itself (idempotently), sees an over-budget `mem_map` refused
//!   `OutOfRange` and a within-budget one succeed, unpins, and sees the
//!   formerly refused map succeed, exits 0;
//! * `child` — spawned by the *pinned* parent: starts unpinned (the mark
//!   is never inherited even though the lowered limit is) so its
//!   over-budget map succeeds, exits 0.
//!
//! The chassis reaps the parent through the producer's non-blocking poll
//! and PASSes only on a parent exit of 0.

use core::panic::PanicInfo;

use alloc::boxed::Box;
use alloc::sync::Arc;

use rustos_abi::{CapabilityId, Errno, WaitFlags, WaitStatus, SYSCALL_MAX_ARGS};
use rustos_arch_aarch64::kernel_arch::timer_frequency_hz;
use rustos_arch_aarch64::paging::{
    configure_device_gigapages, configure_ram_gigapages, AddressSpace as ArchAddressSpace,
    PageTablePool, GIGAPAGE_MASK_WORDS,
};
use rustos_arch_aarch64::{
    enable_fp_el1, exceptions, fault, gic, handle_panic_via_serial, qemu_exit, syscall_entry,
    Aarch64Arch, Aarch64ArchStorage, SERIAL_SINK,
};
use rustos_arch_api::CpuId;
use rustos_caps::CapabilitySet;
use rustos_fdt::Fdt;
use rustos_kalloc::FreeListAllocator;
use rustos_kernel::aarch64::arch_wrapper::{Aarch64BinArch, UART_ONLY_CONSOLES};
use rustos_kernel::aarch64::spawn_producer::{AARCH64_PROCESS_SPAWN, USER_IMAGE_BIAS};
use rustos_kernel::dispatch_core::{dispatch_via_slot, read_raw_args, resolve_user_fault_via_slot};
use rustos_kernel::spawn_layout::USER_STACK_COMMIT_PAGES;
use rustos_kernel_core::{
    AddressSpaceRegistry, BootReserve, DispatchCallbackSlot, EmbeddedProgram, InitSpawnCtx,
    KernelArch, KernelDispatchHook, KernelInitSpawner, KernelProcessWait, LiveMemMap, ProcessWait,
    ProgramRegistry, RandomReserve, NULL_DMA_ALLOC_FACILITY, NULL_MMIO_MAP_FACILITY,
    NULL_SEAT_REGISTRY, NULL_SHARED_MEM_FACILITY,
};
use rustos_kernel_ipc::PortRegistry;
use rustos_kernel_irq::{IrqTable, UnsupportedController};
use rustos_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use rustos_kernel_sched_api::SchedulerArch;
use rustos_kernel_sched_cfq::{Scheduler, SchedulerConfig};
use rustos_kernel_sec::{CapTable, TaskId as SecTaskId};
use rustos_log::{log, Event, EventId, Level};
use rustos_sync::RwLock;

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// The single-core slice runs logical CPU 0 on the boot core.
const BOOT_CPU: CpuId = 0;

/// Gigabytes of identity map the boot address space provides: `[0, 2 GiB)`
/// covers the `virt` board's device MMIO (GiB 0) and the RAM base at GiB 1
/// where this kernel, its heap, and the frame pool live.
const IDENTITY_GIB: usize = 2;

/// Physical frames the production spawn producer draws from: four spawned
/// processes (image, eagerly committed stack top, page tables,
/// identity-window tables) plus the fixture's successful anonymous maps
/// (one [`WITHIN_BYTES`] and two [`OVER_BYTES`] regions ≈ 4.25 MiB).
/// Sized from that appetite with generous headroom (16 MiB).
const FRAME_COUNT: usize = 4096;

/// The `pinned-memory-bytes` bound the `pin` role (and the parent) impose
/// on themselves: the eagerly committed stack top plus 1 MiB of headroom.
/// Derived from the one shared policy constant so the budget always sits
/// above the spawn-time footprint (the committed stack) with room for the
/// within-budget map, while every [`OVER_BYTES`] request decisively
/// crosses it.
const PIN_BOUND_BYTES: u64 = USER_STACK_COMMIT_PAGES * PAGE_SIZE as u64 + (1 << 20);

/// Bytes of the within-budget map the pinned `pin` role performs: far
/// inside the 1 MiB headroom above the spawn-time footprint.
const WITHIN_BYTES: u64 = 256 << 10;

/// Bytes of the over-budget map: with the spawn-time footprint at least
/// the committed stack, `footprint + OVER_BYTES` always crosses
/// [`PIN_BOUND_BYTES`] (2 MiB > 1 MiB headroom), while an unpinned
/// process maps it freely.
const OVER_BYTES: u64 = 2 << 20;

/// Longest decimal argument the rows below need (`u64::MAX` is 20 digits).
const DEC_MAX: usize = 20;

/// Render `value` as a fixed-width, zero-padded decimal byte string at
/// compile time. Leading zeroes are harmless: the fixture's parser accepts
/// them, and a fixed width lets the argument live in a `static` the
/// registry row borrows.
const fn dec_bytes(mut value: u64) -> [u8; DEC_MAX] {
    let mut out = [b'0'; DEC_MAX];
    let mut i = DEC_MAX;
    while i > 0 {
        i -= 1;
        out[i] = b'0' + (value % 10) as u8;
        value /= 10;
        if value == 0 {
            break;
        }
    }
    out
}

/// [`PIN_BOUND_BYTES`] as a decimal argument-vector value.
static PIN_BOUND_ARG: [u8; DEC_MAX] = dec_bytes(PIN_BOUND_BYTES);
/// [`WITHIN_BYTES`] as a decimal argument-vector value.
static WITHIN_ARG: [u8; DEC_MAX] = dec_bytes(WITHIN_BYTES);
/// [`OVER_BYTES`] as a decimal argument-vector value.
static OVER_ARG: [u8; DEC_MAX] = dec_bytes(OVER_BYTES);

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4460);
const TEST_SPAWNED: EventId = EventId(4461);
const TEST_PASS: EventId = EventId(4462);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: u16 = 1;
const FAIL_GIC: u16 = 2;
const FAIL_POOL: u16 = 3;
const FAIL_FRAMES: u16 = 4;
const FAIL_SCHED_NEW: u16 = 5;
const FAIL_SPAWN: u16 = 6;
const FAIL_DEADLOCK: u16 = 7;
const FAIL_NO_DISPATCH: u16 = 8;
const FAIL_HOOK_INSTALL: u16 = 9;
const FAIL_RESOLVER_INSTALL: u16 = 10;
const FAIL_BIAS: u16 = 11;
const FAIL_POLL: u16 = 12;
const FAIL_DRAINED: u16 = 13;
const FAIL_PARENT_STOPPED: u16 = 14;
/// Base finisher for a non-zero parent exit; the parent's diagnostic exit
/// code is added so the failing role/site is identifiable in the finisher.
const FAIL_EXIT_BASE: u16 = 100;

/// Size of the test's bump heap. Lives in `.bss` (zeroed by the trampoline).
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the kernel's own boot identity map.
static BOOT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Identity-mapped physical-frame backing store the live [`FrameAllocator`]
/// serves the spawn producer and the stack-growth fault path from; inside
/// the 2 GiB identity window the producer's page-table walk requires.
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// The dispatch-callback slot the production [`KernelDispatchHook`] is
/// installed into (one slot per binary, set once). Both the syscall
/// callback and the user-fault resolver resolve through it.
static DISPATCH_SLOT: DispatchCallbackSlot = DispatchCallbackSlot::new();

/// Per-CPU storage backing the scheduler's arch handle.
static SCHED_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// Per-CPU storage backing the dispatch hook + spawn ctx arch handle.
static HOOK_ARCH_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// This vertical binds no IRQ lines; the fail-closed controller mirrors
/// what `kernel/core::init` installs when a port exposes no routing.
static IRQ_CONTROLLER: UnsupportedController = UnsupportedController;

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn mem_pin_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// The syscall-dispatch callback every program's `svc` traps reach. It
/// mirrors the production bin-crate callback (`dispatch_aarch64`): read the
/// kernel-stack args frame and forward through the resident production
/// [`KernelDispatchHook`] via the shared `dispatch_via_slot` bridge. An
/// empty slot or a missing caller context fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the exception trampoline lays the frame out on the kernel
    // stack and only invokes us with a valid pointer; the array lives at
    // least until we return.
    let args = unsafe { read_raw_args(args_ptr) };
    match dispatch_via_slot(&DISPATCH_SLOT, number, args) {
        Some(value) => value,
        None => qemu_exit::exit_failure(FAIL_NO_DISPATCH),
    }
}

/// The user-fault resolver the EL1 data-abort path calls for every EL0
/// data abort: the exact production glue (`production_user_fault`), bound
/// to this vertical's own slot so an in-span fault (read or write — a
/// stack push is a write) runs the resident production hook's
/// `resolve_stack_fault` growth path and an unresolvable fault (past the
/// bound, below the span) kills the faulting task through the production
/// fault-exit path.
extern "C" fn mem_pin_user_fault(far: u64, write: bool) -> bool {
    resolve_user_fault_via_slot(&DISPATCH_SLOT, far, write)
}

/// The wait-queue arch adapter over the live scheduler + arch handle — the
/// chassis twin of the boot path's adapter — so `PROCWAIT_WAITQ` wakes (a
/// child's `exit` unparking the parent blocked in the production `wait`)
/// reach the live scheduler. Without it every wake is a fail-safe no-op
/// and the parent parks forever.
struct ChassisWaitArch {
    scheduler: &'static Scheduler<Aarch64BinArch>,
    arch: &'static Aarch64BinArch,
}

impl rustos_kernel_core::waitq::WaitQueueArch for ChassisWaitArch {
    fn unpark(&self, id: rustos_kernel_sched_api::TaskId) {
        // Cancellation-safe: an unpark racing the park records a
        // wake-pending token, so a wake is never lost.
        let _ = self.scheduler.unpark(id);
    }

    fn now_ns(&self) -> u64 {
        KernelArch::monotonic_ns(self.arch, SchedulerArch::current_cpu(self.arch))
    }

    fn set_wakeup(&self, deadline_ns: Option<u64>) {
        SchedulerArch::set_wakeup(self.arch, deadline_ns);
    }

    fn current_task(
        &self,
        cpu: rustos_kernel_sched_api::CpuId,
    ) -> Option<rustos_kernel_sched_api::TaskId> {
        self.scheduler.current_task(cpu)
    }

    fn current_cpu(&self) -> Option<rustos_kernel_sched_api::CpuId> {
        Some(SchedulerArch::current_cpu(self.arch))
    }
}

/// The capability set the parent runs under: `PROC_SPAWN` for its `spawn`
/// calls and `MEM_PIN` for its own pin. The parent's set doubles as the
/// inherited ceiling the production spawn intersects each child's manifest
/// request with, so the `pin` child's `MEM_PIN` request is grantable while
/// `deny` and `child` (which request nothing) genuinely hold nothing.
fn parent_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::PROC_SPAWN);
    caps.insert(CapabilityId::MEM_PIN);
    caps
}

/// The program registry the production `spawn` syscall resolves the
/// parent's child paths against: one `rxe` image, three rows, each pinning
/// its role and its policy-derived numeric parameters through the
/// registered default argument vector. Only the `pin` role requests
/// `CAP_MEM_PIN`; `deny` exists precisely because it holds nothing.
static CHILD_PROGRAMS: [EmbeddedProgram; 3] = [
    EmbeddedProgram {
        path: b"/bin/mp-deny",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"mp", b"deny"],
    },
    EmbeddedProgram {
        path: b"/bin/mp-pin",
        rxe: PROGRAM_RXE,
        caps: &[CapabilityId::MEM_PIN],
        args: &[b"mp", b"pin", &PIN_BOUND_ARG, &WITHIN_ARG, &OVER_ARG],
    },
    EmbeddedProgram {
        path: b"/bin/mp-child",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"mp", b"child", &OVER_ARG],
    },
];

/// The registry over [`CHILD_PROGRAMS`].
static PROGRAMS: ProgramRegistry = ProgramRegistry::new(&CHILD_PROGRAMS);

/// Bring the board up: FP/SIMD on, the `virt` device tree discovered
/// (timer rate, GICv2 bases), the identity-gigapage masks configured from
/// the board facts, the identity MMU + EL1 vectors enabled, the GIC
/// initialised, and the dispatch callback + user-fault resolver installed.
/// Returns the discovered generic-timer rate.
fn bring_up_board() -> u64 {
    // Enable FP/SIMD at EL1 before any code the compiler may lower to NEON
    // (the `rxe` decoder, the spawn image fills, the log formatter).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Configure the identity gigapage masks from the `virt` board facts
    // (Device GiB 0 — the MMIO window — and RAM GiB 1), exactly as the
    // production boot path derives them from discovery: the production
    // spawn producer sizes every child's identity window from these masks,
    // so driving it under the unconfigured defaults would request a window
    // reaching the user bias and the spawn would fail closed.
    let mut device_mask = [0u64; GIGAPAGE_MASK_WORDS];
    device_mask[0] = 0b01;
    configure_device_gigapages(device_mask);
    let mut ram_mask = [0u64; GIGAPAGE_MASK_WORDS];
    ram_mask[0] = 0b10;
    configure_ram_gigapages(ram_mask);

    // Enable the identity MMU + EL1 vectors before any atomic
    // read-modify-write runs: the frame allocator, the scheduler, and every
    // registry the test builds use atomics, which are UNPREDICTABLE on
    // MMU-off Device-typed memory (`plans/PI.md` P6c-2).
    let Some(boot_space) =
        ArchAddressSpace::new_identity_gigapages(&BOOT_PAGE_TABLES, IDENTITY_GIB)
    else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
    // heap, the frame pool, and the device MMIO (all within `[0, 2 GiB)` on
    // the `virt` board), so switching it does not move the ground under the
    // running code; `init_vectors` runs once on the boot CPU with a stack
    // established.
    unsafe {
        boot_space.switch();
        exceptions::init_vectors();
    }
    // The boot space's tables live in the static `BOOT_PAGE_TABLES` pool
    // and the handle carries no `Drop`, so letting it fall out of scope
    // leaves the active translation regime untouched for the kernel's
    // lifetime (the kernel never returns).
    // SAFETY: called once on the boot CPU after the GIC bases were
    // discovered above.
    unsafe {
        gic::init();
    }
    syscall_entry::set_dispatch_callback(dispatch);
    // Bind the production user-fault resolver to this vertical's slot — the
    // fault-driven growth heart this test exists to prove.
    if fault::set_user_fault_resolver(mem_pin_user_fault).is_err() {
        qemu_exit::exit_failure(FAIL_RESOLVER_INSTALL);
    }
    counter_hz
}

/// The leaked-`'static` kernel subsystems the production dispatch hook and
/// spawn context borrow — the vertical's analogue of `KernelState`, lifted
/// by one-shot `Box::leak` publishes exactly as `kernel_core::kernel_main`
/// does (a one-shot publish, not a global mutable static).
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<Aarch64BinArch>,
    arch: &'static Aarch64BinArch,
    caps: &'static RwLock<CapTable>,
    ipc: &'static RwLock<PortRegistry>,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    rng: &'static RwLock<Box<dyn RandomReserve + Send + Sync>>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems: the `kernel/mem` frame allocator over
/// the identity-mapped pool (so the spawn producer and the demand-fault
/// path draw their frames from the production path), the scheduler over
/// the production `KernelArch` wrapper, and the capability / port /
/// address-space / random / IRQ state the production hook borrows.
fn leak_subsystems(counter_hz: u64) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        qemu_exit::exit_failure(FAIL_FRAMES);
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let sched_arch = Arc::new(Aarch64BinArch::new(Aarch64Arch::new(
        &SCHED_STORAGE,
        BOOT_CPU,
        counter_hz,
    )));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), sched_arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(Aarch64BinArch::new(Aarch64Arch::new(
            &HOOK_ARCH_STORAGE,
            BOOT_CPU,
            counter_hz,
        )))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        ipc: Box::leak(Box::new(RwLock::new(PortRegistry::new()))),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        rng: Box::leak(Box::new(RwLock::new(
            Box::new(BootReserve::new()) as Box<dyn RandomReserve + Send + Sync>
        ))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `rustos_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 mem-pin test: starting");

    let counter_hz = bring_up_board();

    // The fixture `rxe`'s baked relocations must target the bias the
    // production producer maps every child at; a drifted constant would
    // admit a child whose pointers do not match its mapping (fail closed).
    if USER_BIAS != USER_IMAGE_BIAS {
        qemu_exit::exit_failure(FAIL_BIAS);
    }

    let sys = leak_subsystems(counter_hz);

    // Publish the wait-queue arch hook so parked waiters (the parent in
    // `wait`) are genuinely unparked by their wake events — the same
    // adapter the production boot path installs.
    let wait_arch: &'static ChassisWaitArch = Box::leak(Box::new(ChassisWaitArch {
        scheduler: sys.sched,
        arch: sys.arch,
    }));
    if rustos_kernel_core::waitq::install_wait_arch(wait_arch).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // The scheduler-side process-wait producer: records every parent/child
    // link the production spawn paths register and backs the production
    // `wait` syscall the parent blocks in.
    let wait_producer: &'static KernelProcessWait<Aarch64BinArch> =
        Box::leak(Box::new(KernelProcessWait::new(sys.arch)));

    // The production live-space producer: serves the `mem_map` pair (the
    // `rustos-rt` heap) and — the point of this vertical — the one-page-
    // per-fault backing the stack-growth resolver maps through it.
    let live: &'static LiveMemMap<Aarch64BinArch> = Box::leak(Box::new(LiveMemMap::new(sys.arch)));

    // Publish the production dispatch hook: every syscall the programs
    // issue — `spawn`, `wait`, `rlimit_set`, `exit` — and every user-fault
    // resolution runs the production caller-context resolution and handler
    // path.
    let hook: &'static KernelDispatchHook<'static, Aarch64BinArch> =
        Box::leak(Box::new(KernelDispatchHook::new(
            sys.sched,
            sys.caps,
            sys.arch,
            &SERIAL_SINK,
            sys.irq_table,
            &IRQ_CONTROLLER,
            sys.ipc,
            sys.aspaces,
            sys.rng,
            &UART_ONLY_CONSOLES,
            sys.frames,
            sys.frames,
            &PROGRAMS,
            &AARCH64_PROCESS_SPAWN,
            wait_producer,
            // No seat / MMIO / DMA surface in this vertical; those
            // producers stay fail-closed. No filesystem or file-map
            // producer either: the only faults this vertical exists to
            // exercise are stack growth, the `StackBytes` bound, and the
            // below-span guard.
            &NULL_SEAT_REGISTRY,
            live,
            &NULL_MMIO_MAP_FACILITY,
            &NULL_DMA_ALLOC_FACILITY,
        )));
    if DISPATCH_SLOT.install_dispatcher(hook).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // Spawn the parent role through the production runtime-spawn seam
    // (`KernelSpawnCtx` assembly inside `KernelInitSpawner`), recorded
    // against the kernel supervisor identity so this chassis can reap it.
    let init_ctx = KernelInitSpawner::new(
        sys.frames,
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.aspaces,
        sys.arch,
        wait_producer,
        sys.irq_table,
        &NULL_SHARED_MEM_FACILITY,
    );
    let Ok(parent_pid) = init_ctx.spawn_driver_process(
        &AARCH64_PROCESS_SPAWN,
        "/bin/mp-parent",
        PROGRAM_RXE,
        parent_caps(),
        &[],
        &[b"mp", b"parent", &PIN_BOUND_ARG],
        None,
    ) else {
        qemu_exit::exit_failure(FAIL_SPAWN);
    };
    note(
        TEST_SPAWNED,
        "aarch64 mem-pin test: parent spawned through the production seam",
    );

    // The budget-bounded cooperative drive: step the scheduler and poll the
    // wait producer for the parent's exit between steps. The parent runs
    // the whole deny / pin / child sequence through production spawn +
    // wait; a parent exit of 0 is the PASS, anything else names the failing
    // site through its diagnostic code.
    #[allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]
    let parent_pid = parent_pid as i32;
    let mut steps = 0u64;
    while steps < MAX_STEPS {
        let _ = sys.sched.step(BOOT_CPU);
        steps += 1;

        // Deliver any wake a handler deferred while the task ran — the same
        // between-dispatches service the production loop performs; without
        // it a child's `exit` never unparks the parent blocked in `wait`.
        let _ = rustos_kernel_core::waitq::drain_pending_wakes();

        match wait_producer.poll(SecTaskId(0), parent_pid, WaitFlags::empty()) {
            Ok(reaped) => match reaped.status {
                WaitStatus::Exited(0) => {
                    note(
                        TEST_PASS,
                        "aarch64 mem-pin test: parent verified all three children and exited 0",
                    );
                    qemu_exit::exit_success();
                }
                WaitStatus::Exited(code) => {
                    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
                    qemu_exit::exit_failure(FAIL_EXIT_BASE + (code as u16));
                }
                WaitStatus::Stopped(_) => {
                    qemu_exit::exit_failure(FAIL_PARENT_STOPPED);
                }
            },
            Err(Errno::WouldBlock) => {}
            Err(_) => qemu_exit::exit_failure(FAIL_POLL),
        }

        // A fully drained workload without a reapable parent means the
        // parent vanished down a path that never recorded its exit; fail
        // with a distinct finisher rather than spinning out the watchdog.
        if sys.sched.live_task_count() == 0 {
            qemu_exit::exit_failure(FAIL_DRAINED);
        }
    }
    qemu_exit::exit_failure(FAIL_DEADLOCK);
}
