[package]
name = "tairix-drv-input-ps2"
description = "TAIRiX i8042 PS/2 keyboard input driver (x86_64)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
tairix-abi = { path = "../../../lib/abi", version = "=0.0.0" }

[lints]
workspace = true
