//! Build-time fixture generator for the WATCHDOG.md B3 aarch64 non-maskable-FIQ
//! masked-section self-sample vertical (`plans/WATCHDOG.md`,
//! `plans/OPEN-DEFECTS.md` D13).
//!
//! Two jobs on the freestanding `aarch64-unknown-none` target (mirroring the
//! other aarch64 verticals — the shared dump helper lives in
//! `tairix_itest_harness`, so no aarch64 build script re-rolls it):
//!
//! 1. Hand the test kernel the aarch64 `virt` linker script the architecture
//!    port owns (the single per-board script).
//! 2. Dump the canonical QEMU `virt` flattened device tree and embed it, so the
//!    test discovers the GICv2 bases and the generic-timer rate from the
//!    firmware tree rather than hard-coding a board constant. QEMU's
//!    `-kernel <ELF>` aarch64 path passes no DTB pointer (`x0 = 0`), so the
//!    board tree is embedded at build time.
//!
//! On any non-aarch64 target (host `cargo build --workspace`, clippy) it emits
//! an inert empty DTB so the crate still builds; the kernel body that consumes
//! it compiles only for the freestanding aarch64 target.
//!
//! Re-running `build.rs` produces byte-identical output, so the test is
//! deterministic.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use tairix_itest_harness::pie::PieArch;

/// Rust target triple of the freestanding aarch64 build.
/// Freestanding target this vertical cross-compiles for.
const ARCH: PieArch = PieArch::Aarch64;

fn main() {
    tairix_itest_harness::emit_target_cfg();
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let manifest_dir = manifest_dir.trim_end_matches('/');

    let dtb_path = PathBuf::from(&out_dir).join("dtb_fixture.rs");

    let target = env::var("TARGET").unwrap_or_default();
    if target == ARCH.target_triple() {
        // The test kernel links with the aarch64 `virt` script the
        // architecture port owns (the single per-board script).
        let linker = format!("{manifest_dir}/../../../kernel/arch/aarch64/link/aarch64-virt.ld");
        println!("cargo:rerun-if-changed={linker}");
        println!("cargo:rustc-link-arg=-T{linker}");

        // One CPU: the masked-section self-sample is a same-CPU property.
        let out_dir_os = std::ffi::OsString::from(&out_dir);
        let dtb = tairix_itest_harness::dump_aarch64_virt_dtb(&out_dir_os, 1);
        write_dtb_fixture(&dtb_path, &dtb);
    } else {
        // Inert stub for host / other targets; the kernel body that uses this
        // compiles only for the freestanding aarch64 target.
        write_dtb_fixture(&dtb_path, &[]);
    }
}

/// Emit the embedded `virt` device tree as a Rust source the test includes.
fn write_dtb_fixture(path: &std::path::Path, dtb: &[u8]) {
    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// Canonical QEMU `virt` flattened device tree, dumped at build\n");
    out.push_str("/// time for the aarch64-none target (empty on host builds).\n");
    out.push_str("pub const DTB_BLOB: &[u8] = &[");
    for (i, b) in dtb.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        let _ = write!(out, "0x{b:02x}, ");
    }
    out.push_str("\n];\n");
    fs::write(path, out).expect("write dtb_fixture.rs");
}
