//! The freestanding riscv64 test kernel: enter U-mode with the adversarial
//! thread-pointer fixture and assert the kernel keeps its own hart identity.

use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU32, Ordering};

use tairix_abi::rxe::LoadImage;
use tairix_abi::{CapabilityId, CapabilityQuery, SyscallNumber, SYSCALL_MAX_ARGS};
use tairix_arch_riscv64::{
    handle_panic_via_serial, paging, qemu_exit, smp, syscall_entry, trap, userentry::UserMode,
    SERIAL_SINK,
};
use tairix_kalloc::{FreeListAllocator, Heap, HEAP_BYTES};
use tairix_kernel_core::{spawn_and_enter, SpawnMode, SpawnRequest};
use tairix_kernel_mem::{AddressSpace, DirectPhysMap, Frame, PhysAddr, UserStack};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// Static boot heap, in the linker's NOLOAD `.heap` section so the boot
/// trampoline neither zeroes nor counts it in the usable memory map. The spawn
/// caller allocates the startup-vector block buffer from it.
#[link_section = ".heap"]
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the allocator
/// is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// The hart this test runs on. QEMU's `virt` board hands hart 0 to the boot
/// path, and the enrolment gives the guest two CPUs so the fixture's hostile
/// low-bit `1` names a *real* sibling: a kernel that trusted the U-mode `tp`
/// would resolve CPU 1 here, not fall back safely to the boot CPU.
const BOOT_HART: u32 = 0;

/// Syscalls the fixture is expected to make before it exits: one `yield` per
/// hostile-`tp` round.
const EXPECTED_YIELDS: u32 = 2;

/// Gigabytes of identity map (kernel + the `virt` board's low MMIO + RAM).
const IDENTITY_GIGABYTES: usize = 4;

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB, matching the sibling U-mode verticals).
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at.
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program (any value).
const CANARY: u64 = 0xC0FF_EE00_D15E_A5ED;

/// Physical frames handed to the spawn builder: the program's segments, the
/// user stack, and the startup block, with headroom.
const FRAME_COUNT: usize = 320;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4290);
const TEST_FAIL: EventId = EventId(4292);

/// `SiFive` Test failure codes, distinct per failure site.
const FAIL_POOL: u16 = 1;
const FAIL_PARSE: u16 = 2;
const FAIL_SPAWN_RETURNED: u16 = 3;
const FAIL_WRONG_SYSCALL: u16 = 4;
const FAIL_HOSTILE_HART: u16 = 5;
const FAIL_TP_CLOBBERED: u16 = 6;
const FAIL_SHORT_RUN: u16 = 7;

/// Page-table pool backing the Sv39 hierarchy (lives in `.bss`).
static PAGE_TABLE_POOL: paging::PageTablePool = paging::PageTablePool::new();

/// Physical-frame backing store the spawn builder allocates user pages from.
/// `align(4096)` so each `PAGE_SIZE` slice is a valid page frame;
/// identity-mapped, so the builder reaches it through [`DirectPhysMap`].
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Set once the run has been driven so a re-entry cannot re-run it.
static TEST_DRIVEN: AtomicU32 = AtomicU32::new(0);

/// Hostile-`tp` rounds observed so far, so the exit path can insist the fixture
/// actually completed both instead of exiting early.
static YIELDS_SEEN: AtomicU32 = AtomicU32::new(0);

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared riscv64 panic bridge (parks the hart; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn tp_isolation_qemu_riscv64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A `CapabilityQuery` granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The syscall dispatch callback every `ecall` from the fixture reaches.
///
/// This is the assertion that matters: the fixture has just written a hostile
/// value into `tp`, so if the trap vector let that value survive, the kernel's
/// own per-hart identity read resolves whatever the *program* chose. Reading it
/// here — from the first kernel code the trap path calls — is therefore a direct
/// witness of the trap-entry `tp` discipline.
extern "C" fn check_hart_then_dispatch(
    number: u64,
    args_ptr: *const [u64; SYSCALL_MAX_ARGS],
) -> u64 {
    if smp::current_hartid() != BOOT_HART {
        note(
            TEST_FAIL,
            "kernel resolved a hart identity the U-mode program supplied",
        );
        qemu_exit::exit_failure(FAIL_HOSTILE_HART);
    }

    if number == u64::from(SyscallNumber::YIELD.as_u16()) {
        YIELDS_SEEN.fetch_add(1, Ordering::Relaxed);
        // Return to the fixture so it can check its own `tp` came back and run
        // the next round. There is no scheduler here: a `yield` with nothing
        // else runnable simply resumes the caller.
        return 0;
    }

    if number != u64::from(SyscallNumber::EXIT.as_u16()) {
        note(TEST_FAIL, "fixture issued an unexpected syscall");
        qemu_exit::exit_failure(FAIL_WRONG_SYSCALL);
    }

    // SAFETY: the trap vector built the `[u64; SYSCALL_MAX_ARGS]` array and
    // passes a pointer valid for this call (`syscall_entry` contract).
    let args = unsafe { *args_ptr };
    if args[0] != 0 {
        note(
            TEST_FAIL,
            "fixture reported its own thread pointer was clobbered by a trap",
        );
        qemu_exit::exit_failure(FAIL_TP_CLOBBERED);
    }
    if YIELDS_SEEN.load(Ordering::Relaxed) != EXPECTED_YIELDS {
        note(TEST_FAIL, "fixture exited before completing both rounds");
        qemu_exit::exit_failure(FAIL_SHORT_RUN);
    }
    qemu_exit::exit_success();
}

/// Hand out the next identity-mapped physical frame from [`FRAME_POOL`].
fn frame_source() -> impl FnMut() -> Option<Frame> {
    let mut next = 0usize;
    move || {
        if next >= FRAME_COUNT {
            return None;
        }
        let offset = next * paging::PAGE_SIZE;
        next += 1;
        // The pool is identity-mapped, so its kernel virtual address is also its
        // physical address.
        let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
        Some(Frame::containing(PhysAddr::new(base)))
    }
}

/// Boot entry point (called by the arch crate's boot trampoline).
#[no_mangle]
pub extern "C" fn kernel_main(_hartid: u64, _dtb: u64) -> ! {
    if TEST_DRIVEN
        .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_POOL);
    }

    note(
        TEST_START,
        "riscv64 thread-pointer isolation: building the U-mode image",
    );

    let Some(arch) =
        paging::AddressSpace::new_identity_gigapages(&PAGE_TABLE_POOL, IDENTITY_GIGABYTES)
    else {
        note(TEST_FAIL, "page-table pool exhausted (identity map)");
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc` and `sp`, so the
    // `satp` switch is sound.
    unsafe { arch.switch() };
    // SAFETY: called once on the boot hart with a stack established; only the
    // program's deliberate `ecall`s reach the vector (no interrupt source is
    // armed).
    unsafe { trap::init_traps() };
    syscall_entry::set_dispatch_callback(check_hart_then_dispatch);

    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        note(TEST_FAIL, "fixture rxe image failed to parse");
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    let mut space = AddressSpace::new(arch);
    let physmap = DirectPhysMap::identity(u64::from(u32::MAX) + 1); // 4 GiB
    let request = SpawnRequest {
        image: &image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"tp-probe"],
        env: &[],
        canary: CANARY,
    };

    note(TEST_START, "dropping into the adversarial fixture");

    // SAFETY: `space` is the active address space (we `switch`ed to it above)
    // and the trap vector is installed, so the program's `ecall`s are handled.
    // `spawn_and_enter` checks `CAP_PROC_SPAWN`, builds the image into `space`,
    // and `enter_user`s into it; on the authorised path it diverges.
    let outcome = unsafe {
        spawn_and_enter(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &UserMode::new(),
            &mut space,
            &physmap,
            &request,
            frame_source(),
        )
    };

    match outcome {
        Err(_) => {
            note(TEST_FAIL, "spawn_and_enter returned instead of entering");
            qemu_exit::exit_failure(FAIL_SPAWN_RETURNED);
        }
        Ok(never) => match never {},
    }
}
