//! The freestanding riscv64 test kernel: build a U-mode image for the C
//! program and drop into it through the production spawn caller, servicing the
//! syscalls it issues.

use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU32, Ordering};

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery, SyscallNumber, SYSCALL_MAX_ARGS};
use rustos_arch_riscv64::{
    handle_panic_via_serial, paging, qemu_exit, syscall_entry, trap, userentry::UserMode,
    SERIAL_SINK,
};
use rustos_kalloc::{FreeListAllocator, Heap, HEAP_BYTES};
use rustos_kernel_core::{spawn_and_enter, SpawnRequest};
use rustos_kernel_mem::{AddressSpace, DirectPhysMap, Frame, PhysAddr, UserStack};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;
use rustos_log::{log, Event, EventId, Level};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// Static boot heap, in the linker's NOLOAD `.heap` section so the boot
/// trampoline neither zeroes nor counts it in the usable memory map. The
/// spawn caller allocates the startup-vector block buffer from it.
#[link_section = ".heap"]
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// Exit code the C program returns when every abi-v1 check and both syscall
/// round-trips pass (`csrc/main.c` `EXIT_OK`).
const EXPECTED_EXIT: u64 = 99;
/// Capability id the program queries (`csrc/main.c` `PROBE_CAP`, which names
/// `ROS_CAP_DRV_KERNEL`); the callback asserts the marshalled argument equals
/// it. Derived from the same `lib/abi` source of truth, never a bare literal.
const PROBE_CAP: u64 = CapabilityId::DRV_KERNEL.as_u16() as u64;
/// Sentinel `clock_get` returns to the program (`csrc/main.c`
/// `CLOCK_SENTINEL`), exercising full 64-bit result marshalling.
const CLOCK_SENTINEL: u64 = 0x0123_4567_89ab_cdef;

/// Gigabytes of identity map (kernel + the `virt` board's low MMIO + RAM).
const IDENTITY_GIGABYTES: usize = 4;

/// User stack base (1 MiB into the high user region) and size. crt0 carves a
/// 1 MiB scratch span off the stack, so the stack must comfortably exceed it.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB > crt0's 1 MiB scratch + call frames).
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up, well
/// clear of the program image and the stack).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program (any value).
const CANARY: u64 = 0xC0FF_EE00_D15E_A5ED;

/// Number of physical frames the test hands the spawn builder: the program's
/// segments, the user stack, and the startup block. Sized with headroom.
const FRAME_COUNT: usize = 320;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4250);
const TEST_FAIL: EventId = EventId(4252);

/// `SiFive` Test failure codes, distinct per failure site.
const FAIL_POOL: u16 = 1;
const FAIL_PARSE: u16 = 2;
const FAIL_SPAWN_RETURNED: u16 = 3;
const FAIL_WRONG_SYSCALL: u16 = 4;
const FAIL_WRONG_CODE: u16 = 5;
const FAIL_WRONG_CAP: u16 = 6;

/// Page-table pool backing the Sv39 hierarchy (lives in `.bss`).
static PAGE_TABLE_POOL: paging::PageTablePool = paging::PageTablePool::new();

/// Physical-frame backing store the spawn builder allocates user pages from.
/// `align(4096)` so each `FRAME_SIZE` slice is a valid page frame; identity-
/// mapped (its physical address equals its kernel virtual address), so the
/// builder reaches it through [`DirectPhysMap::identity`].
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Set once the round-trip has been driven so a re-entry cannot re-run it.
static TEST_DRIVEN: AtomicU32 = AtomicU32::new(0);

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared riscv64 panic bridge (parks the hart; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn c_program_qemu_riscv64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A `CapabilityQuery` granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires (`AGENTS.md` §5.4).
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The syscall dispatch callback the C program's traps reach.
///
/// Services the two round-trip syscalls (`cap_query` → "held", `clock_get` →
/// the 64-bit sentinel) and, on `exit`, asserts the program computed
/// [`EXPECTED_EXIT`] before writing the PASS finisher. Any unexpected syscall,
/// a wrong `cap_query` argument, or a wrong exit code writes a distinct failure
/// finisher. The `cap_query` / `clock_get` arms return the answer to user
/// mode; the `exit` and failure arms never return.
extern "C" fn dispatch_and_finish(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the trap vector built the `[u64; SYSCALL_MAX_ARGS]` array and
    // passes a pointer valid for this call (`syscall_entry` contract).
    let args = unsafe { *args_ptr };

    if number == u64::from(SyscallNumber::CAP_QUERY.as_u16()) {
        if args[0] != PROBE_CAP {
            note(TEST_FAIL, "cap_query marshalled the wrong capability id");
            qemu_exit::exit_failure(FAIL_WRONG_CAP);
        }
        // Report the capability as held (the C program checks for `1`).
        return 1;
    }

    if number == u64::from(SyscallNumber::CLOCK_GET.as_u16()) {
        return CLOCK_SENTINEL;
    }

    if number == u64::from(SyscallNumber::EXIT.as_u16()) {
        if args[0] != EXPECTED_EXIT {
            note(TEST_FAIL, "C program exited with the wrong code");
            qemu_exit::exit_failure(FAIL_WRONG_CODE);
        }
        qemu_exit::exit_success();
    }

    note(TEST_FAIL, "C program issued an unexpected syscall");
    qemu_exit::exit_failure(FAIL_WRONG_SYSCALL);
}

/// Hand out the next identity-mapped physical frame from [`FRAME_POOL`].
fn frame_source() -> impl FnMut() -> Option<Frame> {
    let mut next = 0usize;
    move || {
        if next >= FRAME_COUNT {
            return None;
        }
        let offset = next * paging::PAGE_SIZE;
        next += 1;
        // The pool is identity-mapped, so its kernel virtual address is also
        // its physical address.
        let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
        Some(Frame::containing(PhysAddr::new(base)))
    }
}

/// Boot entry point (called by the arch crate's boot trampoline).
#[no_mangle]
pub extern "C" fn kernel_main(_hartid: u64, _dtb: u64) -> ! {
    if TEST_DRIVEN
        .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_POOL);
    }

    note(
        TEST_START,
        "riscv64 C-program round-trip: building the U-mode image",
    );

    // 1. Sv39 address space identity-mapping the kernel + MMIO, then activate it
    //    and install the trap vector before any user mapping is added.
    let Some(arch) =
        paging::AddressSpace::new_identity_gigapages(&PAGE_TABLE_POOL, IDENTITY_GIGABYTES)
    else {
        note(TEST_FAIL, "page-table pool exhausted (identity map)");
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc` and `sp`, so the
    // `satp` switch is sound.
    unsafe { arch.switch() };
    // SAFETY: called once on the boot hart with a stack established; only the
    // program's deliberate `ecall`s reach the vector (no interrupt source is
    // armed).
    unsafe { trap::init_traps() };
    syscall_entry::set_dispatch_callback(dispatch_and_finish);

    // 2. Parse the build-time `rxe` blob against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        note(TEST_FAIL, "C program rxe image failed to parse");
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    // 3. Build the U-mode image into the (active) address space and enter it
    //    through the production capability-checked, audited spawn caller.
    // The arch `paging::AddressSpace` implements the Arch HAL page-table
    // surface (`mmu::AddressSpace` + `tlb::TlbShootdown`) directly, so the
    // `kernel/mem` façade drives it with no per-test adapter (`AGENTS.md`
    // §2.2; the Stage W5b-2 wiring removed the old `PageTableOps` shim).
    let mut space = AddressSpace::new(arch);
    let physmap = DirectPhysMap::identity(u64::from(u32::MAX) + 1); // 4 GiB
    let request = SpawnRequest {
        image: &image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"prog"],
        env: &[],
        canary: CANARY,
    };

    note(TEST_START, "dropping into the spawned C program");

    // SAFETY: `space` is the active address space (we `switch`ed to it above)
    // and the trap vector is installed, so the new program's `ecall`s are
    // handled. `spawn_and_enter` checks `CAP_PROC_SPAWN`, builds the image into
    // `space`, and `enter_user`s into it; on the authorised path it diverges.
    let outcome = unsafe {
        spawn_and_enter(
            &SpawnAuthority,
            &SERIAL_SINK,
            &UserMode::new(),
            &mut space,
            &physmap,
            &request,
            frame_source(),
        )
    };

    // `spawn_and_enter` only returns on a denial or a build failure; the
    // authorised, well-formed path diverges into U-mode. Reaching here is a
    // closed failure.
    match outcome {
        Err(_) => {
            note(TEST_FAIL, "spawn_and_enter returned instead of entering");
            qemu_exit::exit_failure(FAIL_SPAWN_RETURNED);
        }
        Ok(never) => match never {},
    }
}
