//! The kernel's on-disk application store handle (`plans/APPS.md`
//! deliverable 8).
//!
//! One `'static` [`AppStore`] carries the build's embedded application
//! trust anchor and the readiness latch the boot path resolves once the
//! read-only `/System` mount reaches a terminal state. A boot path with a
//! storage floor installs it into the syscall layer
//! (`KernelDispatchHook::with_app_store`) so the `spawn` syscall can
//! resolve a `…/<Name>.app/Run` path as a verified on-disk bundle; the
//! `/System` mount install (`crate::system_mount`) resolves the latch on
//! every outcome, and the storage bring-up failure paths resolve it
//! *unavailable* so a parked spawn always wakes and fails closed rather
//! than waiting forever.

use tairix_kernel_core::AppStore;

// `SYSTEM_APP_SIGNER_PUBKEY: [u8; 32]`, generated by `build.rs` from the
// dedicated `SYSTEM_APP_SIGNING_SEED` — a trust domain distinct from the
// driver-signing anchor.
include!(concat!(env!("OUT_DIR"), "/app_trust.rs"));

/// The single application store every boot path shares: pending until the
/// `/System` mount install resolves it, trusting exactly the build's
/// app-signing key.
pub static APP_STORE: AppStore = AppStore::pending(SYSTEM_APP_SIGNER_PUBKEY);

#[cfg(test)]
mod tests {
    use super::SYSTEM_APP_SIGNER_PUBKEY;
    use crate::driver_catalog::KERNEL_DRIVER_SIGNER_PUBKEY;

    /// The application and driver trust anchors are distinct trust
    /// domains: an authority to sign an app bundle must never also be an
    /// authority to sign a driver. Equal keys would collapse the two
    /// gates into one.
    #[test]
    fn app_and_driver_trust_anchors_are_distinct() {
        assert_ne!(SYSTEM_APP_SIGNER_PUBKEY, KERNEL_DRIVER_SIGNER_PUBKEY);
    }
}
