//! Shared user-space layout constants for the PID 1 (`init`) spawn seam
//! and the runtime `spawn` producer.
//!
//! Every architecture port lays its first user program — and every child
//! the `spawn` syscall builds — out at the *same* offsets above the
//! build-time image bias, with the *same* stack/MMIO-window sizing and the
//! *same* canary seeds. Those values are equal across the ports by
//! definition (they describe one user-space layout, not a per-architecture
//! register layout), so they live here once rather than being copy-pasted
//! into each `init_spawn` / `spawn_producer` sibling.
//!
//! The image bias lives here too, as the generated [`CHILD_USER_BIAS`]:
//! one workspace relocation bias covers every embedded *and* on-disk `Run`
//! rxe, so each port derives its absolute bases as
//! `CHILD_USER_BIAS + <offset>` and the per-fixture `*_USER_BIAS` values
//! are compile-time-pinned to it.
//!
//! This module is also the single home for the data that is equal across
//! every port *by definition*: the registry of embedded
//! programs the runtime `spawn` syscall resolves (their absolute paths,
//! manifest∩user capability sets, and startup-argument vectors), the
//! `CAP_PROC_SPAWN` [`SpawnAuthority`] every spawn seam authorises under,
//! and PID 1 `init`'s own grant and argument vector. The per-port
//! `ProcessSpawn` / `InitSpawn` implementations (the architecture paging
//! glue) are the deliberate trait carve-out and stay beside each port;
//! the values they *consume* live here once.

use tairix_abi::{CapabilityId, CapabilityQuery, LoadImage};
use tairix_caps::CapabilitySet;
#[cfg(not(all(freestanding, kernel_isa = "aarch64")))]
use tairix_kernel_core::EmbeddedProgram;
use tairix_kernel_core::{ProgramRegistry, StackSpan};
use tairix_kernel_mem::{derive_user_layout, UserLayout};

use crate::program_manifests::INIT_MANIFEST;
#[cfg(not(all(freestanding, kernel_isa = "aarch64")))]
use crate::program_manifests::{
    CAT_MANIFEST, CLEAR_MANIFEST, DEVMGR_MANIFEST, LOGIN_MANIFEST, LS_MANIFEST, MAN_MANIFEST,
    NETSTACK_MANIFEST, PS_MANIFEST, RESET_MANIFEST, SEATMGR_MANIFEST, SHELL_MANIFEST,
    STRESS_MANIFEST, SYSINFOD_MANIFEST, SYSINFO_MANIFEST, SYSMON_MANIFEST, TOP_MANIFEST,
    USERS_TOOL_MANIFEST,
};

// `CHILD_USER_BIAS: u64`, generated by `build.rs` from the one workspace
// relocation bias every embedded and on-disk `Run` rxe is baked for, so it
// survives on the aarch64 production build, which embeds no program rows.
include!(concat!(env!("OUT_DIR"), "/user_bias.rs"));

// The embedded program fixtures exist only where the registry below
// carries rows: the aarch64 production boot spawns every command app and
// service from its verified on-disk `/System` store bundle (`plans/APPS.md`
// deliverable 8), so it embeds none of them (`build.rs` skips their
// builds), while x86_64/riscv64 keep them as their explicitly-justified
// boot floor until their storage floors land.
#[cfg(not(all(freestanding, kernel_isa = "aarch64")))]
mod program_rxes {
    // `SHELL_RXE: &[u8]` and `SHELL_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/shell_rxe.rs"));
    // `LOGIN_RXE: &[u8]` and `LOGIN_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/login_rxe.rs"));
    // `DEVMGR_RXE: &[u8]` and `DEVMGR_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/devmgr_rxe.rs"));
    // `SYSINFOD_RXE: &[u8]` and `SYSINFOD_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/sysinfod_rxe.rs"));
    // `SEATMGR_RXE: &[u8]` and `SEATMGR_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/seatmgr_rxe.rs"));
    // `NETSTACK_RXE: &[u8]` and `NETSTACK_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/netstack_rxe.rs"));
    // `PS_RXE: &[u8]` and `PS_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/ps_rxe.rs"));
    // `SYSINFO_RXE: &[u8]` and `SYSINFO_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/sysinfo_rxe.rs"));
    // `SYSMON_RXE: &[u8]` and `SYSMON_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/sysmon_rxe.rs"));
    // `STRESS_RXE: &[u8]` and `STRESS_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/stress_rxe.rs"));
    // `TOP_RXE: &[u8]` and `TOP_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/top_rxe.rs"));
    // `LS_RXE: &[u8]` and `LS_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/ls_rxe.rs"));
    // `CAT_RXE: &[u8]` and `CAT_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/cat_rxe.rs"));
    // `MAN_RXE: &[u8]` and `MAN_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/man_rxe.rs"));
    // `CLEAR_RXE: &[u8]` and `CLEAR_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/clear_rxe.rs"));
    // `RESET_RXE: &[u8]` and `RESET_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/reset_rxe.rs"));
    // `USERS_CLI_RXE: &[u8]` and `USERS_CLI_USER_BIAS: u64`, generated by `build.rs`.
    include!(concat!(env!("OUT_DIR"), "/users_cli_rxe.rs"));

    // Every embedded program is relocated for the one shared user bias
    // ([`super::CHILD_USER_BIAS`]); every port maps each child at that
    // bias, so a fixture baked for a different bias is a build defect
    // caught at compile time rather than a child whose pointers do not
    // match where it is mapped.
    const _: () = assert!(SHELL_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(LOGIN_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(DEVMGR_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(SYSINFOD_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(SEATMGR_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(NETSTACK_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(PS_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(SYSINFO_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(SYSMON_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(STRESS_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(TOP_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(LS_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(CAT_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(MAN_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(CLEAR_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(RESET_USER_BIAS == super::CHILD_USER_BIAS);
    const _: () = assert!(USERS_CLI_USER_BIAS == super::CHILD_USER_BIAS);
}

#[cfg(not(all(freestanding, kernel_isa = "aarch64")))]
use program_rxes::{
    CAT_RXE, CLEAR_RXE, DEVMGR_RXE, LOGIN_RXE, LS_RXE, MAN_RXE, NETSTACK_RXE, PS_RXE, RESET_RXE,
    SEATMGR_RXE, SHELL_RXE, STRESS_RXE, SYSINFOD_RXE, SYSINFO_RXE, SYSMON_RXE, TOP_RXE,
    USERS_CLI_RXE,
};

// The registered program paths live in `spawn_paths` (pure data, so its
// store-spelling drift test runs on the CI host); this module binds each
// path to its baked rxe, manifest, and argument vector. On the aarch64
// production build the rows are gone and the `spawn` syscall derives a
// bundle path's meaning from the path itself, so no path constants remain.
#[cfg(not(all(freestanding, kernel_isa = "aarch64")))]
pub use crate::spawn_paths::{
    CAT_PATH, CLEAR_PATH, DEVMGR_PATH, LOGIN_PATH, LS_PATH, MAN_PATH, NETSTACK_PATH, PS_PATH,
    RESET_PATH, SEATMGR_PATH, SHELL_PATH, STRESS_PATH, SYSINFOD_PATH, SYSINFO_PATH, SYSMON_PATH,
    TOP_PATH, USERS_CLI_PATH,
};

/// The embedded programs the runtime `spawn` syscall can resolve, each
/// carrying the capability set its manifest requests and its
/// startup-argument vector: the login service PID
/// 1 launches as the per-console session supervisor (`plans/PI.md` P11), and
/// the `Shell` session program login spawns as an authenticated user's shell
/// of choice (`plans/SPAWN.md` `SP3b`). The `rxe`s are baked at build time
/// (`build.rs`).
///
/// Each row's request is the shared, pinned manifest list from
/// [`crate::program_manifests`] (`plans/CAPABILITY_USE.md` CU2): the shell
/// requests the session baseline; login is the one privileged
/// spawn-as-user holder; each service and tool requests exactly what it
/// exercises. The rationale for every list lives on the manifest constant
/// it names.
///
/// These rows are the x86_64/riscv64 boot floor: on the aarch64 production
/// build the registry below is empty and every one of these programs is
/// spawned from its verified on-disk `/System` store bundle instead
/// (`plans/APPS.md` deliverable 8).
#[cfg(not(all(freestanding, kernel_isa = "aarch64")))]
pub static SPAWN_PROGRAMS: [EmbeddedProgram; 17] = [
    EmbeddedProgram {
        path: SHELL_PATH,
        rxe: SHELL_RXE,
        caps: SHELL_MANIFEST,
        args: &[b"shell"],
    },
    EmbeddedProgram {
        path: LOGIN_PATH,
        rxe: LOGIN_RXE,
        caps: LOGIN_MANIFEST,
        args: &[b"login"],
    },
    EmbeddedProgram {
        path: DEVMGR_PATH,
        rxe: DEVMGR_RXE,
        caps: DEVMGR_MANIFEST,
        args: &[b"devmgr"],
    },
    EmbeddedProgram {
        path: SYSINFOD_PATH,
        rxe: SYSINFOD_RXE,
        caps: SYSINFOD_MANIFEST,
        args: &[b"sysinfod"],
    },
    EmbeddedProgram {
        path: SEATMGR_PATH,
        rxe: SEATMGR_RXE,
        caps: SEATMGR_MANIFEST,
        args: &[b"seatmgr"],
    },
    EmbeddedProgram {
        path: NETSTACK_PATH,
        rxe: NETSTACK_RXE,
        caps: NETSTACK_MANIFEST,
        args: &[b"netstack"],
    },
    EmbeddedProgram {
        path: PS_PATH,
        rxe: PS_RXE,
        caps: PS_MANIFEST,
        args: &[b"ps"],
    },
    EmbeddedProgram {
        path: SYSINFO_PATH,
        rxe: SYSINFO_RXE,
        caps: SYSINFO_MANIFEST,
        args: &[b"sysinfo"],
    },
    EmbeddedProgram {
        path: SYSMON_PATH,
        rxe: SYSMON_RXE,
        caps: SYSMON_MANIFEST,
        args: &[b"sysmon"],
    },
    EmbeddedProgram {
        path: STRESS_PATH,
        rxe: STRESS_RXE,
        caps: STRESS_MANIFEST,
        args: &[b"stress"],
    },
    EmbeddedProgram {
        path: TOP_PATH,
        rxe: TOP_RXE,
        caps: TOP_MANIFEST,
        args: &[b"top"],
    },
    EmbeddedProgram {
        path: LS_PATH,
        rxe: LS_RXE,
        caps: LS_MANIFEST,
        args: &[b"ls"],
    },
    EmbeddedProgram {
        path: CAT_PATH,
        rxe: CAT_RXE,
        caps: CAT_MANIFEST,
        args: &[b"cat"],
    },
    EmbeddedProgram {
        path: MAN_PATH,
        rxe: MAN_RXE,
        caps: MAN_MANIFEST,
        args: &[b"man"],
    },
    EmbeddedProgram {
        path: CLEAR_PATH,
        rxe: CLEAR_RXE,
        caps: CLEAR_MANIFEST,
        args: &[b"clear"],
    },
    EmbeddedProgram {
        path: RESET_PATH,
        rxe: RESET_RXE,
        caps: RESET_MANIFEST,
        args: &[b"reset"],
    },
    EmbeddedProgram {
        path: USERS_CLI_PATH,
        rxe: USERS_CLI_RXE,
        caps: USERS_TOOL_MANIFEST,
        args: &[b"users"],
    },
];

/// The `'static` embedded-program registry every port's boot path installs
/// through `BootInfo::with_spawn`. One shared registry over the shared
/// [`SPAWN_PROGRAMS`].
#[cfg(not(all(freestanding, kernel_isa = "aarch64")))]
pub static PROGRAM_REGISTRY: ProgramRegistry = ProgramRegistry::new(&SPAWN_PROGRAMS);

/// The aarch64 production boot embeds no program rows: every command app
/// and service ships as a complete, signed on-disk bundle the `spawn`
/// syscall verifies through the shared load gate, so the registry is
/// empty and only the disk path can resolve a program (`plans/APPS.md`
/// deliverable 8). PID 1 `init` stays compiled in — it is entered by the
/// boot path before any volume is mounted, never spawned through the
/// registry.
#[cfg(all(freestanding, kernel_isa = "aarch64"))]
pub static PROGRAM_REGISTRY: ProgramRegistry = ProgramRegistry::EMPTY;

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege
/// the spawn callers (`spawn_image` for a runtime child, `spawn_and_enter`
/// for PID 1) require to authorise building a child image. It does not widen the child's authority, which is its registered
/// program's declared set intersected with its user's grants. Shared by every port's `spawn_producer` and `init_spawn` seam
/// rather than redefined in each.
pub struct SpawnAuthority;

impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// PID 1 `init`'s startup-argument vector. Shared across the ports.
pub const INIT_ARGS: &[&[u8]] = &[b"init"];

/// PID 1 `init`'s effective capability set, built from the shared, pinned
/// [`crate::program_manifests::INIT_MANIFEST`] (`plans/PI.md` P6a/P6b,
/// `plans/SPAWN.md` `SP3b`). The boot path passes this as both the user
/// grant and the manifest request, so the intersection the kernel derives
/// is the same set — `init` is granted no more. Spawning is not ambient
/// authority: the child PID 1 launches receives only *its own*
/// manifest∩user-grant set, never `init`'s. The set
/// is identical across the ports, so it is built here once.
pub fn init_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    for cap in INIT_MANIFEST {
        caps.insert(*cap);
    }
    caps
}

/// Reserved user stack span in pages (8 MiB — 2048 pages). The span is
/// the structural bound the stack may ever occupy: its bottom guard page
/// is what a runaway stack faults on, and the demand-grown stack path
/// (`plans/SPAWN.md` SP11) backs pages inside it on fault, bounded by the
/// task's settable stack resource limit. Derived from the one default
/// stack policy value ([`tairix_kernel_core::DEFAULT_STACK_LIMIT_BYTES`],
/// which `LimitSet::DEFAULT` carries as the `StackBytes` bound), so the
/// settable default and the structural span can never silently diverge.
pub const USER_STACK_RESERVE_PAGES: u64 =
    tairix_kernel_core::DEFAULT_STACK_LIMIT_BYTES / tairix_kernel_mem::PAGE_SIZE as u64;

// The default stack policy must be a whole number of pages, or the span
// derivation above would silently round it down.
const _: () = assert!(
    tairix_kernel_core::DEFAULT_STACK_LIMIT_BYTES % tairix_kernel_mem::PAGE_SIZE as u64 == 0
);

/// Eagerly committed user stack pages at the top of the reserved span
/// (128 KiB — 32 pages): enough that a program's startup (`tairix-rt`
/// `_start` → startup-vector validation → `main`'s first frames) never
/// takes a growth fault, while the uncommitted remainder of the span is
/// backed on demand by the fault-driven growth path — so a process pays
/// only the stack it actually touches (RAM sized to the working set, not
/// to the span).
pub const USER_STACK_COMMIT_PAGES: u64 = 32;

// The committed top must fit inside the reserved span; a policy that
// violates this would refuse every spawn (the derivation fails closed),
// so it is rejected at compile time instead.
const _: () = assert!(USER_STACK_COMMIT_PAGES <= USER_STACK_RESERVE_PAGES);

/// Derive the stack and startup-vector-block placement for one spawned
/// image (the [`tairix_kernel_mem::derive_user_layout`] mechanism bound
/// to this workspace's layout policy): a [`USER_STACK_RESERVE_PAGES`]
/// stack span with its top [`USER_STACK_COMMIT_PAGES`] eagerly mapped,
/// with the device window at [`MMIO_WINDOW_OFFSET`] as the ceiling the
/// layout must stay below.
///
/// The placement scales with the image instead of capping it at a fixed
/// slot — the former fixed 1 MiB stack offset silently collided with any
/// program whose mapped image outgrew it (the desktop session's `Run`
/// was refused at spawn the moment its BSS crossed the boundary), the
/// capacity-ceiling defect this derivation replaces. Every port consumes
/// this one definition, so the layout policy cannot diverge per
/// architecture.
///
/// Fails closed with `None` — the caller refuses the spawn — when the
/// layout cannot fit below the device window or an address computation
/// overflows.
#[must_use]
pub fn user_layout(image: &LoadImage, bias: u64) -> Option<UserLayout> {
    let ceiling = bias.checked_add(MMIO_WINDOW_OFFSET)?;
    derive_user_layout(
        image,
        bias,
        USER_STACK_RESERVE_PAGES,
        USER_STACK_COMMIT_PAGES,
        ceiling,
    )
}

/// The stack span the admission path records for one spawned process,
/// derived from `layout`: the reserved span's lowest page, the committed
/// bottom, and the span top [`USER_STACK_COMMIT_PAGES`] above that bottom
/// (one guard page below the startup block). Every port passes this one
/// derivation to `admit_process`/`admit_init`, so the recorded span and
/// the mapped layout can never diverge per architecture.
///
/// Fails closed with `None` when the span arithmetic overflows or the
/// bounds are malformed — the caller refuses the spawn, exactly as for a
/// [`user_layout`] refusal.
#[must_use]
pub fn stack_span(layout: &UserLayout) -> Option<StackSpan> {
    let commit_bytes = USER_STACK_COMMIT_PAGES.checked_mul(tairix_kernel_mem::PAGE_SIZE as u64)?;
    let top = layout.stack_base.checked_add(commit_bytes)?;
    StackSpan::new(layout.stack_reserve_base, layout.stack_base, top)
}

/// Offset of the device-window virtual region above the image bias
/// (`plans/PI.md` 5d-0-ii (b′)): placed 1 GiB above the image bias — far
/// clear of the program image, stack, and startup block, and the lowest of
/// the four guarded windows.
///
/// Every port retains a live address space and grants its tasks an
/// `mmio_map` device window out of this region, so the offset — shared by
/// each port's `init_spawn` and `spawn_producer` — is
/// one value, not a per-port copy.
pub const MMIO_WINDOW_OFFSET: u64 = 0x4000_0000;

/// Pages backing the device-window region: the window's full reserved
/// virtual span (1 GiB, up to the DMA window above it). The span is the
/// structural bound; the per-task window map's bookkeeping grows lazily
/// with actual use, so a task mapping a few register blocks pays bytes
/// while a display service can map a whole multi-megabyte scan-out
/// surface out of the same window.
pub const MMIO_WINDOW_PAGES: usize =
    ((DMA_WINDOW_OFFSET - MMIO_WINDOW_OFFSET) / tairix_kernel_mem::PAGE_SIZE as u64) as usize;

/// Offset of the guarded DMA-buffer virtual window above the image bias
/// (`plans/PI.md` 5d-0-ii (c) DMA half): placed 2 GiB above the bias — above
/// the device window (1 GiB up) and far clear of the program image, stack,
/// and startup block. The `dma_alloc` carve hands each request a
/// guard-bracketed buffer out of `[bias + DMA_WINDOW_OFFSET, … +
/// DMA_WINDOW_PAGES·4 KiB)`. One value shared by every port for the same
/// reason as [`MMIO_WINDOW_OFFSET`].
pub const DMA_WINDOW_OFFSET: u64 = 0x8000_0000;

/// Pages backing the DMA-buffer window: the window's full reserved
/// virtual span (1 GiB, up to the shared-memory window above it), like
/// [`MMIO_WINDOW_PAGES`]. The span is the structural bound; the window
/// map's slot bookkeeping grows lazily with the peak concurrent carve,
/// so a driver serving two coherent buffers pays a few bytes while a
/// USB host-controller driver serving a multi-drive enclosure — one
/// demand-allocated ring/buffer region per attached device — carves
/// tens of regions out of the same window. The former fixed 256-page
/// (1 MiB) ceiling was a capacity defect: it held ~7 of the ~68 KiB
/// per-device USB regions, so a 13-device enclosure exhausted it
/// mid-walk and the whole port was skipped.
pub const DMA_WINDOW_PAGES: usize =
    ((SHARED_WINDOW_OFFSET - DMA_WINDOW_OFFSET) / tairix_kernel_mem::PAGE_SIZE as u64) as usize;

/// Offset of the cross-process shared-memory virtual window above the image
/// bias: placed 3 GiB above the bias — above the DMA window (which spans
/// `[2 GiB, 3 GiB)`) and far clear of the program image, stack,
/// startup block, and the device and DMA windows below it. The
/// `shm_create` / `shm_map` syscalls map a granted shared region out of
/// `[bias + SHARED_WINDOW_OFFSET, ... + SHARED_WINDOW_PAGES * 4 KiB)`. One
/// value shared by every port for the same reason as [`MMIO_WINDOW_OFFSET`].
pub const SHARED_WINDOW_OFFSET: u64 = 0xC000_0000;

/// Pages backing the shared-memory window: the window's full reserved
/// virtual span (1 GiB, up to the anonymous-heap window above it). Like
/// [`MMIO_WINDOW_PAGES`] the span is the structural bound and the window
/// map grows its bookkeeping lazily, so a granted full-screen frame
/// region maps out of the same window a small URB buffer does.
pub const SHARED_WINDOW_PAGES: usize =
    ((ANON_WINDOW_OFFSET - SHARED_WINDOW_OFFSET) / tairix_kernel_mem::PAGE_SIZE as u64) as usize;

/// Offset of the non-`FIXED` anonymous-heap virtual window above the image
/// bias (`plans/PI.md` 5d-0-ii (c)): placed 4 GiB above the bias — the
/// **topmost** of the four guarded windows, above the device (1 GiB), DMA
/// (2 GiB), and shared-memory (3 GiB) windows and far clear of the program
/// image, stack, and startup block. It is highest so it can extend upward
/// toward the per-architecture user-VA ceiling without colliding with a
/// fixed-size sibling — the room that lets the heap window scale with
/// discovered RAM and the demand-paged file-mapping window take every
/// remaining page above the heap window's top (the
/// [`crate::user_windows::user_windows`] split). The `mem_map` placement
/// allocator hands each non-`FIXED` request a base out of
/// `[bias + ANON_WINDOW_OFFSET, … + anon_pages·4 KiB)`, and `file_map`
/// reservations land in the window from there up to the user-VA ceiling.
/// One value shared by every port for the same reason as
/// [`MMIO_WINDOW_OFFSET`].
pub const ANON_WINDOW_OFFSET: u64 = 0x1_0000_0000;

/// Per-process stack-canary seed handed to PID 1 `init`. Any value; the kernel RNG-seeded canary is a later stage.
pub const INIT_CANARY: u64 = 0x1117_A5ED_C0DE_0001;

/// Per-process stack-canary seed handed to a spawned child. Any value; the kernel RNG-seeded canary is a later stage.
pub const CHILD_CANARY: u64 = 0x1117_A5ED_C0DE_5E55;
