//! The freestanding aarch64 test kernel: spawn the driver-stub program
//! through the production parameterised spawn path and complete the
//! Stage 4.HW register handshake over production IPC (`PLAN.md` Stage 4.HW).

use core::panic::PanicInfo;

use alloc::boxed::Box;
use alloc::sync::Arc;

use rustos_abi::{CapabilityId, DescriptorTable, DriverRegisterReply, SYSCALL_MAX_ARGS};
use rustos_arch_aarch64::kernel_arch::timer_frequency_hz;
use rustos_arch_aarch64::paging::{
    configure_device_gigapages, configure_ram_gigapages, AddressSpace as ArchAddressSpace,
    PageTablePool, GIGAPAGE_MASK_WORDS,
};
use rustos_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, Aarch64Arch,
    Aarch64ArchStorage, SERIAL_SINK,
};
use rustos_arch_api::CpuId;
use rustos_bumpalloc::BumpAllocator;
use rustos_caps::CapabilitySet;
use rustos_fdt::Fdt;
use rustos_kernel::aarch64::arch_wrapper::{Aarch64BinArch, UART_ONLY_CONSOLES};
use rustos_kernel::aarch64::spawn_producer::{AARCH64_PROCESS_SPAWN, USER_IMAGE_BIAS};
use rustos_kernel::dispatch_core::{dispatch_via_slot, read_raw_args};
use rustos_kernel_core::AddressSpaceRegistry;
use rustos_kernel_core::{
    BootReserve, DispatchCallbackSlot, EmbeddedProgram, KernelDispatchHook, KernelSpawnCtx,
    ProgramRegistry, RandomReserve, NULL_DMA_ALLOC_FACILITY, NULL_INPUT_FOCUS, NULL_MEM_MAP,
    NULL_MMIO_MAP_FACILITY, NULL_PROCESS_WAIT,
};
use rustos_kernel_ipc::{EndpointId, Port, PortRegistry};
use rustos_kernel_irq::{IrqTable, UnsupportedController};
use rustos_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use rustos_kernel_sched_eevdf::{Scheduler, SchedulerConfig};
use rustos_kernel_sec::{CapTable, TaskCapabilities, TaskId as SecTaskId, UserId};
use rustos_log::{log, Event, EventId, Level};
use rustos_sync::RwLock;

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// The single-core slice runs logical CPU 0 on the boot core.
const BOOT_CPU: CpuId = 0;

/// Gigabytes of identity map the boot address space provides: `[0, 2 GiB)`
/// covers the `virt` board's device MMIO (GiB 0) and the RAM base at GiB 1
/// where this kernel, its heap, and the frame pool live.
const IDENTITY_GIB: usize = 2;

/// Registry path the verified driver-stub `rxe` payload is resolved under —
/// the `/System/Drivers/` home of OS-shipped loadable drivers
/// (`AGENTS.md` §16.2). Byte-for-byte lookup, no alias resolution (§2.1).
const DRIVER_PATH: &[u8] = b"/System/Drivers/drvstub.rxe";

/// Reply endpoint id the host binds and hands the spawned stub. Any unused
/// id works; `arg(1)` carries its ASCII decimal form ("7").
const REPLY_ENDPOINT: EndpointId = EndpointId(7);

/// ASCII decimal form of [`REPLY_ENDPOINT`] passed as the stub's `arg(1)`.
const REPLY_ENDPOINT_ARG: &[u8] = b"7";

/// Raw handle value the stub reports — pinned to the fixture program's
/// `STUB_HANDLE_RAW` (`driver_register_program/src/main.rs`); the PASS check
/// asserts the decoded reply round-tripped it.
const STUB_HANDLE_RAW: u64 = 0x00D8_0001;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the handshake stalled. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Physical frames the live allocator serves (8 MiB): the stub's image
/// pages, its 1.125 MiB user stack, the startup block, its page tables, and
/// the 2 MiB arena block the kthread-stack allocator may chain.
const FRAME_COUNT: usize = 2048;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4300);
const TEST_SPAWNED: EventId = EventId(4301);
const TEST_PASS: EventId = EventId(4302);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: u16 = 1;
const FAIL_GIC: u16 = 2;
const FAIL_POOL: u16 = 3;
const FAIL_FRAMES: u16 = 4;
const FAIL_BIAS: u16 = 5;
const FAIL_LOOKUP: u16 = 6;
const FAIL_PORT: u16 = 7;
const FAIL_SCHED_NEW: u16 = 8;
const FAIL_HOOK_INSTALL: u16 = 9;
const FAIL_SPAWN: u16 = 10;
const FAIL_NO_DISPATCH: u16 = 11;
const FAIL_REPLY_DECODE: u16 = 12;
const FAIL_REPLY_OUTCOME: u16 = 13;
const FAIL_DRAINED_NO_REPLY: u16 = 14;
const FAIL_DEADLOCK: u16 = 15;

/// Size of the test's bump heap (4 MiB): the frame-allocator bitmap + buddy
/// lists, the leaked scheduler/hook/registries, and the spawn staging
/// buffers. Lives in `.bss` (zeroed by the boot trampoline).
const HEAP_SIZE: usize = 4 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: BumpAllocator =
    unsafe { BumpAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the boot identity space the test switches to so
/// the MMU is on before any atomic read-modify-write runs (the allocator,
/// the scheduler, and the registries all use them).
static BOOT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Identity-mapped physical-frame backing store the live [`FrameAllocator`]
/// serves; `align(4096)` so each `PAGE_SIZE` slice is a whole frame, inside
/// the 2 GiB identity window the spawn producer's page-table walk requires.
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// The dispatch-callback slot the production [`KernelDispatchHook`] is
/// published into — the vertical's analogue of the bin crate's
/// `DISPATCH_SLOT` (one slot per binary, set once).
static DISPATCH_SLOT: DispatchCallbackSlot = DispatchCallbackSlot::new();

/// Per-CPU bookkeeping backing the scheduler's arch handle (single-CPU
/// vertical, `AGENTS.md` §24.1).
static SCHED_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// Per-CPU bookkeeping backing the dispatch hook + spawn ctx arch handle
/// (a second instance, mirroring `wait_qemu_aarch64`'s producer storage).
static HOOK_ARCH_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// The conservative no-external-IRQ controller, exactly the shape
/// `kernel/core::init` installs when a port exposes no routing.
static IRQ_CONTROLLER: UnsupportedController = UnsupportedController;

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn driver_spawn_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// The syscall-dispatch callback the stub's `svc` traps reach. It mirrors
/// the production bin-crate callback (`dispatch_aarch64`): read the
/// kernel-stack args frame and forward through the resident production
/// [`KernelDispatchHook`] via the shared `dispatch_via_slot` bridge, which
/// resolves the caller context, runs the §5.4 dispatch sequence, and turns
/// a yield/exit outcome into a `reschedule_current` context switch. An
/// empty slot or a missing caller context fails the test loudly
/// (`AGENTS.md` §5.4.5).
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the exception trampoline lays the frame out on the kernel
    // stack and only invokes us with a valid pointer; the array lives at
    // least until we return.
    let args = unsafe { read_raw_args(args_ptr) };
    match dispatch_via_slot(&DISPATCH_SLOT, number, args) {
        Some(value) => value,
        None => qemu_exit::exit_failure(FAIL_NO_DISPATCH),
    }
}

/// The spawned driver stub's granted capability set: a representative
/// user-space-driver grant (`AGENTS.md` §5.2 — manifest∩user). `MEM_DMA`
/// doubles as the reply port's send gate, so the stub's `ipc_send` passes
/// the production per-send capability check while a task without the
/// driver grant cannot forge a reply (`AGENTS.md` §5.4 — fail closed).
fn driver_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::MEM_DMA);
    caps.insert(CapabilityId::IRQ_BIND);
    caps
}

/// The reply port's required send capability — drawn from the driver's
/// granted set above.
fn reply_send_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::MEM_DMA);
    caps
}

/// The verified driver-stub payload registered under its `/System/Drivers/`
/// path — the embedded-program stand-in for the on-disk driver store until
/// the VFS-backed load path lands.
static DRIVER_PROGRAMS: [EmbeddedProgram; 1] = [EmbeddedProgram {
    path: DRIVER_PATH,
    rxe: PROGRAM_RXE,
    // The driver's grant and argument vector come from the verified
    // manifest via the host's load gate, not the registry entry: this
    // vertical drives `spawn_with` with [`driver_caps`] + the reply
    // endpoint directly, so the registry-declared sets stay empty.
    caps: &[],
    args: &[],
}];

/// The registry the host resolves [`DRIVER_PATH`] against (byte-for-byte,
/// no alias resolution — `AGENTS.md` §2.1).
static DRIVER_REGISTRY: ProgramRegistry = ProgramRegistry::new(&DRIVER_PROGRAMS);

/// Reply-port bound: comfortably one [`DriverRegisterReply`] record.
const REPLY_MAX_PAYLOAD: u32 = 64;

/// Reply-port mailbox depth: one in-flight reply plus headroom.
const REPLY_MAILBOX_CAPACITY: usize = 4;

/// Bring the board up for the handshake: FP/SIMD on, the `virt` device
/// tree discovered (timer rate, GICv2 bases), the identity MMU + EL1
/// vectors enabled, the GIC initialised, and the dispatch callback
/// installed. Returns the discovered generic-timer rate.
fn bring_up_board() -> u64 {
    // Enable FP/SIMD at EL1 before any code the compiler may lower to NEON
    // (the `rxe` decoder, `build_process_image`'s fills, the log formatter).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    // P3/P4: discover the board from the embedded `virt` device tree using
    // the early-returning node walks, which stay safe MMU-off.
    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Configure the identity gigapage masks from the `virt` board facts
    // (Device GiB 0 — the MMIO window — and RAM GiB 1), exactly as the
    // production boot path derives them from discovery: the production
    // spawn producer sizes every child's identity window from these masks
    // (`paging::configured_identity_gigapages`), so driving it under the
    // unconfigured defaults (RAM = all slots) would request a window
    // reaching the user bias and the spawn would fail closed.
    let mut device_mask = [0u64; GIGAPAGE_MASK_WORDS];
    device_mask[0] = 0b01;
    configure_device_gigapages(device_mask);
    let mut ram_mask = [0u64; GIGAPAGE_MASK_WORDS];
    ram_mask[0] = 0b10;
    configure_ram_gigapages(ram_mask);

    // Enable the identity MMU + EL1 vectors before any atomic
    // read-modify-write runs: the frame allocator, the scheduler, and every
    // registry the test builds use atomics, which are UNPREDICTABLE on
    // MMU-off Device-typed memory (`plans/PI.md` P6c-2).
    let Some(boot_space) =
        ArchAddressSpace::new_identity_gigapages(&BOOT_PAGE_TABLES, IDENTITY_GIB)
    else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
    // heap, the frame pool, and the device MMIO (all within `[0, 2 GiB)` on
    // the `virt` board), so switching it does not move the ground under the
    // running code; `init_vectors` runs once on the boot CPU with a stack
    // established.
    unsafe {
        boot_space.switch();
        exceptions::init_vectors();
    }
    // The boot space's tables live in the static `BOOT_PAGE_TABLES` pool
    // and the handle carries no `Drop`, so letting it fall out of scope
    // leaves the active translation regime untouched for the kernel's
    // lifetime (the kernel never returns).
    // SAFETY: called once on the boot CPU after the GIC bases were
    // discovered above.
    unsafe {
        gic::init();
    }
    syscall_entry::set_dispatch_callback(dispatch);
    counter_hz
}

/// The leaked-`'static` kernel subsystems the production dispatch hook and
/// spawn context borrow — the vertical's analogue of `KernelState`, lifted
/// by one-shot `Box::leak` publishes exactly as `kernel_core::kernel_main`
/// does (`AGENTS.md` §2.1: a one-shot publish, not a global mutable
/// static).
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<Aarch64BinArch>,
    arch: &'static Aarch64BinArch,
    caps: &'static RwLock<CapTable>,
    ipc: &'static RwLock<PortRegistry>,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    rng: &'static RwLock<Box<dyn RandomReserve + Send + Sync>>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems: the `kernel/mem` frame allocator over
/// the identity-mapped pool (so `spawn_with` draws its image, stack, and
/// page-table frames from the production path, `AGENTS.md` §2.2), the
/// scheduler over the production `KernelArch` wrapper, and the capability /
/// port / address-space / random / IRQ state the production hook borrows.
fn leak_subsystems(counter_hz: u64) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        qemu_exit::exit_failure(FAIL_FRAMES);
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let sched_arch = Arc::new(Aarch64BinArch::new(Aarch64Arch::new(
        &SCHED_STORAGE,
        BOOT_CPU,
        counter_hz,
    )));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), sched_arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(Aarch64BinArch::new(Aarch64Arch::new(
            &HOOK_ARCH_STORAGE,
            BOOT_CPU,
            counter_hz,
        )))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        ipc: Box::leak(Box::new(RwLock::new(PortRegistry::new()))),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        rng: Box::leak(Box::new(RwLock::new(
            Box::new(BootReserve::new()) as Box<dyn RandomReserve + Send + Sync>
        ))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Bind the reply port into the live registry: the host pseudo-task holds
/// exactly the bind authority a send-restricted port requires (`AGENTS.md`
/// §5.2), and the port's send gate is a capability from the driver's
/// granted set, so only the spawned driver can complete the handshake
/// (§5.4).
fn bind_reply_port(ipc: &RwLock<PortRegistry>) {
    let mut host_grant = CapabilitySet::empty();
    host_grant.insert(CapabilityId::IPC_BIND_PRIVILEGED);
    let host_caps = TaskCapabilities::derive(
        SecTaskId(0),
        UserId(0),
        host_grant,
        host_grant,
        &SERIAL_SINK,
    );
    let Ok(port) = Port::create(
        REPLY_ENDPOINT,
        &host_caps,
        reply_send_caps(),
        CapabilitySet::empty(),
        REPLY_MAX_PAYLOAD,
        REPLY_MAILBOX_CAPACITY,
        &SERIAL_SINK,
    ) else {
        qemu_exit::exit_failure(FAIL_PORT);
    };
    match ipc.write().register(port, &SERIAL_SINK) {
        Ok(id) if id == REPLY_ENDPOINT => {}
        _ => qemu_exit::exit_failure(FAIL_PORT),
    }
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `rustos_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 driver-spawn test: starting");

    let counter_hz = bring_up_board();

    // The stub `rxe`'s baked relocations must target the bias the
    // production producer maps every child at; a drifted constant would
    // admit a child whose pointers do not match its mapping (fail closed,
    // `AGENTS.md` §2.9).
    if USER_BIAS != USER_IMAGE_BIAS {
        qemu_exit::exit_failure(FAIL_BIAS);
    }

    // Resolve the verified driver payload from its `/System/Drivers/` path.
    let Some(program) = DRIVER_REGISTRY.lookup(DRIVER_PATH) else {
        qemu_exit::exit_failure(FAIL_LOOKUP);
    };

    let sys = leak_subsystems(counter_hz);

    bind_reply_port(sys.ipc);

    // Publish the production dispatch hook so the stub's syscalls run the
    // production caller-context resolution, copy-in, and `Port::send` path.
    let hook: &'static KernelDispatchHook<'static, Aarch64BinArch> =
        Box::leak(Box::new(KernelDispatchHook::new(
            sys.sched,
            sys.caps,
            sys.arch,
            &SERIAL_SINK,
            sys.irq_table,
            &IRQ_CONTROLLER,
            sys.ipc,
            sys.aspaces,
            sys.rng,
            &UART_ONLY_CONSOLES,
            sys.frames,
            sys.frames,
            &DRIVER_REGISTRY,
            &AARCH64_PROCESS_SPAWN,
            &NULL_PROCESS_WAIT,
            // This test exercises the driver-spawn / IPC path, not keyboard
            // input; the arbiter stays fail-closed (`AGENTS.md` §2.9).
            &NULL_INPUT_FOCUS,
            // This test exercises the driver-spawn / IPC path, not
            // `mem_map` / `mmio_map` / `dma_alloc`; those producers stay
            // fail-closed (`AGENTS.md` §2.9).
            &NULL_MEM_MAP,
            &NULL_MMIO_MAP_FACILITY,
            &NULL_DMA_ALLOC_FACILITY,
        )));
    if DISPATCH_SLOT.install_dispatcher(hook).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // The kernel-side production driver spawn: the verified payload, the
    // driver's granted capability set, and the reply endpoint id in
    // `arg(1)`, admitted through the same `KernelSpawnCtx` path the `spawn`
    // syscall handler uses (`AGENTS.md` §2.2).
    let ctx = KernelSpawnCtx::new(
        sys.frames,
        Some(sys.frames),
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.aspaces,
        sys.arch,
        SecTaskId(0),
        &NULL_PROCESS_WAIT,
        DescriptorTable::standard(),
    );
    if AARCH64_PROCESS_SPAWN
        .spawn_with(
            program.rxe,
            &ctx,
            driver_caps(),
            &[b"drvstub", REPLY_ENDPOINT_ARG],
        )
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(
        TEST_SPAWNED,
        "aarch64 driver-spawn test: driver stub spawned with reply endpoint",
    );

    // The budget-bounded cooperative wait: step the scheduler and poll the
    // reply port between steps. The stub runs, sends its register reply
    // over production `ipc_send`, and exits; a missing, malformed, or
    // wrong-handle reply fails loudly (`AGENTS.md` §7).
    let mut steps = 0u64;
    while steps < MAX_STEPS {
        let _ = sys.sched.step(BOOT_CPU);
        steps += 1;

        let message = sys
            .ipc
            .read()
            .lookup(REPLY_ENDPOINT)
            .and_then(rustos_kernel_ipc::Port::recv);
        if let Some(message) = message {
            // Fail-closed decode: an inconsistent record is rejected whole.
            let Ok(reply) = DriverRegisterReply::from_bytes(message.payload.as_slice()) else {
                qemu_exit::exit_failure(FAIL_REPLY_DECODE);
            };
            match reply.outcome() {
                Ok(handle) if handle.as_u64() == STUB_HANDLE_RAW => {
                    note(
                        TEST_PASS,
                        "aarch64 driver-spawn test: register reply received and verified",
                    );
                    qemu_exit::exit_success();
                }
                _ => qemu_exit::exit_failure(FAIL_REPLY_OUTCOME),
            }
        }

        // A drained workload without a reply means the stub exited down a
        // diagnostic path (or never sent); fail with a distinct finisher.
        if sys.sched.live_task_count() == 0 {
            qemu_exit::exit_failure(FAIL_DRAINED_NO_REPLY);
        }
    }
    qemu_exit::exit_failure(FAIL_DEADLOCK);
}
