//! The freestanding riscv64 test kernel: build a U-mode image for the fixture
//! program and drop into it through the production spawn caller.

use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU32, Ordering};

use rustos_abi::rxe::LoadImage;
use rustos_abi::{CapabilityId, CapabilityQuery, SyscallNumber, SYSCALL_MAX_ARGS};
use rustos_arch_riscv64::{
    handle_panic_via_serial, paging, qemu_exit, syscall_entry, trap, userentry::UserMode,
    SERIAL_SINK,
};
use rustos_bumpalloc::{BumpAllocator, Heap, HEAP_BYTES};
use rustos_kernel_core::{spawn_and_enter, SpawnRequest};
use rustos_kernel_mem::{
    AddressSpace, DirectPhysMap, Frame, MapFlags, Page, PageTableError, PageTableOps, PhysAddr,
    UserStack,
};
use rustos_kernel_syscall::SYSCALL_TABLE_HASH;
use rustos_log::{log, Event, EventId, Level};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// Static boot heap, in the linker's NOLOAD `.heap` section so the boot
/// trampoline neither zeroes nor counts it in the usable memory map. The
/// spawn caller allocates the startup-vector block buffer from it.
#[link_section = ".heap"]
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: BumpAllocator =
    unsafe { BumpAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// Decimal argument the program is spawned with and the exit code it must
/// therefore return. A small positive value distinct from crt0's reserved
/// fail-closed codes (70/71/72) and the program's own (71/72).
const EXPECTED_EXIT: u64 = 42;
/// Argument vector handed to the program: `["prog", "42"]`.
const ARG_VALUE: &[u8] = b"42";

/// Gigabytes of identity map (kernel + the `virt` board's low MMIO + RAM).
const IDENTITY_GIGABYTES: usize = 4;

/// User stack base (1 MiB into the high user region) and size. crt0 carves a
/// 1 MiB scratch span off the stack, so the stack must comfortably exceed it.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB > crt0's 1 MiB scratch + call frames).
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up, well
/// clear of the program image and the stack).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program (any value).
const CANARY: u64 = 0xC0FF_EE00_D15E_A5ED;

/// Number of physical frames the test hands the spawn builder: the program's
/// segments, the user stack, and the startup block. Sized with headroom.
const FRAME_COUNT: usize = 320;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4230);
const TEST_FAIL: EventId = EventId(4232);

/// `SiFive` Test failure codes, distinct per failure site.
const FAIL_POOL: u16 = 1;
const FAIL_PARSE: u16 = 2;
const FAIL_SPAWN_RETURNED: u16 = 3;
const FAIL_WRONG_SYSCALL: u16 = 4;
const FAIL_WRONG_CODE: u16 = 5;

/// Page-table pool backing the Sv39 hierarchy (lives in `.bss`).
static PAGE_TABLE_POOL: paging::PageTablePool = paging::PageTablePool::new();

/// Physical-frame backing store the spawn builder allocates user pages from.
/// `align(4096)` so each `FRAME_SIZE` slice is a valid page frame; identity-
/// mapped (its physical address equals its kernel virtual address), so the
/// builder reaches it through [`DirectPhysMap::identity`].
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Set once the round-trip has been driven so a re-entry cannot re-run it.
static TEST_DRIVEN: AtomicU32 = AtomicU32::new(0);

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared riscv64 panic bridge (parks the hart; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn spawn_program_qemu_riscv64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A `CapabilityQuery` granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires (`AGENTS.md` §5.4). The test does not exercise the
/// denial path here (that is covered by `kernel/core`'s host tests); it proves
/// the *authorised* path runs end to end.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// A `PageTableOps` adapter over the riscv64 Sv39 [`paging::AddressSpace`].
///
/// `kernel/mem`'s `build_process_image` is generic over a [`PageTableOps`]
/// backend; this is the bare-metal riscv64 backend the round-trip needs. It
/// lives in the test crate rather than `kernel/arch/riscv64` because §17.4
/// forbids an architecture crate from depending on `kernel/mem` (where the
/// trait lives); the test crate may depend on both. The `unsafe` Sv39 walk and
/// `satp`/TLB sequencing stay encapsulated in `paging`; this adapter only
/// translates flags and routes calls (`AGENTS.md` §2.10).
struct RiscvUserPageTable {
    arch: paging::AddressSpace,
    pool: &'static paging::PageTablePool,
}

impl RiscvUserPageTable {
    fn new(arch: paging::AddressSpace, pool: &'static paging::PageTablePool) -> Self {
        Self { arch, pool }
    }
}

/// Translate the architecture-neutral [`MapFlags`] into Sv39 permission bits.
/// `map_4k` adds the `VALID`/`ACCESSED`/`DIRTY` bits itself.
fn to_sv39_flags(flags: MapFlags) -> u64 {
    let mut f = 0;
    if flags.contains(MapFlags::READ) {
        f |= paging::flags::READ;
    }
    if flags.contains(MapFlags::WRITE) {
        f |= paging::flags::WRITE;
    }
    if flags.contains(MapFlags::EXEC) {
        f |= paging::flags::EXEC;
    }
    if flags.contains(MapFlags::USER) {
        f |= paging::flags::USER;
    }
    f
}

impl PageTableOps for RiscvUserPageTable {
    fn map(&mut self, page: Page, frame: Frame, flags: MapFlags) -> Result<(), PageTableError> {
        let vaddr = page.start().as_u64();
        let paddr = frame.start().as_u64();
        self.arch
            .map_4k(self.pool, vaddr, paddr, to_sv39_flags(flags))
            .ok_or(PageTableError::AllocFailed(
                rustos_kernel_mem::AllocError::OutOfMemory,
            ))
    }

    fn unmap(&mut self, _page: Page) -> Result<Frame, PageTableError> {
        // The spawn builder never unmaps; refusing keeps the adapter minimal.
        Err(PageTableError::NotMapped)
    }

    fn translate(&self, _page: Page) -> Option<(Frame, MapFlags)> {
        // The spawn builder never translates; it only maps and fills.
        None
    }

    fn flush(&mut self, page: Page) {
        // The address space is already active, so a freshly inserted leaf needs
        // a local TLB shootdown for its virtual address (`sfence.vma {addr}`).
        let vaddr = page.start().as_u64();
        // SAFETY: `sfence.vma` is the documented Sv39 TLB-flush instruction; it
        // touches no memory and only invalidates the cached translation for
        // `vaddr`, which we have just (re)mapped. No Rust spelling exists.
        unsafe {
            core::arch::asm!("sfence.vma {addr}, zero", addr = in(reg) vaddr, options(nostack, preserves_flags));
        }
    }
}

/// The syscall dispatch callback the program's `exit` `ecall` reaches.
///
/// Asserts the program terminated through `exit` with [`EXPECTED_EXIT`], then
/// writes the PASS finisher. It never returns to the trap path (returning would
/// `sret` back into U-mode).
extern "C" fn record_and_exit(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the trap vector built the `[u64; SYSCALL_MAX_ARGS]` array and
    // passes a pointer valid for this call (`syscall_entry` contract).
    let args = unsafe { *args_ptr };

    if number != u64::from(SyscallNumber::EXIT.as_u16()) {
        note(
            TEST_FAIL,
            "program issued an unexpected syscall before exit",
        );
        qemu_exit::exit_failure(FAIL_WRONG_SYSCALL);
    }
    if args[0] != EXPECTED_EXIT {
        note(TEST_FAIL, "program exited with the wrong code");
        qemu_exit::exit_failure(FAIL_WRONG_CODE);
    }
    qemu_exit::exit_success();
}

/// Hand out the next identity-mapped physical frame from [`FRAME_POOL`].
fn frame_source() -> impl FnMut() -> Option<Frame> {
    let mut next = 0usize;
    move || {
        if next >= FRAME_COUNT {
            return None;
        }
        let offset = next * paging::PAGE_SIZE;
        next += 1;
        // The pool is identity-mapped, so its kernel virtual address is also
        // its physical address.
        let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
        Some(Frame::containing(PhysAddr::new(base)))
    }
}

/// Boot entry point (called by the arch crate's boot trampoline).
#[no_mangle]
pub extern "C" fn kernel_main(_hartid: u64, _dtb: u64) -> ! {
    if TEST_DRIVEN
        .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_POOL);
    }

    note(
        TEST_START,
        "riscv64 spawn round-trip: building the U-mode image",
    );

    // 1. Sv39 address space identity-mapping the kernel + MMIO, then activate it
    //    and install the trap vector before any user mapping is added.
    let Some(arch) =
        paging::AddressSpace::new_identity_gigapages(&PAGE_TABLE_POOL, IDENTITY_GIGABYTES)
    else {
        note(TEST_FAIL, "page-table pool exhausted (identity map)");
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc` and `sp`, so the
    // `satp` switch is sound.
    unsafe { arch.switch() };
    // SAFETY: called once on the boot hart with a stack established; only the
    // program's deliberate `ecall` reaches the vector (no interrupt source is
    // armed).
    unsafe { trap::init_traps() };
    syscall_entry::set_dispatch_callback(record_and_exit);

    // 2. Parse the build-time `rxe` blob against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        note(TEST_FAIL, "fixture rxe image failed to parse");
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    // 3. Build the U-mode image into the (active) address space and enter it
    //    through the production capability-checked, audited spawn caller.
    let mut space = AddressSpace::new(RiscvUserPageTable::new(arch, &PAGE_TABLE_POOL));
    let physmap = DirectPhysMap::identity(u64::from(u32::MAX) + 1); // 4 GiB
    let request = SpawnRequest {
        image: &image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"prog", ARG_VALUE],
        env: &[],
        canary: CANARY,
    };

    note(TEST_START, "dropping into the spawned program");

    // SAFETY: `space` is the active address space (we `switch`ed to it above)
    // and the trap vector is installed, so the new program's `ecall` is
    // handled. `spawn_and_enter` checks `CAP_PROC_SPAWN`, builds the image into
    // `space`, and `enter_user`s into it; on the authorised path it diverges.
    let outcome = unsafe {
        spawn_and_enter(
            &SpawnAuthority,
            &SERIAL_SINK,
            &UserMode::new(),
            &mut space,
            &physmap,
            &request,
            frame_source(),
        )
    };

    // `spawn_and_enter` only returns on a denial or a build failure; the
    // authorised, well-formed path diverges into U-mode. Reaching here is a
    // closed failure.
    match outcome {
        Err(_) => {
            note(TEST_FAIL, "spawn_and_enter returned instead of entering");
            qemu_exit::exit_failure(FAIL_SPAWN_RETURNED);
        }
        Ok(never) => match never {},
    }
}
